; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=bpfel < %s | FileCheck %s

define i8 @urem_i8(i8 %x) {
; CHECK-LABEL: urem_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    w1 &= 255
; CHECK-NEXT:    w1 *= 37
; CHECK-NEXT:    w1 >>= 8
; CHECK-NEXT:    w2 = w0
; CHECK-NEXT:    w2 -= w1
; CHECK-NEXT:    w2 &= 254
; CHECK-NEXT:    w2 >>= 1
; CHECK-NEXT:    w2 += w1
; CHECK-NEXT:    w2 >>= 2
; CHECK-NEXT:    w2 *= 7
; CHECK-NEXT:    w0 -= w2
; CHECK-NEXT:    exit
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @srem_i8(i8 %x) {
; CHECK-LABEL: srem_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    w1 <<= 24
; CHECK-NEXT:    w1 s>>= 24
; CHECK-NEXT:    w1 *= -109
; CHECK-NEXT:    w1 >>= 8
; CHECK-NEXT:    w1 += w0
; CHECK-NEXT:    w2 = w1
; CHECK-NEXT:    w2 &= 128
; CHECK-NEXT:    w2 >>= 7
; CHECK-NEXT:    w1 <<= 24
; CHECK-NEXT:    w1 s>>= 26
; CHECK-NEXT:    w1 += w2
; CHECK-NEXT:    w1 *= 7
; CHECK-NEXT:    w0 -= w1
; CHECK-NEXT:    exit
  %r = srem i8 %x, 7
  ret i8 %r
}
