; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=bpfel < %s | FileCheck %s

define i8 @urem_i8(i8 %x) {
; CHECK-LABEL: urem_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    w0 &= 255
; CHECK-NEXT:    w0 *= 293
; CHECK-NEXT:    w0 &= 2047
; CHECK-NEXT:    w0 *= 7
; CHECK-NEXT:    w0 >>= 11
; CHECK-NEXT:    exit
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @srem_i8(i8 %x) {
; CHECK-LABEL: srem_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    w0 = w1
; CHECK-NEXT:    w0 <<= 24
; CHECK-NEXT:    w0 s>>= 24
; CHECK-NEXT:    w1 = w0
; CHECK-NEXT:    w1 >>= 7
; CHECK-NEXT:    w1 &= 6
; CHECK-NEXT:    w0 *= 147
; CHECK-NEXT:    w0 &= 1023
; CHECK-NEXT:    w0 *= 7
; CHECK-NEXT:    w0 >>= 10
; CHECK-NEXT:    w0 -= w1
; CHECK-NEXT:    exit
  %r = srem i8 %x, 7
  ret i8 %r
}
