; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=armv7-linux-gnueabihf -mcpu=cortex-a15 < %s | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv6m-none-eabi -mcpu=cortex-m0 < %s | FileCheck %s --check-prefix=THUMB

define i8 @urem_i8(i8 %x) {
; ARM-LABEL: urem_i8:
; ARM:       @ %bb.0:
; ARM-NEXT:    uxtb r1, r0
; ARM-NEXT:    mov r2, #37
; ARM-NEXT:    smulbb r1, r1, r2
; ARM-NEXT:    sub r2, r0, r1, lsr #8
; ARM-NEXT:    uxtb r2, r2
; ARM-NEXT:    lsr r2, r2, #1
; ARM-NEXT:    add r1, r2, r1, lsr #8
; ARM-NEXT:    lsr r1, r1, #2
; ARM-NEXT:    sub r1, r1, r1, lsl #3
; ARM-NEXT:    add r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: urem_i8:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    uxtb r1, r0
; THUMB-NEXT:    movs r2, #37
; THUMB-NEXT:    muls r2, r1, r2
; THUMB-NEXT:    lsrs r1, r2, #8
; THUMB-NEXT:    subs r2, r0, r1
; THUMB-NEXT:    uxtb r2, r2
; THUMB-NEXT:    lsrs r2, r2, #1
; THUMB-NEXT:    adds r1, r2, r1
; THUMB-NEXT:    lsrs r1, r1, #2
; THUMB-NEXT:    movs r2, #7
; THUMB-NEXT:    muls r2, r1, r2
; THUMB-NEXT:    subs r0, r0, r2
; THUMB-NEXT:    bx lr
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @urem_i8_no_fixup(i8 %x) {
; ARM-LABEL: urem_i8_no_fixup:
; ARM:       @ %bb.0:
; ARM-NEXT:    uxtb r1, r0
; ARM-NEXT:    mov r2, #205
; ARM-NEXT:    smulbb r1, r1, r2
; ARM-NEXT:    lsr r1, r1, #10
; ARM-NEXT:    add r1, r1, r1, lsl #2
; ARM-NEXT:    sub r0, r0, r1
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: urem_i8_no_fixup:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    uxtb r1, r0
; THUMB-NEXT:    movs r2, #205
; THUMB-NEXT:    muls r2, r1, r2
; THUMB-NEXT:    lsrs r1, r2, #10
; THUMB-NEXT:    movs r2, #5
; THUMB-NEXT:    muls r2, r1, r2
; THUMB-NEXT:    subs r0, r0, r2
; THUMB-NEXT:    bx lr
  %r = urem i8 %x, 5
  ret i8 %r
}
