; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mipsel -mcpu=mips32r2 < %s | FileCheck %s --check-prefix=MIPS32
; RUN: llc -mtriple=mips64el -mcpu=mips64r2 < %s | FileCheck %s --check-prefix=MIPS64

define i16 @urem_i16(i16 %x) {
; MIPS32-LABEL: urem_i16:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    andi $1, $4, 65535
; MIPS32-NEXT:    ori $2, $zero, 44151
; MIPS32-NEXT:    mul $1, $1, $2
; MIPS32-NEXT:    srl $1, $1, 22
; MIPS32-NEXT:    addiu $2, $zero, 95
; MIPS32-NEXT:    mul $1, $1, $2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: urem_i16:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    andi $2, $1, 65535
; MIPS64-NEXT:    ori $3, $zero, 44151
; MIPS64-NEXT:    mul $2, $2, $3
; MIPS64-NEXT:    srl $2, $2, 22
; MIPS64-NEXT:    sll $3, $2, 5
; MIPS64-NEXT:    subu $3, $3, $2
; MIPS64-NEXT:    sll $2, $2, 6
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    subu $2, $1, $2
  %r = urem i16 %x, 95
  ret i16 %r
}

define i16 @urem_i16_mask(i16 %x) {
; MIPS32-LABEL: urem_i16_mask:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    andi $1, $4, 65535
; MIPS32-NEXT:    sll $2, $1, 7
; MIPS32-NEXT:    addu $2, $2, $1
; MIPS32-NEXT:    sll $1, $1, 15
; MIPS32-NEXT:    addu $1, $1, $2
; MIPS32-NEXT:    srl $1, $1, 23
; MIPS32-NEXT:    sll $2, $1, 8
; MIPS32-NEXT:    subu $1, $1, $2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    addu $2, $4, $1
;
; MIPS64-LABEL: urem_i16_mask:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    andi $2, $1, 65535
; MIPS64-NEXT:    sll $3, $2, 7
; MIPS64-NEXT:    addu $3, $3, $2
; MIPS64-NEXT:    sll $2, $2, 15
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    srl $2, $2, 23
; MIPS64-NEXT:    sll $3, $2, 8
; MIPS64-NEXT:    subu $2, $2, $3
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    addu $2, $1, $2
  %r = urem i16 %x, 255
  ret i16 %r
}

define i16 @srem_i16(i16 %x) {
; MIPS32-LABEL: srem_i16:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    seh $1, $4
; MIPS32-NEXT:    addiu $2, $zero, 21385
; MIPS32-NEXT:    mul $1, $1, $2
; MIPS32-NEXT:    srl $1, $1, 16
; MIPS32-NEXT:    subu $1, $1, $4
; MIPS32-NEXT:    andi $2, $1, 32768
; MIPS32-NEXT:    srl $2, $2, 15
; MIPS32-NEXT:    seh $1, $1
; MIPS32-NEXT:    sra $1, $1, 6
; MIPS32-NEXT:    addiu $3, $zero, -95
; MIPS32-NEXT:    addu $1, $1, $2
; MIPS32-NEXT:    mul $1, $1, $3
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: srem_i16:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    seh $2, $1
; MIPS64-NEXT:    sll $3, $2, 3
; MIPS64-NEXT:    addu $3, $3, $2
; MIPS64-NEXT:    sll $4, $2, 7
; MIPS64-NEXT:    subu $3, $3, $4
; MIPS64-NEXT:    sll $4, $2, 10
; MIPS64-NEXT:    addu $3, $4, $3
; MIPS64-NEXT:    sll $4, $2, 12
; MIPS64-NEXT:    addu $3, $4, $3
; MIPS64-NEXT:    sll $2, $2, 14
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    srl $2, $2, 16
; MIPS64-NEXT:    subu $2, $2, $1
; MIPS64-NEXT:    andi $3, $2, 32768
; MIPS64-NEXT:    srl $3, $3, 15
; MIPS64-NEXT:    seh $2, $2
; MIPS64-NEXT:    sra $2, $2, 6
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    sll $3, $2, 5
; MIPS64-NEXT:    subu $3, $3, $2
; MIPS64-NEXT:    sll $2, $2, 6
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    addu $2, $1, $2
  %r = srem i16 %x, -95
  ret i16 %r
}

define i16 @srem_i16_no_fixup(i16 %x) {
; MIPS32-LABEL: srem_i16_no_fixup:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    seh $1, $4
; MIPS32-NEXT:    addiu $2, $zero, 21846
; MIPS32-NEXT:    mul $1, $1, $2
; MIPS32-NEXT:    srl $2, $1, 31
; MIPS32-NEXT:    srl $1, $1, 16
; MIPS32-NEXT:    addu $1, $1, $2
; MIPS32-NEXT:    sll $2, $1, 1
; MIPS32-NEXT:    addu $1, $2, $1
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: srem_i16_no_fixup:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    seh $2, $1
; MIPS64-NEXT:    addiu $3, $zero, 21846
; MIPS64-NEXT:    mul $2, $2, $3
; MIPS64-NEXT:    srl $3, $2, 31
; MIPS64-NEXT:    srl $2, $2, 16
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    sll $3, $2, 1
; MIPS64-NEXT:    addu $2, $3, $2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    subu $2, $1, $2
  %r = srem i16 %x, 3
  ret i16 %r
}

define i32 @urem_i32(i32 %x) {
; MIPS32-LABEL: urem_i32:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    lui $1, 22765
; MIPS32-NEXT:    ori $1, $1, 8969
; MIPS32-NEXT:    multu $4, $1
; MIPS32-NEXT:    mfhi $1
; MIPS32-NEXT:    subu $2, $4, $1
; MIPS32-NEXT:    srl $2, $2, 1
; MIPS32-NEXT:    addu $1, $2, $1
; MIPS32-NEXT:    addiu $2, $zero, 95
; MIPS32-NEXT:    srl $1, $1, 6
; MIPS32-NEXT:    mul $1, $1, $2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: urem_i32:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    dext $1, $4, 0, 32
; MIPS64-NEXT:    lui $2, 1
; MIPS64-NEXT:    daddiu $2, $2, 22765
; MIPS64-NEXT:    dsll $2, $2, 16
; MIPS64-NEXT:    daddiu $2, $2, 8969
; MIPS64-NEXT:    dsll $2, $2, 25
; MIPS64-NEXT:    dmultu $1, $2
; MIPS64-NEXT:    mfhi $1
; MIPS64-NEXT:    sll $1, $1, 0
; MIPS64-NEXT:    sll $2, $4, 0
; MIPS64-NEXT:    sll $3, $1, 5
; MIPS64-NEXT:    subu $3, $3, $1
; MIPS64-NEXT:    sll $1, $1, 6
; MIPS64-NEXT:    addu $1, $1, $3
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    subu $2, $2, $1
  %r = urem i32 %x, 95
  ret i32 %r
}

define i32 @urem_i32_no_fixup(i32 %x) {
; MIPS32-LABEL: urem_i32_no_fixup:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    lui $1, 52428
; MIPS32-NEXT:    ori $1, $1, 52429
; MIPS32-NEXT:    multu $4, $1
; MIPS32-NEXT:    mfhi $1
; MIPS32-NEXT:    addiu $2, $zero, -4
; MIPS32-NEXT:    and $2, $1, $2
; MIPS32-NEXT:    srl $1, $1, 2
; MIPS32-NEXT:    addu $1, $2, $1
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: urem_i32_no_fixup:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    lui $1, 52428
; MIPS64-NEXT:    ori $1, $1, 52429
; MIPS64-NEXT:    sll $2, $4, 0
; MIPS64-NEXT:    multu $2, $1
; MIPS64-NEXT:    mfhi $1
; MIPS64-NEXT:    addiu $3, $zero, -4
; MIPS64-NEXT:    and $3, $1, $3
; MIPS64-NEXT:    srl $1, $1, 2
; MIPS64-NEXT:    addu $1, $3, $1
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    subu $2, $2, $1
  %r = urem i32 %x, 5
  ret i32 %r
}
define i8 @urem_i8(i8 %x) {
; MIPS32-LABEL: urem_i8:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    andi $1, $4, 255
; MIPS32-NEXT:    sll $2, $1, 2
; MIPS32-NEXT:    addu $2, $2, $1
; MIPS32-NEXT:    sll $1, $1, 5
; MIPS32-NEXT:    addu $1, $1, $2
; MIPS32-NEXT:    srl $1, $1, 8
; MIPS32-NEXT:    subu $2, $4, $1
; MIPS32-NEXT:    andi $2, $2, 254
; MIPS32-NEXT:    srl $2, $2, 1
; MIPS32-NEXT:    addu $1, $2, $1
; MIPS32-NEXT:    andi $1, $1, 252
; MIPS32-NEXT:    srl $1, $1, 2
; MIPS32-NEXT:    sll $2, $1, 3
; MIPS32-NEXT:    subu $1, $1, $2
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    addu $2, $4, $1
;
; MIPS64-LABEL: urem_i8:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    andi $2, $1, 255
; MIPS64-NEXT:    sll $3, $2, 2
; MIPS64-NEXT:    addu $3, $3, $2
; MIPS64-NEXT:    sll $2, $2, 5
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    srl $2, $2, 8
; MIPS64-NEXT:    subu $3, $1, $2
; MIPS64-NEXT:    andi $3, $3, 254
; MIPS64-NEXT:    srl $3, $3, 1
; MIPS64-NEXT:    addu $2, $3, $2
; MIPS64-NEXT:    andi $2, $2, 252
; MIPS64-NEXT:    srl $2, $2, 2
; MIPS64-NEXT:    sll $3, $2, 3
; MIPS64-NEXT:    subu $2, $2, $3
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    addu $2, $1, $2
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @urem_i8_no_fixup(i8 %x) {
; MIPS32-LABEL: urem_i8_no_fixup:
; MIPS32:       # %bb.0:
; MIPS32-NEXT:    andi $1, $4, 255
; MIPS32-NEXT:    sll $2, $1, 1
; MIPS32-NEXT:    addu $2, $2, $1
; MIPS32-NEXT:    sll $3, $1, 4
; MIPS32-NEXT:    subu $2, $3, $2
; MIPS32-NEXT:    sll $3, $1, 6
; MIPS32-NEXT:    subu $2, $2, $3
; MIPS32-NEXT:    sll $1, $1, 8
; MIPS32-NEXT:    addu $1, $1, $2
; MIPS32-NEXT:    lui $2, 255
; MIPS32-NEXT:    srl $3, $1, 8
; MIPS32-NEXT:    ori $2, $2, 65532
; MIPS32-NEXT:    and $2, $3, $2
; MIPS32-NEXT:    ext $1, $1, 10, 6
; MIPS32-NEXT:    addu $1, $2, $1
; MIPS32-NEXT:    jr $ra
; MIPS32-NEXT:    subu $2, $4, $1
;
; MIPS64-LABEL: urem_i8_no_fixup:
; MIPS64:       # %bb.0:
; MIPS64-NEXT:    sll $1, $4, 0
; MIPS64-NEXT:    andi $2, $1, 255
; MIPS64-NEXT:    sll $3, $2, 1
; MIPS64-NEXT:    addu $3, $3, $2
; MIPS64-NEXT:    sll $4, $2, 4
; MIPS64-NEXT:    subu $3, $4, $3
; MIPS64-NEXT:    sll $4, $2, 6
; MIPS64-NEXT:    lui $5, 255
; MIPS64-NEXT:    subu $3, $3, $4
; MIPS64-NEXT:    ori $4, $5, 65532
; MIPS64-NEXT:    sll $2, $2, 8
; MIPS64-NEXT:    addu $2, $2, $3
; MIPS64-NEXT:    srl $3, $2, 8
; MIPS64-NEXT:    and $3, $3, $4
; MIPS64-NEXT:    ext $2, $2, 10, 6
; MIPS64-NEXT:    addu $2, $3, $2
; MIPS64-NEXT:    jr $ra
; MIPS64-NEXT:    subu $2, $1, $2
  %r = urem i8 %x, 5
  ret i8 %r
}
