; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgpu9.42--amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs -stop-after=ir-translator < %s | FileCheck %s
; RUN: llc -mtriple=amdgpu9.42--amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs < %s | FileCheck %s --check-prefix=ASM
; RUN: llc -mtriple=amdgpu9.0a--amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs < %s -o /dev/null
; RUN: llc -mtriple=amdgpu9.50--amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs < %s -o /dev/null
; RUN: llc -mtriple=amdgpu9.42--amdhsa -global-isel -global-isel-abort=1 -verify-machineinstrs -amdgpu-ir-lower-kernel-arguments=0 < %s -o /dev/null

define amdgpu_kernel void @ptr1_i16_i16_preload_arg(ptr addrspace(1) inreg %out, i16 inreg %arg0, i16 inreg %arg1) #0 {
  ; CHECK-LABEL: name: ptr1_i16_i16_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 3
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr4, $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $sgpr4
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i32), 0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i16) = COPY [[EXTRACT]](i16)
  ; CHECK-NEXT:   [[EXTRACT1:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i32), 16
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(i16) = COPY [[EXTRACT1]](i16)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[COPY4]](i16)
  ; CHECK-NEXT:   [[ZEXT1:%[0-9]+]]:_(i32) = G_ZEXT [[COPY5]](i16)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(i32) = G_ADD [[ZEXT]], [[ZEXT1]]
  ; CHECK-NEXT:   G_STORE [[ADD]](i32), [[INTTOPTR]](p1) :: (store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  ; ASM-LABEL: ptr1_i16_i16_preload_arg:
  ; ASM: .amdhsa_user_sgpr_kernarg_preload_length 3
  %ext = zext i16 %arg0 to i32
  %ext1 = zext i16 %arg1 to i32
  %add = add i32 %ext, %ext1
  store i32 %add, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @i32_ptr1_i32_preload_arg(i32 inreg %arg0, ptr addrspace(1) inreg %out, i32 inreg %arg1) #0 {
  ; CHECK-LABEL: name: i32_ptr1_i32_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 5
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr2, $sgpr6, $sgpr0_sgpr1, $sgpr4_sgpr5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY [[COPY1]](i32)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY [[COPY2]](i32)
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i64) = COPY $sgpr4_sgpr5
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(i64) = COPY [[COPY4]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY5]](i64)
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(i32) = COPY $sgpr6
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(i32) = COPY [[COPY6]](i32)
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(i32) = COPY [[COPY7]](i32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(i32) = G_ADD [[COPY3]], [[COPY8]]
  ; CHECK-NEXT:   G_STORE [[ADD]](i32), [[INTTOPTR]](p1) :: (store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  %add = add i32 %arg0, %arg1
  store i32 %add, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v3i32_preload_arg(ptr addrspace(1) nocapture inreg %out, <3 x i32> inreg %in) #0 {
  ; CHECK-LABEL: name: v3i32_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 7
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr6, $sgpr7, $sgpr8, $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $sgpr6
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i32) = COPY $sgpr7
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(i32) = COPY $sgpr8
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(i96) = G_MERGE_VALUES [[COPY3]](i32), [[COPY4]](i32), [[COPY5]](i32)
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i32) = G_EXTRACT [[MV]](i96), 0
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:_(i32) = COPY [[EXTRACT]](i32)
  ; CHECK-NEXT:   [[EXTRACT1:%[0-9]+]]:_(i32) = G_EXTRACT [[MV]](i96), 32
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:_(i32) = COPY [[EXTRACT1]](i32)
  ; CHECK-NEXT:   [[EXTRACT2:%[0-9]+]]:_(i32) = G_EXTRACT [[MV]](i96), 64
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:_(i32) = COPY [[EXTRACT2]](i32)
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<3 x i32>) = G_BUILD_VECTOR [[COPY6]](i32), [[COPY7]](i32), [[COPY8]](i32)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<3 x i32>), [[INTTOPTR]](p1) :: (store (<3 x i32>) into %ir.out, align 4, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  store <3 x i32> %in, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @half_kernel_preload_arg(ptr addrspace(1) inreg %out, half inreg %in) #0 {
  ; CHECK-LABEL: name: half_kernel_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 3
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr4, $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $sgpr4
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i32), 0
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(f16) = G_BITCAST [[EXTRACT]](i16)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   G_STORE [[BITCAST]](f16), [[INTTOPTR]](p1) :: (store (f16) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  store half %in, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @ptr1_i8_trailing_unused(ptr addrspace(1) inreg %out, i8 inreg %arg0, i32 inreg %unused) #0 {
  ; CHECK-LABEL: name: ptr1_i8_trailing_unused
  ; CHECK: numKernargPreloadSGPRs: 4
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr4, $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $sgpr4
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i8) = G_EXTRACT [[COPY3]](i32), 0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i8) = COPY [[EXTRACT]](i8)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[COPY4]](i8)
  ; CHECK-NEXT:   G_STORE [[ZEXT]](i32), [[INTTOPTR]](p1) :: (store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  %ext = zext i8 %arg0 to i32
  store i32 %ext, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @i32_ptr1_i32_staggered_preload_arg(i32 inreg %arg0, ptr addrspace(1) %out, i32 inreg %arg1) #0 {
  ; CHECK-LABEL: name: i32_ptr1_i32_staggered_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 1
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr2, $sgpr0_sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $sgpr2
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i32) = COPY [[COPY1]](i32)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY [[COPY2]](i32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 16
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[PTR_ADD]](p4) :: (dereferenceable invariant load (i32) from constant-pool, align 16, addrspace 4)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 8
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p4) = nuw nusw inbounds G_PTR_ADD [[INT]], [[C1]](i64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(p1) = G_LOAD [[PTR_ADD1]](p4) :: (dereferenceable invariant load (p1) from %ir.out.kernarg.offset, addrspace 4)
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:_(i32) = G_ADD [[COPY3]], [[LOAD]]
  ; CHECK-NEXT:   G_STORE [[ADD]](i32), [[LOAD1]](p1) :: (store (i32) into %ir.out.load, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  %add = add i32 %arg0, %arg1
  store i32 %add, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @v3bfloat_kernel_preload_arg(ptr addrspace(1) inreg %out, <3 x bfloat> inreg %in) #0 {
  ; CHECK-LABEL: name: v3bfloat_kernel_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 4
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr0_sgpr1, $sgpr2_sgpr3, $sgpr4_sgpr5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i64) = COPY $sgpr4_sgpr5
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i64), 0
  ; CHECK-NEXT:   [[BITCAST:%[0-9]+]]:_(bf16) = G_BITCAST [[EXTRACT]](i16)
  ; CHECK-NEXT:   [[EXTRACT1:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i64), 16
  ; CHECK-NEXT:   [[BITCAST1:%[0-9]+]]:_(bf16) = G_BITCAST [[EXTRACT1]](i16)
  ; CHECK-NEXT:   [[EXTRACT2:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i64), 32
  ; CHECK-NEXT:   [[BITCAST2:%[0-9]+]]:_(bf16) = G_BITCAST [[EXTRACT2]](i16)
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<3 x bf16>) = G_BUILD_VECTOR [[BITCAST]](bf16), [[BITCAST1]](bf16), [[BITCAST2]](bf16)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<3 x bf16>), [[INTTOPTR]](p1) :: (store (<3 x bf16>) into %ir.out, align 8, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  store <3 x bfloat> %in, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @byref_staggered_preload_arg(ptr addrspace(1) inreg %out, ptr addrspace(4) byref(i32) align(256) %in.byref, i32 inreg %after.offset) #0 {
  ; CHECK-LABEL: name: byref_staggered_preload_arg
  ; CHECK: numKernargPreloadSGPRs: 2
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 260
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[PTR_ADD]](p4) :: (dereferenceable invariant load (i32) from constant-pool, addrspace 4)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(i64) = G_CONSTANT i64 256
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p4) = nuw nusw inbounds G_PTR_ADD [[INT]], [[C1]](i64)
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(i32) = G_LOAD [[PTR_ADD1]](p4) :: (dereferenceable invariant load (i32) from %ir.in.byref.byval.kernarg.offset, addrspace 4)
  ; CHECK-NEXT:   G_STORE [[LOAD1]](i32), [[INTTOPTR]](p1) :: (volatile store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   G_STORE [[LOAD]](i32), [[INTTOPTR]](p1) :: (volatile store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  %in = load i32, ptr addrspace(4) %in.byref
  store volatile i32 %in, ptr addrspace(1) %out, align 4
  store volatile i32 %after.offset, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @preload_hidden_remainder(ptr addrspace(1) inreg %out, i8 inreg %unused) #0 {
  ; CHECK-LABEL: name: preload_hidden_remainder
  ; CHECK: numKernargPreloadSGPRs: 10
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr11, $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(i32) = COPY $sgpr11
  ; CHECK-NEXT:   [[EXTRACT:%[0-9]+]]:_(i16) = G_EXTRACT [[COPY3]](i32), 16
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(i16) = COPY [[EXTRACT]](i16)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   [[INT1:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.implicitarg.ptr)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 22
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = G_PTR_ADD [[INT1]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i16) = G_LOAD [[PTR_ADD]](p4) :: (invariant load (i16) from %ir.ptr, addrspace 4)
  ; CHECK-NEXT:   G_STORE [[COPY4]](i16), [[INTTOPTR]](p1) :: (store (i16) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  ; ASM-LABEL: preload_hidden_remainder:
  ; ASM: .amdhsa_user_sgpr_kernarg_preload_length 10
  %implicit = call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
  %ptr = getelementptr i8, ptr addrspace(4) %implicit, i64 22
  %value = load i16, ptr addrspace(4) %ptr
  store i16 %value, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @preload_exhausted(ptr addrspace(1) inreg %out, i512 inreg %unused, i32 inreg %value) #0 {
  ; CHECK-LABEL: name: preload_exhausted
  ; CHECK: numKernargPreloadSGPRs: 2
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $sgpr0_sgpr1, $sgpr2_sgpr3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p4) = COPY $sgpr0_sgpr1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $sgpr2_sgpr3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(i64) = COPY [[COPY1]](i64)
  ; CHECK-NEXT:   [[INTTOPTR:%[0-9]+]]:_(p1) = G_INTTOPTR [[COPY2]](i64)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(i64) = G_CONSTANT i64 72
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p4) = G_PTR_ADD [[COPY]], [[C]](i64)
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(i32) = G_LOAD [[PTR_ADD]](p4) :: (dereferenceable invariant load (i32) from constant-pool, align 8, addrspace 4)
  ; CHECK-NEXT:   [[INT:%[0-9]+]]:_(p4) = G_INTRINSIC intrinsic(@llvm.amdgcn.kernarg.segment.ptr)
  ; CHECK-NEXT:   G_STORE [[LOAD]](i32), [[INTTOPTR]](p1) :: (store (i32) into %ir.out, addrspace 1)
  ; CHECK-NEXT:   S_ENDPGM 0
  store i32 %value, ptr addrspace(1) %out
  ret void
}

declare ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()

attributes #0 = { "amdgpu-agpr-alloc"="0" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" }
