; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m < %s | FileCheck %s --check-prefix=RV32
; RUN: llc -mtriple=riscv64 -mattr=+m < %s | FileCheck %s --check-prefix=RV64

define i16 @urem_i16(i16 %x) {
; RV32-LABEL: urem_i16:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a1, 706416
; RV32-NEXT:    slli a2, a0, 16
; RV32-NEXT:    mulhu a1, a2, a1
; RV32-NEXT:    srli a1, a1, 22
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    sub a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: urem_i16:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a1, 44151
; RV64-NEXT:    slli a1, a1, 4
; RV64-NEXT:    slli a2, a0, 48
; RV64-NEXT:    mulhu a1, a2, a1
; RV64-NEXT:    srli a1, a1, 22
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    sub a0, a0, a1
; RV64-NEXT:    ret
  %r = urem i16 %x, 95
  ret i16 %r
}
define i16 @srem_i16(i16 %x) {
; RV32-LABEL: srem_i16:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a1, 5
; RV32-NEXT:    slli a2, a0, 16
; RV32-NEXT:    srai a2, a2, 16
; RV32-NEXT:    addi a1, a1, 905
; RV32-NEXT:    mul a1, a2, a1
; RV32-NEXT:    srli a1, a1, 16
; RV32-NEXT:    sub a1, a1, a0
; RV32-NEXT:    slli a1, a1, 16
; RV32-NEXT:    srli a2, a1, 31
; RV32-NEXT:    srai a1, a1, 22
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    li a2, -95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    sub a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: srem_i16:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a1, 5
; RV64-NEXT:    slli a2, a0, 48
; RV64-NEXT:    srai a2, a2, 48
; RV64-NEXT:    addi a1, a1, 905
; RV64-NEXT:    mul a1, a2, a1
; RV64-NEXT:    srli a1, a1, 16
; RV64-NEXT:    sub a1, a1, a0
; RV64-NEXT:    slli a1, a1, 48
; RV64-NEXT:    srli a2, a1, 63
; RV64-NEXT:    srai a1, a1, 54
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    li a2, -95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    sub a0, a0, a1
; RV64-NEXT:    ret
  %r = srem i16 %x, -95
  ret i16 %r
}

define i32 @urem_i32(i32 %x) {
; RV32-LABEL: urem_i32:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a1, 364242
; RV32-NEXT:    addi a1, a1, 777
; RV32-NEXT:    mulhu a1, a0, a1
; RV32-NEXT:    sub a2, a0, a1
; RV32-NEXT:    srli a2, a2, 1
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    srli a1, a1, 6
; RV32-NEXT:    li a2, 95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    sub a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: urem_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a1, %hi(.LCPI2_0)
; RV64-NEXT:    ld a1, %lo(.LCPI2_0)(a1)
; RV64-NEXT:    slli a2, a0, 32
; RV64-NEXT:    srli a2, a2, 32
; RV64-NEXT:    mulhu a1, a2, a1
; RV64-NEXT:    li a2, 95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    subw a0, a0, a1
; RV64-NEXT:    ret
  %r = urem i32 %x, 95
  ret i32 %r
}

define i32 @srem_i32(i32 %x) {
; RV32-LABEL: srem_i32:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a1, 342167
; RV32-NEXT:    addi a1, a1, -389
; RV32-NEXT:    mulh a1, a0, a1
; RV32-NEXT:    sub a1, a1, a0
; RV32-NEXT:    srli a2, a1, 31
; RV32-NEXT:    srai a1, a1, 6
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    li a2, -95
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    sub a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: srem_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a1, 342167
; RV64-NEXT:    sext.w a2, a0
; RV64-NEXT:    addi a1, a1, -389
; RV64-NEXT:    mul a1, a2, a1
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    sub a1, a1, a0
; RV64-NEXT:    srliw a2, a1, 31
; RV64-NEXT:    sraiw a1, a1, 6
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    li a2, -95
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    subw a0, a0, a1
; RV64-NEXT:    ret
  %r = srem i32 %x, -95
  ret i32 %r
}
define i8 @urem_i8(i8 %x) {
; RV32-LABEL: urem_i8:
; RV32:       # %bb.0:
; RV32-NEXT:    li a1, 37
; RV32-NEXT:    zext.b a2, a0
; RV32-NEXT:    mul a1, a2, a1
; RV32-NEXT:    srli a1, a1, 8
; RV32-NEXT:    sub a2, a0, a1
; RV32-NEXT:    slli a2, a2, 24
; RV32-NEXT:    srli a2, a2, 25
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    srli a1, a1, 2
; RV32-NEXT:    slli a2, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sub a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: urem_i8:
; RV64:       # %bb.0:
; RV64-NEXT:    li a1, 37
; RV64-NEXT:    zext.b a2, a0
; RV64-NEXT:    mul a1, a2, a1
; RV64-NEXT:    srli a1, a1, 8
; RV64-NEXT:    sub a2, a0, a1
; RV64-NEXT:    slli a2, a2, 56
; RV64-NEXT:    srli a2, a2, 57
; RV64-NEXT:    add a1, a2, a1
; RV64-NEXT:    srli a1, a1, 2
; RV64-NEXT:    slli a2, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sub a0, a0, a2
; RV64-NEXT:    ret
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @srem_i8(i8 %x) {
; RV32-LABEL: srem_i8:
; RV32:       # %bb.0:
; RV32-NEXT:    li a1, -109
; RV32-NEXT:    slli a2, a0, 24
; RV32-NEXT:    srai a2, a2, 24
; RV32-NEXT:    mul a1, a2, a1
; RV32-NEXT:    srli a1, a1, 8
; RV32-NEXT:    add a1, a1, a0
; RV32-NEXT:    slli a1, a1, 24
; RV32-NEXT:    srli a2, a1, 31
; RV32-NEXT:    srai a1, a1, 26
; RV32-NEXT:    add a1, a1, a2
; RV32-NEXT:    slli a2, a1, 3
; RV32-NEXT:    add a0, a0, a1
; RV32-NEXT:    sub a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: srem_i8:
; RV64:       # %bb.0:
; RV64-NEXT:    li a1, -109
; RV64-NEXT:    slli a2, a0, 56
; RV64-NEXT:    srai a2, a2, 56
; RV64-NEXT:    mul a1, a2, a1
; RV64-NEXT:    srli a1, a1, 8
; RV64-NEXT:    add a1, a1, a0
; RV64-NEXT:    slli a1, a1, 56
; RV64-NEXT:    srli a2, a1, 63
; RV64-NEXT:    srai a1, a1, 58
; RV64-NEXT:    add a1, a1, a2
; RV64-NEXT:    slli a2, a1, 3
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    sub a0, a0, a2
; RV64-NEXT:    ret
  %r = srem i8 %x, 7
  ret i8 %r
}
