; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -o - -global-isel %s -stop-after=ir-translator | FileCheck %s

define <4 x i1> @foo() {
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(<4 x i1>) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[ANYEXT:%[0-9]+]]:_(<4 x i32>) = G_ANYEXT [[DEF]](<4 x i1>)
  ; CHECK-NEXT:   $xmm0 = COPY [[ANYEXT]](<4 x i32>)
  ; CHECK-NEXT:   RET 0, implicit $xmm0
entry:
  ret <4 x i1> undef ;
}
