; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -O0 -global-isel -stop-after=ir-translator -verify-machineinstrs %s -o - 2>&1 | FileCheck %s

define i8 @zext_i1_to_i8(i1 %val) {
  ; CHECK-LABEL: name: zext_i1_to_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i8) = G_ZEXT [[TRUNC]](i1)
  ; CHECK-NEXT:   $al = COPY [[ZEXT]](i8)
  ; CHECK-NEXT:   RET 0, implicit $al
  %res = zext i1 %val to i8
  ret i8 %res
}

define i16 @zext_i1_to_i16(i1 %val) {
  ; CHECK-LABEL: name: zext_i1_to_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i16) = G_ZEXT [[TRUNC]](i1)
  ; CHECK-NEXT:   $ax = COPY [[ZEXT]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = zext i1 %val to i16
  ret i16 %res
}

define i32 @zext_i1_to_i32(i1 %val) {
  ; CHECK-LABEL: name: zext_i1_to_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[TRUNC]](i1)
  ; CHECK-NEXT:   $eax = COPY [[ZEXT]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = zext i1 %val to i32
  ret i32 %res
}

define i64 @zext_i1_to_i64(i1 %val) {
  ; CHECK-LABEL: name: zext_i1_to_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i1) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i64) = G_ZEXT [[TRUNC]](i1)
  ; CHECK-NEXT:   $rax = COPY [[ZEXT]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = zext i1 %val to i64
  ret i64 %res
}

define i16 @zext_i8_to_i16(i8 %val) {
  ; CHECK-LABEL: name: zext_i8_to_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i16) = G_ZEXT [[TRUNC]](i8)
  ; CHECK-NEXT:   $ax = COPY [[ZEXT]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = zext i8 %val to i16
  ret i16 %res
}

define i32 @zext_i8_to_i32(i8 %val) {
  ; CHECK-LABEL: name: zext_i8_to_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[TRUNC]](i8)
  ; CHECK-NEXT:   $eax = COPY [[ZEXT]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = zext i8 %val to i32
  ret i32 %res
}

define i64 @zext_i8_to_i64(i8 %val) {
  ; CHECK-LABEL: name: zext_i8_to_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i64) = G_ZEXT [[TRUNC]](i8)
  ; CHECK-NEXT:   $rax = COPY [[ZEXT]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = zext i8 %val to i64
  ret i64 %res
}

define i32 @zext_i16_to_i32(i16 %val) {
  ; CHECK-LABEL: name: zext_i16_to_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i32) = G_ZEXT [[TRUNC]](i16)
  ; CHECK-NEXT:   $eax = COPY [[ZEXT]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = zext i16 %val to i32
  ret i32 %res
}

define i64 @zext_i16_to_i64(i16 %val) {
  ; CHECK-LABEL: name: zext_i16_to_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i64) = G_ZEXT [[TRUNC]](i16)
  ; CHECK-NEXT:   $rax = COPY [[ZEXT]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = zext i16 %val to i64
  ret i64 %res
}

define i64 @zext_i32_to_i64(i32 %val) {
  ; CHECK-LABEL: name: zext_i32_to_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[ZEXT:%[0-9]+]]:_(i64) = G_ZEXT [[COPY]](i32)
  ; CHECK-NEXT:   $rax = COPY [[ZEXT]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = zext i32 %val to i64
  ret i64 %res
}

define i8 @test_sdiv_i8(i8 %arg1, i8 %arg2) {
  ; CHECK-LABEL: name: test_sdiv_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i8) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[SDIV:%[0-9]+]]:_(i8) = G_SDIV [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $al = COPY [[SDIV]](i8)
  ; CHECK-NEXT:   RET 0, implicit $al
  %res = sdiv i8 %arg1, %arg2
  ret i8 %res
}

define i16 @test_sdiv_i16(i16 %arg1, i16 %arg2) {
  ; CHECK-LABEL: name: test_sdiv_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[SDIV:%[0-9]+]]:_(i16) = G_SDIV [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $ax = COPY [[SDIV]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = sdiv i16 %arg1, %arg2
  ret i16 %res
}

define i32 @test_sdiv_i32(i32 %arg1, i32 %arg2) {
  ; CHECK-LABEL: name: test_sdiv_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[SDIV:%[0-9]+]]:_(i32) = G_SDIV [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $eax = COPY [[SDIV]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = sdiv i32 %arg1, %arg2
  ret i32 %res
}

define i64 @test_sdiv_i64(i64 %arg1, i64 %arg2) {
  ; CHECK-LABEL: name: test_sdiv_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi, $rsi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i64) = COPY $rdi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $rsi
  ; CHECK-NEXT:   [[SDIV:%[0-9]+]]:_(i64) = G_SDIV [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $rax = COPY [[SDIV]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = sdiv i64 %arg1, %arg2
  ret i64 %res
}
define float @test_fptrunc(double %in) {
  ; CHECK-LABEL: name: test_fptrunc
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(f64) = COPY $xmm0
  ; CHECK-NEXT:   [[FPTRUNC:%[0-9]+]]:_(f32) = G_FPTRUNC [[COPY]](f64)
  ; CHECK-NEXT:   $xmm0 = COPY [[FPTRUNC]](f32)
  ; CHECK-NEXT:   RET 0, implicit $xmm0
  %res = fptrunc double %in to float
  ret float %res
}

define i8 @test_srem_i8(i8 %arg1, i8 %arg2) {
  ; CHECK-LABEL: name: test_srem_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i8) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[SREM:%[0-9]+]]:_(i8) = G_SREM [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $al = COPY [[SREM]](i8)
  ; CHECK-NEXT:   RET 0, implicit $al
  %res = srem i8 %arg1, %arg2
  ret i8 %res
}

define i16 @test_srem_i16(i16 %arg1, i16 %arg2) {
  ; CHECK-LABEL: name: test_srem_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[SREM:%[0-9]+]]:_(i16) = G_SREM [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $ax = COPY [[SREM]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = srem i16 %arg1, %arg2
  ret i16 %res
}

define i32 @test_srem_i32(i32 %arg1, i32 %arg2) {
  ; CHECK-LABEL: name: test_srem_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[SREM:%[0-9]+]]:_(i32) = G_SREM [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $eax = COPY [[SREM]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = srem i32 %arg1, %arg2
  ret i32 %res
}

define i64 @test_srem_i64(i64 %arg1, i64 %arg2) {
  ; CHECK-LABEL: name: test_srem_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi, $rsi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i64) = COPY $rdi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $rsi
  ; CHECK-NEXT:   [[SREM:%[0-9]+]]:_(i64) = G_SREM [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $rax = COPY [[SREM]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = srem i64 %arg1, %arg2
  ret i64 %res
}

define i8 @test_udiv_i8(i8 %arg1, i8 %arg2) {
  ; CHECK-LABEL: name: test_udiv_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i8) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[UDIV:%[0-9]+]]:_(i8) = G_UDIV [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $al = COPY [[UDIV]](i8)
  ; CHECK-NEXT:   RET 0, implicit $al
  %res = udiv i8 %arg1, %arg2
  ret i8 %res
}

define i16 @test_udiv_i16(i16 %arg1, i16 %arg2) {
  ; CHECK-LABEL: name: test_udiv_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[UDIV:%[0-9]+]]:_(i16) = G_UDIV [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $ax = COPY [[UDIV]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = udiv i16 %arg1, %arg2
  ret i16 %res
}

define i32 @test_udiv_i32(i32 %arg1, i32 %arg2) {
  ; CHECK-LABEL: name: test_udiv_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[UDIV:%[0-9]+]]:_(i32) = G_UDIV [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $eax = COPY [[UDIV]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = udiv i32 %arg1, %arg2
  ret i32 %res
}

define i64 @test_udiv_i64(i64 %arg1, i64 %arg2) {
  ; CHECK-LABEL: name: test_udiv_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi, $rsi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i64) = COPY $rdi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $rsi
  ; CHECK-NEXT:   [[UDIV:%[0-9]+]]:_(i64) = G_UDIV [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $rax = COPY [[UDIV]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = udiv i64 %arg1, %arg2
  ret i64 %res
}

define i8 @test_urem_i8(i8 %arg1, i8 %arg2) {
  ; CHECK-LABEL: name: test_urem_i8
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i8) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i8) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[UREM:%[0-9]+]]:_(i8) = G_UREM [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $al = COPY [[UREM]](i8)
  ; CHECK-NEXT:   RET 0, implicit $al
  %res = urem i8 %arg1, %arg2
  ret i8 %res
}

define i16 @test_urem_i16(i16 %arg1, i16 %arg2) {
  ; CHECK-LABEL: name: test_urem_i16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(i16) = G_TRUNC [[COPY]](i32)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[TRUNC1:%[0-9]+]]:_(i16) = G_TRUNC [[COPY1]](i32)
  ; CHECK-NEXT:   [[UREM:%[0-9]+]]:_(i16) = G_UREM [[TRUNC]], [[TRUNC1]]
  ; CHECK-NEXT:   $ax = COPY [[UREM]](i16)
  ; CHECK-NEXT:   RET 0, implicit $ax
  %res = urem i16 %arg1, %arg2
  ret i16 %res
}

define i32 @test_urem_i32(i32 %arg1, i32 %arg2) {
  ; CHECK-LABEL: name: test_urem_i32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i32) = COPY $edi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i32) = COPY $esi
  ; CHECK-NEXT:   [[UREM:%[0-9]+]]:_(i32) = G_UREM [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $eax = COPY [[UREM]](i32)
  ; CHECK-NEXT:   RET 0, implicit $eax
  %res = urem i32 %arg1, %arg2
  ret i32 %res
}

define i64 @test_urem_i64(i64 %arg1, i64 %arg2) {
  ; CHECK-LABEL: name: test_urem_i64
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi, $rsi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(i64) = COPY $rdi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(i64) = COPY $rsi
  ; CHECK-NEXT:   [[UREM:%[0-9]+]]:_(i64) = G_UREM [[COPY]], [[COPY1]]
  ; CHECK-NEXT:   $rax = COPY [[UREM]](i64)
  ; CHECK-NEXT:   RET 0, implicit $rax
  %res = urem i64 %arg1, %arg2
  ret i64 %res
}

define <2 x float> @test_const_v2f32() {
  ; CHECK-LABEL: name: test_const_v2f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 1.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<2 x f32>) = G_BUILD_VECTOR [[C]](f32), [[C]](f32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(f32), [[UV1:%[0-9]+]]:_(f32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<2 x f32>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(f32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<4 x f32>) = G_BUILD_VECTOR [[UV]](f32), [[UV1]](f32), [[DEF]](f32), [[DEF]](f32)
  ; CHECK-NEXT:   $xmm0 = COPY [[BUILD_VECTOR1]](<4 x f32>)
  ; CHECK-NEXT:   RET 0, implicit $xmm0
  ret <2 x float> <float 1.0, float 1.0>
}

define <3 x float> @test_const_v3f32() {
  ; CHECK-LABEL: name: test_const_v3f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 1.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<3 x f32>) = G_BUILD_VECTOR [[C]](f32), [[C]](f32), [[C]](f32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(f32), [[UV1:%[0-9]+]]:_(f32), [[UV2:%[0-9]+]]:_(f32) = G_UNMERGE_VALUES [[BUILD_VECTOR]](<3 x f32>)
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:_(f32) = G_IMPLICIT_DEF
  ; CHECK-NEXT:   [[BUILD_VECTOR1:%[0-9]+]]:_(<4 x f32>) = G_BUILD_VECTOR [[UV]](f32), [[UV1]](f32), [[UV2]](f32), [[DEF]](f32)
  ; CHECK-NEXT:   $xmm0 = COPY [[BUILD_VECTOR1]](<4 x f32>)
  ; CHECK-NEXT:   RET 0, implicit $xmm0
  ret <3 x float> <float 1.0, float 1.0, float 1.0>
}

define <5 x float> @test_const_v5f32() {
  ; CHECK-LABEL: name: test_const_v5f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $rdi
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 1.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<5 x f32>) = G_BUILD_VECTOR [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<5 x f32>), [[COPY]](p0) :: (store (<5 x f32>), align 32)
  ; CHECK-NEXT:   $rax = COPY [[COPY]](p0)
  ; CHECK-NEXT:   RET 0, $rax
  ret <5 x float> <float 1.0, float 1.0, float 1.0, float 1.0, float 1.0>
}

define <6 x float> @test_const_v6f32() {
  ; CHECK-LABEL: name: test_const_v6f32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(p0) = COPY $rdi
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(f32) = G_FCONSTANT float 1.000000e+00
  ; CHECK-NEXT:   [[BUILD_VECTOR:%[0-9]+]]:_(<6 x f32>) = G_BUILD_VECTOR [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32), [[C]](f32)
  ; CHECK-NEXT:   G_STORE [[BUILD_VECTOR]](<6 x f32>), [[COPY]](p0) :: (store (<6 x f32>), align 32)
  ; CHECK-NEXT:   $rax = COPY [[COPY]](p0)
  ; CHECK-NEXT:   RET 0, $rax
  ret <6 x float> <float 1.0, float 1.0, float 1.0, float 1.0, float 1.0, float 1.0>
}
