; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 4
; RUN: opt < %s -S -passes="cgscc(openmp-opt-postlink-cgscc),ipsccp,simplifycfg" | FileCheck %s

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32, i32, i32 }

@__omp_offloading_daxpy_kernel_environment = weak_odr protected local_unnamed_addr constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 1024, i32 1, i32 1, i32 0, i32 0, i32 0, i32 0 }, ptr null, ptr null }

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #0

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #0

; Function Attrs: convergent nocallback nounwind
declare void @llvm.nvvm.barrier0() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #0

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #0

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #0

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected void @__omp_offloading_daxpy(ptr noalias noundef %arg, ptr noundef %arg1, i64 noundef %arg2, ptr noundef %arg3) local_unnamed_addr #2 {
entry:
  %i = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #4, !range !16
  %i4 = tail call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #5, !range !17
  %i5 = shl nsw i32 %i, 10
  %i6 = or disjoint i32 %i5, 1023
  %i7 = shl nsw i32 %i4, 10
  %i8 = tail call i32 @llvm.smin.i32(i32 %i6, i32 1023), !range !18
  %i9 = icmp slt i32 %i, 1
  br i1 %i9, label %bb, label %bb46

bb:                                               ; preds = %entry
  %i10 = inttoptr i64 %arg2 to ptr
  br label %bb11

bb11:                                             ; preds = %bb41, %bb
  %i12 = phi i32 [ %i8, %bb ], [ %i44, %bb41 ]
  %i13 = phi i32 [ %i5, %bb ], [ %i42, %bb41 ]
  %i14 = zext i32 %i13 to i64
  %i15 = zext i32 %i12 to i64
  %i16 = inttoptr i64 %i14 to ptr
  %i17 = inttoptr i64 %i15 to ptr
  %i18 = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #6
  %i19 = icmp eq i32 %i18, 0
  %i20 = ptrtoint ptr %i16 to i64
  %i21 = ptrtoint ptr %i17 to i64
  %i22 = trunc i64 %i20 to i32
  %i23 = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #4
  %i24 = add nsw i32 %i23, %i22
  %i25 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #5
  %i26 = sext i32 %i24 to i64
  %i27 = icmp ugt i64 %i26, %i21
  br i1 %i27, label %bb41, label %bb28

bb28:                                             ; preds = %bb11
  %i29 = bitcast i64 %arg2 to double
  br label %bb30

bb30:                                             ; preds = %bb30, %bb28
  %i31 = phi i64 [ %i26, %bb28 ], [ %i39, %bb30 ]
  %i32 = phi i32 [ %i24, %bb28 ], [ %i38, %bb30 ]
  tail call i1 @__ompx_split() #7
  %i33 = getelementptr inbounds double, ptr %arg3, i64 %i31
  %i34 = load double, ptr %i33, align 8, !tbaa !19
  %i35 = getelementptr inbounds double, ptr %arg1, i64 %i31
  %i36 = load double, ptr %i35, align 8, !tbaa !19
  %i37 = tail call double @llvm.fmuladd.f64(double %i29, double %i34, double %i36)
  store double %i37, ptr %i35, align 8, !tbaa !19
  %i38 = add nsw i32 %i25, %i32
  %i39 = sext i32 %i38 to i64
  %i40 = icmp ugt i64 %i39, %i21
  br i1 %i40, label %bb41, label %bb30

bb41:                                             ; preds = %bb30, %bb11
  tail call void @llvm.nvvm.barrier0() #8
  %i42 = add nsw i32 %i13, %i7
  %i43 = add nsw i32 %i12, %i7
  %i44 = tail call i32 @llvm.smin.i32(i32 %i43, i32 1023)
  %i45 = icmp slt i32 %i42, 1024
  br i1 %i45, label %bb11, label %bb46

bb46:                                             ; preds = %bb41, %entry
  ret void
}

; Function Attrs: convergent
declare i1 @__ompx_split() local_unnamed_addr #3

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fmuladd.f64(double, double, double) #0

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #1 = { convergent nocallback nounwind }
attributes #2 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "omp_target_num_teams"="1" "omp_target_thread_limit"="1024" "stack-protector-buffer-size"="8" "target-cpu"="sm_86" "target-features"="+ptx81,+sm_86" }
attributes #3 = { convergent "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_86" "target-features"="+ptx81,+sm_86" }
attributes #4 = { nofree nosync willreturn "llvm.assume"="ompx_no_call_asm" }
attributes #5 = { nosync "llvm.assume"="ompx_no_call_asm" }
attributes #6 = { nofree willreturn "llvm.assume"="ompx_no_call_asm" }
attributes #7 = { convergent nounwind }
attributes #8 = { "llvm.assume"="ompx_no_call_asm,ompx_aligned_barrier" }

!llvm.ident = !{!0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !1}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8, !9}
!nvvm.annotations = !{!10, !11, !12, !13}
!omp_offload.info = !{!14}
!nvvmir.version = !{!15}

!0 = !{!"clang version 19.0.0git (git@github.com:tgymnich/llvm-project.git 28b6d786631efec5a92d5068355fdc2b98d0178a)"}
!1 = !{!"clang version 3.8.0 (tags/RELEASE_380/final)"}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{i32 1, !"ThinLTO", i32 0}
!8 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!9 = !{i32 2, !"SDK Version", [2 x i32] [i32 12, i32 1]}
!10 = !{ptr @__omp_offloading_daxpy, !"maxclusterrank", i32 1}
!11 = !{ptr @__omp_offloading_daxpy, !"minctasm", i32 1}
!12 = !{ptr @__omp_offloading_daxpy, !"maxntidx", i32 1024}
!13 = !{ptr @__omp_offloading_daxpy, !"kernel", i32 1}
!14 = !{i32 0, i32 64769, i32 2753303, !"daxpy", i32 21, i32 0, i32 0}
!15 = !{i32 2, i32 0}
!16 = !{i32 0, i32 -1}
!17 = !{i32 1, i32 0}
!18 = !{i32 -2147483648, i32 1024}
!19 = !{!20, !20, i64 0}
!20 = !{!"double", !21, i64 0}
!21 = !{!"omnipotent char", !22, i64 0}
!22 = !{!"Simple C/C++ TBAA"}


; CHECK-LABEL: define weak_odr protected void @__omp_offloading_daxpy(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef [[ARG1:%.*]], i64 noundef [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I25:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #[[ATTR4:[0-9]+]]
; CHECK-NEXT:    [[I23:%.*]] = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    [[I18:%.*]] = tail call noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #[[ATTR6:[0-9]+]]
; CHECK-NEXT:    [[I4:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #[[ATTR4]], !range [[RNG17:![0-9]+]]
; CHECK-NEXT:    [[I:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #[[ATTR5]], !range [[RNG18:![0-9]+]]
; CHECK-NEXT:    [[I5:%.*]] = shl nsw i32 [[I]], 10
; CHECK-NEXT:    [[I6:%.*]] = or disjoint i32 [[I5]], 1023
; CHECK-NEXT:    [[I7:%.*]] = shl nsw i32 [[I4]], 10
; CHECK-NEXT:    [[I8:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I6]], i32 1023), !range [[RNG19:![0-9]+]]
; CHECK-NEXT:    [[I9:%.*]] = icmp slt i32 [[I]], 1
; CHECK-NEXT:    br i1 [[I9]], label [[BB:%.*]], label [[BB46:%.*]]
; CHECK:       bb:
; CHECK-NEXT:    [[I10:%.*]] = inttoptr i64 [[ARG2]] to ptr
; CHECK-NEXT:    br label [[BB11:%.*]]
; CHECK:       bb11:
; CHECK-NEXT:    [[I756:%.*]] = phi i32 [ [[I756]], [[BB41:%.*]] ], [ [[I7]], [[BB]] ]
; CHECK-NEXT:    [[I2554:%.*]] = phi i32 [ [[I2554]], [[BB41]] ], [ [[I25]], [[BB]] ]
; CHECK-NEXT:    [[I447:%.*]] = phi i32 [ [[I447]], [[BB41]] ], [ [[I4]], [[BB]] ]
; CHECK-NEXT:    [[I2344:%.*]] = phi i32 [ [[I2344]], [[BB41]] ], [ [[I23]], [[BB]] ]
; CHECK-NEXT:    [[I41:%.*]] = phi i32 [ [[I41]], [[BB41]] ], [ [[I]], [[BB]] ]
; CHECK-NEXT:    [[I1813:%.*]] = phi i32 [ [[I1813]], [[BB41]] ], [ [[I18]], [[BB]] ]
; CHECK-NEXT:    [[I12:%.*]] = phi i32 [ [[I8]], [[BB]] ], [ [[I44:%.*]], [[BB41]] ]
; CHECK-NEXT:    [[I13:%.*]] = phi i32 [ [[I5]], [[BB]] ], [ [[I42:%.*]], [[BB41]] ]
; CHECK-NEXT:    [[I14:%.*]] = zext i32 [[I13]] to i64
; CHECK-NEXT:    [[I15:%.*]] = zext i32 [[I12]] to i64
; CHECK-NEXT:    [[I16:%.*]] = inttoptr i64 [[I14]] to ptr
; CHECK-NEXT:    [[I17:%.*]] = inttoptr i64 [[I15]] to ptr
; CHECK-NEXT:    [[I19:%.*]] = icmp eq i32 [[I1813]], 0
; CHECK-NEXT:    [[I20:%.*]] = ptrtoint ptr [[I16]] to i64
; CHECK-NEXT:    [[I21:%.*]] = ptrtoint ptr [[I17]] to i64
; CHECK-NEXT:    [[I22:%.*]] = trunc i64 [[I20]] to i32
; CHECK-NEXT:    [[I24:%.*]] = add nsw i32 [[I2344]], [[I22]]
; CHECK-NEXT:    [[I26:%.*]] = sext i32 [[I24]] to i64
; CHECK-NEXT:    [[I27:%.*]] = icmp ugt i64 [[I26]], [[I21]]
; CHECK-NEXT:    br i1 [[I27]], label [[BB41]], label [[BB28:%.*]]
; CHECK:       bb28:
; CHECK-NEXT:    [[I29:%.*]] = bitcast i64 [[ARG2]] to double
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 acquire, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    [[I18_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 0
; CHECK-NEXT:    store i32 [[I1813]], ptr [[I18_CACHEIDX]], align 4
; CHECK-NEXT:    [[I_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[I41]], ptr [[I_CACHEIDX]], align 4
; CHECK-NEXT:    [[I23_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[I2344]], ptr [[I23_CACHEIDX]], align 4
; CHECK-NEXT:    [[I4_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[I447]], ptr [[I4_CACHEIDX]], align 4
; CHECK-NEXT:    [[I13_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 4
; CHECK-NEXT:    store i32 [[I13]], ptr [[I13_CACHEIDX]], align 4
; CHECK-NEXT:    [[I12_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 5
; CHECK-NEXT:    store i32 [[I12]], ptr [[I12_CACHEIDX]], align 4
; CHECK-NEXT:    [[I32_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 6
; CHECK-NEXT:    store i32 [[I24]], ptr [[I32_CACHEIDX]], align 4
; CHECK-NEXT:    [[I25_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 7
; CHECK-NEXT:    store i32 [[I2554]], ptr [[I25_CACHEIDX]], align 4
; CHECK-NEXT:    [[I31_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 8
; CHECK-NEXT:    store i64 [[I26]], ptr [[I31_CACHEIDX]], align 8
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
; CHECK:       bb41:
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR7:[0-9]+]]
; CHECK-NEXT:    [[I42]] = add nsw i32 [[I13]], [[I756]]
; CHECK-NEXT:    [[I43:%.*]] = add nsw i32 [[I12]], [[I756]]
; CHECK-NEXT:    [[I44]] = tail call i32 @llvm.smin.i32(i32 [[I43]], i32 1023)
; CHECK-NEXT:    [[I45:%.*]] = icmp slt i32 [[I42]], 1024
; CHECK-NEXT:    br i1 [[I45]], label [[BB11]], label [[BB46]]
; CHECK:       bb46:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define weak_odr protected void @__omp_offloading_daxpy_contd_0(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef [[ARG1:%.*]], i64 noundef [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR2]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 1
; CHECK-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT:%.*]], label [[THREADEXIT:%.*]]
; CHECK:       bb11:
; CHECK-NEXT:    [[I14:%.*]] = zext i32 [[I42:%.*]] to i64
; CHECK-NEXT:    [[I15:%.*]] = zext i32 [[I44:%.*]] to i64
; CHECK-NEXT:    [[I16:%.*]] = inttoptr i64 [[I14]] to ptr
; CHECK-NEXT:    [[I17:%.*]] = inttoptr i64 [[I15]] to ptr
; CHECK-NEXT:    [[I19:%.*]] = icmp eq i32 [[I1811:%.*]], 0
; CHECK-NEXT:    [[I20:%.*]] = ptrtoint ptr [[I16]] to i64
; CHECK-NEXT:    [[I21:%.*]] = ptrtoint ptr [[I17]] to i64
; CHECK-NEXT:    [[I22:%.*]] = trunc i64 [[I20]] to i32
; CHECK-NEXT:    [[I24:%.*]] = add nsw i32 [[I2342:%.*]], [[I22]]
; CHECK-NEXT:    [[I26:%.*]] = sext i32 [[I24]] to i64
; CHECK-NEXT:    [[I27:%.*]] = icmp ugt i64 [[I26]], [[I21]]
; CHECK-NEXT:    br i1 [[I27]], label [[BB41:%.*]], label [[BB28:%.*]]
; CHECK:       bb28:
; CHECK-NEXT:    [[I29:%.*]] = bitcast i64 [[ARG2]] to double
; CHECK-NEXT:    br label [[CACHESTORE:%.*]]
; CHECK:       CacheStore:
; CHECK-NEXT:    [[I2553:%.*]] = phi i32 [ [[I2552:%.*]], [[BB28]] ], [ [[I25_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I1251:%.*]] = phi i32 [ [[I44]], [[BB28]] ], [ [[I12_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I1349:%.*]] = phi i32 [ [[I42]], [[BB28]] ], [ [[I13_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I446:%.*]] = phi i32 [ [[I445:%.*]], [[BB28]] ], [ [[I4_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I2343:%.*]] = phi i32 [ [[I2342]], [[BB28]] ], [ [[I23_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I30:%.*]] = phi i32 [ [[I28:%.*]], [[BB28]] ], [ [[I_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I1812:%.*]] = phi i32 [ [[I1811]], [[BB28]] ], [ [[I18_CACHE:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I31:%.*]] = phi i64 [ [[I26]], [[BB28]] ], [ [[I39:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[I32:%.*]] = phi i32 [ [[I24]], [[BB28]] ], [ [[I38:%.*]], [[CACHEREMAT]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 acquire, align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[TMP9]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP10]], align 8
; CHECK-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    [[I18_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 0
; CHECK-NEXT:    store i32 [[I1812]], ptr [[I18_CACHEIDX]], align 4
; CHECK-NEXT:    [[I_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 1
; CHECK-NEXT:    store i32 [[I30]], ptr [[I_CACHEIDX]], align 4
; CHECK-NEXT:    [[I23_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 2
; CHECK-NEXT:    store i32 [[I2343]], ptr [[I23_CACHEIDX]], align 4
; CHECK-NEXT:    [[I4_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 3
; CHECK-NEXT:    store i32 [[I446]], ptr [[I4_CACHEIDX]], align 4
; CHECK-NEXT:    [[I13_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 4
; CHECK-NEXT:    store i32 [[I1349]], ptr [[I13_CACHEIDX]], align 4
; CHECK-NEXT:    [[I12_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 5
; CHECK-NEXT:    store i32 [[I1251]], ptr [[I12_CACHEIDX]], align 4
; CHECK-NEXT:    [[I32_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 6
; CHECK-NEXT:    store i32 [[I32]], ptr [[I32_CACHEIDX]], align 4
; CHECK-NEXT:    [[I25_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 7
; CHECK-NEXT:    store i32 [[I2553]], ptr [[I25_CACHEIDX]], align 4
; CHECK-NEXT:    [[I31_CACHEIDX:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL]], i32 0, i32 8
; CHECK-NEXT:    store i64 [[I31]], ptr [[I31_CACHEIDX]], align 8
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       CacheRemat:
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP11]], align 8
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds ptr, ptr [[TMP12]], i32 1
; CHECK-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP13]], align 8
; CHECK-NEXT:    [[CACHECELL1:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-NEXT:    [[I18_CACHEIDX2:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 0
; CHECK-NEXT:    [[I18_CACHE]] = load i32, ptr [[I18_CACHEIDX2]], align 4
; CHECK-NEXT:    [[I_CACHEIDX3:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 1
; CHECK-NEXT:    [[I_CACHE]] = load i32, ptr [[I_CACHEIDX3]], align 4
; CHECK-NEXT:    [[I23_CACHEIDX4:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 2
; CHECK-NEXT:    [[I23_CACHE]] = load i32, ptr [[I23_CACHEIDX4]], align 4
; CHECK-NEXT:    [[I4_CACHEIDX5:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 3
; CHECK-NEXT:    [[I4_CACHE]] = load i32, ptr [[I4_CACHEIDX5]], align 4
; CHECK-NEXT:    [[I13_CACHEIDX6:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 4
; CHECK-NEXT:    [[I13_CACHE]] = load i32, ptr [[I13_CACHEIDX6]], align 4
; CHECK-NEXT:    [[I12_CACHEIDX7:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 5
; CHECK-NEXT:    [[I12_CACHE]] = load i32, ptr [[I12_CACHEIDX7]], align 4
; CHECK-NEXT:    [[I32_CACHEIDX8:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 6
; CHECK-NEXT:    [[I32_CACHE:%.*]] = load i32, ptr [[I32_CACHEIDX8]], align 4
; CHECK-NEXT:    [[I25_CACHEIDX9:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 7
; CHECK-NEXT:    [[I25_CACHE]] = load i32, ptr [[I25_CACHEIDX9]], align 4
; CHECK-NEXT:    [[I31_CACHEIDX10:%.*]] = getelementptr inbounds [[CACHE_CELL]], ptr [[CACHECELL1]], i32 0, i32 8
; CHECK-NEXT:    [[I31_CACHE:%.*]] = load i64, ptr [[I31_CACHEIDX10]], align 8
; CHECK-NEXT:    [[I5_RECOMPUTE:%.*]] = shl nsw i32 [[I_CACHE]], 10
; CHECK-NEXT:    [[I6_RECOMPUTE:%.*]] = or disjoint i32 [[I5_RECOMPUTE]], 1023
; CHECK-NEXT:    [[I8_RECOMPUTE:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I6_RECOMPUTE]], i32 1023), !range [[RNG19]]
; CHECK-NEXT:    [[I7_RECOMPUTE:%.*]] = shl nsw i32 [[I4_CACHE]], 10
; CHECK-NEXT:    [[I14_RECOMPUTE:%.*]] = zext i32 [[I13_CACHE]] to i64
; CHECK-NEXT:    [[I16_RECOMPUTE:%.*]] = inttoptr i64 [[I14_RECOMPUTE]] to ptr
; CHECK-NEXT:    [[I20_RECOMPUTE:%.*]] = ptrtoint ptr [[I16_RECOMPUTE]] to i64
; CHECK-NEXT:    [[I22_RECOMPUTE:%.*]] = trunc i64 [[I20_RECOMPUTE]] to i32
; CHECK-NEXT:    [[I24_RECOMPUTE:%.*]] = add nsw i32 [[I23_CACHE]], [[I22_RECOMPUTE]]
; CHECK-NEXT:    [[I26_RECOMPUTE:%.*]] = sext i32 [[I24_RECOMPUTE]] to i64
; CHECK-NEXT:    [[I15_RECOMPUTE:%.*]] = zext i32 [[I12_CACHE]] to i64
; CHECK-NEXT:    [[I17_RECOMPUTE:%.*]] = inttoptr i64 [[I15_RECOMPUTE]] to ptr
; CHECK-NEXT:    [[I21_RECOMPUTE:%.*]] = ptrtoint ptr [[I17_RECOMPUTE]] to i64
; CHECK-NEXT:    [[I27_RECOMPUTE:%.*]] = icmp ugt i64 [[I26_RECOMPUTE]], [[I21_RECOMPUTE]]
; CHECK-NEXT:    [[I29_RECOMPUTE:%.*]] = bitcast i64 [[ARG2]] to double
; CHECK-NEXT:    [[I33:%.*]] = getelementptr inbounds double, ptr [[ARG3]], i64 [[I31_CACHE]]
; CHECK-NEXT:    [[I34:%.*]] = load double, ptr [[I33]], align 8, !tbaa [[TBAA20:![0-9]+]]
; CHECK-NEXT:    [[I35:%.*]] = getelementptr inbounds double, ptr [[ARG1]], i64 [[I31_CACHE]]
; CHECK-NEXT:    [[I36:%.*]] = load double, ptr [[I35]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[I37:%.*]] = tail call double @llvm.fmuladd.f64(double [[I29_RECOMPUTE]], double [[I34]], double [[I36]])
; CHECK-NEXT:    store double [[I37]], ptr [[I35]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[I38]] = add nsw i32 [[I25_CACHE]], [[I32_CACHE]]
; CHECK-NEXT:    [[I39]] = sext i32 [[I38]] to i64
; CHECK-NEXT:    [[I40:%.*]] = icmp ugt i64 [[I39]], [[I21_RECOMPUTE]]
; CHECK-NEXT:    br i1 [[I40]], label [[BB41]], label [[CACHESTORE]]
; CHECK:       bb41:
; CHECK-NEXT:    [[I755:%.*]] = phi i32 [ [[I7_RECOMPUTE]], [[CACHEREMAT]] ], [ [[I755]], [[BB11:%.*]] ]
; CHECK-NEXT:    [[I2552]] = phi i32 [ [[I25_CACHE]], [[CACHEREMAT]] ], [ [[I2552]], [[BB11]] ]
; CHECK-NEXT:    [[I1250:%.*]] = phi i32 [ [[I12_CACHE]], [[CACHEREMAT]] ], [ [[I44]], [[BB11]] ]
; CHECK-NEXT:    [[I1348:%.*]] = phi i32 [ [[I13_CACHE]], [[CACHEREMAT]] ], [ [[I42]], [[BB11]] ]
; CHECK-NEXT:    [[I445]] = phi i32 [ [[I4_CACHE]], [[CACHEREMAT]] ], [ [[I445]], [[BB11]] ]
; CHECK-NEXT:    [[I2342]] = phi i32 [ [[I23_CACHE]], [[CACHEREMAT]] ], [ [[I2342]], [[BB11]] ]
; CHECK-NEXT:    [[I28]] = phi i32 [ [[I_CACHE]], [[CACHEREMAT]] ], [ [[I28]], [[BB11]] ]
; CHECK-NEXT:    [[I1811]] = phi i32 [ [[I18_CACHE]], [[CACHEREMAT]] ], [ [[I1811]], [[BB11]] ]
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR7]]
; CHECK-NEXT:    [[I42]] = add nsw i32 [[I1348]], [[I755]]
; CHECK-NEXT:    [[I43:%.*]] = add nsw i32 [[I1250]], [[I755]]
; CHECK-NEXT:    [[I44]] = tail call i32 @llvm.smin.i32(i32 [[I43]], i32 1023)
; CHECK-NEXT:    [[I45:%.*]] = icmp slt i32 [[I42]], 1024
; CHECK-NEXT:    br i1 [[I45]], label [[BB11]], label [[BB46:%.*]]
; CHECK:       bb46:
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;.
; CHECK: [[RNG17]] = !{i32 1, i32 0}
; CHECK: [[RNG18]] = !{i32 0, i32 -1}
; CHECK: [[RNG19]] = !{i32 -2147483648, i32 1024}
; CHECK: [[TBAA20]] = !{[[META21:![0-9]+]], [[META21]], i64 0}
; CHECK: [[META21]] = !{!"double", [[META22:![0-9]+]], i64 0}
; CHECK: [[META22]] = !{!"omnipotent char", [[META23:![0-9]+]], i64 0}
; CHECK: [[META23]] = !{!"Simple C/C++ TBAA"}
;.
