; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 4
; RUN: opt < %s -S -passes="openmp-opt-postlink,ipsccp,simplifycfg" | FileCheck %s

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.DeviceMemoryPoolTy = type { ptr, i64 }
%struct.DeviceMemoryPoolTrackingTy = type { i64, i64, i64, i64 }
%struct.DeviceEnvironmentTy = type { i32, i32, i32, i32, i64, i64, i64, i64 }
%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32, i32, ptr }
%struct.NuclideGridPoint = type { double, double, double, double, double, double }

@__omp_rtl_device_memory_pool = weak protected global %struct.DeviceMemoryPoolTy zeroinitializer, align 8
@__omp_rtl_device_memory_pool_tracker = weak protected global %struct.DeviceMemoryPoolTrackingTy zeroinitializer, align 8
@__omp_rtl_device_environment = weak protected addrspace(4) global %struct.DeviceEnvironmentTy undef, align 8
@anon.c274b8f03cfdd4407cb1d89714014eb3.0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@anon.c274b8f03cfdd4407cb1d89714014eb3.1 = private unnamed_addr constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @anon.c274b8f03cfdd4407cb1d89714014eb3.0 }, align 8
@__omp_offloading_run_event_based_simulation_dynamic_environment = weak_odr protected global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_run_event_based_simulation_kernel_environment = weak_odr protected local_unnamed_addr constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 128, i32 0, i32 0, i32 0, i32 0, i32 0, ptr null }, ptr @anon.c274b8f03cfdd4407cb1d89714014eb3.1, ptr @__omp_offloading_run_event_based_simulation_dynamic_environment }
@llvm.used = appending global [3 x ptr] [ptr addrspacecast (ptr addrspace(4) @__omp_rtl_device_environment to ptr), ptr @__omp_rtl_device_memory_pool, ptr @__omp_rtl_device_memory_pool_tracker], section "llvm.metadata"

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #1

; Function Attrs: convergent nocallback nounwind
declare void @llvm.nvvm.barrier0() #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #0

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #0

; Function Attrs: alwaysinline norecurse nounwind
define weak_odr protected void @__omp_offloading_run_event_based_simulation(ptr noalias noundef %arg, ptr noundef nonnull align 8 dereferenceable(64) %arg1, ptr noundef nonnull align 8 dereferenceable(112) %arg2, ptr noundef %arg3) local_unnamed_addr #3 {
bb:
  %i = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x() #5
  %i4 = getelementptr inbounds i8, ptr %arg1, i64 24
  %i5 = load i32, ptr %i4, align 8, !tbaa !14
  %i6 = add nsw i32 %i5, -1
  %i7 = icmp sgt i32 %i5, 0
  br i1 %i7, label %bb8, label %bb330

bb8:                                              ; preds = %bb
  %i9 = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #6, !range !21
  %i10 = tail call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #7, !range !22
  %i11 = icmp ult i32 %i9, %i10
  tail call void @llvm.assume(i1 noundef %i11) #8
  %i12 = shl nsw i32 %i9, 7
  %i13 = shl nsw i32 %i10, 7
  %i14 = icmp slt i32 %i12, %i5
  br i1 %i14, label %bb15, label %bb330

bb15:                                             ; preds = %bb8
  %i16 = or disjoint i32 %i12, 127
  %i17 = tail call i32 @llvm.smin.i32(i32 %i16, i32 %i6), !range !23
  %i18 = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #7
  %i19 = getelementptr inbounds i8, ptr %arg1, i64 8
  %i20 = getelementptr inbounds i8, ptr %arg1, i64 16
  %i21 = getelementptr inbounds i8, ptr %arg2, i64 8
  %i22 = getelementptr inbounds i8, ptr %arg2, i64 24
  %i23 = getelementptr inbounds i8, ptr %arg2, i64 32
  %i24 = getelementptr inbounds i8, ptr %arg2, i64 40
  %i25 = getelementptr inbounds i8, ptr %arg2, i64 16
  %i26 = getelementptr inbounds i8, ptr %arg1, i64 40
  %i27 = getelementptr inbounds i8, ptr %arg1, i64 44
  %i28 = getelementptr inbounds i8, ptr %arg2, i64 76
  br label %bb29

bb29:                                             ; preds = %bb325, %bb15
  %i30 = phi i32 [ %i17, %bb15 ], [ %i328, %bb325 ]
  %i31 = phi i32 [ %i12, %bb15 ], [ %i326, %bb325 ]
  %i32 = zext i32 %i30 to i64
  tail call void @llvm.nvvm.barrier0() #9
  %i33 = load i32, ptr %i4, align 8, !tbaa !14
  %i34 = icmp sgt i32 %i33, 0
  br i1 %i34, label %bb35, label %bb325

bb35:                                             ; preds = %bb29
  %i36 = add nsw i32 %i31, %i
  %i37 = sext i32 %i36 to i64
  %i38 = icmp ugt i64 %i37, %i32
  br i1 %i38, label %bb325, label %bb39

bb39:                                             ; preds = %bb35, %bb302
  %i40 = phi i64 [ %i323, %bb302 ], [ %i37, %bb35 ]
  %i41 = trunc i64 %i40 to i32
  %i42 = shl nsw i32 %i41, 1
  %i43 = sext i32 %i42 to i64
  %i44 = and i64 %i43, 9223372036854775806
  %i45 = icmp eq i64 %i44, 0
  br i1 %i45, label %bb69, label %bb46

bb46:                                             ; preds = %bb39, %bb46
  %i47 = phi i64 [ %i58, %bb46 ], [ 0, %bb39 ]
  %i48 = phi i64 [ %i57, %bb46 ], [ 1, %bb39 ]
  %i49 = phi i64 [ %i60, %bb46 ], [ 1, %bb39 ]
  %i50 = phi i64 [ %i61, %bb46 ], [ 2806196910506780709, %bb39 ]
  %i51 = phi i64 [ %i62, %bb46 ], [ %i44, %bb39 ]
  %i52 = and i64 %i51, 1
  %i53 = icmp eq i64 %i52, 0
  %i54 = mul i64 %i50, %i47
  %i55 = add i64 %i54, %i49
  %i56 = select i1 %i53, i64 1, i64 %i50
  %i57 = mul i64 %i56, %i48
  %i58 = select i1 %i53, i64 %i47, i64 %i55
  %i59 = add i64 %i50, 1
  %i60 = mul i64 %i59, %i49
  %i61 = mul i64 %i50, %i50
  %i62 = lshr i64 %i51, 1
  %i63 = icmp ult i64 %i51, 2
  br i1 %i63, label %bb64, label %bb46

bb64:                                             ; preds = %bb46
  %i67 = mul i64 %i57, 1070
  %i68 = add i64 %i67, %i58
  br label %bb69

bb69:                                             ; preds = %bb64, %bb39
  %i70 = phi i64 [ 1070, %bb39 ], [ %i68, %bb64 ]
  %i71 = mul i64 %i70, 2806196910506780709
  %i72 = add i64 %i71, 1
  %i73 = and i64 %i72, 9223372036854775807
  %i74 = uitofp i64 %i73 to double
  %i75 = fmul double %i74, 0x3C00000000000000
  %i76 = mul i64 %i72, 2806196910506780709
  %i77 = add i64 %i76, 1
  %i78 = and i64 %i77, 9223372036854775807
  %i79 = uitofp i64 %i78 to double
  %i80 = fmul double %i79, 0x3C00000000000000
  %i81 = fcmp uge double %i80, 5.200000e-02
  br i1 %i81, label %bb82, label %bb103

bb82:                                             ; preds = %bb69
  %i83 = fcmp uge double %i80, 3.270000e-01
  br i1 %i83, label %bb84, label %bb103

bb84:                                             ; preds = %bb82
  %i85 = fcmp uge double %i80, 4.610000e-01
  br i1 %i85, label %bb86, label %bb103

bb86:                                             ; preds = %bb84
  %i87 = fcmp uge double %i80, 0x3FE3AE147AE147AF
  br i1 %i87, label %bb88, label %bb103

bb88:                                             ; preds = %bb86
  %i89 = fcmp uge double %i80, 6.790000e-01
  br i1 %i89, label %bb90, label %bb103

bb90:                                             ; preds = %bb88
  %i91 = fcmp uge double %i80, 0x3FE7D70A3D70A3D8
  br i1 %i91, label %bb92, label %bb103

bb92:                                             ; preds = %bb90
  %i93 = fcmp uge double %i80, 8.000000e-01
  br i1 %i93, label %bb94, label %bb103

bb94:                                             ; preds = %bb92
  %i95 = fcmp uge double %i80, 8.080000e-01
  br i1 %i95, label %bb96, label %bb103

bb96:                                             ; preds = %bb94
  %i97 = fcmp uge double %i80, 0x3FEA5604189374BD
  br i1 %i97, label %bb98, label %bb103

bb98:                                             ; preds = %bb96
  %i99 = fcmp uge double %i80, 0x3FEB22D0E560418A
  br i1 %i99, label %bb100, label %bb103

bb100:                                            ; preds = %bb98
  %i101 = fcmp uge double %i80, 0x3FEB8D4FDF3B645B
  br i1 %i101, label %bb102, label %bb103

bb102:                                            ; preds = %bb100
  br label %bb103

bb103:                                            ; preds = %bb102, %bb100, %bb98, %bb96, %bb94, %bb92, %bb90, %bb88, %bb86, %bb84, %bb82, %bb69
  %i104 = phi i32 [ 1, %bb69 ], [ 2, %bb82 ], [ 3, %bb84 ], [ 4, %bb86 ], [ 5, %bb88 ], [ 6, %bb90 ], [ 7, %bb92 ], [ 8, %bb94 ], [ 9, %bb96 ], [ 10, %bb98 ], [ 11, %bb100 ], [ 0, %bb102 ]
  %i105 = load i64, ptr %i19, align 8, !tbaa !24
  %i106 = load i64, ptr %i20, align 8, !tbaa !25
  %i107 = load ptr, ptr %arg2, align 8, !tbaa !26
  %i108 = load ptr, ptr %i21, align 8, !tbaa !28
  %i109 = load ptr, ptr %i22, align 8, !tbaa !29
  %i110 = load ptr, ptr %i23, align 8, !tbaa !30
  %i111 = load ptr, ptr %i24, align 8, !tbaa !31
  %i112 = load ptr, ptr %i25, align 8, !tbaa !32
  %i113 = load i32, ptr %i26, align 8, !tbaa !33
  %i114 = load i32, ptr %i27, align 4, !tbaa !34
  %i115 = load i32, ptr %i28, align 4, !tbaa !35
  switch i32 %i113, label %bb139 [
    i32 0, label %bb116
    i32 2, label %bb134
  ]

bb116:                                            ; preds = %bb103
  %i117 = mul nsw i64 %i106, %i105
  %i118 = icmp sgt i64 %i117, 2
  br i1 %i118, label %bb119, label %bb139

bb119:                                            ; preds = %bb116
  %i120 = add nsw i64 %i117, -1
  br label %bb121

bb121:                                            ; preds = %bb121, %bb119
  %i122 = phi i64 [ %i132, %bb121 ], [ %i120, %bb119 ]
  %i123 = phi i64 [ %i131, %bb121 ], [ 0, %bb119 ]
  %i124 = phi i64 [ %i130, %bb121 ], [ %i120, %bb119 ]
  %i125 = lshr i64 %i122, 1
  %i126 = add nuw nsw i64 %i125, %i123
  %i127 = getelementptr inbounds double, ptr %i109, i64 %i126
  %i128 = load double, ptr %i127, align 8, !tbaa !36
  %i129 = fcmp ogt double %i128, %i75
  %i130 = select i1 %i129, i64 %i126, i64 %i124
  %i131 = select i1 %i129, i64 %i123, i64 %i126
  %i132 = sub nsw i64 %i130, %i131
  %i133 = icmp sgt i64 %i132, 1
  br i1 %i133, label %bb121, label %bb139

bb134:                                            ; preds = %bb103
  tail call void @__ompx_split() #10
  %i135 = sitofp i32 %i114 to double
  %i136 = fdiv double 1.000000e+00, %i135
  %i137 = fdiv double %i75, %i136
  %i138 = fptosi double %i137 to i64
  br label %bb139

bb139:                                            ; preds = %bb121, %bb134, %bb116, %bb103
  %i140 = phi i64 [ %i138, %bb134 ], [ -1, %bb103 ], [ 0, %bb116 ], [ %i131, %bb121 ]
  %i141 = zext nneg i32 %i104 to i64
  %i142 = getelementptr inbounds i32, ptr %i107, i64 %i141
  %i143 = load i32, ptr %i142, align 4, !tbaa !38
  %i144 = icmp sgt i32 %i143, 0
  br i1 %i144, label %bb145, label %bb302

bb145:                                            ; preds = %bb139
  %i146 = mul nsw i32 %i115, %i104
  %i147 = mul nsw i64 %i140, %i105
  %i148 = getelementptr i32, ptr %i110, i64 %i147
  %i149 = add i64 %i106, -1
  %i150 = icmp sgt i64 %i106, 2
  %i151 = add nsw i32 %i114, -1
  %i152 = sext i32 %i151 to i64
  %i153 = icmp eq i64 %i140, %i152
  %i154 = add nsw i64 %i140, 1
  %i155 = mul nsw i64 %i154, %i105
  %i156 = getelementptr i32, ptr %i110, i64 %i155
  %i157 = trunc i64 %i106 to i32
  %i158 = add i32 %i157, -1
  br label %bb159

bb159:                                            ; preds = %bb255, %bb145
  %i160 = phi double [ 0.000000e+00, %bb145 ], [ %i298, %bb255 ]
  %i161 = phi double [ 0.000000e+00, %bb145 ], [ %i297, %bb255 ]
  %i162 = phi double [ 0.000000e+00, %bb145 ], [ %i296, %bb255 ]
  %i163 = phi double [ 0.000000e+00, %bb145 ], [ %i295, %bb255 ]
  %i164 = phi double [ 0.000000e+00, %bb145 ], [ %i294, %bb255 ]
  %i165 = phi i32 [ 0, %bb145 ], [ %i299, %bb255 ]
  %i166 = add nsw i32 %i165, %i146
  %i167 = sext i32 %i166 to i64
  %i168 = getelementptr inbounds i32, ptr %i112, i64 %i167
  %i169 = load i32, ptr %i168, align 4, !tbaa !38
  %i170 = getelementptr inbounds double, ptr %i108, i64 %i167
  %i171 = load double, ptr %i170, align 8, !tbaa !36
  switch i32 %i113, label %bb208 [
    i32 1, label %bb172
    i32 0, label %bb197
  ]

bb172:                                            ; preds = %bb159
  tail call void @__ompx_split() #10
  %i173 = sext i32 %i169 to i64
  %i174 = mul nsw i64 %i106, %i173
  %i175 = getelementptr %struct.NuclideGridPoint, ptr %i111, i64 %i174
  br i1 %i150, label %bb176, label %bb189

bb176:                                            ; preds = %bb172, %bb176
  %i177 = phi i64 [ %i187, %bb176 ], [ %i149, %bb172 ]
  %i178 = phi i64 [ %i186, %bb176 ], [ 0, %bb172 ]
  %i179 = phi i64 [ %i185, %bb176 ], [ %i149, %bb172 ]
  %i180 = lshr i64 %i177, 1
  %i181 = add nuw nsw i64 %i180, %i178
  %i182 = getelementptr inbounds %struct.NuclideGridPoint, ptr %i175, i64 %i181
  %i183 = load double, ptr %i182, align 8, !tbaa !39
  %i184 = fcmp ogt double %i183, %i75
  %i185 = select i1 %i184, i64 %i181, i64 %i179
  %i186 = select i1 %i184, i64 %i178, i64 %i181
  %i187 = sub nsw i64 %i185, %i186
  %i188 = icmp sgt i64 %i187, 1
  br i1 %i188, label %bb176, label %bb189

bb189:                                            ; preds = %bb176, %bb172
  %i190 = phi i64 [ 0, %bb172 ], [ %i186, %bb176 ]
  %i191 = icmp eq i64 %i190, %i149
  br i1 %i191, label %bb192, label %bb195

bb192:                                            ; preds = %bb189
  %i193 = getelementptr %struct.NuclideGridPoint, ptr %i175, i64 %i149
  %i194 = getelementptr i8, ptr %i193, i64 -48
  br label %bb255

bb195:                                            ; preds = %bb189
  %i196 = getelementptr %struct.NuclideGridPoint, ptr %i175, i64 %i190
  br label %bb255

bb197:                                            ; preds = %bb159
  %i198 = sext i32 %i169 to i64
  %i199 = getelementptr i32, ptr %i148, i64 %i198
  %i200 = load i32, ptr %i199, align 4, !tbaa !38
  %i201 = sext i32 %i200 to i64
  %i202 = icmp eq i64 %i149, %i201
  %i203 = mul nsw i64 %i106, %i198
  %i204 = getelementptr %struct.NuclideGridPoint, ptr %i111, i64 %i203
  %i205 = getelementptr %struct.NuclideGridPoint, ptr %i204, i64 %i201
  %i206 = select i1 %i202, i64 -48, i64 0
  %i207 = getelementptr i8, ptr %i205, i64 %i206
  br label %bb255

bb208:                                            ; preds = %bb159
  tail call void @__ompx_split() #10
  %i209 = sext i32 %i169 to i64
  %i210 = getelementptr i32, ptr %i148, i64 %i209
  %i211 = load i32, ptr %i210, align 4, !tbaa !38
  br i1 %i153, label %bb216, label %bb212

bb212:                                            ; preds = %bb208
  %i213 = getelementptr i32, ptr %i156, i64 %i209
  %i214 = load i32, ptr %i213, align 4, !tbaa !38
  %i215 = add nsw i32 %i214, 1
  br label %bb216

bb216:                                            ; preds = %bb212, %bb208
  %i217 = phi i32 [ %i215, %bb212 ], [ %i158, %bb208 ]
  %i218 = mul nsw i64 %i106, %i209
  %i219 = sext i32 %i211 to i64
  %i220 = getelementptr %struct.NuclideGridPoint, ptr %i111, i64 %i218
  %i221 = getelementptr %struct.NuclideGridPoint, ptr %i220, i64 %i219
  %i222 = load double, ptr %i221, align 8, !tbaa !39
  %i223 = sext i32 %i217 to i64
  %i224 = fcmp ult double %i222, %i75
  br i1 %i224, label %bb225, label %bb245

bb225:                                            ; preds = %bb216
  %i226 = getelementptr %struct.NuclideGridPoint, ptr %i220, i64 %i223
  %i227 = load double, ptr %i226, align 8, !tbaa !39
  %i228 = fcmp ugt double %i227, %i75
  br i1 %i228, label %bb229, label %bb245

bb229:                                            ; preds = %bb225
  %i230 = sub nsw i64 %i223, %i219
  %i231 = icmp sgt i64 %i230, 1
  br i1 %i231, label %bb232, label %bb245

bb232:                                            ; preds = %bb229, %bb232
  %i233 = phi i64 [ %i243, %bb232 ], [ %i230, %bb229 ]
  %i234 = phi i64 [ %i242, %bb232 ], [ %i219, %bb229 ]
  %i235 = phi i64 [ %i241, %bb232 ], [ %i223, %bb229 ]
  %i236 = lshr i64 %i233, 1
  %i237 = add nsw i64 %i236, %i234
  %i238 = getelementptr inbounds %struct.NuclideGridPoint, ptr %i220, i64 %i237
  %i239 = load double, ptr %i238, align 8, !tbaa !39
  %i240 = fcmp ogt double %i239, %i75
  %i241 = select i1 %i240, i64 %i237, i64 %i235
  %i242 = select i1 %i240, i64 %i234, i64 %i237
  %i243 = sub nsw i64 %i241, %i242
  %i244 = icmp sgt i64 %i243, 1
  br i1 %i244, label %bb232, label %bb245

bb245:                                            ; preds = %bb232, %bb229, %bb225, %bb216
  %i246 = phi i64 [ 0, %bb216 ], [ %i219, %bb229 ], [ %i149, %bb225 ], [ %i242, %bb232 ]
  %i247 = shl i64 %i246, 32
  %i248 = ashr exact i64 %i247, 32
  %i249 = icmp eq i64 %i248, %i149
  br i1 %i249, label %bb250, label %bb253

bb250:                                            ; preds = %bb245
  %i251 = getelementptr %struct.NuclideGridPoint, ptr %i220, i64 %i149
  %i252 = getelementptr i8, ptr %i251, i64 -48
  br label %bb255

bb253:                                            ; preds = %bb245
  %i254 = getelementptr %struct.NuclideGridPoint, ptr %i220, i64 %i248
  br label %bb255

bb255:                                            ; preds = %bb253, %bb250, %bb197, %bb195, %bb192
  %i256 = phi ptr [ %i194, %bb192 ], [ %i196, %bb195 ], [ %i252, %bb250 ], [ %i254, %bb253 ], [ %i207, %bb197 ]
  %i257 = getelementptr inbounds i8, ptr %i256, i64 48
  %i258 = load double, ptr %i257, align 8, !tbaa !39
  %i259 = fsub double %i258, %i75
  %i260 = load double, ptr %i256, align 8, !tbaa !39
  %i261 = fsub double %i258, %i260
  %i262 = getelementptr inbounds i8, ptr %i256, i64 56
  %i263 = load double, ptr %i262, align 8, !tbaa !41
  %i264 = getelementptr inbounds i8, ptr %i256, i64 8
  %i265 = load double, ptr %i264, align 8, !tbaa !41
  %i266 = fsub double %i263, %i265
  %i267 = fneg double %i259
  %i268 = fdiv double %i267, %i261
  %i269 = tail call double @llvm.fmuladd.f64(double %i268, double %i266, double %i263)
  %i270 = getelementptr inbounds i8, ptr %i256, i64 64
  %i271 = load double, ptr %i270, align 8, !tbaa !42
  %i272 = getelementptr inbounds i8, ptr %i256, i64 16
  %i273 = load double, ptr %i272, align 8, !tbaa !42
  %i274 = fsub double %i271, %i273
  %i275 = tail call double @llvm.fmuladd.f64(double %i268, double %i274, double %i271)
  %i276 = getelementptr inbounds i8, ptr %i256, i64 72
  %i277 = load double, ptr %i276, align 8, !tbaa !43
  %i278 = getelementptr inbounds i8, ptr %i256, i64 24
  %i279 = load double, ptr %i278, align 8, !tbaa !43
  %i280 = fsub double %i277, %i279
  %i281 = tail call double @llvm.fmuladd.f64(double %i268, double %i280, double %i277)
  %i282 = getelementptr inbounds i8, ptr %i256, i64 80
  %i283 = load double, ptr %i282, align 8, !tbaa !44
  %i284 = getelementptr inbounds i8, ptr %i256, i64 32
  %i285 = load double, ptr %i284, align 8, !tbaa !44
  %i286 = fsub double %i283, %i285
  %i287 = tail call double @llvm.fmuladd.f64(double %i268, double %i286, double %i283)
  %i288 = getelementptr inbounds i8, ptr %i256, i64 88
  %i289 = load double, ptr %i288, align 8, !tbaa !45
  %i290 = getelementptr inbounds i8, ptr %i256, i64 40
  %i291 = load double, ptr %i290, align 8, !tbaa !45
  %i292 = fsub double %i289, %i291
  %i293 = tail call double @llvm.fmuladd.f64(double %i268, double %i292, double %i289)
  %i294 = tail call double @llvm.fmuladd.f64(double %i269, double %i171, double %i164)
  %i295 = tail call double @llvm.fmuladd.f64(double %i275, double %i171, double %i163)
  %i296 = tail call double @llvm.fmuladd.f64(double %i281, double %i171, double %i162)
  %i297 = tail call double @llvm.fmuladd.f64(double %i287, double %i171, double %i161)
  %i298 = tail call double @llvm.fmuladd.f64(double %i293, double %i171, double %i160)
  %i299 = add nuw nsw i32 %i165, 1
  %i300 = load i32, ptr %i142, align 4, !tbaa !38
  %i301 = icmp slt i32 %i299, %i300
  br i1 %i301, label %bb159, label %bb302

bb302:                                            ; preds = %bb255, %bb139
  %i303 = phi double [ 0.000000e+00, %bb139 ], [ %i294, %bb255 ]
  %i304 = phi double [ 0.000000e+00, %bb139 ], [ %i295, %bb255 ]
  %i305 = phi double [ 0.000000e+00, %bb139 ], [ %i296, %bb255 ]
  %i306 = phi double [ 0.000000e+00, %bb139 ], [ %i297, %bb255 ]
  %i307 = phi double [ 0.000000e+00, %bb139 ], [ %i298, %bb255 ]
  %i308 = fcmp ogt double %i303, -1.000000e+00
  %i309 = select i1 %i308, double %i303, double -1.000000e+00
  %i310 = fcmp ogt double %i304, %i309
  %i311 = select i1 %i310, double %i304, double %i309
  %i312 = fcmp ogt double %i305, %i311
  %i313 = select i1 %i312, double %i305, double %i311
  %i314 = fcmp ogt double %i306, %i313
  %i315 = select i1 %i314, double %i306, double %i313
  %i316 = select i1 %i310, i64 2, i64 1
  %i317 = fcmp ogt double %i307, %i315
  %i318 = select i1 %i312, i64 3, i64 %i316
  %i319 = select i1 %i314, i64 4, i64 %i318
  %i320 = select i1 %i317, i64 5, i64 %i319
  %i321 = getelementptr inbounds i64, ptr %arg3, i64 %i40
  store i64 %i320, ptr %i321, align 8, !tbaa !46
  %i322 = add nsw i32 %i18, %i41
  %i323 = sext i32 %i322 to i64
  %i324 = icmp ugt i64 %i323, %i32
  br i1 %i324, label %bb325, label %bb39

bb325:                                            ; preds = %bb302, %bb35, %bb29
  tail call void @llvm.nvvm.barrier0() #9
  %i326 = add nsw i32 %i31, %i13
  %i327 = add nsw i32 %i30, %i13
  %i328 = tail call i32 @llvm.smin.i32(i32 %i327, i32 %i6)
  %i329 = icmp slt i32 %i326, %i5
  br i1 %i329, label %bb29, label %bb330

bb330:                                            ; preds = %bb325, %bb8, %bb
  ret void
}

; Function Attrs: convergent
declare void @__ompx_split(...) local_unnamed_addr #4

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fmuladd.f64(double, double, double) #0

attributes #0 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
attributes #2 = { convergent nocallback nounwind }
attributes #3 = { alwaysinline norecurse nounwind "frame-pointer"="all" "kernel" "no-trapping-math"="true" "omp_target_thread_limit"="128" "stack-protector-buffer-size"="8" "target-cpu"="sm_86" "target-features"="+ptx83,+sm_86" }
attributes #4 = { convergent "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_86" "target-features"="+ptx83,+sm_86" }
attributes #5 = { "llvm.assume"="ompx_no_call_asm" }
attributes #6 = { nofree nosync willreturn "llvm.assume"="ompx_no_call_asm" }
attributes #7 = { nosync "llvm.assume"="ompx_no_call_asm" }
attributes #8 = { memory(write) "llvm.assume"="ompx_no_call_asm" }
attributes #9 = { "llvm.assume"="ompx_no_call_asm,ompx_aligned_barrier" }
attributes #10 = { convergent nounwind }

!llvm.ident = !{!0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !1, !1, !0, !1, !1, !0, !1, !1, !0, !1, !1, !0, !1, !1, !0, !1, !1}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8, !9}
!nvvmir.version = !{!10, !10, !10, !10, !10, !10, !10, !10, !10, !10, !10, !10}
!nvvm.annotations = !{!11, !12}
!omp_offload.info = !{!13}

!0 = !{!"clang version 19.0.0git (git@github.com:tgymnich/llvm-project.git 3ab6ac657ffe454901ed6f5e78a906e9dba4e1af)"}
!1 = !{!"clang version 3.8.0 (tags/RELEASE_380/final)"}
!2 = !{i32 1, !"wchar_size", i32 4}
!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 2}
!7 = !{i32 1, !"ThinLTO", i32 0}
!8 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!9 = !{i32 2, !"SDK Version", [2 x i32] [i32 12, i32 3]}
!10 = !{i32 2, i32 0}
!11 = !{ptr @__omp_offloading_run_event_based_simulation, !"maxntidx", i32 128}
!12 = !{ptr @__omp_offloading_run_event_based_simulation, !"kernel", i32 1}
!13 = !{i32 0, i32 64769, i32 2228997, !"run_event_based_simulation", i32 51, i32 0, i32 0}
!14 = !{!15, !16, i64 24}
!15 = !{!"", !16, i64 0, !19, i64 8, !19, i64 16, !16, i64 24, !20, i64 32, !16, i64 40, !16, i64 44, !16, i64 48, !16, i64 52, !16, i64 56, !16, i64 60}
!16 = !{!"int", !17, i64 0}
!17 = !{!"omnipotent char", !18, i64 0}
!18 = !{!"Simple C/C++ TBAA"}
!19 = !{!"long", !17, i64 0}
!20 = !{!"any pointer", !17, i64 0}
!21 = !{i32 0, i32 -1}
!22 = !{i32 1, i32 0}
!23 = !{i32 -2147483648, i32 2147483647}
!24 = !{!15, !19, i64 8}
!25 = !{!15, !19, i64 16}
!26 = !{!27, !20, i64 0}
!27 = !{!"", !20, i64 0, !20, i64 8, !20, i64 16, !20, i64 24, !20, i64 32, !20, i64 40, !16, i64 48, !16, i64 52, !16, i64 56, !16, i64 60, !19, i64 64, !16, i64 72, !16, i64 76, !20, i64 80, !16, i64 88, !20, i64 96, !16, i64 104}
!28 = !{!27, !20, i64 8}
!29 = !{!27, !20, i64 24}
!30 = !{!27, !20, i64 32}
!31 = !{!27, !20, i64 40}
!32 = !{!27, !20, i64 16}
!33 = !{!15, !16, i64 40}
!34 = !{!15, !16, i64 44}
!35 = !{!27, !16, i64 76}
!36 = !{!37, !37, i64 0}
!37 = !{!"double", !17, i64 0}
!38 = !{!16, !16, i64 0}
!39 = !{!40, !37, i64 0}
!40 = !{!"", !37, i64 0, !37, i64 8, !37, i64 16, !37, i64 24, !37, i64 32, !37, i64 40}
!41 = !{!40, !37, i64 8}
!42 = !{!40, !37, i64 16}
!43 = !{!40, !37, i64 24}
!44 = !{!40, !37, i64 32}
!45 = !{!40, !37, i64 40}
!46 = !{!47, !47, i64 0}
!47 = !{!"long long", !17, i64 0}
; CHECK-LABEL: define weak_odr protected void @__omp_offloading_run_event_based_simulation(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef nonnull align 8 dereferenceable(64) [[ARG1:%.*]], ptr noundef nonnull align 8 dereferenceable(112) [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[I18:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    [[I10:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #[[ATTR5]], !range [[RNG17:![0-9]+]]
; CHECK-NEXT:    [[I9:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #[[ATTR6:[0-9]+]], !range [[RNG18:![0-9]+]]
; CHECK-NEXT:    [[I:%.*]] = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x() #[[ATTR7:[0-9]+]]
; CHECK-NEXT:    [[I4:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I5:%.*]] = load i32, ptr [[I4]], align 8, !tbaa [[TBAA19:![0-9]+]]
; CHECK-NEXT:    [[I6:%.*]] = add nsw i32 [[I5]], -1
; CHECK-NEXT:    [[I7:%.*]] = icmp sgt i32 [[I5]], 0
; CHECK-NEXT:    br i1 [[I7]], label [[BB8:%.*]], label [[BB330:%.*]]
; CHECK:       bb8:
; CHECK-NEXT:    [[I11:%.*]] = icmp ult i32 [[I9]], [[I10]]
; CHECK-NEXT:    tail call void @llvm.assume(i1 noundef [[I11]]) #[[ATTR8:[0-9]+]]
; CHECK-NEXT:    [[I12:%.*]] = shl nsw i32 [[I9]], 7
; CHECK-NEXT:    [[I13:%.*]] = shl nsw i32 [[I10]], 7
; CHECK-NEXT:    [[I14:%.*]] = icmp slt i32 [[I12]], [[I5]]
; CHECK-NEXT:    br i1 [[I14]], label [[BB15:%.*]], label [[BB330]]
; CHECK:       bb15:
; CHECK-NEXT:    [[I16:%.*]] = or disjoint i32 [[I12]], 127
; CHECK-NEXT:    [[I17:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I16]], i32 [[I6]]), !range [[RNG26:![0-9]+]]
; CHECK-NEXT:    [[I19:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 8
; CHECK-NEXT:    [[I20:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 16
; CHECK-NEXT:    [[I21:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 8
; CHECK-NEXT:    [[I22:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 24
; CHECK-NEXT:    [[I23:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 32
; CHECK-NEXT:    [[I24:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 40
; CHECK-NEXT:    [[I25:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 16
; CHECK-NEXT:    [[I26:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 40
; CHECK-NEXT:    [[I27:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 44
; CHECK-NEXT:    [[I28:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 76
; CHECK-NEXT:    br label [[BB29:%.*]]
; CHECK:       bb29:
; CHECK-NEXT:    [[I28320:%.*]] = phi ptr [ [[I28]], [[BB15]] ], [ [[I28325:%.*]], [[BB325:%.*]] ]
; CHECK-NEXT:    [[I25313:%.*]] = phi ptr [ [[I25]], [[BB15]] ], [ [[I25318:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I24306:%.*]] = phi ptr [ [[I24]], [[BB15]] ], [ [[I24311:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I23299:%.*]] = phi ptr [ [[I23]], [[BB15]] ], [ [[I23304:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I22292:%.*]] = phi ptr [ [[I22]], [[BB15]] ], [ [[I22297:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I21285:%.*]] = phi ptr [ [[I21]], [[BB15]] ], [ [[I21290:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I6284:%.*]] = phi i32 [ [[I6]], [[BB15]] ], [ [[I6282:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I27259:%.*]] = phi ptr [ [[I27]], [[BB15]] ], [ [[I27264:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I26252:%.*]] = phi ptr [ [[I26]], [[BB15]] ], [ [[I26257:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I20245:%.*]] = phi ptr [ [[I20]], [[BB15]] ], [ [[I20250:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I19238:%.*]] = phi ptr [ [[I19]], [[BB15]] ], [ [[I19243:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I4237:%.*]] = phi ptr [ [[I4]], [[BB15]] ], [ [[I4235:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I13226:%.*]] = phi i32 [ [[I13]], [[BB15]] ], [ [[I13229:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I18223:%.*]] = phi i32 [ [[I18]], [[BB15]] ], [ [[I18221:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I216:%.*]] = phi i32 [ [[I]], [[BB15]] ], [ [[I208:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I5183:%.*]] = phi i32 [ [[I5]], [[BB15]] ], [ [[I5181:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I10136:%.*]] = phi i32 [ [[I10]], [[BB15]] ], [ [[I10134:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I30:%.*]] = phi i32 [ [[I17]], [[BB15]] ], [ [[I328:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I31:%.*]] = phi i32 [ [[I12]], [[BB15]] ], [ [[I326:%.*]], [[BB325]] ]
; CHECK-NEXT:    [[I32:%.*]] = zext i32 [[I30]] to i64
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9:[0-9]+]]
; CHECK-NEXT:    [[I33:%.*]] = load i32, ptr [[I4237]], align 8, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[I34:%.*]] = icmp sgt i32 [[I33]], 0
; CHECK-NEXT:    br i1 [[I34]], label [[BB35:%.*]], label [[BB325]]
; CHECK:       bb35:
; CHECK-NEXT:    [[I36:%.*]] = add nsw i32 [[I31]], [[I216]]
; CHECK-NEXT:    [[I37:%.*]] = sext i32 [[I36]] to i64
; CHECK-NEXT:    [[I38:%.*]] = icmp ugt i64 [[I37]], [[I32]]
; CHECK-NEXT:    br i1 [[I38]], label [[BB325]], label [[BB39:%.*]]
; CHECK:       bb39:
; CHECK-NEXT:    [[I28326:%.*]] = phi ptr [ [[I28320]], [[BB35]] ], [ [[I28323:%.*]], [[BB302:%.*]] ]
; CHECK-NEXT:    [[I25319:%.*]] = phi ptr [ [[I25313]], [[BB35]] ], [ [[I25316:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I24312:%.*]] = phi ptr [ [[I24306]], [[BB35]] ], [ [[I24309:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I23305:%.*]] = phi ptr [ [[I23299]], [[BB35]] ], [ [[I23302:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I22298:%.*]] = phi ptr [ [[I22292]], [[BB35]] ], [ [[I22295:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I21291:%.*]] = phi ptr [ [[I21285]], [[BB35]] ], [ [[I21288:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I6283:%.*]] = phi i32 [ [[I6284]], [[BB35]] ], [ [[I6280:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I32277:%.*]] = phi i64 [ [[I32]], [[BB35]] ], [ [[I32275:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I27265:%.*]] = phi ptr [ [[I27259]], [[BB35]] ], [ [[I27262:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I26258:%.*]] = phi ptr [ [[I26252]], [[BB35]] ], [ [[I26255:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I20251:%.*]] = phi ptr [ [[I20245]], [[BB35]] ], [ [[I20248:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I19244:%.*]] = phi ptr [ [[I19238]], [[BB35]] ], [ [[I19241:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I4236:%.*]] = phi ptr [ [[I4237]], [[BB35]] ], [ [[I4233:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I13230:%.*]] = phi i32 [ [[I13226]], [[BB35]] ], [ [[I13227:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I18222:%.*]] = phi i32 [ [[I18223]], [[BB35]] ], [ [[I18219:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I212:%.*]] = phi i32 [ [[I216]], [[BB35]] ], [ [[I195:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I5182:%.*]] = phi i32 [ [[I5183]], [[BB35]] ], [ [[I5179:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I30176:%.*]] = phi i32 [ [[I30]], [[BB35]] ], [ [[I30173:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I31170:%.*]] = phi i32 [ [[I31]], [[BB35]] ], [ [[I31167:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I10135:%.*]] = phi i32 [ [[I10136]], [[BB35]] ], [ [[I10132:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I40:%.*]] = phi i64 [ [[I37]], [[BB35]] ], [ [[I323:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I41:%.*]] = trunc i64 [[I40]] to i32
; CHECK-NEXT:    [[I42:%.*]] = shl nsw i32 [[I41]], 1
; CHECK-NEXT:    [[I43:%.*]] = sext i32 [[I42]] to i64
; CHECK-NEXT:    [[I44:%.*]] = and i64 [[I43]], 9223372036854775806
; CHECK-NEXT:    [[I45:%.*]] = icmp eq i64 [[I44]], 0
; CHECK-NEXT:    br i1 [[I45]], label [[BB69:%.*]], label [[BB46:%.*]]
; CHECK:       bb46:
; CHECK-NEXT:    [[I47:%.*]] = phi i64 [ 0, [[BB39]] ], [ [[I58:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I48:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I57:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I49:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I60:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I50:%.*]] = phi i64 [ 2806196910506780709, [[BB39]] ], [ [[I61:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I51:%.*]] = phi i64 [ [[I44]], [[BB39]] ], [ [[I62:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I52:%.*]] = and i64 [[I51]], 1
; CHECK-NEXT:    [[I53:%.*]] = icmp eq i64 [[I52]], 0
; CHECK-NEXT:    [[I54:%.*]] = mul i64 [[I50]], [[I47]]
; CHECK-NEXT:    [[I55:%.*]] = add i64 [[I54]], [[I49]]
; CHECK-NEXT:    [[I56:%.*]] = select i1 [[I53]], i64 1, i64 [[I50]]
; CHECK-NEXT:    [[I57]] = mul i64 [[I56]], [[I48]]
; CHECK-NEXT:    [[I58]] = select i1 [[I53]], i64 [[I47]], i64 [[I55]]
; CHECK-NEXT:    [[I59:%.*]] = add i64 [[I50]], 1
; CHECK-NEXT:    [[I60]] = mul i64 [[I59]], [[I49]]
; CHECK-NEXT:    [[I61]] = mul i64 [[I50]], [[I50]]
; CHECK-NEXT:    [[I62]] = lshr i64 [[I51]], 1
; CHECK-NEXT:    [[I63:%.*]] = icmp ult i64 [[I51]], 2
; CHECK-NEXT:    br i1 [[I63]], label [[BB64:%.*]], label [[BB46]]
; CHECK:       bb64:
; CHECK-NEXT:    [[I67:%.*]] = mul i64 [[I57]], 1070
; CHECK-NEXT:    [[I68:%.*]] = add i64 [[I67]], [[I58]]
; CHECK-NEXT:    br label [[BB69]]
; CHECK:       bb69:
; CHECK-NEXT:    [[I70:%.*]] = phi i64 [ [[I68]], [[BB64]] ], [ 1070, [[BB39]] ]
; CHECK-NEXT:    [[I71:%.*]] = mul i64 [[I70]], 2806196910506780709
; CHECK-NEXT:    [[I72:%.*]] = add i64 [[I71]], 1
; CHECK-NEXT:    [[I73:%.*]] = and i64 [[I72]], 9223372036854775807
; CHECK-NEXT:    [[I74:%.*]] = uitofp i64 [[I73]] to double
; CHECK-NEXT:    [[I75:%.*]] = fmul double [[I74]], 0x3C00000000000000
; CHECK-NEXT:    [[I76:%.*]] = mul i64 [[I72]], 2806196910506780709
; CHECK-NEXT:    [[I77:%.*]] = add i64 [[I76]], 1
; CHECK-NEXT:    [[I78:%.*]] = and i64 [[I77]], 9223372036854775807
; CHECK-NEXT:    [[I79:%.*]] = uitofp i64 [[I78]] to double
; CHECK-NEXT:    [[I80:%.*]] = fmul double [[I79]], 0x3C00000000000000
; CHECK-NEXT:    [[I81:%.*]] = fcmp uge double [[I80]], 5.200000e-02
; CHECK-NEXT:    br i1 [[I81]], label [[BB82:%.*]], label [[BB103:%.*]]
; CHECK:       bb82:
; CHECK-NEXT:    [[I83:%.*]] = fcmp uge double [[I80]], 3.270000e-01
; CHECK-NEXT:    br i1 [[I83]], label [[BB84:%.*]], label [[BB103]]
; CHECK:       bb84:
; CHECK-NEXT:    [[I85:%.*]] = fcmp uge double [[I80]], 4.610000e-01
; CHECK-NEXT:    br i1 [[I85]], label [[BB86:%.*]], label [[BB103]]
; CHECK:       bb86:
; CHECK-NEXT:    [[I87:%.*]] = fcmp uge double [[I80]], 0x3FE3AE147AE147AF
; CHECK-NEXT:    br i1 [[I87]], label [[BB88:%.*]], label [[BB103]]
; CHECK:       bb88:
; CHECK-NEXT:    [[I89:%.*]] = fcmp uge double [[I80]], 6.790000e-01
; CHECK-NEXT:    br i1 [[I89]], label [[BB90:%.*]], label [[BB103]]
; CHECK:       bb90:
; CHECK-NEXT:    [[I91:%.*]] = fcmp uge double [[I80]], 0x3FE7D70A3D70A3D8
; CHECK-NEXT:    br i1 [[I91]], label [[BB92:%.*]], label [[BB103]]
; CHECK:       bb92:
; CHECK-NEXT:    [[I93:%.*]] = fcmp uge double [[I80]], 8.000000e-01
; CHECK-NEXT:    br i1 [[I93]], label [[BB94:%.*]], label [[BB103]]
; CHECK:       bb94:
; CHECK-NEXT:    [[I95:%.*]] = fcmp uge double [[I80]], 8.080000e-01
; CHECK-NEXT:    br i1 [[I95]], label [[BB96:%.*]], label [[BB103]]
; CHECK:       bb96:
; CHECK-NEXT:    [[I97:%.*]] = fcmp uge double [[I80]], 0x3FEA5604189374BD
; CHECK-NEXT:    br i1 [[I97]], label [[BB98:%.*]], label [[BB103]]
; CHECK:       bb98:
; CHECK-NEXT:    [[I99:%.*]] = fcmp uge double [[I80]], 0x3FEB22D0E560418A
; CHECK-NEXT:    br i1 [[I99]], label [[BB100:%.*]], label [[BB103]]
; CHECK:       bb100:
; CHECK-NEXT:    [[I101:%.*]] = fcmp uge double [[I80]], 0x3FEB8D4FDF3B645B
; CHECK-NEXT:    br i1 [[I101]], label [[BB103_FROM_BB102:%.*]], label [[BB103]]
; CHECK:       bb103.from.bb102:
; CHECK-NEXT:    br label [[BB103]]
; CHECK:       bb103:
; CHECK-NEXT:    [[I104:%.*]] = phi i32 [ 0, [[BB103_FROM_BB102]] ], [ 1, [[BB69]] ], [ 2, [[BB82]] ], [ 3, [[BB84]] ], [ 4, [[BB86]] ], [ 5, [[BB88]] ], [ 6, [[BB90]] ], [ 7, [[BB92]] ], [ 8, [[BB94]] ], [ 9, [[BB96]] ], [ 10, [[BB98]] ], [ 11, [[BB100]] ]
; CHECK-NEXT:    [[I105:%.*]] = load i64, ptr [[I19244]], align 8, !tbaa [[TBAA27:![0-9]+]]
; CHECK-NEXT:    [[I106:%.*]] = load i64, ptr [[I20251]], align 8, !tbaa [[TBAA28:![0-9]+]]
; CHECK-NEXT:    [[I107:%.*]] = load ptr, ptr [[ARG2]], align 8, !tbaa [[TBAA29:![0-9]+]]
; CHECK-NEXT:    [[I108:%.*]] = load ptr, ptr [[I21291]], align 8, !tbaa [[TBAA31:![0-9]+]]
; CHECK-NEXT:    [[I109:%.*]] = load ptr, ptr [[I22298]], align 8, !tbaa [[TBAA32:![0-9]+]]
; CHECK-NEXT:    [[I110:%.*]] = load ptr, ptr [[I23305]], align 8, !tbaa [[TBAA33:![0-9]+]]
; CHECK-NEXT:    [[I111:%.*]] = load ptr, ptr [[I24312]], align 8, !tbaa [[TBAA34:![0-9]+]]
; CHECK-NEXT:    [[I112:%.*]] = load ptr, ptr [[I25319]], align 8, !tbaa [[TBAA35:![0-9]+]]
; CHECK-NEXT:    [[I113:%.*]] = load i32, ptr [[I26258]], align 8, !tbaa [[TBAA36:![0-9]+]]
; CHECK-NEXT:    [[I114:%.*]] = load i32, ptr [[I27265]], align 4, !tbaa [[TBAA37:![0-9]+]]
; CHECK-NEXT:    [[I115:%.*]] = load i32, ptr [[I28326]], align 4, !tbaa [[TBAA38:![0-9]+]]
; CHECK-NEXT:    switch i32 [[I113]], label [[BB139:%.*]] [
; CHECK-NEXT:      i32 0, label [[BB116:%.*]]
; CHECK-NEXT:      i32 2, label [[CACHESTORE0:%.*]]
; CHECK-NEXT:    ]
; CHECK:       bb116:
; CHECK-NEXT:    [[I117:%.*]] = mul nsw i64 [[I106]], [[I105]]
; CHECK-NEXT:    [[I118:%.*]] = icmp sgt i64 [[I117]], 2
; CHECK-NEXT:    br i1 [[I118]], label [[BB119:%.*]], label [[BB139]]
; CHECK:       bb119:
; CHECK-NEXT:    [[I120:%.*]] = add nsw i64 [[I117]], -1
; CHECK-NEXT:    br label [[BB121:%.*]]
; CHECK:       bb121:
; CHECK-NEXT:    [[I122:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I132:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I123:%.*]] = phi i64 [ 0, [[BB119]] ], [ [[I131:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I124:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I130:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I125:%.*]] = lshr i64 [[I122]], 1
; CHECK-NEXT:    [[I126:%.*]] = add nuw nsw i64 [[I125]], [[I123]]
; CHECK-NEXT:    [[I127:%.*]] = getelementptr inbounds double, ptr [[I109]], i64 [[I126]]
; CHECK-NEXT:    [[I128:%.*]] = load double, ptr [[I127]], align 8, !tbaa [[TBAA39:![0-9]+]]
; CHECK-NEXT:    [[I129:%.*]] = fcmp ogt double [[I128]], [[I75]]
; CHECK-NEXT:    [[I130]] = select i1 [[I129]], i64 [[I126]], i64 [[I124]]
; CHECK-NEXT:    [[I131]] = select i1 [[I129]], i64 [[I123]], i64 [[I126]]
; CHECK-NEXT:    [[I132]] = sub nsw i64 [[I130]], [[I131]]
; CHECK-NEXT:    [[I133:%.*]] = icmp sgt i64 [[I132]], 1
; CHECK-NEXT:    br i1 [[I133]], label [[BB121]], label [[BB139]]
; CHECK:       CacheStore0:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I10135]], ptr [[TMP6]], align 4, !invariant.group [[META41:![0-9]+]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[TMP7]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I70]], ptr [[TMP8]], align 8, !invariant.group [[META42:![0-9]+]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i64, ptr [[TMP9]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[TMP10]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I115]], ptr [[TMP11]], align 4, !invariant.group [[META43:![0-9]+]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[TMP13]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP14]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I114]], ptr [[TMP15]], align 4, !invariant.group [[META44:![0-9]+]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i64, ptr [[TMP16]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP17]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[TMP18]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP19]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 2, ptr [[TMP20]], align 4, !invariant.group [[META45:![0-9]+]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i64, ptr [[TMP21]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i32, ptr [[TMP22]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP23]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds ptr, ptr [[TMP25]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I112]], ptr [[TMP26]], align 8, !invariant.group [[META46:![0-9]+]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP27]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP29]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i32, ptr [[TMP30]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds ptr, ptr [[TMP31]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds ptr, ptr [[TMP32]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I111]], ptr [[TMP33]], align 8, !invariant.group [[META47:![0-9]+]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i64, ptr [[TMP34]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i32, ptr [[TMP35]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i32, ptr [[TMP36]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds i32, ptr [[TMP37]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds ptr, ptr [[TMP38]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds ptr, ptr [[TMP39]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds ptr, ptr [[TMP40]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I110]], ptr [[TMP41]], align 8, !invariant.group [[META48:![0-9]+]]
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i64, ptr [[TMP42]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, ptr [[TMP43]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds i32, ptr [[TMP44]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP47:%.*]] = getelementptr inbounds ptr, ptr [[TMP46]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds ptr, ptr [[TMP47]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds ptr, ptr [[TMP48]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP50:%.*]] = getelementptr inbounds ptr, ptr [[TMP49]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I108]], ptr [[TMP50]], align 8, !invariant.group [[META49:![0-9]+]]
; CHECK-NEXT:    [[TMP51:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i64, ptr [[TMP51]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds i32, ptr [[TMP52]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds i32, ptr [[TMP53]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds i32, ptr [[TMP54]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP56:%.*]] = getelementptr inbounds ptr, ptr [[TMP55]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP57:%.*]] = getelementptr inbounds ptr, ptr [[TMP56]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP58:%.*]] = getelementptr inbounds ptr, ptr [[TMP57]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds ptr, ptr [[TMP58]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds ptr, ptr [[TMP59]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I107]], ptr [[TMP60]], align 8, !invariant.group [[META50:![0-9]+]]
; CHECK-NEXT:    [[TMP61:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP62:%.*]] = getelementptr inbounds i64, ptr [[TMP61]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds i32, ptr [[TMP63]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds i32, ptr [[TMP64]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP66:%.*]] = getelementptr inbounds ptr, ptr [[TMP65]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr inbounds ptr, ptr [[TMP66]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr inbounds ptr, ptr [[TMP67]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP69:%.*]] = getelementptr inbounds ptr, ptr [[TMP68]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP70:%.*]] = getelementptr inbounds ptr, ptr [[TMP69]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP71:%.*]] = getelementptr inbounds i64, ptr [[TMP70]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I106]], ptr [[TMP71]], align 8, !invariant.group [[META51:![0-9]+]]
; CHECK-NEXT:    [[TMP72:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP73:%.*]] = getelementptr inbounds i64, ptr [[TMP72]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds i32, ptr [[TMP73]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP75:%.*]] = getelementptr inbounds i32, ptr [[TMP74]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP76:%.*]] = getelementptr inbounds i32, ptr [[TMP75]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP77:%.*]] = getelementptr inbounds ptr, ptr [[TMP76]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP78:%.*]] = getelementptr inbounds ptr, ptr [[TMP77]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP79:%.*]] = getelementptr inbounds ptr, ptr [[TMP78]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP80:%.*]] = getelementptr inbounds ptr, ptr [[TMP79]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP81:%.*]] = getelementptr inbounds ptr, ptr [[TMP80]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP82:%.*]] = getelementptr inbounds i64, ptr [[TMP81]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP83:%.*]] = getelementptr inbounds i64, ptr [[TMP82]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I105]], ptr [[TMP83]], align 8, !invariant.group [[META52:![0-9]+]]
; CHECK-NEXT:    [[TMP84:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP85:%.*]] = getelementptr inbounds i64, ptr [[TMP84]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP86:%.*]] = getelementptr inbounds i32, ptr [[TMP85]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP87:%.*]] = getelementptr inbounds i32, ptr [[TMP86]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP88:%.*]] = getelementptr inbounds i32, ptr [[TMP87]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP89:%.*]] = getelementptr inbounds ptr, ptr [[TMP88]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP90:%.*]] = getelementptr inbounds ptr, ptr [[TMP89]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP91:%.*]] = getelementptr inbounds ptr, ptr [[TMP90]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr inbounds ptr, ptr [[TMP91]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP93:%.*]] = getelementptr inbounds ptr, ptr [[TMP92]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP94:%.*]] = getelementptr inbounds i64, ptr [[TMP93]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP95:%.*]] = getelementptr inbounds i64, ptr [[TMP94]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP96:%.*]] = getelementptr inbounds i32, ptr [[TMP95]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I104]], ptr [[TMP96]], align 4, !invariant.group [[META53:![0-9]+]]
; CHECK-NEXT:    [[TMP97:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP98:%.*]] = getelementptr inbounds i64, ptr [[TMP97]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP99:%.*]] = getelementptr inbounds i32, ptr [[TMP98]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP100:%.*]] = getelementptr inbounds i32, ptr [[TMP99]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i32, ptr [[TMP100]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP102:%.*]] = getelementptr inbounds ptr, ptr [[TMP101]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds ptr, ptr [[TMP102]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds ptr, ptr [[TMP103]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds ptr, ptr [[TMP104]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds ptr, ptr [[TMP105]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i64, ptr [[TMP106]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds i64, ptr [[TMP107]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds i32, ptr [[TMP108]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP110:%.*]] = getelementptr inbounds i64, ptr [[TMP109]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I40]], ptr [[TMP110]], align 8, !invariant.group [[META54:![0-9]+]]
; CHECK-NEXT:    [[TMP111:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP112:%.*]] = getelementptr inbounds i64, ptr [[TMP111]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP113:%.*]] = getelementptr inbounds i32, ptr [[TMP112]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP114:%.*]] = getelementptr inbounds i32, ptr [[TMP113]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP115:%.*]] = getelementptr inbounds i32, ptr [[TMP114]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP116:%.*]] = getelementptr inbounds ptr, ptr [[TMP115]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP117:%.*]] = getelementptr inbounds ptr, ptr [[TMP116]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP118:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP119:%.*]] = getelementptr inbounds ptr, ptr [[TMP118]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds ptr, ptr [[TMP119]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP121:%.*]] = getelementptr inbounds i64, ptr [[TMP120]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP122:%.*]] = getelementptr inbounds i64, ptr [[TMP121]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP123:%.*]] = getelementptr inbounds i32, ptr [[TMP122]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP124:%.*]] = getelementptr inbounds i64, ptr [[TMP123]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr inbounds i32, ptr [[TMP124]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I31170]], ptr [[TMP125]], align 4, !invariant.group [[META55:![0-9]+]]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP127:%.*]] = getelementptr inbounds i64, ptr [[TMP126]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP128:%.*]] = getelementptr inbounds i32, ptr [[TMP127]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP129:%.*]] = getelementptr inbounds i32, ptr [[TMP128]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP130:%.*]] = getelementptr inbounds i32, ptr [[TMP129]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP131:%.*]] = getelementptr inbounds ptr, ptr [[TMP130]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP132:%.*]] = getelementptr inbounds ptr, ptr [[TMP131]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP133:%.*]] = getelementptr inbounds ptr, ptr [[TMP132]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP134:%.*]] = getelementptr inbounds ptr, ptr [[TMP133]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP135:%.*]] = getelementptr inbounds ptr, ptr [[TMP134]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP136:%.*]] = getelementptr inbounds i64, ptr [[TMP135]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP137:%.*]] = getelementptr inbounds i64, ptr [[TMP136]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP138:%.*]] = getelementptr inbounds i32, ptr [[TMP137]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP139:%.*]] = getelementptr inbounds i64, ptr [[TMP138]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP140:%.*]] = getelementptr inbounds i32, ptr [[TMP139]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP141:%.*]] = getelementptr inbounds i32, ptr [[TMP140]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I30176]], ptr [[TMP141]], align 4, !invariant.group [[META56:![0-9]+]]
; CHECK-NEXT:    [[TMP142:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP143:%.*]] = getelementptr inbounds i64, ptr [[TMP142]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP144:%.*]] = getelementptr inbounds i32, ptr [[TMP143]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP145:%.*]] = getelementptr inbounds i32, ptr [[TMP144]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP146:%.*]] = getelementptr inbounds i32, ptr [[TMP145]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP147:%.*]] = getelementptr inbounds ptr, ptr [[TMP146]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP148:%.*]] = getelementptr inbounds ptr, ptr [[TMP147]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP149:%.*]] = getelementptr inbounds ptr, ptr [[TMP148]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP150:%.*]] = getelementptr inbounds ptr, ptr [[TMP149]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP151:%.*]] = getelementptr inbounds ptr, ptr [[TMP150]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP152:%.*]] = getelementptr inbounds i64, ptr [[TMP151]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP153:%.*]] = getelementptr inbounds i64, ptr [[TMP152]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP154:%.*]] = getelementptr inbounds i32, ptr [[TMP153]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP155:%.*]] = getelementptr inbounds i64, ptr [[TMP154]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP156:%.*]] = getelementptr inbounds i32, ptr [[TMP155]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP157:%.*]] = getelementptr inbounds i32, ptr [[TMP156]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP158:%.*]] = getelementptr inbounds i32, ptr [[TMP157]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I5182]], ptr [[TMP158]], align 4, !invariant.group [[META57:![0-9]+]]
; CHECK-NEXT:    [[TMP159:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP160:%.*]] = getelementptr inbounds i64, ptr [[TMP159]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP161:%.*]] = getelementptr inbounds i32, ptr [[TMP160]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP162:%.*]] = getelementptr inbounds i32, ptr [[TMP161]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP163:%.*]] = getelementptr inbounds i32, ptr [[TMP162]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP164:%.*]] = getelementptr inbounds ptr, ptr [[TMP163]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP165:%.*]] = getelementptr inbounds ptr, ptr [[TMP164]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP166:%.*]] = getelementptr inbounds ptr, ptr [[TMP165]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP167:%.*]] = getelementptr inbounds ptr, ptr [[TMP166]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP168:%.*]] = getelementptr inbounds ptr, ptr [[TMP167]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP169:%.*]] = getelementptr inbounds i64, ptr [[TMP168]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP170:%.*]] = getelementptr inbounds i64, ptr [[TMP169]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP171:%.*]] = getelementptr inbounds i32, ptr [[TMP170]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP172:%.*]] = getelementptr inbounds i64, ptr [[TMP171]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP173:%.*]] = getelementptr inbounds i32, ptr [[TMP172]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP174:%.*]] = getelementptr inbounds i32, ptr [[TMP173]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP175:%.*]] = getelementptr inbounds i32, ptr [[TMP174]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP176:%.*]] = getelementptr inbounds i32, ptr [[TMP175]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I212]], ptr [[TMP176]], align 4, !invariant.group [[META58:![0-9]+]]
; CHECK-NEXT:    [[TMP177:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP178:%.*]] = getelementptr inbounds i64, ptr [[TMP177]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP179:%.*]] = getelementptr inbounds i32, ptr [[TMP178]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP180:%.*]] = getelementptr inbounds i32, ptr [[TMP179]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP181:%.*]] = getelementptr inbounds i32, ptr [[TMP180]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP182:%.*]] = getelementptr inbounds ptr, ptr [[TMP181]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP183:%.*]] = getelementptr inbounds ptr, ptr [[TMP182]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP184:%.*]] = getelementptr inbounds ptr, ptr [[TMP183]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP185:%.*]] = getelementptr inbounds ptr, ptr [[TMP184]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP186:%.*]] = getelementptr inbounds ptr, ptr [[TMP185]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP187:%.*]] = getelementptr inbounds i64, ptr [[TMP186]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP188:%.*]] = getelementptr inbounds i64, ptr [[TMP187]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP189:%.*]] = getelementptr inbounds i32, ptr [[TMP188]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP190:%.*]] = getelementptr inbounds i64, ptr [[TMP189]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP191:%.*]] = getelementptr inbounds i32, ptr [[TMP190]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP192:%.*]] = getelementptr inbounds i32, ptr [[TMP191]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP193:%.*]] = getelementptr inbounds i32, ptr [[TMP192]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP194:%.*]] = getelementptr inbounds i32, ptr [[TMP193]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP195:%.*]] = getelementptr inbounds i32, ptr [[TMP194]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I18222]], ptr [[TMP195]], align 4, !invariant.group [[META59:![0-9]+]]
; CHECK-NEXT:    br label [[THREADEXIT:%.*]]
; CHECK:       bb139:
; CHECK-NEXT:    [[I140:%.*]] = phi i64 [ -1, [[BB103]] ], [ 0, [[BB116]] ], [ [[I131]], [[BB121]] ]
; CHECK-NEXT:    [[I141:%.*]] = zext nneg i32 [[I104]] to i64
; CHECK-NEXT:    [[I142:%.*]] = getelementptr inbounds i32, ptr [[I107]], i64 [[I141]]
; CHECK-NEXT:    [[I143:%.*]] = load i32, ptr [[I142]], align 4, !tbaa [[TBAA60:![0-9]+]]
; CHECK-NEXT:    [[I144:%.*]] = icmp sgt i32 [[I143]], 0
; CHECK-NEXT:    br i1 [[I144]], label [[BB145:%.*]], label [[BB302]]
; CHECK:       bb145:
; CHECK-NEXT:    [[I146:%.*]] = mul nsw i32 [[I115]], [[I104]]
; CHECK-NEXT:    [[I147:%.*]] = mul nsw i64 [[I140]], [[I105]]
; CHECK-NEXT:    [[I148:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I147]]
; CHECK-NEXT:    [[I149:%.*]] = add i64 [[I106]], -1
; CHECK-NEXT:    [[I150:%.*]] = icmp sgt i64 [[I106]], 2
; CHECK-NEXT:    [[I151:%.*]] = add nsw i32 [[I114]], -1
; CHECK-NEXT:    [[I152:%.*]] = sext i32 [[I151]] to i64
; CHECK-NEXT:    [[I153:%.*]] = icmp eq i64 [[I140]], [[I152]]
; CHECK-NEXT:    [[I154:%.*]] = add nsw i64 [[I140]], 1
; CHECK-NEXT:    [[I155:%.*]] = mul nsw i64 [[I154]], [[I105]]
; CHECK-NEXT:    [[I156:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I155]]
; CHECK-NEXT:    [[I157:%.*]] = trunc i64 [[I106]] to i32
; CHECK-NEXT:    [[I158:%.*]] = add i32 [[I157]], -1
; CHECK-NEXT:    br label [[BB159:%.*]]
; CHECK:       bb159:
; CHECK-NEXT:    [[I149345:%.*]] = phi i64 [ [[I149]], [[BB145]] ], [ [[I149345]], [[BB197:%.*]] ]
; CHECK-NEXT:    [[I156336:%.*]] = phi ptr [ [[I156]], [[BB145]] ], [ [[I156336]], [[BB197]] ]
; CHECK-NEXT:    [[I148334:%.*]] = phi ptr [ [[I148]], [[BB145]] ], [ [[I148334]], [[BB197]] ]
; CHECK-NEXT:    [[I153332:%.*]] = phi i1 [ [[I153]], [[BB145]] ], [ [[I153332]], [[BB197]] ]
; CHECK-NEXT:    [[I146330:%.*]] = phi i32 [ [[I146]], [[BB145]] ], [ [[I146330]], [[BB197]] ]
; CHECK-NEXT:    [[I142328:%.*]] = phi ptr [ [[I142]], [[BB145]] ], [ [[I142328]], [[BB197]] ]
; CHECK-NEXT:    [[I28324:%.*]] = phi ptr [ [[I28326]], [[BB145]] ], [ [[I28324]], [[BB197]] ]
; CHECK-NEXT:    [[I25317:%.*]] = phi ptr [ [[I25319]], [[BB145]] ], [ [[I25317]], [[BB197]] ]
; CHECK-NEXT:    [[I24310:%.*]] = phi ptr [ [[I24312]], [[BB145]] ], [ [[I24310]], [[BB197]] ]
; CHECK-NEXT:    [[I23303:%.*]] = phi ptr [ [[I23305]], [[BB145]] ], [ [[I23303]], [[BB197]] ]
; CHECK-NEXT:    [[I22296:%.*]] = phi ptr [ [[I22298]], [[BB145]] ], [ [[I22296]], [[BB197]] ]
; CHECK-NEXT:    [[I21289:%.*]] = phi ptr [ [[I21291]], [[BB145]] ], [ [[I21289]], [[BB197]] ]
; CHECK-NEXT:    [[I6281:%.*]] = phi i32 [ [[I6283]], [[BB145]] ], [ [[I6281]], [[BB197]] ]
; CHECK-NEXT:    [[I32276:%.*]] = phi i64 [ [[I32277]], [[BB145]] ], [ [[I32276]], [[BB197]] ]
; CHECK-NEXT:    [[I41272:%.*]] = phi i32 [ [[I41]], [[BB145]] ], [ [[I41272]], [[BB197]] ]
; CHECK-NEXT:    [[I75268:%.*]] = phi double [ [[I75]], [[BB145]] ], [ [[I75268]], [[BB197]] ]
; CHECK-NEXT:    [[I27263:%.*]] = phi ptr [ [[I27265]], [[BB145]] ], [ [[I27263]], [[BB197]] ]
; CHECK-NEXT:    [[I26256:%.*]] = phi ptr [ [[I26258]], [[BB145]] ], [ [[I26256]], [[BB197]] ]
; CHECK-NEXT:    [[I20249:%.*]] = phi ptr [ [[I20251]], [[BB145]] ], [ [[I20249]], [[BB197]] ]
; CHECK-NEXT:    [[I19242:%.*]] = phi ptr [ [[I19244]], [[BB145]] ], [ [[I19242]], [[BB197]] ]
; CHECK-NEXT:    [[I4234:%.*]] = phi ptr [ [[I4236]], [[BB145]] ], [ [[I4234]], [[BB197]] ]
; CHECK-NEXT:    [[I13228:%.*]] = phi i32 [ [[I13230]], [[BB145]] ], [ [[I13228]], [[BB197]] ]
; CHECK-NEXT:    [[I18220:%.*]] = phi i32 [ [[I18222]], [[BB145]] ], [ [[I18220]], [[BB197]] ]
; CHECK-NEXT:    [[I197:%.*]] = phi i32 [ [[I212]], [[BB145]] ], [ [[I197]], [[BB197]] ]
; CHECK-NEXT:    [[I5180:%.*]] = phi i32 [ [[I5182]], [[BB145]] ], [ [[I5180]], [[BB197]] ]
; CHECK-NEXT:    [[I30174:%.*]] = phi i32 [ [[I30176]], [[BB145]] ], [ [[I30174]], [[BB197]] ]
; CHECK-NEXT:    [[I31168:%.*]] = phi i32 [ [[I31170]], [[BB145]] ], [ [[I31168]], [[BB197]] ]
; CHECK-NEXT:    [[I40164:%.*]] = phi i64 [ [[I40]], [[BB145]] ], [ [[I40164]], [[BB197]] ]
; CHECK-NEXT:    [[I106158:%.*]] = phi i64 [ [[I106]], [[BB145]] ], [ [[I106158]], [[BB197]] ]
; CHECK-NEXT:    [[I108154:%.*]] = phi ptr [ [[I108]], [[BB145]] ], [ [[I108154]], [[BB197]] ]
; CHECK-NEXT:    [[I111150:%.*]] = phi ptr [ [[I111]], [[BB145]] ], [ [[I111150]], [[BB197]] ]
; CHECK-NEXT:    [[I112147:%.*]] = phi ptr [ [[I112]], [[BB145]] ], [ [[I112147]], [[BB197]] ]
; CHECK-NEXT:    [[I113144:%.*]] = phi i32 [ [[I113]], [[BB145]] ], [ 0, [[BB197]] ]
; CHECK-NEXT:    [[I70139:%.*]] = phi i64 [ [[I70]], [[BB145]] ], [ [[I70139]], [[BB197]] ]
; CHECK-NEXT:    [[I10133:%.*]] = phi i32 [ [[I10135]], [[BB145]] ], [ [[I10133]], [[BB197]] ]
; CHECK-NEXT:    [[I160:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I298:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I161:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I297:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I162:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I296:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I163:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I295:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I164:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I294:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I165:%.*]] = phi i32 [ 0, [[BB145]] ], [ [[I299:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I166:%.*]] = add nsw i32 [[I165]], [[I146330]]
; CHECK-NEXT:    [[I167:%.*]] = sext i32 [[I166]] to i64
; CHECK-NEXT:    [[I168:%.*]] = getelementptr inbounds i32, ptr [[I112147]], i64 [[I167]]
; CHECK-NEXT:    [[I169:%.*]] = load i32, ptr [[I168]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I170:%.*]] = getelementptr inbounds double, ptr [[I108154]], i64 [[I167]]
; CHECK-NEXT:    [[I171:%.*]] = load double, ptr [[I170]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    switch i32 [[I113144]], label [[CACHESTORE2:%.*]] [
; CHECK-NEXT:      i32 1, label [[CACHESTORE1:%.*]]
; CHECK-NEXT:      i32 0, label [[BB197]]
; CHECK-NEXT:    ]
; CHECK:       CacheStore1:
; CHECK-NEXT:    [[TMP196:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP197:%.*]] = load ptr, ptr [[TMP196]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR27:%.*]] = getelementptr inbounds i32, ptr [[TMP197]], i32 1
; CHECK-NEXT:    [[CACHEIDX28:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR27]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP198:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP199:%.*]] = load ptr, ptr [[TMP198]], align 8
; CHECK-NEXT:    [[TMP200:%.*]] = getelementptr inbounds ptr, ptr [[TMP199]], i32 1
; CHECK-NEXT:    [[CACHE_OUT_PTR29:%.*]] = load ptr, ptr [[TMP200]], align 8
; CHECK-NEXT:    [[TMP201:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET30:%.*]] = load i32, ptr [[TMP201]], align 4
; CHECK-NEXT:    [[TMP202:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP202]], align 4, !invariant.group [[META61:![0-9]+]]
; CHECK-NEXT:    [[TMP203:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP204:%.*]] = getelementptr inbounds i64, ptr [[TMP203]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP204]], align 8, !invariant.group [[META62:![0-9]+]]
; CHECK-NEXT:    [[TMP205:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP206:%.*]] = getelementptr inbounds i64, ptr [[TMP205]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP207:%.*]] = getelementptr inbounds ptr, ptr [[TMP206]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP207]], align 8, !invariant.group [[META63:![0-9]+]]
; CHECK-NEXT:    [[TMP208:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP209:%.*]] = getelementptr inbounds i64, ptr [[TMP208]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP210:%.*]] = getelementptr inbounds ptr, ptr [[TMP209]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP211:%.*]] = getelementptr inbounds i32, ptr [[TMP210]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP211]], align 4, !invariant.group [[META64:![0-9]+]]
; CHECK-NEXT:    [[TMP212:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP213:%.*]] = getelementptr inbounds i64, ptr [[TMP212]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP214:%.*]] = getelementptr inbounds ptr, ptr [[TMP213]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP215:%.*]] = getelementptr inbounds i32, ptr [[TMP214]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP216:%.*]] = getelementptr inbounds i1, ptr [[TMP215]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP216]], align 1, !invariant.group [[META65:![0-9]+]]
; CHECK-NEXT:    [[TMP217:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP218:%.*]] = getelementptr inbounds i64, ptr [[TMP217]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP219:%.*]] = getelementptr inbounds ptr, ptr [[TMP218]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP220:%.*]] = getelementptr inbounds i32, ptr [[TMP219]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP221:%.*]] = getelementptr inbounds i1, ptr [[TMP220]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP222:%.*]] = getelementptr inbounds ptr, ptr [[TMP221]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP222]], align 8, !invariant.group [[META66:![0-9]+]]
; CHECK-NEXT:    [[TMP223:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP224:%.*]] = getelementptr inbounds i64, ptr [[TMP223]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP225:%.*]] = getelementptr inbounds ptr, ptr [[TMP224]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP226:%.*]] = getelementptr inbounds i32, ptr [[TMP225]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP227:%.*]] = getelementptr inbounds i1, ptr [[TMP226]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP228:%.*]] = getelementptr inbounds ptr, ptr [[TMP227]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP229:%.*]] = getelementptr inbounds ptr, ptr [[TMP228]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP229]], align 8, !invariant.group [[META67:![0-9]+]]
; CHECK-NEXT:    [[TMP230:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP231:%.*]] = getelementptr inbounds i64, ptr [[TMP230]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP232:%.*]] = getelementptr inbounds ptr, ptr [[TMP231]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP233:%.*]] = getelementptr inbounds i32, ptr [[TMP232]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP234:%.*]] = getelementptr inbounds i1, ptr [[TMP233]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP235:%.*]] = getelementptr inbounds ptr, ptr [[TMP234]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP236:%.*]] = getelementptr inbounds ptr, ptr [[TMP235]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP237:%.*]] = getelementptr inbounds double, ptr [[TMP236]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP237]], align 8, !invariant.group [[META68:![0-9]+]]
; CHECK-NEXT:    [[TMP238:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP239:%.*]] = getelementptr inbounds i64, ptr [[TMP238]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP240:%.*]] = getelementptr inbounds ptr, ptr [[TMP239]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP241:%.*]] = getelementptr inbounds i32, ptr [[TMP240]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP242:%.*]] = getelementptr inbounds i1, ptr [[TMP241]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP243:%.*]] = getelementptr inbounds ptr, ptr [[TMP242]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP244:%.*]] = getelementptr inbounds ptr, ptr [[TMP243]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP245:%.*]] = getelementptr inbounds double, ptr [[TMP244]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP246:%.*]] = getelementptr inbounds i32, ptr [[TMP245]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP246]], align 4, !invariant.group [[META69:![0-9]+]]
; CHECK-NEXT:    [[TMP247:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP248:%.*]] = getelementptr inbounds i64, ptr [[TMP247]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP249:%.*]] = getelementptr inbounds ptr, ptr [[TMP248]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP250:%.*]] = getelementptr inbounds i32, ptr [[TMP249]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr inbounds i1, ptr [[TMP250]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr inbounds ptr, ptr [[TMP251]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP253:%.*]] = getelementptr inbounds ptr, ptr [[TMP252]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP254:%.*]] = getelementptr inbounds double, ptr [[TMP253]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP255:%.*]] = getelementptr inbounds i32, ptr [[TMP254]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr inbounds i32, ptr [[TMP255]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP256]], align 4, !invariant.group [[META70:![0-9]+]]
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP258:%.*]] = getelementptr inbounds i64, ptr [[TMP257]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr inbounds ptr, ptr [[TMP258]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr inbounds i32, ptr [[TMP259]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP261:%.*]] = getelementptr inbounds i1, ptr [[TMP260]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP262:%.*]] = getelementptr inbounds ptr, ptr [[TMP261]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP263:%.*]] = getelementptr inbounds ptr, ptr [[TMP262]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP264:%.*]] = getelementptr inbounds double, ptr [[TMP263]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP265:%.*]] = getelementptr inbounds i32, ptr [[TMP264]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP266:%.*]] = getelementptr inbounds i32, ptr [[TMP265]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP267:%.*]] = getelementptr inbounds double, ptr [[TMP266]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP267]], align 8, !invariant.group [[META71:![0-9]+]]
; CHECK-NEXT:    [[TMP268:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP269:%.*]] = getelementptr inbounds i64, ptr [[TMP268]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP270:%.*]] = getelementptr inbounds ptr, ptr [[TMP269]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP271:%.*]] = getelementptr inbounds i32, ptr [[TMP270]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP272:%.*]] = getelementptr inbounds i1, ptr [[TMP271]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP273:%.*]] = getelementptr inbounds ptr, ptr [[TMP272]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP274:%.*]] = getelementptr inbounds ptr, ptr [[TMP273]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP275:%.*]] = getelementptr inbounds double, ptr [[TMP274]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP276:%.*]] = getelementptr inbounds i32, ptr [[TMP275]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP277:%.*]] = getelementptr inbounds i32, ptr [[TMP276]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP278:%.*]] = getelementptr inbounds double, ptr [[TMP277]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP279:%.*]] = getelementptr inbounds double, ptr [[TMP278]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP279]], align 8, !invariant.group [[META72:![0-9]+]]
; CHECK-NEXT:    [[TMP280:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP281:%.*]] = getelementptr inbounds i64, ptr [[TMP280]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP282:%.*]] = getelementptr inbounds ptr, ptr [[TMP281]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP283:%.*]] = getelementptr inbounds i32, ptr [[TMP282]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP284:%.*]] = getelementptr inbounds i1, ptr [[TMP283]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP285:%.*]] = getelementptr inbounds ptr, ptr [[TMP284]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP286:%.*]] = getelementptr inbounds ptr, ptr [[TMP285]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP287:%.*]] = getelementptr inbounds double, ptr [[TMP286]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP288:%.*]] = getelementptr inbounds i32, ptr [[TMP287]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP289:%.*]] = getelementptr inbounds i32, ptr [[TMP288]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP290:%.*]] = getelementptr inbounds double, ptr [[TMP289]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP291:%.*]] = getelementptr inbounds double, ptr [[TMP290]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP292:%.*]] = getelementptr inbounds double, ptr [[TMP291]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP292]], align 8, !invariant.group [[META73:![0-9]+]]
; CHECK-NEXT:    [[TMP293:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP294:%.*]] = getelementptr inbounds i64, ptr [[TMP293]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP295:%.*]] = getelementptr inbounds ptr, ptr [[TMP294]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP296:%.*]] = getelementptr inbounds i32, ptr [[TMP295]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP297:%.*]] = getelementptr inbounds i1, ptr [[TMP296]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP298:%.*]] = getelementptr inbounds ptr, ptr [[TMP297]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP299:%.*]] = getelementptr inbounds ptr, ptr [[TMP298]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP300:%.*]] = getelementptr inbounds double, ptr [[TMP299]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP301:%.*]] = getelementptr inbounds i32, ptr [[TMP300]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP302:%.*]] = getelementptr inbounds i32, ptr [[TMP301]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP303:%.*]] = getelementptr inbounds double, ptr [[TMP302]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP304:%.*]] = getelementptr inbounds double, ptr [[TMP303]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP305:%.*]] = getelementptr inbounds double, ptr [[TMP304]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP306:%.*]] = getelementptr inbounds double, ptr [[TMP305]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP306]], align 8, !invariant.group [[META74:![0-9]+]]
; CHECK-NEXT:    [[TMP307:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP308:%.*]] = getelementptr inbounds i64, ptr [[TMP307]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP309:%.*]] = getelementptr inbounds ptr, ptr [[TMP308]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP310:%.*]] = getelementptr inbounds i32, ptr [[TMP309]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP311:%.*]] = getelementptr inbounds i1, ptr [[TMP310]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP312:%.*]] = getelementptr inbounds ptr, ptr [[TMP311]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP313:%.*]] = getelementptr inbounds ptr, ptr [[TMP312]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP314:%.*]] = getelementptr inbounds double, ptr [[TMP313]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP315:%.*]] = getelementptr inbounds i32, ptr [[TMP314]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP316:%.*]] = getelementptr inbounds i32, ptr [[TMP315]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP317:%.*]] = getelementptr inbounds double, ptr [[TMP316]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP318:%.*]] = getelementptr inbounds double, ptr [[TMP317]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP319:%.*]] = getelementptr inbounds double, ptr [[TMP318]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP320:%.*]] = getelementptr inbounds double, ptr [[TMP319]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP321:%.*]] = getelementptr inbounds double, ptr [[TMP320]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP321]], align 8, !invariant.group [[META75:![0-9]+]]
; CHECK-NEXT:    [[TMP322:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP323:%.*]] = getelementptr inbounds i64, ptr [[TMP322]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP324:%.*]] = getelementptr inbounds ptr, ptr [[TMP323]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP325:%.*]] = getelementptr inbounds i32, ptr [[TMP324]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP326:%.*]] = getelementptr inbounds i1, ptr [[TMP325]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP327:%.*]] = getelementptr inbounds ptr, ptr [[TMP326]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP328:%.*]] = getelementptr inbounds ptr, ptr [[TMP327]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP329:%.*]] = getelementptr inbounds double, ptr [[TMP328]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP330:%.*]] = getelementptr inbounds i32, ptr [[TMP329]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP331:%.*]] = getelementptr inbounds i32, ptr [[TMP330]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP332:%.*]] = getelementptr inbounds double, ptr [[TMP331]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP333:%.*]] = getelementptr inbounds double, ptr [[TMP332]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP334:%.*]] = getelementptr inbounds double, ptr [[TMP333]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP335:%.*]] = getelementptr inbounds double, ptr [[TMP334]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP336:%.*]] = getelementptr inbounds double, ptr [[TMP335]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP337:%.*]] = getelementptr inbounds i32, ptr [[TMP336]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 1, ptr [[TMP337]], align 4, !invariant.group [[META76:![0-9]+]]
; CHECK-NEXT:    [[TMP338:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP339:%.*]] = getelementptr inbounds i64, ptr [[TMP338]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP340:%.*]] = getelementptr inbounds ptr, ptr [[TMP339]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP341:%.*]] = getelementptr inbounds i32, ptr [[TMP340]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP342:%.*]] = getelementptr inbounds i1, ptr [[TMP341]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP343:%.*]] = getelementptr inbounds ptr, ptr [[TMP342]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP344:%.*]] = getelementptr inbounds ptr, ptr [[TMP343]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP345:%.*]] = getelementptr inbounds double, ptr [[TMP344]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP346:%.*]] = getelementptr inbounds i32, ptr [[TMP345]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP347:%.*]] = getelementptr inbounds i32, ptr [[TMP346]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP348:%.*]] = getelementptr inbounds double, ptr [[TMP347]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP349:%.*]] = getelementptr inbounds double, ptr [[TMP348]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP350:%.*]] = getelementptr inbounds double, ptr [[TMP349]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP351:%.*]] = getelementptr inbounds double, ptr [[TMP350]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP352:%.*]] = getelementptr inbounds double, ptr [[TMP351]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP353:%.*]] = getelementptr inbounds i32, ptr [[TMP352]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP354:%.*]] = getelementptr inbounds ptr, ptr [[TMP353]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP354]], align 8, !invariant.group [[META77:![0-9]+]]
; CHECK-NEXT:    [[TMP355:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP356:%.*]] = getelementptr inbounds i64, ptr [[TMP355]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP357:%.*]] = getelementptr inbounds ptr, ptr [[TMP356]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP358:%.*]] = getelementptr inbounds i32, ptr [[TMP357]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP359:%.*]] = getelementptr inbounds i1, ptr [[TMP358]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP360:%.*]] = getelementptr inbounds ptr, ptr [[TMP359]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP361:%.*]] = getelementptr inbounds ptr, ptr [[TMP360]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP362:%.*]] = getelementptr inbounds double, ptr [[TMP361]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP363:%.*]] = getelementptr inbounds i32, ptr [[TMP362]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP364:%.*]] = getelementptr inbounds i32, ptr [[TMP363]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP365:%.*]] = getelementptr inbounds double, ptr [[TMP364]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP366:%.*]] = getelementptr inbounds double, ptr [[TMP365]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP367:%.*]] = getelementptr inbounds double, ptr [[TMP366]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP368:%.*]] = getelementptr inbounds double, ptr [[TMP367]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP369:%.*]] = getelementptr inbounds double, ptr [[TMP368]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP370:%.*]] = getelementptr inbounds i32, ptr [[TMP369]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP371:%.*]] = getelementptr inbounds ptr, ptr [[TMP370]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP372:%.*]] = getelementptr inbounds ptr, ptr [[TMP371]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP372]], align 8, !invariant.group [[META78:![0-9]+]]
; CHECK-NEXT:    [[TMP373:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP374:%.*]] = getelementptr inbounds i64, ptr [[TMP373]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP375:%.*]] = getelementptr inbounds ptr, ptr [[TMP374]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP376:%.*]] = getelementptr inbounds i32, ptr [[TMP375]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP377:%.*]] = getelementptr inbounds i1, ptr [[TMP376]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP378:%.*]] = getelementptr inbounds ptr, ptr [[TMP377]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP379:%.*]] = getelementptr inbounds ptr, ptr [[TMP378]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP380:%.*]] = getelementptr inbounds double, ptr [[TMP379]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP381:%.*]] = getelementptr inbounds i32, ptr [[TMP380]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP382:%.*]] = getelementptr inbounds i32, ptr [[TMP381]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP383:%.*]] = getelementptr inbounds double, ptr [[TMP382]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP384:%.*]] = getelementptr inbounds double, ptr [[TMP383]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP385:%.*]] = getelementptr inbounds double, ptr [[TMP384]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP386:%.*]] = getelementptr inbounds double, ptr [[TMP385]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP387:%.*]] = getelementptr inbounds double, ptr [[TMP386]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP388:%.*]] = getelementptr inbounds i32, ptr [[TMP387]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP389:%.*]] = getelementptr inbounds ptr, ptr [[TMP388]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP390:%.*]] = getelementptr inbounds ptr, ptr [[TMP389]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP391:%.*]] = getelementptr inbounds ptr, ptr [[TMP390]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP391]], align 8, !invariant.group [[META79:![0-9]+]]
; CHECK-NEXT:    [[TMP392:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP393:%.*]] = getelementptr inbounds i64, ptr [[TMP392]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP394:%.*]] = getelementptr inbounds ptr, ptr [[TMP393]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP395:%.*]] = getelementptr inbounds i32, ptr [[TMP394]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP396:%.*]] = getelementptr inbounds i1, ptr [[TMP395]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP397:%.*]] = getelementptr inbounds ptr, ptr [[TMP396]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP398:%.*]] = getelementptr inbounds ptr, ptr [[TMP397]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP399:%.*]] = getelementptr inbounds double, ptr [[TMP398]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP400:%.*]] = getelementptr inbounds i32, ptr [[TMP399]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP401:%.*]] = getelementptr inbounds i32, ptr [[TMP400]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP402:%.*]] = getelementptr inbounds double, ptr [[TMP401]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP403:%.*]] = getelementptr inbounds double, ptr [[TMP402]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP404:%.*]] = getelementptr inbounds double, ptr [[TMP403]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP405:%.*]] = getelementptr inbounds double, ptr [[TMP404]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP406:%.*]] = getelementptr inbounds double, ptr [[TMP405]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP407:%.*]] = getelementptr inbounds i32, ptr [[TMP406]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP408:%.*]] = getelementptr inbounds ptr, ptr [[TMP407]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP409:%.*]] = getelementptr inbounds ptr, ptr [[TMP408]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP410:%.*]] = getelementptr inbounds ptr, ptr [[TMP409]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP411:%.*]] = getelementptr inbounds i64, ptr [[TMP410]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP411]], align 8, !invariant.group [[META80:![0-9]+]]
; CHECK-NEXT:    [[TMP412:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP413:%.*]] = getelementptr inbounds i64, ptr [[TMP412]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP414:%.*]] = getelementptr inbounds ptr, ptr [[TMP413]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP415:%.*]] = getelementptr inbounds i32, ptr [[TMP414]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP416:%.*]] = getelementptr inbounds i1, ptr [[TMP415]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP417:%.*]] = getelementptr inbounds ptr, ptr [[TMP416]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP418:%.*]] = getelementptr inbounds ptr, ptr [[TMP417]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP419:%.*]] = getelementptr inbounds double, ptr [[TMP418]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP420:%.*]] = getelementptr inbounds i32, ptr [[TMP419]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP421:%.*]] = getelementptr inbounds i32, ptr [[TMP420]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP422:%.*]] = getelementptr inbounds double, ptr [[TMP421]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP423:%.*]] = getelementptr inbounds double, ptr [[TMP422]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP424:%.*]] = getelementptr inbounds double, ptr [[TMP423]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP425:%.*]] = getelementptr inbounds double, ptr [[TMP424]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP426:%.*]] = getelementptr inbounds double, ptr [[TMP425]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP427:%.*]] = getelementptr inbounds i32, ptr [[TMP426]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP428:%.*]] = getelementptr inbounds ptr, ptr [[TMP427]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP429:%.*]] = getelementptr inbounds ptr, ptr [[TMP428]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP430:%.*]] = getelementptr inbounds ptr, ptr [[TMP429]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP431:%.*]] = getelementptr inbounds i64, ptr [[TMP430]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP432:%.*]] = getelementptr inbounds i64, ptr [[TMP431]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP432]], align 8, !invariant.group [[META81:![0-9]+]]
; CHECK-NEXT:    [[TMP433:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP434:%.*]] = getelementptr inbounds i64, ptr [[TMP433]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP435:%.*]] = getelementptr inbounds ptr, ptr [[TMP434]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP436:%.*]] = getelementptr inbounds i32, ptr [[TMP435]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP437:%.*]] = getelementptr inbounds i1, ptr [[TMP436]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP438:%.*]] = getelementptr inbounds ptr, ptr [[TMP437]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP439:%.*]] = getelementptr inbounds ptr, ptr [[TMP438]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP440:%.*]] = getelementptr inbounds double, ptr [[TMP439]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP441:%.*]] = getelementptr inbounds i32, ptr [[TMP440]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP442:%.*]] = getelementptr inbounds i32, ptr [[TMP441]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP443:%.*]] = getelementptr inbounds double, ptr [[TMP442]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP444:%.*]] = getelementptr inbounds double, ptr [[TMP443]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP445:%.*]] = getelementptr inbounds double, ptr [[TMP444]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP446:%.*]] = getelementptr inbounds double, ptr [[TMP445]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP447:%.*]] = getelementptr inbounds double, ptr [[TMP446]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP448:%.*]] = getelementptr inbounds i32, ptr [[TMP447]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP449:%.*]] = getelementptr inbounds ptr, ptr [[TMP448]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP450:%.*]] = getelementptr inbounds ptr, ptr [[TMP449]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP451:%.*]] = getelementptr inbounds ptr, ptr [[TMP450]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP452:%.*]] = getelementptr inbounds i64, ptr [[TMP451]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP453:%.*]] = getelementptr inbounds i64, ptr [[TMP452]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP454:%.*]] = getelementptr inbounds i32, ptr [[TMP453]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP454]], align 4, !invariant.group [[META82:![0-9]+]]
; CHECK-NEXT:    [[TMP455:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP456:%.*]] = getelementptr inbounds i64, ptr [[TMP455]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP457:%.*]] = getelementptr inbounds ptr, ptr [[TMP456]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP458:%.*]] = getelementptr inbounds i32, ptr [[TMP457]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP459:%.*]] = getelementptr inbounds i1, ptr [[TMP458]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP460:%.*]] = getelementptr inbounds ptr, ptr [[TMP459]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP461:%.*]] = getelementptr inbounds ptr, ptr [[TMP460]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP462:%.*]] = getelementptr inbounds double, ptr [[TMP461]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP463:%.*]] = getelementptr inbounds i32, ptr [[TMP462]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP464:%.*]] = getelementptr inbounds i32, ptr [[TMP463]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP465:%.*]] = getelementptr inbounds double, ptr [[TMP464]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP466:%.*]] = getelementptr inbounds double, ptr [[TMP465]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP467:%.*]] = getelementptr inbounds double, ptr [[TMP466]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP468:%.*]] = getelementptr inbounds double, ptr [[TMP467]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP469:%.*]] = getelementptr inbounds double, ptr [[TMP468]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP470:%.*]] = getelementptr inbounds i32, ptr [[TMP469]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP471:%.*]] = getelementptr inbounds ptr, ptr [[TMP470]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP472:%.*]] = getelementptr inbounds ptr, ptr [[TMP471]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP473:%.*]] = getelementptr inbounds ptr, ptr [[TMP472]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP474:%.*]] = getelementptr inbounds i64, ptr [[TMP473]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP475:%.*]] = getelementptr inbounds i64, ptr [[TMP474]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP476:%.*]] = getelementptr inbounds i32, ptr [[TMP475]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP477:%.*]] = getelementptr inbounds i32, ptr [[TMP476]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP477]], align 4, !invariant.group [[META83:![0-9]+]]
; CHECK-NEXT:    [[TMP478:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP479:%.*]] = getelementptr inbounds i64, ptr [[TMP478]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP480:%.*]] = getelementptr inbounds ptr, ptr [[TMP479]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP481:%.*]] = getelementptr inbounds i32, ptr [[TMP480]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP482:%.*]] = getelementptr inbounds i1, ptr [[TMP481]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP483:%.*]] = getelementptr inbounds ptr, ptr [[TMP482]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP484:%.*]] = getelementptr inbounds ptr, ptr [[TMP483]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP485:%.*]] = getelementptr inbounds double, ptr [[TMP484]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP486:%.*]] = getelementptr inbounds i32, ptr [[TMP485]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP487:%.*]] = getelementptr inbounds i32, ptr [[TMP486]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP488:%.*]] = getelementptr inbounds double, ptr [[TMP487]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP489:%.*]] = getelementptr inbounds double, ptr [[TMP488]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP490:%.*]] = getelementptr inbounds double, ptr [[TMP489]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP491:%.*]] = getelementptr inbounds double, ptr [[TMP490]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP492:%.*]] = getelementptr inbounds double, ptr [[TMP491]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP493:%.*]] = getelementptr inbounds i32, ptr [[TMP492]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP494:%.*]] = getelementptr inbounds ptr, ptr [[TMP493]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP495:%.*]] = getelementptr inbounds ptr, ptr [[TMP494]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP496:%.*]] = getelementptr inbounds ptr, ptr [[TMP495]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP497:%.*]] = getelementptr inbounds i64, ptr [[TMP496]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP498:%.*]] = getelementptr inbounds i64, ptr [[TMP497]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP499:%.*]] = getelementptr inbounds i32, ptr [[TMP498]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP500:%.*]] = getelementptr inbounds i32, ptr [[TMP499]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP501:%.*]] = getelementptr inbounds i32, ptr [[TMP500]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP501]], align 4, !invariant.group [[META84:![0-9]+]]
; CHECK-NEXT:    [[TMP502:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP503:%.*]] = getelementptr inbounds i64, ptr [[TMP502]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP504:%.*]] = getelementptr inbounds ptr, ptr [[TMP503]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP505:%.*]] = getelementptr inbounds i32, ptr [[TMP504]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP506:%.*]] = getelementptr inbounds i1, ptr [[TMP505]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP507:%.*]] = getelementptr inbounds ptr, ptr [[TMP506]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP508:%.*]] = getelementptr inbounds ptr, ptr [[TMP507]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP509:%.*]] = getelementptr inbounds double, ptr [[TMP508]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP510:%.*]] = getelementptr inbounds i32, ptr [[TMP509]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP511:%.*]] = getelementptr inbounds i32, ptr [[TMP510]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP512:%.*]] = getelementptr inbounds double, ptr [[TMP511]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP513:%.*]] = getelementptr inbounds double, ptr [[TMP512]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP514:%.*]] = getelementptr inbounds double, ptr [[TMP513]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP515:%.*]] = getelementptr inbounds double, ptr [[TMP514]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP516:%.*]] = getelementptr inbounds double, ptr [[TMP515]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP517:%.*]] = getelementptr inbounds i32, ptr [[TMP516]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP518:%.*]] = getelementptr inbounds ptr, ptr [[TMP517]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP519:%.*]] = getelementptr inbounds ptr, ptr [[TMP518]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP520:%.*]] = getelementptr inbounds ptr, ptr [[TMP519]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP521:%.*]] = getelementptr inbounds i64, ptr [[TMP520]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP522:%.*]] = getelementptr inbounds i64, ptr [[TMP521]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP523:%.*]] = getelementptr inbounds i32, ptr [[TMP522]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP524:%.*]] = getelementptr inbounds i32, ptr [[TMP523]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP525:%.*]] = getelementptr inbounds i32, ptr [[TMP524]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP526:%.*]] = getelementptr inbounds i32, ptr [[TMP525]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP526]], align 4, !invariant.group [[META85:![0-9]+]]
; CHECK-NEXT:    [[TMP527:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP528:%.*]] = getelementptr inbounds i64, ptr [[TMP527]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP529:%.*]] = getelementptr inbounds ptr, ptr [[TMP528]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP530:%.*]] = getelementptr inbounds i32, ptr [[TMP529]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP531:%.*]] = getelementptr inbounds i1, ptr [[TMP530]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP532:%.*]] = getelementptr inbounds ptr, ptr [[TMP531]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP533:%.*]] = getelementptr inbounds ptr, ptr [[TMP532]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP534:%.*]] = getelementptr inbounds double, ptr [[TMP533]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP535:%.*]] = getelementptr inbounds i32, ptr [[TMP534]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP536:%.*]] = getelementptr inbounds i32, ptr [[TMP535]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP537:%.*]] = getelementptr inbounds double, ptr [[TMP536]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP538:%.*]] = getelementptr inbounds double, ptr [[TMP537]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP539:%.*]] = getelementptr inbounds double, ptr [[TMP538]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP540:%.*]] = getelementptr inbounds double, ptr [[TMP539]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP541:%.*]] = getelementptr inbounds double, ptr [[TMP540]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP542:%.*]] = getelementptr inbounds i32, ptr [[TMP541]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP543:%.*]] = getelementptr inbounds ptr, ptr [[TMP542]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP544:%.*]] = getelementptr inbounds ptr, ptr [[TMP543]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP545:%.*]] = getelementptr inbounds ptr, ptr [[TMP544]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP546:%.*]] = getelementptr inbounds i64, ptr [[TMP545]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP547:%.*]] = getelementptr inbounds i64, ptr [[TMP546]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP548:%.*]] = getelementptr inbounds i32, ptr [[TMP547]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP549:%.*]] = getelementptr inbounds i32, ptr [[TMP548]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP550:%.*]] = getelementptr inbounds i32, ptr [[TMP549]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP551:%.*]] = getelementptr inbounds i32, ptr [[TMP550]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP552:%.*]] = getelementptr inbounds i32, ptr [[TMP551]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP552]], align 4, !invariant.group [[META86:![0-9]+]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb197:
; CHECK-NEXT:    [[I198:%.*]] = sext i32 [[I169]] to i64
; CHECK-NEXT:    [[I199:%.*]] = getelementptr i32, ptr [[I148334]], i64 [[I198]]
; CHECK-NEXT:    [[I200:%.*]] = load i32, ptr [[I199]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I201:%.*]] = sext i32 [[I200]] to i64
; CHECK-NEXT:    [[I202:%.*]] = icmp eq i64 [[I149345]], [[I201]]
; CHECK-NEXT:    [[I203:%.*]] = mul nsw i64 [[I106158]], [[I198]]
; CHECK-NEXT:    [[I204:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT:%.*]], ptr [[I111150]], i64 [[I203]]
; CHECK-NEXT:    [[I205:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I204]], i64 [[I201]]
; CHECK-NEXT:    [[I206:%.*]] = select i1 [[I202]], i64 -48, i64 0
; CHECK-NEXT:    [[I207:%.*]] = getelementptr i8, ptr [[I205]], i64 [[I206]]
; CHECK-NEXT:    [[I257:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 48
; CHECK-NEXT:    [[I258:%.*]] = load double, ptr [[I257]], align 8, !tbaa [[TBAA87:![0-9]+]]
; CHECK-NEXT:    [[I259:%.*]] = fsub double [[I258]], [[I75268]]
; CHECK-NEXT:    [[I260:%.*]] = load double, ptr [[I207]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I261:%.*]] = fsub double [[I258]], [[I260]]
; CHECK-NEXT:    [[I262:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 56
; CHECK-NEXT:    [[I263:%.*]] = load double, ptr [[I262]], align 8, !tbaa [[TBAA89:![0-9]+]]
; CHECK-NEXT:    [[I264:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 8
; CHECK-NEXT:    [[I265:%.*]] = load double, ptr [[I264]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I266:%.*]] = fsub double [[I263]], [[I265]]
; CHECK-NEXT:    [[I267:%.*]] = fneg double [[I259]]
; CHECK-NEXT:    [[I268:%.*]] = fdiv double [[I267]], [[I261]]
; CHECK-NEXT:    [[I269:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I266]], double [[I263]])
; CHECK-NEXT:    [[I270:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 64
; CHECK-NEXT:    [[I271:%.*]] = load double, ptr [[I270]], align 8, !tbaa [[TBAA90:![0-9]+]]
; CHECK-NEXT:    [[I272:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 16
; CHECK-NEXT:    [[I273:%.*]] = load double, ptr [[I272]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I274:%.*]] = fsub double [[I271]], [[I273]]
; CHECK-NEXT:    [[I275:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I274]], double [[I271]])
; CHECK-NEXT:    [[I276:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 72
; CHECK-NEXT:    [[I277:%.*]] = load double, ptr [[I276]], align 8, !tbaa [[TBAA91:![0-9]+]]
; CHECK-NEXT:    [[I278:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 24
; CHECK-NEXT:    [[I279:%.*]] = load double, ptr [[I278]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I280:%.*]] = fsub double [[I277]], [[I279]]
; CHECK-NEXT:    [[I281:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I280]], double [[I277]])
; CHECK-NEXT:    [[I282:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 80
; CHECK-NEXT:    [[I283:%.*]] = load double, ptr [[I282]], align 8, !tbaa [[TBAA92:![0-9]+]]
; CHECK-NEXT:    [[I284:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 32
; CHECK-NEXT:    [[I285:%.*]] = load double, ptr [[I284]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I286:%.*]] = fsub double [[I283]], [[I285]]
; CHECK-NEXT:    [[I287:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I286]], double [[I283]])
; CHECK-NEXT:    [[I288:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 88
; CHECK-NEXT:    [[I289:%.*]] = load double, ptr [[I288]], align 8, !tbaa [[TBAA93:![0-9]+]]
; CHECK-NEXT:    [[I290:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 40
; CHECK-NEXT:    [[I291:%.*]] = load double, ptr [[I290]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I292:%.*]] = fsub double [[I289]], [[I291]]
; CHECK-NEXT:    [[I293:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I292]], double [[I289]])
; CHECK-NEXT:    [[I294]] = tail call double @llvm.fmuladd.f64(double [[I269]], double [[I171]], double [[I164]])
; CHECK-NEXT:    [[I295]] = tail call double @llvm.fmuladd.f64(double [[I275]], double [[I171]], double [[I163]])
; CHECK-NEXT:    [[I296]] = tail call double @llvm.fmuladd.f64(double [[I281]], double [[I171]], double [[I162]])
; CHECK-NEXT:    [[I297]] = tail call double @llvm.fmuladd.f64(double [[I287]], double [[I171]], double [[I161]])
; CHECK-NEXT:    [[I298]] = tail call double @llvm.fmuladd.f64(double [[I293]], double [[I171]], double [[I160]])
; CHECK-NEXT:    [[I299]] = add nuw nsw i32 [[I165]], 1
; CHECK-NEXT:    [[I300:%.*]] = load i32, ptr [[I142328]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I301:%.*]] = icmp slt i32 [[I299]], [[I300]]
; CHECK-NEXT:    br i1 [[I301]], label [[BB159]], label [[BB302]]
; CHECK:       CacheStore2:
; CHECK-NEXT:    [[TMP553:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP554:%.*]] = load ptr, ptr [[TMP553]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR70:%.*]] = getelementptr inbounds i32, ptr [[TMP554]], i32 2
; CHECK-NEXT:    [[CACHEIDX71:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR70]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP555:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP556:%.*]] = load ptr, ptr [[TMP555]], align 8
; CHECK-NEXT:    [[TMP557:%.*]] = getelementptr inbounds ptr, ptr [[TMP556]], i32 2
; CHECK-NEXT:    [[CACHE_OUT_PTR72:%.*]] = load ptr, ptr [[TMP557]], align 8
; CHECK-NEXT:    [[TMP558:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET73:%.*]] = load i32, ptr [[TMP558]], align 4
; CHECK-NEXT:    [[TMP559:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP559]], align 4, !invariant.group [[META94:![0-9]+]]
; CHECK-NEXT:    [[TMP560:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP561:%.*]] = getelementptr inbounds i64, ptr [[TMP560]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP561]], align 8, !invariant.group [[META95:![0-9]+]]
; CHECK-NEXT:    [[TMP562:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP563:%.*]] = getelementptr inbounds i64, ptr [[TMP562]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP564:%.*]] = getelementptr inbounds ptr, ptr [[TMP563]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP564]], align 8, !invariant.group [[META96:![0-9]+]]
; CHECK-NEXT:    [[TMP565:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP566:%.*]] = getelementptr inbounds i64, ptr [[TMP565]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP567:%.*]] = getelementptr inbounds ptr, ptr [[TMP566]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP568:%.*]] = getelementptr inbounds i32, ptr [[TMP567]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP568]], align 4, !invariant.group [[META97:![0-9]+]]
; CHECK-NEXT:    [[TMP569:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP570:%.*]] = getelementptr inbounds i64, ptr [[TMP569]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP571:%.*]] = getelementptr inbounds ptr, ptr [[TMP570]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP572:%.*]] = getelementptr inbounds i32, ptr [[TMP571]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP573:%.*]] = getelementptr inbounds i1, ptr [[TMP572]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP573]], align 1, !invariant.group [[META98:![0-9]+]]
; CHECK-NEXT:    [[TMP574:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP575:%.*]] = getelementptr inbounds i64, ptr [[TMP574]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP576:%.*]] = getelementptr inbounds ptr, ptr [[TMP575]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP577:%.*]] = getelementptr inbounds i32, ptr [[TMP576]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP578:%.*]] = getelementptr inbounds i1, ptr [[TMP577]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP579:%.*]] = getelementptr inbounds ptr, ptr [[TMP578]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP579]], align 8, !invariant.group [[META99:![0-9]+]]
; CHECK-NEXT:    [[TMP580:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP581:%.*]] = getelementptr inbounds i64, ptr [[TMP580]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP582:%.*]] = getelementptr inbounds ptr, ptr [[TMP581]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP583:%.*]] = getelementptr inbounds i32, ptr [[TMP582]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP584:%.*]] = getelementptr inbounds i1, ptr [[TMP583]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP585:%.*]] = getelementptr inbounds ptr, ptr [[TMP584]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP586:%.*]] = getelementptr inbounds ptr, ptr [[TMP585]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP586]], align 8, !invariant.group [[META100:![0-9]+]]
; CHECK-NEXT:    [[TMP587:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP588:%.*]] = getelementptr inbounds i64, ptr [[TMP587]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP589:%.*]] = getelementptr inbounds ptr, ptr [[TMP588]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP590:%.*]] = getelementptr inbounds i32, ptr [[TMP589]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP591:%.*]] = getelementptr inbounds i1, ptr [[TMP590]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP592:%.*]] = getelementptr inbounds ptr, ptr [[TMP591]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP593:%.*]] = getelementptr inbounds ptr, ptr [[TMP592]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP594:%.*]] = getelementptr inbounds double, ptr [[TMP593]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP594]], align 8, !invariant.group [[META101:![0-9]+]]
; CHECK-NEXT:    [[TMP595:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP596:%.*]] = getelementptr inbounds i64, ptr [[TMP595]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP597:%.*]] = getelementptr inbounds ptr, ptr [[TMP596]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP598:%.*]] = getelementptr inbounds i32, ptr [[TMP597]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP599:%.*]] = getelementptr inbounds i1, ptr [[TMP598]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP600:%.*]] = getelementptr inbounds ptr, ptr [[TMP599]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP601:%.*]] = getelementptr inbounds ptr, ptr [[TMP600]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP602:%.*]] = getelementptr inbounds double, ptr [[TMP601]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP603:%.*]] = getelementptr inbounds i32, ptr [[TMP602]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP603]], align 4, !invariant.group [[META102:![0-9]+]]
; CHECK-NEXT:    [[TMP604:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP605:%.*]] = getelementptr inbounds i64, ptr [[TMP604]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP606:%.*]] = getelementptr inbounds ptr, ptr [[TMP605]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP607:%.*]] = getelementptr inbounds i32, ptr [[TMP606]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP608:%.*]] = getelementptr inbounds i1, ptr [[TMP607]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP609:%.*]] = getelementptr inbounds ptr, ptr [[TMP608]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP610:%.*]] = getelementptr inbounds ptr, ptr [[TMP609]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP611:%.*]] = getelementptr inbounds double, ptr [[TMP610]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP612:%.*]] = getelementptr inbounds i32, ptr [[TMP611]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP613:%.*]] = getelementptr inbounds i32, ptr [[TMP612]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP613]], align 4, !invariant.group [[META103:![0-9]+]]
; CHECK-NEXT:    [[TMP614:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP615:%.*]] = getelementptr inbounds i64, ptr [[TMP614]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP616:%.*]] = getelementptr inbounds ptr, ptr [[TMP615]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP617:%.*]] = getelementptr inbounds i32, ptr [[TMP616]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP618:%.*]] = getelementptr inbounds i1, ptr [[TMP617]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP619:%.*]] = getelementptr inbounds ptr, ptr [[TMP618]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP620:%.*]] = getelementptr inbounds ptr, ptr [[TMP619]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP621:%.*]] = getelementptr inbounds double, ptr [[TMP620]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP622:%.*]] = getelementptr inbounds i32, ptr [[TMP621]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP623:%.*]] = getelementptr inbounds i32, ptr [[TMP622]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP624:%.*]] = getelementptr inbounds double, ptr [[TMP623]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP624]], align 8, !invariant.group [[META104:![0-9]+]]
; CHECK-NEXT:    [[TMP625:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP626:%.*]] = getelementptr inbounds i64, ptr [[TMP625]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP627:%.*]] = getelementptr inbounds ptr, ptr [[TMP626]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP628:%.*]] = getelementptr inbounds i32, ptr [[TMP627]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP629:%.*]] = getelementptr inbounds i1, ptr [[TMP628]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP630:%.*]] = getelementptr inbounds ptr, ptr [[TMP629]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP631:%.*]] = getelementptr inbounds ptr, ptr [[TMP630]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP632:%.*]] = getelementptr inbounds double, ptr [[TMP631]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP633:%.*]] = getelementptr inbounds i32, ptr [[TMP632]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP634:%.*]] = getelementptr inbounds i32, ptr [[TMP633]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP635:%.*]] = getelementptr inbounds double, ptr [[TMP634]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP636:%.*]] = getelementptr inbounds double, ptr [[TMP635]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP636]], align 8, !invariant.group [[META105:![0-9]+]]
; CHECK-NEXT:    [[TMP637:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP638:%.*]] = getelementptr inbounds i64, ptr [[TMP637]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP639:%.*]] = getelementptr inbounds ptr, ptr [[TMP638]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP640:%.*]] = getelementptr inbounds i32, ptr [[TMP639]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP641:%.*]] = getelementptr inbounds i1, ptr [[TMP640]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP642:%.*]] = getelementptr inbounds ptr, ptr [[TMP641]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP643:%.*]] = getelementptr inbounds ptr, ptr [[TMP642]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP644:%.*]] = getelementptr inbounds double, ptr [[TMP643]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP645:%.*]] = getelementptr inbounds i32, ptr [[TMP644]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP646:%.*]] = getelementptr inbounds i32, ptr [[TMP645]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP647:%.*]] = getelementptr inbounds double, ptr [[TMP646]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP648:%.*]] = getelementptr inbounds double, ptr [[TMP647]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP649:%.*]] = getelementptr inbounds double, ptr [[TMP648]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP649]], align 8, !invariant.group [[META106:![0-9]+]]
; CHECK-NEXT:    [[TMP650:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP651:%.*]] = getelementptr inbounds i64, ptr [[TMP650]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP652:%.*]] = getelementptr inbounds ptr, ptr [[TMP651]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP653:%.*]] = getelementptr inbounds i32, ptr [[TMP652]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP654:%.*]] = getelementptr inbounds i1, ptr [[TMP653]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP655:%.*]] = getelementptr inbounds ptr, ptr [[TMP654]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP656:%.*]] = getelementptr inbounds ptr, ptr [[TMP655]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP657:%.*]] = getelementptr inbounds double, ptr [[TMP656]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP658:%.*]] = getelementptr inbounds i32, ptr [[TMP657]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP659:%.*]] = getelementptr inbounds i32, ptr [[TMP658]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP660:%.*]] = getelementptr inbounds double, ptr [[TMP659]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP661:%.*]] = getelementptr inbounds double, ptr [[TMP660]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP662:%.*]] = getelementptr inbounds double, ptr [[TMP661]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP663:%.*]] = getelementptr inbounds double, ptr [[TMP662]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP663]], align 8, !invariant.group [[META107:![0-9]+]]
; CHECK-NEXT:    [[TMP664:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP665:%.*]] = getelementptr inbounds i64, ptr [[TMP664]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP666:%.*]] = getelementptr inbounds ptr, ptr [[TMP665]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP667:%.*]] = getelementptr inbounds i32, ptr [[TMP666]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP668:%.*]] = getelementptr inbounds i1, ptr [[TMP667]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP669:%.*]] = getelementptr inbounds ptr, ptr [[TMP668]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP670:%.*]] = getelementptr inbounds ptr, ptr [[TMP669]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP671:%.*]] = getelementptr inbounds double, ptr [[TMP670]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP672:%.*]] = getelementptr inbounds i32, ptr [[TMP671]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP673:%.*]] = getelementptr inbounds i32, ptr [[TMP672]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP674:%.*]] = getelementptr inbounds double, ptr [[TMP673]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP675:%.*]] = getelementptr inbounds double, ptr [[TMP674]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP676:%.*]] = getelementptr inbounds double, ptr [[TMP675]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP677:%.*]] = getelementptr inbounds double, ptr [[TMP676]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP678:%.*]] = getelementptr inbounds double, ptr [[TMP677]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP678]], align 8, !invariant.group [[META108:![0-9]+]]
; CHECK-NEXT:    [[TMP679:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP680:%.*]] = getelementptr inbounds i64, ptr [[TMP679]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP681:%.*]] = getelementptr inbounds ptr, ptr [[TMP680]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP682:%.*]] = getelementptr inbounds i32, ptr [[TMP681]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP683:%.*]] = getelementptr inbounds i1, ptr [[TMP682]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP684:%.*]] = getelementptr inbounds ptr, ptr [[TMP683]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP685:%.*]] = getelementptr inbounds ptr, ptr [[TMP684]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP686:%.*]] = getelementptr inbounds double, ptr [[TMP685]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP687:%.*]] = getelementptr inbounds i32, ptr [[TMP686]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP688:%.*]] = getelementptr inbounds i32, ptr [[TMP687]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP689:%.*]] = getelementptr inbounds double, ptr [[TMP688]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP690:%.*]] = getelementptr inbounds double, ptr [[TMP689]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP691:%.*]] = getelementptr inbounds double, ptr [[TMP690]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP692:%.*]] = getelementptr inbounds double, ptr [[TMP691]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP693:%.*]] = getelementptr inbounds double, ptr [[TMP692]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP694:%.*]] = getelementptr inbounds i32, ptr [[TMP693]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I113144]], ptr [[TMP694]], align 4, !invariant.group [[META109:![0-9]+]]
; CHECK-NEXT:    [[TMP695:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP696:%.*]] = getelementptr inbounds i64, ptr [[TMP695]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP697:%.*]] = getelementptr inbounds ptr, ptr [[TMP696]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP698:%.*]] = getelementptr inbounds i32, ptr [[TMP697]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP699:%.*]] = getelementptr inbounds i1, ptr [[TMP698]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP700:%.*]] = getelementptr inbounds ptr, ptr [[TMP699]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP701:%.*]] = getelementptr inbounds ptr, ptr [[TMP700]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP702:%.*]] = getelementptr inbounds double, ptr [[TMP701]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP703:%.*]] = getelementptr inbounds i32, ptr [[TMP702]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP704:%.*]] = getelementptr inbounds i32, ptr [[TMP703]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP705:%.*]] = getelementptr inbounds double, ptr [[TMP704]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP706:%.*]] = getelementptr inbounds double, ptr [[TMP705]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP707:%.*]] = getelementptr inbounds double, ptr [[TMP706]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP708:%.*]] = getelementptr inbounds double, ptr [[TMP707]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP709:%.*]] = getelementptr inbounds double, ptr [[TMP708]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP710:%.*]] = getelementptr inbounds i32, ptr [[TMP709]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP711:%.*]] = getelementptr inbounds ptr, ptr [[TMP710]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP711]], align 8, !invariant.group [[META110:![0-9]+]]
; CHECK-NEXT:    [[TMP712:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP713:%.*]] = getelementptr inbounds i64, ptr [[TMP712]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP714:%.*]] = getelementptr inbounds ptr, ptr [[TMP713]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP715:%.*]] = getelementptr inbounds i32, ptr [[TMP714]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP716:%.*]] = getelementptr inbounds i1, ptr [[TMP715]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP717:%.*]] = getelementptr inbounds ptr, ptr [[TMP716]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP718:%.*]] = getelementptr inbounds ptr, ptr [[TMP717]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP719:%.*]] = getelementptr inbounds double, ptr [[TMP718]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP720:%.*]] = getelementptr inbounds i32, ptr [[TMP719]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP721:%.*]] = getelementptr inbounds i32, ptr [[TMP720]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP722:%.*]] = getelementptr inbounds double, ptr [[TMP721]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP723:%.*]] = getelementptr inbounds double, ptr [[TMP722]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP724:%.*]] = getelementptr inbounds double, ptr [[TMP723]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP725:%.*]] = getelementptr inbounds double, ptr [[TMP724]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP726:%.*]] = getelementptr inbounds double, ptr [[TMP725]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP727:%.*]] = getelementptr inbounds i32, ptr [[TMP726]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP728:%.*]] = getelementptr inbounds ptr, ptr [[TMP727]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP729:%.*]] = getelementptr inbounds ptr, ptr [[TMP728]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP729]], align 8, !invariant.group [[META111:![0-9]+]]
; CHECK-NEXT:    [[TMP730:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP731:%.*]] = getelementptr inbounds i64, ptr [[TMP730]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP732:%.*]] = getelementptr inbounds ptr, ptr [[TMP731]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP733:%.*]] = getelementptr inbounds i32, ptr [[TMP732]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP734:%.*]] = getelementptr inbounds i1, ptr [[TMP733]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP735:%.*]] = getelementptr inbounds ptr, ptr [[TMP734]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP736:%.*]] = getelementptr inbounds ptr, ptr [[TMP735]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP737:%.*]] = getelementptr inbounds double, ptr [[TMP736]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP738:%.*]] = getelementptr inbounds i32, ptr [[TMP737]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP739:%.*]] = getelementptr inbounds i32, ptr [[TMP738]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP740:%.*]] = getelementptr inbounds double, ptr [[TMP739]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP741:%.*]] = getelementptr inbounds double, ptr [[TMP740]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP742:%.*]] = getelementptr inbounds double, ptr [[TMP741]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP743:%.*]] = getelementptr inbounds double, ptr [[TMP742]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP744:%.*]] = getelementptr inbounds double, ptr [[TMP743]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP745:%.*]] = getelementptr inbounds i32, ptr [[TMP744]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP746:%.*]] = getelementptr inbounds ptr, ptr [[TMP745]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP747:%.*]] = getelementptr inbounds ptr, ptr [[TMP746]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP748:%.*]] = getelementptr inbounds ptr, ptr [[TMP747]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP748]], align 8, !invariant.group [[META112:![0-9]+]]
; CHECK-NEXT:    [[TMP749:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP750:%.*]] = getelementptr inbounds i64, ptr [[TMP749]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP751:%.*]] = getelementptr inbounds ptr, ptr [[TMP750]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP752:%.*]] = getelementptr inbounds i32, ptr [[TMP751]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP753:%.*]] = getelementptr inbounds i1, ptr [[TMP752]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP754:%.*]] = getelementptr inbounds ptr, ptr [[TMP753]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP755:%.*]] = getelementptr inbounds ptr, ptr [[TMP754]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP756:%.*]] = getelementptr inbounds double, ptr [[TMP755]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP757:%.*]] = getelementptr inbounds i32, ptr [[TMP756]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP758:%.*]] = getelementptr inbounds i32, ptr [[TMP757]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP759:%.*]] = getelementptr inbounds double, ptr [[TMP758]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP760:%.*]] = getelementptr inbounds double, ptr [[TMP759]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP761:%.*]] = getelementptr inbounds double, ptr [[TMP760]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP762:%.*]] = getelementptr inbounds double, ptr [[TMP761]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP763:%.*]] = getelementptr inbounds double, ptr [[TMP762]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP764:%.*]] = getelementptr inbounds i32, ptr [[TMP763]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP765:%.*]] = getelementptr inbounds ptr, ptr [[TMP764]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP766:%.*]] = getelementptr inbounds ptr, ptr [[TMP765]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP767:%.*]] = getelementptr inbounds ptr, ptr [[TMP766]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP768:%.*]] = getelementptr inbounds i64, ptr [[TMP767]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP768]], align 8, !invariant.group [[META113:![0-9]+]]
; CHECK-NEXT:    [[TMP769:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP770:%.*]] = getelementptr inbounds i64, ptr [[TMP769]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP771:%.*]] = getelementptr inbounds ptr, ptr [[TMP770]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP772:%.*]] = getelementptr inbounds i32, ptr [[TMP771]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP773:%.*]] = getelementptr inbounds i1, ptr [[TMP772]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP774:%.*]] = getelementptr inbounds ptr, ptr [[TMP773]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP775:%.*]] = getelementptr inbounds ptr, ptr [[TMP774]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP776:%.*]] = getelementptr inbounds double, ptr [[TMP775]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP777:%.*]] = getelementptr inbounds i32, ptr [[TMP776]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP778:%.*]] = getelementptr inbounds i32, ptr [[TMP777]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP779:%.*]] = getelementptr inbounds double, ptr [[TMP778]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP780:%.*]] = getelementptr inbounds double, ptr [[TMP779]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP781:%.*]] = getelementptr inbounds double, ptr [[TMP780]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP782:%.*]] = getelementptr inbounds double, ptr [[TMP781]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP783:%.*]] = getelementptr inbounds double, ptr [[TMP782]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP784:%.*]] = getelementptr inbounds i32, ptr [[TMP783]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP785:%.*]] = getelementptr inbounds ptr, ptr [[TMP784]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP786:%.*]] = getelementptr inbounds ptr, ptr [[TMP785]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP787:%.*]] = getelementptr inbounds ptr, ptr [[TMP786]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP788:%.*]] = getelementptr inbounds i64, ptr [[TMP787]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP789:%.*]] = getelementptr inbounds i64, ptr [[TMP788]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP789]], align 8, !invariant.group [[META114:![0-9]+]]
; CHECK-NEXT:    [[TMP790:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP791:%.*]] = getelementptr inbounds i64, ptr [[TMP790]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP792:%.*]] = getelementptr inbounds ptr, ptr [[TMP791]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP793:%.*]] = getelementptr inbounds i32, ptr [[TMP792]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP794:%.*]] = getelementptr inbounds i1, ptr [[TMP793]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP795:%.*]] = getelementptr inbounds ptr, ptr [[TMP794]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP796:%.*]] = getelementptr inbounds ptr, ptr [[TMP795]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP797:%.*]] = getelementptr inbounds double, ptr [[TMP796]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP798:%.*]] = getelementptr inbounds i32, ptr [[TMP797]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP799:%.*]] = getelementptr inbounds i32, ptr [[TMP798]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP800:%.*]] = getelementptr inbounds double, ptr [[TMP799]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP801:%.*]] = getelementptr inbounds double, ptr [[TMP800]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP802:%.*]] = getelementptr inbounds double, ptr [[TMP801]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP803:%.*]] = getelementptr inbounds double, ptr [[TMP802]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP804:%.*]] = getelementptr inbounds double, ptr [[TMP803]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP805:%.*]] = getelementptr inbounds i32, ptr [[TMP804]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP806:%.*]] = getelementptr inbounds ptr, ptr [[TMP805]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP807:%.*]] = getelementptr inbounds ptr, ptr [[TMP806]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP808:%.*]] = getelementptr inbounds ptr, ptr [[TMP807]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP809:%.*]] = getelementptr inbounds i64, ptr [[TMP808]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP810:%.*]] = getelementptr inbounds i64, ptr [[TMP809]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP811:%.*]] = getelementptr inbounds i32, ptr [[TMP810]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP811]], align 4, !invariant.group [[META115:![0-9]+]]
; CHECK-NEXT:    [[TMP812:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP813:%.*]] = getelementptr inbounds i64, ptr [[TMP812]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP814:%.*]] = getelementptr inbounds ptr, ptr [[TMP813]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP815:%.*]] = getelementptr inbounds i32, ptr [[TMP814]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP816:%.*]] = getelementptr inbounds i1, ptr [[TMP815]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP817:%.*]] = getelementptr inbounds ptr, ptr [[TMP816]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP818:%.*]] = getelementptr inbounds ptr, ptr [[TMP817]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP819:%.*]] = getelementptr inbounds double, ptr [[TMP818]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP820:%.*]] = getelementptr inbounds i32, ptr [[TMP819]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP821:%.*]] = getelementptr inbounds i32, ptr [[TMP820]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP822:%.*]] = getelementptr inbounds double, ptr [[TMP821]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP823:%.*]] = getelementptr inbounds double, ptr [[TMP822]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP824:%.*]] = getelementptr inbounds double, ptr [[TMP823]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP825:%.*]] = getelementptr inbounds double, ptr [[TMP824]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP826:%.*]] = getelementptr inbounds double, ptr [[TMP825]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP827:%.*]] = getelementptr inbounds i32, ptr [[TMP826]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP828:%.*]] = getelementptr inbounds ptr, ptr [[TMP827]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP829:%.*]] = getelementptr inbounds ptr, ptr [[TMP828]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP830:%.*]] = getelementptr inbounds ptr, ptr [[TMP829]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP831:%.*]] = getelementptr inbounds i64, ptr [[TMP830]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP832:%.*]] = getelementptr inbounds i64, ptr [[TMP831]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP833:%.*]] = getelementptr inbounds i32, ptr [[TMP832]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP834:%.*]] = getelementptr inbounds i32, ptr [[TMP833]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP834]], align 4, !invariant.group [[META116:![0-9]+]]
; CHECK-NEXT:    [[TMP835:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP836:%.*]] = getelementptr inbounds i64, ptr [[TMP835]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP837:%.*]] = getelementptr inbounds ptr, ptr [[TMP836]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP838:%.*]] = getelementptr inbounds i32, ptr [[TMP837]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP839:%.*]] = getelementptr inbounds i1, ptr [[TMP838]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP840:%.*]] = getelementptr inbounds ptr, ptr [[TMP839]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP841:%.*]] = getelementptr inbounds ptr, ptr [[TMP840]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP842:%.*]] = getelementptr inbounds double, ptr [[TMP841]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP843:%.*]] = getelementptr inbounds i32, ptr [[TMP842]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP844:%.*]] = getelementptr inbounds i32, ptr [[TMP843]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP845:%.*]] = getelementptr inbounds double, ptr [[TMP844]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP846:%.*]] = getelementptr inbounds double, ptr [[TMP845]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP847:%.*]] = getelementptr inbounds double, ptr [[TMP846]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP848:%.*]] = getelementptr inbounds double, ptr [[TMP847]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP849:%.*]] = getelementptr inbounds double, ptr [[TMP848]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP850:%.*]] = getelementptr inbounds i32, ptr [[TMP849]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP851:%.*]] = getelementptr inbounds ptr, ptr [[TMP850]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP852:%.*]] = getelementptr inbounds ptr, ptr [[TMP851]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP853:%.*]] = getelementptr inbounds ptr, ptr [[TMP852]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP854:%.*]] = getelementptr inbounds i64, ptr [[TMP853]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP855:%.*]] = getelementptr inbounds i64, ptr [[TMP854]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP856:%.*]] = getelementptr inbounds i32, ptr [[TMP855]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP857:%.*]] = getelementptr inbounds i32, ptr [[TMP856]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP858:%.*]] = getelementptr inbounds i32, ptr [[TMP857]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP858]], align 4, !invariant.group [[META117:![0-9]+]]
; CHECK-NEXT:    [[TMP859:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP860:%.*]] = getelementptr inbounds i64, ptr [[TMP859]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP861:%.*]] = getelementptr inbounds ptr, ptr [[TMP860]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP862:%.*]] = getelementptr inbounds i32, ptr [[TMP861]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP863:%.*]] = getelementptr inbounds i1, ptr [[TMP862]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP864:%.*]] = getelementptr inbounds ptr, ptr [[TMP863]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP865:%.*]] = getelementptr inbounds ptr, ptr [[TMP864]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP866:%.*]] = getelementptr inbounds double, ptr [[TMP865]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP867:%.*]] = getelementptr inbounds i32, ptr [[TMP866]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP868:%.*]] = getelementptr inbounds i32, ptr [[TMP867]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP869:%.*]] = getelementptr inbounds double, ptr [[TMP868]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP870:%.*]] = getelementptr inbounds double, ptr [[TMP869]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP871:%.*]] = getelementptr inbounds double, ptr [[TMP870]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP872:%.*]] = getelementptr inbounds double, ptr [[TMP871]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP873:%.*]] = getelementptr inbounds double, ptr [[TMP872]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP874:%.*]] = getelementptr inbounds i32, ptr [[TMP873]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP875:%.*]] = getelementptr inbounds ptr, ptr [[TMP874]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP876:%.*]] = getelementptr inbounds ptr, ptr [[TMP875]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP877:%.*]] = getelementptr inbounds ptr, ptr [[TMP876]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP878:%.*]] = getelementptr inbounds i64, ptr [[TMP877]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP879:%.*]] = getelementptr inbounds i64, ptr [[TMP878]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP880:%.*]] = getelementptr inbounds i32, ptr [[TMP879]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP881:%.*]] = getelementptr inbounds i32, ptr [[TMP880]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP882:%.*]] = getelementptr inbounds i32, ptr [[TMP881]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP883:%.*]] = getelementptr inbounds i32, ptr [[TMP882]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP883]], align 4, !invariant.group [[META118:![0-9]+]]
; CHECK-NEXT:    [[TMP884:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP885:%.*]] = getelementptr inbounds i64, ptr [[TMP884]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP886:%.*]] = getelementptr inbounds ptr, ptr [[TMP885]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP887:%.*]] = getelementptr inbounds i32, ptr [[TMP886]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP888:%.*]] = getelementptr inbounds i1, ptr [[TMP887]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP889:%.*]] = getelementptr inbounds ptr, ptr [[TMP888]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP890:%.*]] = getelementptr inbounds ptr, ptr [[TMP889]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP891:%.*]] = getelementptr inbounds double, ptr [[TMP890]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP892:%.*]] = getelementptr inbounds i32, ptr [[TMP891]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP893:%.*]] = getelementptr inbounds i32, ptr [[TMP892]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP894:%.*]] = getelementptr inbounds double, ptr [[TMP893]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP895:%.*]] = getelementptr inbounds double, ptr [[TMP894]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP896:%.*]] = getelementptr inbounds double, ptr [[TMP895]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP897:%.*]] = getelementptr inbounds double, ptr [[TMP896]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP898:%.*]] = getelementptr inbounds double, ptr [[TMP897]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP899:%.*]] = getelementptr inbounds i32, ptr [[TMP898]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP900:%.*]] = getelementptr inbounds ptr, ptr [[TMP899]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP901:%.*]] = getelementptr inbounds ptr, ptr [[TMP900]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP902:%.*]] = getelementptr inbounds ptr, ptr [[TMP901]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP903:%.*]] = getelementptr inbounds i64, ptr [[TMP902]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP904:%.*]] = getelementptr inbounds i64, ptr [[TMP903]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP905:%.*]] = getelementptr inbounds i32, ptr [[TMP904]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP906:%.*]] = getelementptr inbounds i32, ptr [[TMP905]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP907:%.*]] = getelementptr inbounds i32, ptr [[TMP906]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP908:%.*]] = getelementptr inbounds i32, ptr [[TMP907]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP909:%.*]] = getelementptr inbounds i32, ptr [[TMP908]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP909]], align 4, !invariant.group [[META119:![0-9]+]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb302:
; CHECK-NEXT:    [[I28323]] = phi ptr [ [[I28326]], [[BB139]] ], [ [[I28324]], [[BB197]] ]
; CHECK-NEXT:    [[I25316]] = phi ptr [ [[I25319]], [[BB139]] ], [ [[I25317]], [[BB197]] ]
; CHECK-NEXT:    [[I24309]] = phi ptr [ [[I24312]], [[BB139]] ], [ [[I24310]], [[BB197]] ]
; CHECK-NEXT:    [[I23302]] = phi ptr [ [[I23305]], [[BB139]] ], [ [[I23303]], [[BB197]] ]
; CHECK-NEXT:    [[I22295]] = phi ptr [ [[I22298]], [[BB139]] ], [ [[I22296]], [[BB197]] ]
; CHECK-NEXT:    [[I21288]] = phi ptr [ [[I21291]], [[BB139]] ], [ [[I21289]], [[BB197]] ]
; CHECK-NEXT:    [[I6280]] = phi i32 [ [[I6283]], [[BB139]] ], [ [[I6281]], [[BB197]] ]
; CHECK-NEXT:    [[I32275]] = phi i64 [ [[I32277]], [[BB139]] ], [ [[I32276]], [[BB197]] ]
; CHECK-NEXT:    [[I41271:%.*]] = phi i32 [ [[I41]], [[BB139]] ], [ [[I41272]], [[BB197]] ]
; CHECK-NEXT:    [[I27262]] = phi ptr [ [[I27265]], [[BB139]] ], [ [[I27263]], [[BB197]] ]
; CHECK-NEXT:    [[I26255]] = phi ptr [ [[I26258]], [[BB139]] ], [ [[I26256]], [[BB197]] ]
; CHECK-NEXT:    [[I20248]] = phi ptr [ [[I20251]], [[BB139]] ], [ [[I20249]], [[BB197]] ]
; CHECK-NEXT:    [[I19241]] = phi ptr [ [[I19244]], [[BB139]] ], [ [[I19242]], [[BB197]] ]
; CHECK-NEXT:    [[I4233]] = phi ptr [ [[I4236]], [[BB139]] ], [ [[I4234]], [[BB197]] ]
; CHECK-NEXT:    [[I13227]] = phi i32 [ [[I13230]], [[BB139]] ], [ [[I13228]], [[BB197]] ]
; CHECK-NEXT:    [[I18219]] = phi i32 [ [[I18222]], [[BB139]] ], [ [[I18220]], [[BB197]] ]
; CHECK-NEXT:    [[I195]] = phi i32 [ [[I212]], [[BB139]] ], [ [[I197]], [[BB197]] ]
; CHECK-NEXT:    [[I5179]] = phi i32 [ [[I5182]], [[BB139]] ], [ [[I5180]], [[BB197]] ]
; CHECK-NEXT:    [[I30173]] = phi i32 [ [[I30176]], [[BB139]] ], [ [[I30174]], [[BB197]] ]
; CHECK-NEXT:    [[I31167]] = phi i32 [ [[I31170]], [[BB139]] ], [ [[I31168]], [[BB197]] ]
; CHECK-NEXT:    [[I40163:%.*]] = phi i64 [ [[I40]], [[BB139]] ], [ [[I40164]], [[BB197]] ]
; CHECK-NEXT:    [[I10132]] = phi i32 [ [[I10135]], [[BB139]] ], [ [[I10133]], [[BB197]] ]
; CHECK-NEXT:    [[I303:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I294]], [[BB197]] ]
; CHECK-NEXT:    [[I304:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I295]], [[BB197]] ]
; CHECK-NEXT:    [[I305:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I296]], [[BB197]] ]
; CHECK-NEXT:    [[I306:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I297]], [[BB197]] ]
; CHECK-NEXT:    [[I307:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I298]], [[BB197]] ]
; CHECK-NEXT:    [[I308:%.*]] = fcmp ogt double [[I303]], -1.000000e+00
; CHECK-NEXT:    [[I309:%.*]] = select i1 [[I308]], double [[I303]], double -1.000000e+00
; CHECK-NEXT:    [[I310:%.*]] = fcmp ogt double [[I304]], [[I309]]
; CHECK-NEXT:    [[I311:%.*]] = select i1 [[I310]], double [[I304]], double [[I309]]
; CHECK-NEXT:    [[I312:%.*]] = fcmp ogt double [[I305]], [[I311]]
; CHECK-NEXT:    [[I313:%.*]] = select i1 [[I312]], double [[I305]], double [[I311]]
; CHECK-NEXT:    [[I314:%.*]] = fcmp ogt double [[I306]], [[I313]]
; CHECK-NEXT:    [[I315:%.*]] = select i1 [[I314]], double [[I306]], double [[I313]]
; CHECK-NEXT:    [[I316:%.*]] = select i1 [[I310]], i64 2, i64 1
; CHECK-NEXT:    [[I317:%.*]] = fcmp ogt double [[I307]], [[I315]]
; CHECK-NEXT:    [[I318:%.*]] = select i1 [[I312]], i64 3, i64 [[I316]]
; CHECK-NEXT:    [[I319:%.*]] = select i1 [[I314]], i64 4, i64 [[I318]]
; CHECK-NEXT:    [[I320:%.*]] = select i1 [[I317]], i64 5, i64 [[I319]]
; CHECK-NEXT:    [[I321:%.*]] = getelementptr inbounds i64, ptr [[ARG3]], i64 [[I40163]]
; CHECK-NEXT:    store i64 [[I320]], ptr [[I321]], align 8, !tbaa [[TBAA120:![0-9]+]]
; CHECK-NEXT:    [[I322:%.*]] = add nsw i32 [[I18219]], [[I41271]]
; CHECK-NEXT:    [[I323]] = sext i32 [[I322]] to i64
; CHECK-NEXT:    [[I324:%.*]] = icmp ugt i64 [[I323]], [[I32275]]
; CHECK-NEXT:    br i1 [[I324]], label [[BB325]], label [[BB39]]
; CHECK:       bb325:
; CHECK-NEXT:    [[I28325]] = phi ptr [ [[I28323]], [[BB302]] ], [ [[I28320]], [[BB35]] ], [ [[I28320]], [[BB29]] ]
; CHECK-NEXT:    [[I25318]] = phi ptr [ [[I25316]], [[BB302]] ], [ [[I25313]], [[BB35]] ], [ [[I25313]], [[BB29]] ]
; CHECK-NEXT:    [[I24311]] = phi ptr [ [[I24309]], [[BB302]] ], [ [[I24306]], [[BB35]] ], [ [[I24306]], [[BB29]] ]
; CHECK-NEXT:    [[I23304]] = phi ptr [ [[I23302]], [[BB302]] ], [ [[I23299]], [[BB35]] ], [ [[I23299]], [[BB29]] ]
; CHECK-NEXT:    [[I22297]] = phi ptr [ [[I22295]], [[BB302]] ], [ [[I22292]], [[BB35]] ], [ [[I22292]], [[BB29]] ]
; CHECK-NEXT:    [[I21290]] = phi ptr [ [[I21288]], [[BB302]] ], [ [[I21285]], [[BB35]] ], [ [[I21285]], [[BB29]] ]
; CHECK-NEXT:    [[I6282]] = phi i32 [ [[I6280]], [[BB302]] ], [ [[I6284]], [[BB35]] ], [ [[I6284]], [[BB29]] ]
; CHECK-NEXT:    [[I27264]] = phi ptr [ [[I27262]], [[BB302]] ], [ [[I27259]], [[BB35]] ], [ [[I27259]], [[BB29]] ]
; CHECK-NEXT:    [[I26257]] = phi ptr [ [[I26255]], [[BB302]] ], [ [[I26252]], [[BB35]] ], [ [[I26252]], [[BB29]] ]
; CHECK-NEXT:    [[I20250]] = phi ptr [ [[I20248]], [[BB302]] ], [ [[I20245]], [[BB35]] ], [ [[I20245]], [[BB29]] ]
; CHECK-NEXT:    [[I19243]] = phi ptr [ [[I19241]], [[BB302]] ], [ [[I19238]], [[BB35]] ], [ [[I19238]], [[BB29]] ]
; CHECK-NEXT:    [[I4235]] = phi ptr [ [[I4233]], [[BB302]] ], [ [[I4237]], [[BB35]] ], [ [[I4237]], [[BB29]] ]
; CHECK-NEXT:    [[I13229]] = phi i32 [ [[I13227]], [[BB302]] ], [ [[I13226]], [[BB35]] ], [ [[I13226]], [[BB29]] ]
; CHECK-NEXT:    [[I18221]] = phi i32 [ [[I18219]], [[BB302]] ], [ [[I18223]], [[BB35]] ], [ [[I18223]], [[BB29]] ]
; CHECK-NEXT:    [[I208]] = phi i32 [ [[I195]], [[BB302]] ], [ [[I216]], [[BB35]] ], [ [[I216]], [[BB29]] ]
; CHECK-NEXT:    [[I5181]] = phi i32 [ [[I5179]], [[BB302]] ], [ [[I5183]], [[BB35]] ], [ [[I5183]], [[BB29]] ]
; CHECK-NEXT:    [[I30175:%.*]] = phi i32 [ [[I30173]], [[BB302]] ], [ [[I30]], [[BB35]] ], [ [[I30]], [[BB29]] ]
; CHECK-NEXT:    [[I31169:%.*]] = phi i32 [ [[I31167]], [[BB302]] ], [ [[I31]], [[BB35]] ], [ [[I31]], [[BB29]] ]
; CHECK-NEXT:    [[I10134]] = phi i32 [ [[I10132]], [[BB302]] ], [ [[I10136]], [[BB35]] ], [ [[I10136]], [[BB29]] ]
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I326]] = add nsw i32 [[I31169]], [[I13229]]
; CHECK-NEXT:    [[I327:%.*]] = add nsw i32 [[I30175]], [[I13229]]
; CHECK-NEXT:    [[I328]] = tail call i32 @llvm.smin.i32(i32 [[I327]], i32 [[I6282]])
; CHECK-NEXT:    [[I329:%.*]] = icmp slt i32 [[I326]], [[I5181]]
; CHECK-NEXT:    br i1 [[I329]], label [[BB29]], label [[BB330]]
; CHECK:       bb330:
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define weak_odr protected void @__omp_offloading_run_event_based_simulation_contd_0(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef nonnull align 8 dereferenceable(64) [[ARG1:%.*]], ptr noundef nonnull align 8 dereferenceable(112) [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 3
; CHECK-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT0:%.*]], label [[THREADEXIT:%.*]]
; CHECK:       bb35:
; CHECK-NEXT:    [[I36:%.*]] = add nsw i32 [[I326_BB29:%.*]], [[I208:%.*]]
; CHECK-NEXT:    [[I37:%.*]] = sext i32 [[I36]] to i64
; CHECK-NEXT:    [[I38:%.*]] = icmp ugt i64 [[I37]], [[I32:%.*]]
; CHECK-NEXT:    br i1 [[I38]], label [[BB325:%.*]], label [[BB39:%.*]]
; CHECK:       bb39:
; CHECK-NEXT:    [[I28326:%.*]] = phi ptr [ [[I28325:%.*]], [[BB35:%.*]] ], [ [[I28323:%.*]], [[BB302:%.*]] ]
; CHECK-NEXT:    [[I25319:%.*]] = phi ptr [ [[I25318:%.*]], [[BB35]] ], [ [[I25316:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I24312:%.*]] = phi ptr [ [[I24311:%.*]], [[BB35]] ], [ [[I24309:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I23305:%.*]] = phi ptr [ [[I23304:%.*]], [[BB35]] ], [ [[I23302:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I22298:%.*]] = phi ptr [ [[I22297:%.*]], [[BB35]] ], [ [[I22295:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I21291:%.*]] = phi ptr [ [[I21290:%.*]], [[BB35]] ], [ [[I21288:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I6283:%.*]] = phi i32 [ [[I6282:%.*]], [[BB35]] ], [ [[I6280:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I32277:%.*]] = phi i64 [ [[I32]], [[BB35]] ], [ [[I32275:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I27265:%.*]] = phi ptr [ [[I27264:%.*]], [[BB35]] ], [ [[I27262:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I26258:%.*]] = phi ptr [ [[I26257:%.*]], [[BB35]] ], [ [[I26255:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I20251:%.*]] = phi ptr [ [[I20250:%.*]], [[BB35]] ], [ [[I20248:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I19244:%.*]] = phi ptr [ [[I19243:%.*]], [[BB35]] ], [ [[I19241:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I4236:%.*]] = phi ptr [ [[I4235:%.*]], [[BB35]] ], [ [[I4233:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I13230:%.*]] = phi i32 [ [[I13229:%.*]], [[BB35]] ], [ [[I13227:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I18222:%.*]] = phi i32 [ [[I18221:%.*]], [[BB35]] ], [ [[I18219:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I212:%.*]] = phi i32 [ [[I208]], [[BB35]] ], [ [[I195:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I5182:%.*]] = phi i32 [ [[I5181:%.*]], [[BB35]] ], [ [[I5179:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I30176:%.*]] = phi i32 [ [[I328_BB29:%.*]], [[BB35]] ], [ [[I30173:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I31170:%.*]] = phi i32 [ [[I326_BB29]], [[BB35]] ], [ [[I31167:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I10135:%.*]] = phi i32 [ [[I10134:%.*]], [[BB35]] ], [ [[I10132:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I40:%.*]] = phi i64 [ [[I37]], [[BB35]] ], [ [[I323:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I41:%.*]] = trunc i64 [[I40]] to i32
; CHECK-NEXT:    [[I42:%.*]] = shl nsw i32 [[I41]], 1
; CHECK-NEXT:    [[I43:%.*]] = sext i32 [[I42]] to i64
; CHECK-NEXT:    [[I44:%.*]] = and i64 [[I43]], 9223372036854775806
; CHECK-NEXT:    [[I45:%.*]] = icmp eq i64 [[I44]], 0
; CHECK-NEXT:    br i1 [[I45]], label [[BB69:%.*]], label [[BB46:%.*]]
; CHECK:       bb46:
; CHECK-NEXT:    [[I47:%.*]] = phi i64 [ 0, [[BB39]] ], [ [[I58:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I48:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I57:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I49:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I60:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I50:%.*]] = phi i64 [ 2806196910506780709, [[BB39]] ], [ [[I61:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I51:%.*]] = phi i64 [ [[I44]], [[BB39]] ], [ [[I62:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I52:%.*]] = and i64 [[I51]], 1
; CHECK-NEXT:    [[I53:%.*]] = icmp eq i64 [[I52]], 0
; CHECK-NEXT:    [[I54:%.*]] = mul i64 [[I50]], [[I47]]
; CHECK-NEXT:    [[I55:%.*]] = add i64 [[I54]], [[I49]]
; CHECK-NEXT:    [[I56:%.*]] = select i1 [[I53]], i64 1, i64 [[I50]]
; CHECK-NEXT:    [[I57]] = mul i64 [[I56]], [[I48]]
; CHECK-NEXT:    [[I58]] = select i1 [[I53]], i64 [[I47]], i64 [[I55]]
; CHECK-NEXT:    [[I59:%.*]] = add i64 [[I50]], 1
; CHECK-NEXT:    [[I60]] = mul i64 [[I59]], [[I49]]
; CHECK-NEXT:    [[I61]] = mul i64 [[I50]], [[I50]]
; CHECK-NEXT:    [[I62]] = lshr i64 [[I51]], 1
; CHECK-NEXT:    [[I63:%.*]] = icmp ult i64 [[I51]], 2
; CHECK-NEXT:    br i1 [[I63]], label [[BB64:%.*]], label [[BB46]]
; CHECK:       bb64:
; CHECK-NEXT:    [[I67:%.*]] = mul i64 [[I57]], 1070
; CHECK-NEXT:    [[I68:%.*]] = add i64 [[I67]], [[I58]]
; CHECK-NEXT:    br label [[BB69]]
; CHECK:       bb69:
; CHECK-NEXT:    [[I70:%.*]] = phi i64 [ [[I68]], [[BB64]] ], [ 1070, [[BB39]] ]
; CHECK-NEXT:    [[I71:%.*]] = mul i64 [[I70]], 2806196910506780709
; CHECK-NEXT:    [[I72:%.*]] = add i64 [[I71]], 1
; CHECK-NEXT:    [[I73:%.*]] = and i64 [[I72]], 9223372036854775807
; CHECK-NEXT:    [[I74:%.*]] = uitofp i64 [[I73]] to double
; CHECK-NEXT:    [[I75:%.*]] = fmul double [[I74]], 0x3C00000000000000
; CHECK-NEXT:    [[I76:%.*]] = mul i64 [[I72]], 2806196910506780709
; CHECK-NEXT:    [[I77:%.*]] = add i64 [[I76]], 1
; CHECK-NEXT:    [[I78:%.*]] = and i64 [[I77]], 9223372036854775807
; CHECK-NEXT:    [[I79:%.*]] = uitofp i64 [[I78]] to double
; CHECK-NEXT:    [[I80:%.*]] = fmul double [[I79]], 0x3C00000000000000
; CHECK-NEXT:    [[I81:%.*]] = fcmp uge double [[I80]], 5.200000e-02
; CHECK-NEXT:    br i1 [[I81]], label [[BB82:%.*]], label [[BB103:%.*]]
; CHECK:       bb82:
; CHECK-NEXT:    [[I83:%.*]] = fcmp uge double [[I80]], 3.270000e-01
; CHECK-NEXT:    br i1 [[I83]], label [[BB84:%.*]], label [[BB103]]
; CHECK:       bb84:
; CHECK-NEXT:    [[I85:%.*]] = fcmp uge double [[I80]], 4.610000e-01
; CHECK-NEXT:    br i1 [[I85]], label [[BB86:%.*]], label [[BB103]]
; CHECK:       bb86:
; CHECK-NEXT:    [[I87:%.*]] = fcmp uge double [[I80]], 0x3FE3AE147AE147AF
; CHECK-NEXT:    br i1 [[I87]], label [[BB88:%.*]], label [[BB103]]
; CHECK:       bb88:
; CHECK-NEXT:    [[I89:%.*]] = fcmp uge double [[I80]], 6.790000e-01
; CHECK-NEXT:    br i1 [[I89]], label [[BB90:%.*]], label [[BB103]]
; CHECK:       bb90:
; CHECK-NEXT:    [[I91:%.*]] = fcmp uge double [[I80]], 0x3FE7D70A3D70A3D8
; CHECK-NEXT:    br i1 [[I91]], label [[BB92:%.*]], label [[BB103]]
; CHECK:       bb92:
; CHECK-NEXT:    [[I93:%.*]] = fcmp uge double [[I80]], 8.000000e-01
; CHECK-NEXT:    br i1 [[I93]], label [[BB94:%.*]], label [[BB103]]
; CHECK:       bb94:
; CHECK-NEXT:    [[I95:%.*]] = fcmp uge double [[I80]], 8.080000e-01
; CHECK-NEXT:    br i1 [[I95]], label [[BB96:%.*]], label [[BB103]]
; CHECK:       bb96:
; CHECK-NEXT:    [[I97:%.*]] = fcmp uge double [[I80]], 0x3FEA5604189374BD
; CHECK-NEXT:    br i1 [[I97]], label [[BB98:%.*]], label [[BB103]]
; CHECK:       bb98:
; CHECK-NEXT:    [[I99:%.*]] = fcmp uge double [[I80]], 0x3FEB22D0E560418A
; CHECK-NEXT:    br i1 [[I99]], label [[BB100:%.*]], label [[BB103]]
; CHECK:       bb100:
; CHECK-NEXT:    [[I101:%.*]] = fcmp uge double [[I80]], 0x3FEB8D4FDF3B645B
; CHECK-NEXT:    br i1 [[I101]], label [[BB103_FROM_BB102:%.*]], label [[BB103]]
; CHECK:       bb103.from.bb102:
; CHECK-NEXT:    br label [[BB103]]
; CHECK:       bb103:
; CHECK-NEXT:    [[I104:%.*]] = phi i32 [ 0, [[BB103_FROM_BB102]] ], [ 1, [[BB69]] ], [ 2, [[BB82]] ], [ 3, [[BB84]] ], [ 4, [[BB86]] ], [ 5, [[BB88]] ], [ 6, [[BB90]] ], [ 7, [[BB92]] ], [ 8, [[BB94]] ], [ 9, [[BB96]] ], [ 10, [[BB98]] ], [ 11, [[BB100]] ]
; CHECK-NEXT:    [[I105:%.*]] = load i64, ptr [[I19244]], align 8, !tbaa [[TBAA27]]
; CHECK-NEXT:    [[I106:%.*]] = load i64, ptr [[I20251]], align 8, !tbaa [[TBAA28]]
; CHECK-NEXT:    [[I107:%.*]] = load ptr, ptr [[ARG2]], align 8, !tbaa [[TBAA29]]
; CHECK-NEXT:    [[I108:%.*]] = load ptr, ptr [[I21291]], align 8, !tbaa [[TBAA31]]
; CHECK-NEXT:    [[I109:%.*]] = load ptr, ptr [[I22298]], align 8, !tbaa [[TBAA32]]
; CHECK-NEXT:    [[I110:%.*]] = load ptr, ptr [[I23305]], align 8, !tbaa [[TBAA33]]
; CHECK-NEXT:    [[I111:%.*]] = load ptr, ptr [[I24312]], align 8, !tbaa [[TBAA34]]
; CHECK-NEXT:    [[I112:%.*]] = load ptr, ptr [[I25319]], align 8, !tbaa [[TBAA35]]
; CHECK-NEXT:    [[I113:%.*]] = load i32, ptr [[I26258]], align 8, !tbaa [[TBAA36]]
; CHECK-NEXT:    [[I114:%.*]] = load i32, ptr [[I27265]], align 4, !tbaa [[TBAA37]]
; CHECK-NEXT:    [[I115:%.*]] = load i32, ptr [[I28326]], align 4, !tbaa [[TBAA38]]
; CHECK-NEXT:    switch i32 [[I113]], label [[BB139:%.*]] [
; CHECK-NEXT:      i32 0, label [[BB116:%.*]]
; CHECK-NEXT:      i32 2, label [[CACHESTORE0:%.*]]
; CHECK-NEXT:    ]
; CHECK:       bb116:
; CHECK-NEXT:    [[I117:%.*]] = mul nsw i64 [[I106]], [[I105]]
; CHECK-NEXT:    [[I118:%.*]] = icmp sgt i64 [[I117]], 2
; CHECK-NEXT:    br i1 [[I118]], label [[BB119:%.*]], label [[BB139]]
; CHECK:       bb119:
; CHECK-NEXT:    [[I120:%.*]] = add nsw i64 [[I117]], -1
; CHECK-NEXT:    br label [[BB121:%.*]]
; CHECK:       bb121:
; CHECK-NEXT:    [[I122:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I132:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I123:%.*]] = phi i64 [ 0, [[BB119]] ], [ [[I131:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I124:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I130:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I125:%.*]] = lshr i64 [[I122]], 1
; CHECK-NEXT:    [[I126:%.*]] = add nuw nsw i64 [[I125]], [[I123]]
; CHECK-NEXT:    [[I127:%.*]] = getelementptr inbounds double, ptr [[I109]], i64 [[I126]]
; CHECK-NEXT:    [[I128:%.*]] = load double, ptr [[I127]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    [[I129:%.*]] = fcmp ogt double [[I128]], [[I75]]
; CHECK-NEXT:    [[I130]] = select i1 [[I129]], i64 [[I126]], i64 [[I124]]
; CHECK-NEXT:    [[I131]] = select i1 [[I129]], i64 [[I123]], i64 [[I126]]
; CHECK-NEXT:    [[I132]] = sub nsw i64 [[I130]], [[I131]]
; CHECK-NEXT:    [[I133:%.*]] = icmp sgt i64 [[I132]], 1
; CHECK-NEXT:    br i1 [[I133]], label [[BB121]], label [[BB139]]
; CHECK:       CacheStore0:
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[TMP9]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP10]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET:%.*]] = load i32, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I10135]], ptr [[TMP12]], align 4, !invariant.group [[META41]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[TMP13]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I70]], ptr [[TMP14]], align 8, !invariant.group [[META42]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[TMP15]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I115]], ptr [[TMP17]], align 4, !invariant.group [[META43]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[TMP18]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP19]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP20]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I114]], ptr [[TMP21]], align 4, !invariant.group [[META44]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i64, ptr [[TMP22]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP23]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP25]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 2, ptr [[TMP26]], align 4, !invariant.group [[META45]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP27]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP29]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i32, ptr [[TMP30]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds ptr, ptr [[TMP31]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I112]], ptr [[TMP32]], align 8, !invariant.group [[META46]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i64, ptr [[TMP33]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i32, ptr [[TMP34]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i32, ptr [[TMP35]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i32, ptr [[TMP36]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds ptr, ptr [[TMP37]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds ptr, ptr [[TMP38]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I111]], ptr [[TMP39]], align 8, !invariant.group [[META47]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds i64, ptr [[TMP40]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds i32, ptr [[TMP41]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i32, ptr [[TMP42]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, ptr [[TMP43]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds ptr, ptr [[TMP44]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds ptr, ptr [[TMP45]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP47:%.*]] = getelementptr inbounds ptr, ptr [[TMP46]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I110]], ptr [[TMP47]], align 8, !invariant.group [[META48]]
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds i64, ptr [[TMP48]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP50:%.*]] = getelementptr inbounds i32, ptr [[TMP49]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP51:%.*]] = getelementptr inbounds i32, ptr [[TMP50]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i32, ptr [[TMP51]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds ptr, ptr [[TMP52]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds ptr, ptr [[TMP53]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds ptr, ptr [[TMP54]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP56:%.*]] = getelementptr inbounds ptr, ptr [[TMP55]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I108]], ptr [[TMP56]], align 8, !invariant.group [[META49]]
; CHECK-NEXT:    [[TMP57:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP58:%.*]] = getelementptr inbounds i64, ptr [[TMP57]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i32, ptr [[TMP58]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds i32, ptr [[TMP59]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP61:%.*]] = getelementptr inbounds i32, ptr [[TMP60]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP62:%.*]] = getelementptr inbounds ptr, ptr [[TMP61]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds ptr, ptr [[TMP62]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds ptr, ptr [[TMP63]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds ptr, ptr [[TMP64]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP66:%.*]] = getelementptr inbounds ptr, ptr [[TMP65]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I107]], ptr [[TMP66]], align 8, !invariant.group [[META50]]
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr inbounds i64, ptr [[TMP67]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP69:%.*]] = getelementptr inbounds i32, ptr [[TMP68]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP70:%.*]] = getelementptr inbounds i32, ptr [[TMP69]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP71:%.*]] = getelementptr inbounds i32, ptr [[TMP70]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP72:%.*]] = getelementptr inbounds ptr, ptr [[TMP71]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP73:%.*]] = getelementptr inbounds ptr, ptr [[TMP72]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds ptr, ptr [[TMP73]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP75:%.*]] = getelementptr inbounds ptr, ptr [[TMP74]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP76:%.*]] = getelementptr inbounds ptr, ptr [[TMP75]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP77:%.*]] = getelementptr inbounds i64, ptr [[TMP76]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I106]], ptr [[TMP77]], align 8, !invariant.group [[META51]]
; CHECK-NEXT:    [[TMP78:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP79:%.*]] = getelementptr inbounds i64, ptr [[TMP78]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP80:%.*]] = getelementptr inbounds i32, ptr [[TMP79]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP81:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP82:%.*]] = getelementptr inbounds i32, ptr [[TMP81]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP83:%.*]] = getelementptr inbounds ptr, ptr [[TMP82]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP84:%.*]] = getelementptr inbounds ptr, ptr [[TMP83]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP85:%.*]] = getelementptr inbounds ptr, ptr [[TMP84]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP86:%.*]] = getelementptr inbounds ptr, ptr [[TMP85]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP87:%.*]] = getelementptr inbounds ptr, ptr [[TMP86]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP88:%.*]] = getelementptr inbounds i64, ptr [[TMP87]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP89:%.*]] = getelementptr inbounds i64, ptr [[TMP88]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I105]], ptr [[TMP89]], align 8, !invariant.group [[META52]]
; CHECK-NEXT:    [[TMP90:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP91:%.*]] = getelementptr inbounds i64, ptr [[TMP90]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr inbounds i32, ptr [[TMP91]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP93:%.*]] = getelementptr inbounds i32, ptr [[TMP92]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP94:%.*]] = getelementptr inbounds i32, ptr [[TMP93]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP95:%.*]] = getelementptr inbounds ptr, ptr [[TMP94]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP96:%.*]] = getelementptr inbounds ptr, ptr [[TMP95]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP97:%.*]] = getelementptr inbounds ptr, ptr [[TMP96]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP98:%.*]] = getelementptr inbounds ptr, ptr [[TMP97]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP99:%.*]] = getelementptr inbounds ptr, ptr [[TMP98]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP100:%.*]] = getelementptr inbounds i64, ptr [[TMP99]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i64, ptr [[TMP100]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP102:%.*]] = getelementptr inbounds i32, ptr [[TMP101]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I104]], ptr [[TMP102]], align 4, !invariant.group [[META53]]
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds i64, ptr [[TMP103]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds i32, ptr [[TMP104]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds i32, ptr [[TMP105]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i32, ptr [[TMP106]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds ptr, ptr [[TMP107]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds ptr, ptr [[TMP108]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP110:%.*]] = getelementptr inbounds ptr, ptr [[TMP109]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP111:%.*]] = getelementptr inbounds ptr, ptr [[TMP110]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP112:%.*]] = getelementptr inbounds ptr, ptr [[TMP111]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP113:%.*]] = getelementptr inbounds i64, ptr [[TMP112]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP114:%.*]] = getelementptr inbounds i64, ptr [[TMP113]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP115:%.*]] = getelementptr inbounds i32, ptr [[TMP114]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP116:%.*]] = getelementptr inbounds i64, ptr [[TMP115]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I40]], ptr [[TMP116]], align 8, !invariant.group [[META54]]
; CHECK-NEXT:    [[TMP117:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP118:%.*]] = getelementptr inbounds i64, ptr [[TMP117]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP119:%.*]] = getelementptr inbounds i32, ptr [[TMP118]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds i32, ptr [[TMP119]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP121:%.*]] = getelementptr inbounds i32, ptr [[TMP120]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP122:%.*]] = getelementptr inbounds ptr, ptr [[TMP121]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP123:%.*]] = getelementptr inbounds ptr, ptr [[TMP122]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP124:%.*]] = getelementptr inbounds ptr, ptr [[TMP123]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr inbounds ptr, ptr [[TMP124]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr inbounds ptr, ptr [[TMP125]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP127:%.*]] = getelementptr inbounds i64, ptr [[TMP126]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP128:%.*]] = getelementptr inbounds i64, ptr [[TMP127]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP129:%.*]] = getelementptr inbounds i32, ptr [[TMP128]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP130:%.*]] = getelementptr inbounds i64, ptr [[TMP129]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP131:%.*]] = getelementptr inbounds i32, ptr [[TMP130]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I31170]], ptr [[TMP131]], align 4, !invariant.group [[META55]]
; CHECK-NEXT:    [[TMP132:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP133:%.*]] = getelementptr inbounds i64, ptr [[TMP132]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP134:%.*]] = getelementptr inbounds i32, ptr [[TMP133]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP135:%.*]] = getelementptr inbounds i32, ptr [[TMP134]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP136:%.*]] = getelementptr inbounds i32, ptr [[TMP135]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP137:%.*]] = getelementptr inbounds ptr, ptr [[TMP136]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP138:%.*]] = getelementptr inbounds ptr, ptr [[TMP137]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP139:%.*]] = getelementptr inbounds ptr, ptr [[TMP138]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP140:%.*]] = getelementptr inbounds ptr, ptr [[TMP139]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP141:%.*]] = getelementptr inbounds ptr, ptr [[TMP140]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP142:%.*]] = getelementptr inbounds i64, ptr [[TMP141]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP143:%.*]] = getelementptr inbounds i64, ptr [[TMP142]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP144:%.*]] = getelementptr inbounds i32, ptr [[TMP143]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP145:%.*]] = getelementptr inbounds i64, ptr [[TMP144]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP146:%.*]] = getelementptr inbounds i32, ptr [[TMP145]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP147:%.*]] = getelementptr inbounds i32, ptr [[TMP146]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I30176]], ptr [[TMP147]], align 4, !invariant.group [[META56]]
; CHECK-NEXT:    [[TMP148:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP149:%.*]] = getelementptr inbounds i64, ptr [[TMP148]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP150:%.*]] = getelementptr inbounds i32, ptr [[TMP149]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP151:%.*]] = getelementptr inbounds i32, ptr [[TMP150]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP152:%.*]] = getelementptr inbounds i32, ptr [[TMP151]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP153:%.*]] = getelementptr inbounds ptr, ptr [[TMP152]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP154:%.*]] = getelementptr inbounds ptr, ptr [[TMP153]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP155:%.*]] = getelementptr inbounds ptr, ptr [[TMP154]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP156:%.*]] = getelementptr inbounds ptr, ptr [[TMP155]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP157:%.*]] = getelementptr inbounds ptr, ptr [[TMP156]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP158:%.*]] = getelementptr inbounds i64, ptr [[TMP157]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP159:%.*]] = getelementptr inbounds i64, ptr [[TMP158]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP160:%.*]] = getelementptr inbounds i32, ptr [[TMP159]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP161:%.*]] = getelementptr inbounds i64, ptr [[TMP160]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP162:%.*]] = getelementptr inbounds i32, ptr [[TMP161]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP163:%.*]] = getelementptr inbounds i32, ptr [[TMP162]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP164:%.*]] = getelementptr inbounds i32, ptr [[TMP163]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I5182]], ptr [[TMP164]], align 4, !invariant.group [[META57]]
; CHECK-NEXT:    [[TMP165:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP166:%.*]] = getelementptr inbounds i64, ptr [[TMP165]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP167:%.*]] = getelementptr inbounds i32, ptr [[TMP166]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP168:%.*]] = getelementptr inbounds i32, ptr [[TMP167]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP169:%.*]] = getelementptr inbounds i32, ptr [[TMP168]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP170:%.*]] = getelementptr inbounds ptr, ptr [[TMP169]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP171:%.*]] = getelementptr inbounds ptr, ptr [[TMP170]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP172:%.*]] = getelementptr inbounds ptr, ptr [[TMP171]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP173:%.*]] = getelementptr inbounds ptr, ptr [[TMP172]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP174:%.*]] = getelementptr inbounds ptr, ptr [[TMP173]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP175:%.*]] = getelementptr inbounds i64, ptr [[TMP174]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP176:%.*]] = getelementptr inbounds i64, ptr [[TMP175]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP177:%.*]] = getelementptr inbounds i32, ptr [[TMP176]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP178:%.*]] = getelementptr inbounds i64, ptr [[TMP177]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP179:%.*]] = getelementptr inbounds i32, ptr [[TMP178]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP180:%.*]] = getelementptr inbounds i32, ptr [[TMP179]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP181:%.*]] = getelementptr inbounds i32, ptr [[TMP180]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP182:%.*]] = getelementptr inbounds i32, ptr [[TMP181]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I212]], ptr [[TMP182]], align 4, !invariant.group [[META58]]
; CHECK-NEXT:    [[TMP183:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP184:%.*]] = getelementptr inbounds i64, ptr [[TMP183]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP185:%.*]] = getelementptr inbounds i32, ptr [[TMP184]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP186:%.*]] = getelementptr inbounds i32, ptr [[TMP185]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP187:%.*]] = getelementptr inbounds i32, ptr [[TMP186]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP188:%.*]] = getelementptr inbounds ptr, ptr [[TMP187]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP189:%.*]] = getelementptr inbounds ptr, ptr [[TMP188]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP190:%.*]] = getelementptr inbounds ptr, ptr [[TMP189]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP191:%.*]] = getelementptr inbounds ptr, ptr [[TMP190]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP192:%.*]] = getelementptr inbounds ptr, ptr [[TMP191]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP193:%.*]] = getelementptr inbounds i64, ptr [[TMP192]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP194:%.*]] = getelementptr inbounds i64, ptr [[TMP193]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP195:%.*]] = getelementptr inbounds i32, ptr [[TMP194]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP196:%.*]] = getelementptr inbounds i64, ptr [[TMP195]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP197:%.*]] = getelementptr inbounds i32, ptr [[TMP196]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP198:%.*]] = getelementptr inbounds i32, ptr [[TMP197]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP199:%.*]] = getelementptr inbounds i32, ptr [[TMP198]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP200:%.*]] = getelementptr inbounds i32, ptr [[TMP199]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP201:%.*]] = getelementptr inbounds i32, ptr [[TMP200]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I18222]], ptr [[TMP201]], align 4, !invariant.group [[META59]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       CacheRemat0:
; CHECK-NEXT:    [[TMP202:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP203:%.*]] = load ptr, ptr [[TMP202]], align 8
; CHECK-NEXT:    [[TMP204:%.*]] = getelementptr inbounds ptr, ptr [[TMP203]], i32 3
; CHECK-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP204]], align 8
; CHECK-NEXT:    [[TMP205:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_IN_OFFSET:%.*]] = load i32, ptr [[TMP205]], align 4
; CHECK-NEXT:    [[TMP206:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-NEXT:    [[I10_CACHE:%.*]] = load i32, ptr [[TMP206]], align 4, !invariant.group [[META41]]
; CHECK-NEXT:    [[TMP207:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP208:%.*]] = getelementptr inbounds i64, ptr [[TMP207]], i32 [[GTID]]
; CHECK-NEXT:    [[I70_CACHE:%.*]] = load i64, ptr [[TMP208]], align 8, !invariant.group [[META42]]
; CHECK-NEXT:    [[TMP209:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP210:%.*]] = getelementptr inbounds i64, ptr [[TMP209]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP211:%.*]] = getelementptr inbounds i32, ptr [[TMP210]], i32 [[GTID]]
; CHECK-NEXT:    [[I115_CACHE:%.*]] = load i32, ptr [[TMP211]], align 4, !invariant.group [[META43]]
; CHECK-NEXT:    [[TMP212:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP213:%.*]] = getelementptr inbounds i64, ptr [[TMP212]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP214:%.*]] = getelementptr inbounds i32, ptr [[TMP213]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP215:%.*]] = getelementptr inbounds i32, ptr [[TMP214]], i32 [[GTID]]
; CHECK-NEXT:    [[I114_CACHE:%.*]] = load i32, ptr [[TMP215]], align 4, !invariant.group [[META44]]
; CHECK-NEXT:    [[TMP216:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP217:%.*]] = getelementptr inbounds i64, ptr [[TMP216]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP218:%.*]] = getelementptr inbounds i32, ptr [[TMP217]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP219:%.*]] = getelementptr inbounds i32, ptr [[TMP218]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP220:%.*]] = getelementptr inbounds i32, ptr [[TMP219]], i32 [[GTID]]
; CHECK-NEXT:    [[I113_CACHE:%.*]] = load i32, ptr [[TMP220]], align 4, !invariant.group [[META45]]
; CHECK-NEXT:    [[TMP221:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP222:%.*]] = getelementptr inbounds i64, ptr [[TMP221]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP223:%.*]] = getelementptr inbounds i32, ptr [[TMP222]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP224:%.*]] = getelementptr inbounds i32, ptr [[TMP223]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP225:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP226:%.*]] = getelementptr inbounds ptr, ptr [[TMP225]], i32 [[GTID]]
; CHECK-NEXT:    [[I112_CACHE:%.*]] = load ptr, ptr [[TMP226]], align 8, !invariant.group [[META46]]
; CHECK-NEXT:    [[TMP227:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP228:%.*]] = getelementptr inbounds i64, ptr [[TMP227]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP229:%.*]] = getelementptr inbounds i32, ptr [[TMP228]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP230:%.*]] = getelementptr inbounds i32, ptr [[TMP229]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP231:%.*]] = getelementptr inbounds i32, ptr [[TMP230]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP232:%.*]] = getelementptr inbounds ptr, ptr [[TMP231]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP233:%.*]] = getelementptr inbounds ptr, ptr [[TMP232]], i32 [[GTID]]
; CHECK-NEXT:    [[I111_CACHE:%.*]] = load ptr, ptr [[TMP233]], align 8, !invariant.group [[META47]]
; CHECK-NEXT:    [[TMP234:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP235:%.*]] = getelementptr inbounds i64, ptr [[TMP234]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP236:%.*]] = getelementptr inbounds i32, ptr [[TMP235]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP237:%.*]] = getelementptr inbounds i32, ptr [[TMP236]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP238:%.*]] = getelementptr inbounds i32, ptr [[TMP237]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP239:%.*]] = getelementptr inbounds ptr, ptr [[TMP238]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP240:%.*]] = getelementptr inbounds ptr, ptr [[TMP239]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP241:%.*]] = getelementptr inbounds ptr, ptr [[TMP240]], i32 [[GTID]]
; CHECK-NEXT:    [[I110_CACHE:%.*]] = load ptr, ptr [[TMP241]], align 8, !invariant.group [[META48]]
; CHECK-NEXT:    [[TMP242:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP243:%.*]] = getelementptr inbounds i64, ptr [[TMP242]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP244:%.*]] = getelementptr inbounds i32, ptr [[TMP243]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP245:%.*]] = getelementptr inbounds i32, ptr [[TMP244]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP246:%.*]] = getelementptr inbounds i32, ptr [[TMP245]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP247:%.*]] = getelementptr inbounds ptr, ptr [[TMP246]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP248:%.*]] = getelementptr inbounds ptr, ptr [[TMP247]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP249:%.*]] = getelementptr inbounds ptr, ptr [[TMP248]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP250:%.*]] = getelementptr inbounds ptr, ptr [[TMP249]], i32 [[GTID]]
; CHECK-NEXT:    [[I108_CACHE:%.*]] = load ptr, ptr [[TMP250]], align 8, !invariant.group [[META49]]
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr inbounds i64, ptr [[TMP251]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP253:%.*]] = getelementptr inbounds i32, ptr [[TMP252]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP254:%.*]] = getelementptr inbounds i32, ptr [[TMP253]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP255:%.*]] = getelementptr inbounds i32, ptr [[TMP254]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr inbounds ptr, ptr [[TMP255]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr inbounds ptr, ptr [[TMP256]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP258:%.*]] = getelementptr inbounds ptr, ptr [[TMP257]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr inbounds ptr, ptr [[TMP258]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr inbounds ptr, ptr [[TMP259]], i32 [[GTID]]
; CHECK-NEXT:    [[I107_CACHE:%.*]] = load ptr, ptr [[TMP260]], align 8, !invariant.group [[META50]]
; CHECK-NEXT:    [[TMP261:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP262:%.*]] = getelementptr inbounds i64, ptr [[TMP261]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP263:%.*]] = getelementptr inbounds i32, ptr [[TMP262]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP264:%.*]] = getelementptr inbounds i32, ptr [[TMP263]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP265:%.*]] = getelementptr inbounds i32, ptr [[TMP264]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP266:%.*]] = getelementptr inbounds ptr, ptr [[TMP265]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP267:%.*]] = getelementptr inbounds ptr, ptr [[TMP266]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP268:%.*]] = getelementptr inbounds ptr, ptr [[TMP267]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP269:%.*]] = getelementptr inbounds ptr, ptr [[TMP268]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP270:%.*]] = getelementptr inbounds ptr, ptr [[TMP269]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP271:%.*]] = getelementptr inbounds i64, ptr [[TMP270]], i32 [[GTID]]
; CHECK-NEXT:    [[I106_CACHE:%.*]] = load i64, ptr [[TMP271]], align 8, !invariant.group [[META51]]
; CHECK-NEXT:    [[TMP272:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP273:%.*]] = getelementptr inbounds i64, ptr [[TMP272]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP274:%.*]] = getelementptr inbounds i32, ptr [[TMP273]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP275:%.*]] = getelementptr inbounds i32, ptr [[TMP274]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP276:%.*]] = getelementptr inbounds i32, ptr [[TMP275]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP277:%.*]] = getelementptr inbounds ptr, ptr [[TMP276]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP278:%.*]] = getelementptr inbounds ptr, ptr [[TMP277]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP279:%.*]] = getelementptr inbounds ptr, ptr [[TMP278]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP280:%.*]] = getelementptr inbounds ptr, ptr [[TMP279]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP281:%.*]] = getelementptr inbounds ptr, ptr [[TMP280]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP282:%.*]] = getelementptr inbounds i64, ptr [[TMP281]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP283:%.*]] = getelementptr inbounds i64, ptr [[TMP282]], i32 [[GTID]]
; CHECK-NEXT:    [[I105_CACHE:%.*]] = load i64, ptr [[TMP283]], align 8, !invariant.group [[META52]]
; CHECK-NEXT:    [[TMP284:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP285:%.*]] = getelementptr inbounds i64, ptr [[TMP284]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP286:%.*]] = getelementptr inbounds i32, ptr [[TMP285]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP287:%.*]] = getelementptr inbounds i32, ptr [[TMP286]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP288:%.*]] = getelementptr inbounds i32, ptr [[TMP287]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP289:%.*]] = getelementptr inbounds ptr, ptr [[TMP288]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP290:%.*]] = getelementptr inbounds ptr, ptr [[TMP289]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP291:%.*]] = getelementptr inbounds ptr, ptr [[TMP290]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP292:%.*]] = getelementptr inbounds ptr, ptr [[TMP291]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP293:%.*]] = getelementptr inbounds ptr, ptr [[TMP292]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP294:%.*]] = getelementptr inbounds i64, ptr [[TMP293]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP295:%.*]] = getelementptr inbounds i64, ptr [[TMP294]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP296:%.*]] = getelementptr inbounds i32, ptr [[TMP295]], i32 [[GTID]]
; CHECK-NEXT:    [[I104_CACHE:%.*]] = load i32, ptr [[TMP296]], align 4, !invariant.group [[META53]]
; CHECK-NEXT:    [[TMP297:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP298:%.*]] = getelementptr inbounds i64, ptr [[TMP297]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP299:%.*]] = getelementptr inbounds i32, ptr [[TMP298]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP300:%.*]] = getelementptr inbounds i32, ptr [[TMP299]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP301:%.*]] = getelementptr inbounds i32, ptr [[TMP300]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP302:%.*]] = getelementptr inbounds ptr, ptr [[TMP301]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP303:%.*]] = getelementptr inbounds ptr, ptr [[TMP302]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP304:%.*]] = getelementptr inbounds ptr, ptr [[TMP303]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP305:%.*]] = getelementptr inbounds ptr, ptr [[TMP304]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP306:%.*]] = getelementptr inbounds ptr, ptr [[TMP305]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP307:%.*]] = getelementptr inbounds i64, ptr [[TMP306]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP308:%.*]] = getelementptr inbounds i64, ptr [[TMP307]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP309:%.*]] = getelementptr inbounds i32, ptr [[TMP308]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP310:%.*]] = getelementptr inbounds i64, ptr [[TMP309]], i32 [[GTID]]
; CHECK-NEXT:    [[I40_CACHE:%.*]] = load i64, ptr [[TMP310]], align 8, !invariant.group [[META54]]
; CHECK-NEXT:    [[TMP311:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP312:%.*]] = getelementptr inbounds i64, ptr [[TMP311]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP313:%.*]] = getelementptr inbounds i32, ptr [[TMP312]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP314:%.*]] = getelementptr inbounds i32, ptr [[TMP313]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP315:%.*]] = getelementptr inbounds i32, ptr [[TMP314]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP316:%.*]] = getelementptr inbounds ptr, ptr [[TMP315]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP317:%.*]] = getelementptr inbounds ptr, ptr [[TMP316]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP318:%.*]] = getelementptr inbounds ptr, ptr [[TMP317]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP319:%.*]] = getelementptr inbounds ptr, ptr [[TMP318]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP320:%.*]] = getelementptr inbounds ptr, ptr [[TMP319]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP321:%.*]] = getelementptr inbounds i64, ptr [[TMP320]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP322:%.*]] = getelementptr inbounds i64, ptr [[TMP321]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP323:%.*]] = getelementptr inbounds i32, ptr [[TMP322]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP324:%.*]] = getelementptr inbounds i64, ptr [[TMP323]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP325:%.*]] = getelementptr inbounds i32, ptr [[TMP324]], i32 [[GTID]]
; CHECK-NEXT:    [[I31_CACHE:%.*]] = load i32, ptr [[TMP325]], align 4, !invariant.group [[META55]]
; CHECK-NEXT:    [[TMP326:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP327:%.*]] = getelementptr inbounds i64, ptr [[TMP326]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP328:%.*]] = getelementptr inbounds i32, ptr [[TMP327]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP329:%.*]] = getelementptr inbounds i32, ptr [[TMP328]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP330:%.*]] = getelementptr inbounds i32, ptr [[TMP329]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP331:%.*]] = getelementptr inbounds ptr, ptr [[TMP330]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP332:%.*]] = getelementptr inbounds ptr, ptr [[TMP331]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP333:%.*]] = getelementptr inbounds ptr, ptr [[TMP332]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP334:%.*]] = getelementptr inbounds ptr, ptr [[TMP333]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP335:%.*]] = getelementptr inbounds ptr, ptr [[TMP334]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP336:%.*]] = getelementptr inbounds i64, ptr [[TMP335]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP337:%.*]] = getelementptr inbounds i64, ptr [[TMP336]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP338:%.*]] = getelementptr inbounds i32, ptr [[TMP337]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP339:%.*]] = getelementptr inbounds i64, ptr [[TMP338]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP340:%.*]] = getelementptr inbounds i32, ptr [[TMP339]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP341:%.*]] = getelementptr inbounds i32, ptr [[TMP340]], i32 [[GTID]]
; CHECK-NEXT:    [[I30_CACHE:%.*]] = load i32, ptr [[TMP341]], align 4, !invariant.group [[META56]]
; CHECK-NEXT:    [[TMP342:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP343:%.*]] = getelementptr inbounds i64, ptr [[TMP342]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP344:%.*]] = getelementptr inbounds i32, ptr [[TMP343]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP345:%.*]] = getelementptr inbounds i32, ptr [[TMP344]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP346:%.*]] = getelementptr inbounds i32, ptr [[TMP345]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP347:%.*]] = getelementptr inbounds ptr, ptr [[TMP346]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP348:%.*]] = getelementptr inbounds ptr, ptr [[TMP347]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP349:%.*]] = getelementptr inbounds ptr, ptr [[TMP348]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP350:%.*]] = getelementptr inbounds ptr, ptr [[TMP349]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP351:%.*]] = getelementptr inbounds ptr, ptr [[TMP350]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP352:%.*]] = getelementptr inbounds i64, ptr [[TMP351]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP353:%.*]] = getelementptr inbounds i64, ptr [[TMP352]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP354:%.*]] = getelementptr inbounds i32, ptr [[TMP353]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP355:%.*]] = getelementptr inbounds i64, ptr [[TMP354]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP356:%.*]] = getelementptr inbounds i32, ptr [[TMP355]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP357:%.*]] = getelementptr inbounds i32, ptr [[TMP356]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP358:%.*]] = getelementptr inbounds i32, ptr [[TMP357]], i32 [[GTID]]
; CHECK-NEXT:    [[I5_CACHE:%.*]] = load i32, ptr [[TMP358]], align 4, !invariant.group [[META57]]
; CHECK-NEXT:    [[TMP359:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP360:%.*]] = getelementptr inbounds i64, ptr [[TMP359]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP361:%.*]] = getelementptr inbounds i32, ptr [[TMP360]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP362:%.*]] = getelementptr inbounds i32, ptr [[TMP361]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP363:%.*]] = getelementptr inbounds i32, ptr [[TMP362]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP364:%.*]] = getelementptr inbounds ptr, ptr [[TMP363]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP365:%.*]] = getelementptr inbounds ptr, ptr [[TMP364]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP366:%.*]] = getelementptr inbounds ptr, ptr [[TMP365]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP367:%.*]] = getelementptr inbounds ptr, ptr [[TMP366]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP368:%.*]] = getelementptr inbounds ptr, ptr [[TMP367]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP369:%.*]] = getelementptr inbounds i64, ptr [[TMP368]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP370:%.*]] = getelementptr inbounds i64, ptr [[TMP369]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP371:%.*]] = getelementptr inbounds i32, ptr [[TMP370]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP372:%.*]] = getelementptr inbounds i64, ptr [[TMP371]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP373:%.*]] = getelementptr inbounds i32, ptr [[TMP372]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP374:%.*]] = getelementptr inbounds i32, ptr [[TMP373]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP375:%.*]] = getelementptr inbounds i32, ptr [[TMP374]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP376:%.*]] = getelementptr inbounds i32, ptr [[TMP375]], i32 [[GTID]]
; CHECK-NEXT:    [[I_CACHE:%.*]] = load i32, ptr [[TMP376]], align 4, !invariant.group [[META58]]
; CHECK-NEXT:    [[TMP377:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP378:%.*]] = getelementptr inbounds i64, ptr [[TMP377]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP379:%.*]] = getelementptr inbounds i32, ptr [[TMP378]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP380:%.*]] = getelementptr inbounds i32, ptr [[TMP379]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP381:%.*]] = getelementptr inbounds i32, ptr [[TMP380]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP382:%.*]] = getelementptr inbounds ptr, ptr [[TMP381]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP383:%.*]] = getelementptr inbounds ptr, ptr [[TMP382]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP384:%.*]] = getelementptr inbounds ptr, ptr [[TMP383]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP385:%.*]] = getelementptr inbounds ptr, ptr [[TMP384]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP386:%.*]] = getelementptr inbounds ptr, ptr [[TMP385]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP387:%.*]] = getelementptr inbounds i64, ptr [[TMP386]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP388:%.*]] = getelementptr inbounds i64, ptr [[TMP387]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP389:%.*]] = getelementptr inbounds i32, ptr [[TMP388]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP390:%.*]] = getelementptr inbounds i64, ptr [[TMP389]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP391:%.*]] = getelementptr inbounds i32, ptr [[TMP390]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP392:%.*]] = getelementptr inbounds i32, ptr [[TMP391]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP393:%.*]] = getelementptr inbounds i32, ptr [[TMP392]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP394:%.*]] = getelementptr inbounds i32, ptr [[TMP393]], i32 [[CACHE_IN_OFFSET]]
; CHECK-NEXT:    [[TMP395:%.*]] = getelementptr inbounds i32, ptr [[TMP394]], i32 [[GTID]]
; CHECK-NEXT:    [[I18_CACHE:%.*]] = load i32, ptr [[TMP395]], align 4, !invariant.group [[META59]]
; CHECK-NEXT:    [[I13_RECOMPUTE:%.*]] = shl nsw i32 [[I10_CACHE]], 7
; CHECK-NEXT:    [[I4_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I19_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 8
; CHECK-NEXT:    [[I20_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 16
; CHECK-NEXT:    [[I26_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 40
; CHECK-NEXT:    [[I27_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 44
; CHECK-NEXT:    [[I71_RECOMPUTE:%.*]] = mul i64 [[I70_CACHE]], 2806196910506780709
; CHECK-NEXT:    [[I72_RECOMPUTE:%.*]] = add i64 [[I71_RECOMPUTE]], 1
; CHECK-NEXT:    [[I73_RECOMPUTE:%.*]] = and i64 [[I72_RECOMPUTE]], 9223372036854775807
; CHECK-NEXT:    [[I74_RECOMPUTE:%.*]] = uitofp i64 [[I73_RECOMPUTE]] to double
; CHECK-NEXT:    [[I75_RECOMPUTE:%.*]] = fmul double [[I74_RECOMPUTE]], 0x3C00000000000000
; CHECK-NEXT:    [[I41_RECOMPUTE:%.*]] = trunc i64 [[I40_CACHE]] to i32
; CHECK-NEXT:    [[I32_RECOMPUTE:%.*]] = zext i32 [[I30_CACHE]] to i64
; CHECK-NEXT:    [[I6_RECOMPUTE:%.*]] = add nsw i32 [[I5_CACHE]], -1
; CHECK-NEXT:    [[I21_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 8
; CHECK-NEXT:    [[I22_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 24
; CHECK-NEXT:    [[I23_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 32
; CHECK-NEXT:    [[I24_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 40
; CHECK-NEXT:    [[I25_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 16
; CHECK-NEXT:    [[I28_RECOMPUTE:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 76
; CHECK-NEXT:    [[I135:%.*]] = sitofp i32 [[I114_CACHE]] to double
; CHECK-NEXT:    [[I136:%.*]] = fdiv double 1.000000e+00, [[I135]]
; CHECK-NEXT:    [[I137:%.*]] = fdiv double [[I75_RECOMPUTE]], [[I136]]
; CHECK-NEXT:    [[I138:%.*]] = fptosi double [[I137]] to i64
; CHECK-NEXT:    br label [[BB139]]
; CHECK:       bb139:
; CHECK-NEXT:    [[I28322:%.*]] = phi ptr [ [[I28_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I28326]], [[BB103]] ], [ [[I28326]], [[BB116]] ], [ [[I28326]], [[BB121]] ]
; CHECK-NEXT:    [[I25315:%.*]] = phi ptr [ [[I25_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I25319]], [[BB103]] ], [ [[I25319]], [[BB116]] ], [ [[I25319]], [[BB121]] ]
; CHECK-NEXT:    [[I24308:%.*]] = phi ptr [ [[I24_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I24312]], [[BB103]] ], [ [[I24312]], [[BB116]] ], [ [[I24312]], [[BB121]] ]
; CHECK-NEXT:    [[I23301:%.*]] = phi ptr [ [[I23_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I23305]], [[BB103]] ], [ [[I23305]], [[BB116]] ], [ [[I23305]], [[BB121]] ]
; CHECK-NEXT:    [[I22294:%.*]] = phi ptr [ [[I22_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I22298]], [[BB103]] ], [ [[I22298]], [[BB116]] ], [ [[I22298]], [[BB121]] ]
; CHECK-NEXT:    [[I21287:%.*]] = phi ptr [ [[I21_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I21291]], [[BB103]] ], [ [[I21291]], [[BB116]] ], [ [[I21291]], [[BB121]] ]
; CHECK-NEXT:    [[I6279:%.*]] = phi i32 [ [[I6_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I6283]], [[BB103]] ], [ [[I6283]], [[BB116]] ], [ [[I6283]], [[BB121]] ]
; CHECK-NEXT:    [[I32274:%.*]] = phi i64 [ [[I32_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I32277]], [[BB103]] ], [ [[I32277]], [[BB116]] ], [ [[I32277]], [[BB121]] ]
; CHECK-NEXT:    [[I41270:%.*]] = phi i32 [ [[I41_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I41]], [[BB103]] ], [ [[I41]], [[BB116]] ], [ [[I41]], [[BB121]] ]
; CHECK-NEXT:    [[I75267:%.*]] = phi double [ [[I75_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I75]], [[BB103]] ], [ [[I75]], [[BB116]] ], [ [[I75]], [[BB121]] ]
; CHECK-NEXT:    [[I27261:%.*]] = phi ptr [ [[I27_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I27265]], [[BB103]] ], [ [[I27265]], [[BB116]] ], [ [[I27265]], [[BB121]] ]
; CHECK-NEXT:    [[I26254:%.*]] = phi ptr [ [[I26_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I26258]], [[BB103]] ], [ [[I26258]], [[BB116]] ], [ [[I26258]], [[BB121]] ]
; CHECK-NEXT:    [[I20247:%.*]] = phi ptr [ [[I20_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I20251]], [[BB103]] ], [ [[I20251]], [[BB116]] ], [ [[I20251]], [[BB121]] ]
; CHECK-NEXT:    [[I19240:%.*]] = phi ptr [ [[I19_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I19244]], [[BB103]] ], [ [[I19244]], [[BB116]] ], [ [[I19244]], [[BB121]] ]
; CHECK-NEXT:    [[I4232:%.*]] = phi ptr [ [[I4_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I4236]], [[BB103]] ], [ [[I4236]], [[BB116]] ], [ [[I4236]], [[BB121]] ]
; CHECK-NEXT:    [[I13225:%.*]] = phi i32 [ [[I13_RECOMPUTE]], [[CACHEREMAT0]] ], [ [[I13230]], [[BB103]] ], [ [[I13230]], [[BB116]] ], [ [[I13230]], [[BB121]] ]
; CHECK-NEXT:    [[I18218:%.*]] = phi i32 [ [[I18_CACHE]], [[CACHEREMAT0]] ], [ [[I18222]], [[BB103]] ], [ [[I18222]], [[BB116]] ], [ [[I18222]], [[BB121]] ]
; CHECK-NEXT:    [[I192:%.*]] = phi i32 [ [[I_CACHE]], [[CACHEREMAT0]] ], [ [[I212]], [[BB103]] ], [ [[I212]], [[BB116]] ], [ [[I212]], [[BB121]] ]
; CHECK-NEXT:    [[I5178:%.*]] = phi i32 [ [[I5_CACHE]], [[CACHEREMAT0]] ], [ [[I5182]], [[BB103]] ], [ [[I5182]], [[BB116]] ], [ [[I5182]], [[BB121]] ]
; CHECK-NEXT:    [[I30172:%.*]] = phi i32 [ [[I30_CACHE]], [[CACHEREMAT0]] ], [ [[I30176]], [[BB103]] ], [ [[I30176]], [[BB116]] ], [ [[I30176]], [[BB121]] ]
; CHECK-NEXT:    [[I31166:%.*]] = phi i32 [ [[I31_CACHE]], [[CACHEREMAT0]] ], [ [[I31170]], [[BB103]] ], [ [[I31170]], [[BB116]] ], [ [[I31170]], [[BB121]] ]
; CHECK-NEXT:    [[I40162:%.*]] = phi i64 [ [[I40_CACHE]], [[CACHEREMAT0]] ], [ [[I40]], [[BB103]] ], [ [[I40]], [[BB116]] ], [ [[I40]], [[BB121]] ]
; CHECK-NEXT:    [[I104160:%.*]] = phi i32 [ [[I104_CACHE]], [[CACHEREMAT0]] ], [ [[I104]], [[BB103]] ], [ [[I104]], [[BB116]] ], [ [[I104]], [[BB121]] ]
; CHECK-NEXT:    [[I105159:%.*]] = phi i64 [ [[I105_CACHE]], [[CACHEREMAT0]] ], [ [[I105]], [[BB103]] ], [ [[I105]], [[BB116]] ], [ [[I105]], [[BB121]] ]
; CHECK-NEXT:    [[I106156:%.*]] = phi i64 [ [[I106_CACHE]], [[CACHEREMAT0]] ], [ [[I106]], [[BB103]] ], [ [[I106]], [[BB116]] ], [ [[I106]], [[BB121]] ]
; CHECK-NEXT:    [[I107155:%.*]] = phi ptr [ [[I107_CACHE]], [[CACHEREMAT0]] ], [ [[I107]], [[BB103]] ], [ [[I107]], [[BB116]] ], [ [[I107]], [[BB121]] ]
; CHECK-NEXT:    [[I108152:%.*]] = phi ptr [ [[I108_CACHE]], [[CACHEREMAT0]] ], [ [[I108]], [[BB103]] ], [ [[I108]], [[BB116]] ], [ [[I108]], [[BB121]] ]
; CHECK-NEXT:    [[I110151:%.*]] = phi ptr [ [[I110_CACHE]], [[CACHEREMAT0]] ], [ [[I110]], [[BB103]] ], [ [[I110]], [[BB116]] ], [ [[I110]], [[BB121]] ]
; CHECK-NEXT:    [[I111148:%.*]] = phi ptr [ [[I111_CACHE]], [[CACHEREMAT0]] ], [ [[I111]], [[BB103]] ], [ [[I111]], [[BB116]] ], [ [[I111]], [[BB121]] ]
; CHECK-NEXT:    [[I112145:%.*]] = phi ptr [ [[I112_CACHE]], [[CACHEREMAT0]] ], [ [[I112]], [[BB103]] ], [ [[I112]], [[BB116]] ], [ [[I112]], [[BB121]] ]
; CHECK-NEXT:    [[I113142:%.*]] = phi i32 [ [[I113_CACHE]], [[CACHEREMAT0]] ], [ [[I113]], [[BB103]] ], [ 0, [[BB116]] ], [ 0, [[BB121]] ]
; CHECK-NEXT:    [[I114141:%.*]] = phi i32 [ [[I114_CACHE]], [[CACHEREMAT0]] ], [ [[I114]], [[BB103]] ], [ [[I114]], [[BB116]] ], [ [[I114]], [[BB121]] ]
; CHECK-NEXT:    [[I115140:%.*]] = phi i32 [ [[I115_CACHE]], [[CACHEREMAT0]] ], [ [[I115]], [[BB103]] ], [ [[I115]], [[BB116]] ], [ [[I115]], [[BB121]] ]
; CHECK-NEXT:    [[I70138:%.*]] = phi i64 [ [[I70_CACHE]], [[CACHEREMAT0]] ], [ [[I70]], [[BB103]] ], [ [[I70]], [[BB116]] ], [ [[I70]], [[BB121]] ]
; CHECK-NEXT:    [[I10131:%.*]] = phi i32 [ [[I10_CACHE]], [[CACHEREMAT0]] ], [ [[I10135]], [[BB103]] ], [ [[I10135]], [[BB116]] ], [ [[I10135]], [[BB121]] ]
; CHECK-NEXT:    [[I140:%.*]] = phi i64 [ [[I138]], [[CACHEREMAT0]] ], [ -1, [[BB103]] ], [ 0, [[BB116]] ], [ [[I131]], [[BB121]] ]
; CHECK-NEXT:    [[I141:%.*]] = zext nneg i32 [[I104160]] to i64
; CHECK-NEXT:    [[I142:%.*]] = getelementptr inbounds i32, ptr [[I107155]], i64 [[I141]]
; CHECK-NEXT:    [[I143:%.*]] = load i32, ptr [[I142]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I144:%.*]] = icmp sgt i32 [[I143]], 0
; CHECK-NEXT:    br i1 [[I144]], label [[BB145:%.*]], label [[BB302]]
; CHECK:       bb145:
; CHECK-NEXT:    [[I146:%.*]] = mul nsw i32 [[I115140]], [[I104160]]
; CHECK-NEXT:    [[I147:%.*]] = mul nsw i64 [[I140]], [[I105159]]
; CHECK-NEXT:    [[I148:%.*]] = getelementptr i32, ptr [[I110151]], i64 [[I147]]
; CHECK-NEXT:    [[I149:%.*]] = add i64 [[I106156]], -1
; CHECK-NEXT:    [[I150:%.*]] = icmp sgt i64 [[I106156]], 2
; CHECK-NEXT:    [[I151:%.*]] = add nsw i32 [[I114141]], -1
; CHECK-NEXT:    [[I152:%.*]] = sext i32 [[I151]] to i64
; CHECK-NEXT:    [[I153:%.*]] = icmp eq i64 [[I140]], [[I152]]
; CHECK-NEXT:    [[I154:%.*]] = add nsw i64 [[I140]], 1
; CHECK-NEXT:    [[I155:%.*]] = mul nsw i64 [[I154]], [[I105159]]
; CHECK-NEXT:    [[I156:%.*]] = getelementptr i32, ptr [[I110151]], i64 [[I155]]
; CHECK-NEXT:    [[I157:%.*]] = trunc i64 [[I106156]] to i32
; CHECK-NEXT:    [[I158:%.*]] = add i32 [[I157]], -1
; CHECK-NEXT:    br label [[BB159:%.*]]
; CHECK:       bb159:
; CHECK-NEXT:    [[I149345:%.*]] = phi i64 [ [[I149]], [[BB145]] ], [ [[I149345]], [[BB197:%.*]] ]
; CHECK-NEXT:    [[I156336:%.*]] = phi ptr [ [[I156]], [[BB145]] ], [ [[I156336]], [[BB197]] ]
; CHECK-NEXT:    [[I148334:%.*]] = phi ptr [ [[I148]], [[BB145]] ], [ [[I148334]], [[BB197]] ]
; CHECK-NEXT:    [[I153332:%.*]] = phi i1 [ [[I153]], [[BB145]] ], [ [[I153332]], [[BB197]] ]
; CHECK-NEXT:    [[I146330:%.*]] = phi i32 [ [[I146]], [[BB145]] ], [ [[I146330]], [[BB197]] ]
; CHECK-NEXT:    [[I142328:%.*]] = phi ptr [ [[I142]], [[BB145]] ], [ [[I142328]], [[BB197]] ]
; CHECK-NEXT:    [[I28324:%.*]] = phi ptr [ [[I28322]], [[BB145]] ], [ [[I28324]], [[BB197]] ]
; CHECK-NEXT:    [[I25317:%.*]] = phi ptr [ [[I25315]], [[BB145]] ], [ [[I25317]], [[BB197]] ]
; CHECK-NEXT:    [[I24310:%.*]] = phi ptr [ [[I24308]], [[BB145]] ], [ [[I24310]], [[BB197]] ]
; CHECK-NEXT:    [[I23303:%.*]] = phi ptr [ [[I23301]], [[BB145]] ], [ [[I23303]], [[BB197]] ]
; CHECK-NEXT:    [[I22296:%.*]] = phi ptr [ [[I22294]], [[BB145]] ], [ [[I22296]], [[BB197]] ]
; CHECK-NEXT:    [[I21289:%.*]] = phi ptr [ [[I21287]], [[BB145]] ], [ [[I21289]], [[BB197]] ]
; CHECK-NEXT:    [[I6281:%.*]] = phi i32 [ [[I6279]], [[BB145]] ], [ [[I6281]], [[BB197]] ]
; CHECK-NEXT:    [[I32276:%.*]] = phi i64 [ [[I32274]], [[BB145]] ], [ [[I32276]], [[BB197]] ]
; CHECK-NEXT:    [[I41272:%.*]] = phi i32 [ [[I41270]], [[BB145]] ], [ [[I41272]], [[BB197]] ]
; CHECK-NEXT:    [[I75268:%.*]] = phi double [ [[I75267]], [[BB145]] ], [ [[I75268]], [[BB197]] ]
; CHECK-NEXT:    [[I27263:%.*]] = phi ptr [ [[I27261]], [[BB145]] ], [ [[I27263]], [[BB197]] ]
; CHECK-NEXT:    [[I26256:%.*]] = phi ptr [ [[I26254]], [[BB145]] ], [ [[I26256]], [[BB197]] ]
; CHECK-NEXT:    [[I20249:%.*]] = phi ptr [ [[I20247]], [[BB145]] ], [ [[I20249]], [[BB197]] ]
; CHECK-NEXT:    [[I19242:%.*]] = phi ptr [ [[I19240]], [[BB145]] ], [ [[I19242]], [[BB197]] ]
; CHECK-NEXT:    [[I4234:%.*]] = phi ptr [ [[I4232]], [[BB145]] ], [ [[I4234]], [[BB197]] ]
; CHECK-NEXT:    [[I13228:%.*]] = phi i32 [ [[I13225]], [[BB145]] ], [ [[I13228]], [[BB197]] ]
; CHECK-NEXT:    [[I18220:%.*]] = phi i32 [ [[I18218]], [[BB145]] ], [ [[I18220]], [[BB197]] ]
; CHECK-NEXT:    [[I197:%.*]] = phi i32 [ [[I192]], [[BB145]] ], [ [[I197]], [[BB197]] ]
; CHECK-NEXT:    [[I5180:%.*]] = phi i32 [ [[I5178]], [[BB145]] ], [ [[I5180]], [[BB197]] ]
; CHECK-NEXT:    [[I30174:%.*]] = phi i32 [ [[I30172]], [[BB145]] ], [ [[I30174]], [[BB197]] ]
; CHECK-NEXT:    [[I31168:%.*]] = phi i32 [ [[I31166]], [[BB145]] ], [ [[I31168]], [[BB197]] ]
; CHECK-NEXT:    [[I40164:%.*]] = phi i64 [ [[I40162]], [[BB145]] ], [ [[I40164]], [[BB197]] ]
; CHECK-NEXT:    [[I106158:%.*]] = phi i64 [ [[I106156]], [[BB145]] ], [ [[I106158]], [[BB197]] ]
; CHECK-NEXT:    [[I108154:%.*]] = phi ptr [ [[I108152]], [[BB145]] ], [ [[I108154]], [[BB197]] ]
; CHECK-NEXT:    [[I111150:%.*]] = phi ptr [ [[I111148]], [[BB145]] ], [ [[I111150]], [[BB197]] ]
; CHECK-NEXT:    [[I112147:%.*]] = phi ptr [ [[I112145]], [[BB145]] ], [ [[I112147]], [[BB197]] ]
; CHECK-NEXT:    [[I113144:%.*]] = phi i32 [ [[I113142]], [[BB145]] ], [ 0, [[BB197]] ]
; CHECK-NEXT:    [[I70139:%.*]] = phi i64 [ [[I70138]], [[BB145]] ], [ [[I70139]], [[BB197]] ]
; CHECK-NEXT:    [[I10133:%.*]] = phi i32 [ [[I10131]], [[BB145]] ], [ [[I10133]], [[BB197]] ]
; CHECK-NEXT:    [[I160:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I298:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I161:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I297:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I162:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I296:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I163:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I295:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I164:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I294:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I165:%.*]] = phi i32 [ 0, [[BB145]] ], [ [[I299:%.*]], [[BB197]] ]
; CHECK-NEXT:    [[I166:%.*]] = add nsw i32 [[I165]], [[I146330]]
; CHECK-NEXT:    [[I167:%.*]] = sext i32 [[I166]] to i64
; CHECK-NEXT:    [[I168:%.*]] = getelementptr inbounds i32, ptr [[I112147]], i64 [[I167]]
; CHECK-NEXT:    [[I169:%.*]] = load i32, ptr [[I168]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I170:%.*]] = getelementptr inbounds double, ptr [[I108154]], i64 [[I167]]
; CHECK-NEXT:    [[I171:%.*]] = load double, ptr [[I170]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    switch i32 [[I113144]], label [[CACHESTORE2:%.*]] [
; CHECK-NEXT:      i32 1, label [[CACHESTORE1:%.*]]
; CHECK-NEXT:      i32 0, label [[BB197]]
; CHECK-NEXT:    ]
; CHECK:       CacheStore1:
; CHECK-NEXT:    [[TMP396:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP397:%.*]] = load ptr, ptr [[TMP396]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR27:%.*]] = getelementptr inbounds i32, ptr [[TMP397]], i32 1
; CHECK-NEXT:    [[CACHEIDX28:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR27]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP398:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP399:%.*]] = load ptr, ptr [[TMP398]], align 8
; CHECK-NEXT:    [[TMP400:%.*]] = getelementptr inbounds ptr, ptr [[TMP399]], i32 1
; CHECK-NEXT:    [[CACHE_OUT_PTR29:%.*]] = load ptr, ptr [[TMP400]], align 8
; CHECK-NEXT:    [[TMP401:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET30:%.*]] = load i32, ptr [[TMP401]], align 4
; CHECK-NEXT:    [[TMP402:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP402]], align 4, !invariant.group [[META61]]
; CHECK-NEXT:    [[TMP403:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP404:%.*]] = getelementptr inbounds i64, ptr [[TMP403]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP404]], align 8, !invariant.group [[META62]]
; CHECK-NEXT:    [[TMP405:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP406:%.*]] = getelementptr inbounds i64, ptr [[TMP405]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP407:%.*]] = getelementptr inbounds ptr, ptr [[TMP406]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP407]], align 8, !invariant.group [[META63]]
; CHECK-NEXT:    [[TMP408:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP409:%.*]] = getelementptr inbounds i64, ptr [[TMP408]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP410:%.*]] = getelementptr inbounds ptr, ptr [[TMP409]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP411:%.*]] = getelementptr inbounds i32, ptr [[TMP410]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP411]], align 4, !invariant.group [[META64]]
; CHECK-NEXT:    [[TMP412:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP413:%.*]] = getelementptr inbounds i64, ptr [[TMP412]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP414:%.*]] = getelementptr inbounds ptr, ptr [[TMP413]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP415:%.*]] = getelementptr inbounds i32, ptr [[TMP414]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP416:%.*]] = getelementptr inbounds i1, ptr [[TMP415]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP416]], align 1, !invariant.group [[META65]]
; CHECK-NEXT:    [[TMP417:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP418:%.*]] = getelementptr inbounds i64, ptr [[TMP417]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP419:%.*]] = getelementptr inbounds ptr, ptr [[TMP418]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP420:%.*]] = getelementptr inbounds i32, ptr [[TMP419]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP421:%.*]] = getelementptr inbounds i1, ptr [[TMP420]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP422:%.*]] = getelementptr inbounds ptr, ptr [[TMP421]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP422]], align 8, !invariant.group [[META66]]
; CHECK-NEXT:    [[TMP423:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP424:%.*]] = getelementptr inbounds i64, ptr [[TMP423]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP425:%.*]] = getelementptr inbounds ptr, ptr [[TMP424]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP426:%.*]] = getelementptr inbounds i32, ptr [[TMP425]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP427:%.*]] = getelementptr inbounds i1, ptr [[TMP426]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP428:%.*]] = getelementptr inbounds ptr, ptr [[TMP427]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP429:%.*]] = getelementptr inbounds ptr, ptr [[TMP428]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP429]], align 8, !invariant.group [[META67]]
; CHECK-NEXT:    [[TMP430:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP431:%.*]] = getelementptr inbounds i64, ptr [[TMP430]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP432:%.*]] = getelementptr inbounds ptr, ptr [[TMP431]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP433:%.*]] = getelementptr inbounds i32, ptr [[TMP432]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP434:%.*]] = getelementptr inbounds i1, ptr [[TMP433]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP435:%.*]] = getelementptr inbounds ptr, ptr [[TMP434]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP436:%.*]] = getelementptr inbounds ptr, ptr [[TMP435]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP437:%.*]] = getelementptr inbounds double, ptr [[TMP436]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP437]], align 8, !invariant.group [[META68]]
; CHECK-NEXT:    [[TMP438:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP439:%.*]] = getelementptr inbounds i64, ptr [[TMP438]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP440:%.*]] = getelementptr inbounds ptr, ptr [[TMP439]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP441:%.*]] = getelementptr inbounds i32, ptr [[TMP440]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP442:%.*]] = getelementptr inbounds i1, ptr [[TMP441]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP443:%.*]] = getelementptr inbounds ptr, ptr [[TMP442]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP444:%.*]] = getelementptr inbounds ptr, ptr [[TMP443]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP445:%.*]] = getelementptr inbounds double, ptr [[TMP444]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP446:%.*]] = getelementptr inbounds i32, ptr [[TMP445]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP446]], align 4, !invariant.group [[META69]]
; CHECK-NEXT:    [[TMP447:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP448:%.*]] = getelementptr inbounds i64, ptr [[TMP447]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP449:%.*]] = getelementptr inbounds ptr, ptr [[TMP448]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP450:%.*]] = getelementptr inbounds i32, ptr [[TMP449]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP451:%.*]] = getelementptr inbounds i1, ptr [[TMP450]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP452:%.*]] = getelementptr inbounds ptr, ptr [[TMP451]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP453:%.*]] = getelementptr inbounds ptr, ptr [[TMP452]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP454:%.*]] = getelementptr inbounds double, ptr [[TMP453]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP455:%.*]] = getelementptr inbounds i32, ptr [[TMP454]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP456:%.*]] = getelementptr inbounds i32, ptr [[TMP455]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP456]], align 4, !invariant.group [[META70]]
; CHECK-NEXT:    [[TMP457:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP458:%.*]] = getelementptr inbounds i64, ptr [[TMP457]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP459:%.*]] = getelementptr inbounds ptr, ptr [[TMP458]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP460:%.*]] = getelementptr inbounds i32, ptr [[TMP459]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP461:%.*]] = getelementptr inbounds i1, ptr [[TMP460]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP462:%.*]] = getelementptr inbounds ptr, ptr [[TMP461]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP463:%.*]] = getelementptr inbounds ptr, ptr [[TMP462]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP464:%.*]] = getelementptr inbounds double, ptr [[TMP463]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP465:%.*]] = getelementptr inbounds i32, ptr [[TMP464]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP466:%.*]] = getelementptr inbounds i32, ptr [[TMP465]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP467:%.*]] = getelementptr inbounds double, ptr [[TMP466]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP467]], align 8, !invariant.group [[META71]]
; CHECK-NEXT:    [[TMP468:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP469:%.*]] = getelementptr inbounds i64, ptr [[TMP468]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP470:%.*]] = getelementptr inbounds ptr, ptr [[TMP469]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP471:%.*]] = getelementptr inbounds i32, ptr [[TMP470]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP472:%.*]] = getelementptr inbounds i1, ptr [[TMP471]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP473:%.*]] = getelementptr inbounds ptr, ptr [[TMP472]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP474:%.*]] = getelementptr inbounds ptr, ptr [[TMP473]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP475:%.*]] = getelementptr inbounds double, ptr [[TMP474]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP476:%.*]] = getelementptr inbounds i32, ptr [[TMP475]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP477:%.*]] = getelementptr inbounds i32, ptr [[TMP476]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP478:%.*]] = getelementptr inbounds double, ptr [[TMP477]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP479:%.*]] = getelementptr inbounds double, ptr [[TMP478]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP479]], align 8, !invariant.group [[META72]]
; CHECK-NEXT:    [[TMP480:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP481:%.*]] = getelementptr inbounds i64, ptr [[TMP480]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP482:%.*]] = getelementptr inbounds ptr, ptr [[TMP481]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP483:%.*]] = getelementptr inbounds i32, ptr [[TMP482]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP484:%.*]] = getelementptr inbounds i1, ptr [[TMP483]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP485:%.*]] = getelementptr inbounds ptr, ptr [[TMP484]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP486:%.*]] = getelementptr inbounds ptr, ptr [[TMP485]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP487:%.*]] = getelementptr inbounds double, ptr [[TMP486]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP488:%.*]] = getelementptr inbounds i32, ptr [[TMP487]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP489:%.*]] = getelementptr inbounds i32, ptr [[TMP488]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP490:%.*]] = getelementptr inbounds double, ptr [[TMP489]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP491:%.*]] = getelementptr inbounds double, ptr [[TMP490]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP492:%.*]] = getelementptr inbounds double, ptr [[TMP491]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP492]], align 8, !invariant.group [[META73]]
; CHECK-NEXT:    [[TMP493:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP494:%.*]] = getelementptr inbounds i64, ptr [[TMP493]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP495:%.*]] = getelementptr inbounds ptr, ptr [[TMP494]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP496:%.*]] = getelementptr inbounds i32, ptr [[TMP495]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP497:%.*]] = getelementptr inbounds i1, ptr [[TMP496]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP498:%.*]] = getelementptr inbounds ptr, ptr [[TMP497]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP499:%.*]] = getelementptr inbounds ptr, ptr [[TMP498]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP500:%.*]] = getelementptr inbounds double, ptr [[TMP499]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP501:%.*]] = getelementptr inbounds i32, ptr [[TMP500]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP502:%.*]] = getelementptr inbounds i32, ptr [[TMP501]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP503:%.*]] = getelementptr inbounds double, ptr [[TMP502]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP504:%.*]] = getelementptr inbounds double, ptr [[TMP503]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP505:%.*]] = getelementptr inbounds double, ptr [[TMP504]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP506:%.*]] = getelementptr inbounds double, ptr [[TMP505]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP506]], align 8, !invariant.group [[META74]]
; CHECK-NEXT:    [[TMP507:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP508:%.*]] = getelementptr inbounds i64, ptr [[TMP507]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP509:%.*]] = getelementptr inbounds ptr, ptr [[TMP508]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP510:%.*]] = getelementptr inbounds i32, ptr [[TMP509]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP511:%.*]] = getelementptr inbounds i1, ptr [[TMP510]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP512:%.*]] = getelementptr inbounds ptr, ptr [[TMP511]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP513:%.*]] = getelementptr inbounds ptr, ptr [[TMP512]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP514:%.*]] = getelementptr inbounds double, ptr [[TMP513]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP515:%.*]] = getelementptr inbounds i32, ptr [[TMP514]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP516:%.*]] = getelementptr inbounds i32, ptr [[TMP515]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP517:%.*]] = getelementptr inbounds double, ptr [[TMP516]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP518:%.*]] = getelementptr inbounds double, ptr [[TMP517]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP519:%.*]] = getelementptr inbounds double, ptr [[TMP518]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP520:%.*]] = getelementptr inbounds double, ptr [[TMP519]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP521:%.*]] = getelementptr inbounds double, ptr [[TMP520]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP521]], align 8, !invariant.group [[META75]]
; CHECK-NEXT:    [[TMP522:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP523:%.*]] = getelementptr inbounds i64, ptr [[TMP522]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP524:%.*]] = getelementptr inbounds ptr, ptr [[TMP523]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP525:%.*]] = getelementptr inbounds i32, ptr [[TMP524]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP526:%.*]] = getelementptr inbounds i1, ptr [[TMP525]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP527:%.*]] = getelementptr inbounds ptr, ptr [[TMP526]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP528:%.*]] = getelementptr inbounds ptr, ptr [[TMP527]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP529:%.*]] = getelementptr inbounds double, ptr [[TMP528]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP530:%.*]] = getelementptr inbounds i32, ptr [[TMP529]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP531:%.*]] = getelementptr inbounds i32, ptr [[TMP530]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP532:%.*]] = getelementptr inbounds double, ptr [[TMP531]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP533:%.*]] = getelementptr inbounds double, ptr [[TMP532]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP534:%.*]] = getelementptr inbounds double, ptr [[TMP533]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP535:%.*]] = getelementptr inbounds double, ptr [[TMP534]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP536:%.*]] = getelementptr inbounds double, ptr [[TMP535]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP537:%.*]] = getelementptr inbounds i32, ptr [[TMP536]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 1, ptr [[TMP537]], align 4, !invariant.group [[META76]]
; CHECK-NEXT:    [[TMP538:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP539:%.*]] = getelementptr inbounds i64, ptr [[TMP538]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP540:%.*]] = getelementptr inbounds ptr, ptr [[TMP539]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP541:%.*]] = getelementptr inbounds i32, ptr [[TMP540]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP542:%.*]] = getelementptr inbounds i1, ptr [[TMP541]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP543:%.*]] = getelementptr inbounds ptr, ptr [[TMP542]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP544:%.*]] = getelementptr inbounds ptr, ptr [[TMP543]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP545:%.*]] = getelementptr inbounds double, ptr [[TMP544]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP546:%.*]] = getelementptr inbounds i32, ptr [[TMP545]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP547:%.*]] = getelementptr inbounds i32, ptr [[TMP546]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP548:%.*]] = getelementptr inbounds double, ptr [[TMP547]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP549:%.*]] = getelementptr inbounds double, ptr [[TMP548]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP550:%.*]] = getelementptr inbounds double, ptr [[TMP549]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP551:%.*]] = getelementptr inbounds double, ptr [[TMP550]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP552:%.*]] = getelementptr inbounds double, ptr [[TMP551]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP553:%.*]] = getelementptr inbounds i32, ptr [[TMP552]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP554:%.*]] = getelementptr inbounds ptr, ptr [[TMP553]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP554]], align 8, !invariant.group [[META77]]
; CHECK-NEXT:    [[TMP555:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP556:%.*]] = getelementptr inbounds i64, ptr [[TMP555]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP557:%.*]] = getelementptr inbounds ptr, ptr [[TMP556]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP558:%.*]] = getelementptr inbounds i32, ptr [[TMP557]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP559:%.*]] = getelementptr inbounds i1, ptr [[TMP558]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP560:%.*]] = getelementptr inbounds ptr, ptr [[TMP559]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP561:%.*]] = getelementptr inbounds ptr, ptr [[TMP560]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP562:%.*]] = getelementptr inbounds double, ptr [[TMP561]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP563:%.*]] = getelementptr inbounds i32, ptr [[TMP562]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP564:%.*]] = getelementptr inbounds i32, ptr [[TMP563]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP565:%.*]] = getelementptr inbounds double, ptr [[TMP564]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP566:%.*]] = getelementptr inbounds double, ptr [[TMP565]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP567:%.*]] = getelementptr inbounds double, ptr [[TMP566]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP568:%.*]] = getelementptr inbounds double, ptr [[TMP567]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP569:%.*]] = getelementptr inbounds double, ptr [[TMP568]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP570:%.*]] = getelementptr inbounds i32, ptr [[TMP569]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP571:%.*]] = getelementptr inbounds ptr, ptr [[TMP570]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP572:%.*]] = getelementptr inbounds ptr, ptr [[TMP571]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP572]], align 8, !invariant.group [[META78]]
; CHECK-NEXT:    [[TMP573:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP574:%.*]] = getelementptr inbounds i64, ptr [[TMP573]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP575:%.*]] = getelementptr inbounds ptr, ptr [[TMP574]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP576:%.*]] = getelementptr inbounds i32, ptr [[TMP575]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP577:%.*]] = getelementptr inbounds i1, ptr [[TMP576]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP578:%.*]] = getelementptr inbounds ptr, ptr [[TMP577]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP579:%.*]] = getelementptr inbounds ptr, ptr [[TMP578]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP580:%.*]] = getelementptr inbounds double, ptr [[TMP579]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP581:%.*]] = getelementptr inbounds i32, ptr [[TMP580]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP582:%.*]] = getelementptr inbounds i32, ptr [[TMP581]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP583:%.*]] = getelementptr inbounds double, ptr [[TMP582]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP584:%.*]] = getelementptr inbounds double, ptr [[TMP583]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP585:%.*]] = getelementptr inbounds double, ptr [[TMP584]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP586:%.*]] = getelementptr inbounds double, ptr [[TMP585]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP587:%.*]] = getelementptr inbounds double, ptr [[TMP586]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP588:%.*]] = getelementptr inbounds i32, ptr [[TMP587]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP589:%.*]] = getelementptr inbounds ptr, ptr [[TMP588]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP590:%.*]] = getelementptr inbounds ptr, ptr [[TMP589]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP591:%.*]] = getelementptr inbounds ptr, ptr [[TMP590]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP591]], align 8, !invariant.group [[META79]]
; CHECK-NEXT:    [[TMP592:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP593:%.*]] = getelementptr inbounds i64, ptr [[TMP592]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP594:%.*]] = getelementptr inbounds ptr, ptr [[TMP593]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP595:%.*]] = getelementptr inbounds i32, ptr [[TMP594]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP596:%.*]] = getelementptr inbounds i1, ptr [[TMP595]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP597:%.*]] = getelementptr inbounds ptr, ptr [[TMP596]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP598:%.*]] = getelementptr inbounds ptr, ptr [[TMP597]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP599:%.*]] = getelementptr inbounds double, ptr [[TMP598]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP600:%.*]] = getelementptr inbounds i32, ptr [[TMP599]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP601:%.*]] = getelementptr inbounds i32, ptr [[TMP600]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP602:%.*]] = getelementptr inbounds double, ptr [[TMP601]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP603:%.*]] = getelementptr inbounds double, ptr [[TMP602]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP604:%.*]] = getelementptr inbounds double, ptr [[TMP603]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP605:%.*]] = getelementptr inbounds double, ptr [[TMP604]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP606:%.*]] = getelementptr inbounds double, ptr [[TMP605]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP607:%.*]] = getelementptr inbounds i32, ptr [[TMP606]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP608:%.*]] = getelementptr inbounds ptr, ptr [[TMP607]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP609:%.*]] = getelementptr inbounds ptr, ptr [[TMP608]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP610:%.*]] = getelementptr inbounds ptr, ptr [[TMP609]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP611:%.*]] = getelementptr inbounds i64, ptr [[TMP610]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP611]], align 8, !invariant.group [[META80]]
; CHECK-NEXT:    [[TMP612:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP613:%.*]] = getelementptr inbounds i64, ptr [[TMP612]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP614:%.*]] = getelementptr inbounds ptr, ptr [[TMP613]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP615:%.*]] = getelementptr inbounds i32, ptr [[TMP614]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP616:%.*]] = getelementptr inbounds i1, ptr [[TMP615]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP617:%.*]] = getelementptr inbounds ptr, ptr [[TMP616]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP618:%.*]] = getelementptr inbounds ptr, ptr [[TMP617]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP619:%.*]] = getelementptr inbounds double, ptr [[TMP618]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP620:%.*]] = getelementptr inbounds i32, ptr [[TMP619]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP621:%.*]] = getelementptr inbounds i32, ptr [[TMP620]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP622:%.*]] = getelementptr inbounds double, ptr [[TMP621]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP623:%.*]] = getelementptr inbounds double, ptr [[TMP622]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP624:%.*]] = getelementptr inbounds double, ptr [[TMP623]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP625:%.*]] = getelementptr inbounds double, ptr [[TMP624]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP626:%.*]] = getelementptr inbounds double, ptr [[TMP625]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP627:%.*]] = getelementptr inbounds i32, ptr [[TMP626]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP628:%.*]] = getelementptr inbounds ptr, ptr [[TMP627]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP629:%.*]] = getelementptr inbounds ptr, ptr [[TMP628]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP630:%.*]] = getelementptr inbounds ptr, ptr [[TMP629]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP631:%.*]] = getelementptr inbounds i64, ptr [[TMP630]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP632:%.*]] = getelementptr inbounds i64, ptr [[TMP631]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP632]], align 8, !invariant.group [[META81]]
; CHECK-NEXT:    [[TMP633:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP634:%.*]] = getelementptr inbounds i64, ptr [[TMP633]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP635:%.*]] = getelementptr inbounds ptr, ptr [[TMP634]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP636:%.*]] = getelementptr inbounds i32, ptr [[TMP635]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP637:%.*]] = getelementptr inbounds i1, ptr [[TMP636]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP638:%.*]] = getelementptr inbounds ptr, ptr [[TMP637]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP639:%.*]] = getelementptr inbounds ptr, ptr [[TMP638]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP640:%.*]] = getelementptr inbounds double, ptr [[TMP639]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP641:%.*]] = getelementptr inbounds i32, ptr [[TMP640]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP642:%.*]] = getelementptr inbounds i32, ptr [[TMP641]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP643:%.*]] = getelementptr inbounds double, ptr [[TMP642]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP644:%.*]] = getelementptr inbounds double, ptr [[TMP643]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP645:%.*]] = getelementptr inbounds double, ptr [[TMP644]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP646:%.*]] = getelementptr inbounds double, ptr [[TMP645]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP647:%.*]] = getelementptr inbounds double, ptr [[TMP646]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP648:%.*]] = getelementptr inbounds i32, ptr [[TMP647]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP649:%.*]] = getelementptr inbounds ptr, ptr [[TMP648]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP650:%.*]] = getelementptr inbounds ptr, ptr [[TMP649]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP651:%.*]] = getelementptr inbounds ptr, ptr [[TMP650]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP652:%.*]] = getelementptr inbounds i64, ptr [[TMP651]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP653:%.*]] = getelementptr inbounds i64, ptr [[TMP652]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP654:%.*]] = getelementptr inbounds i32, ptr [[TMP653]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP654]], align 4, !invariant.group [[META82]]
; CHECK-NEXT:    [[TMP655:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP656:%.*]] = getelementptr inbounds i64, ptr [[TMP655]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP657:%.*]] = getelementptr inbounds ptr, ptr [[TMP656]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP658:%.*]] = getelementptr inbounds i32, ptr [[TMP657]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP659:%.*]] = getelementptr inbounds i1, ptr [[TMP658]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP660:%.*]] = getelementptr inbounds ptr, ptr [[TMP659]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP661:%.*]] = getelementptr inbounds ptr, ptr [[TMP660]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP662:%.*]] = getelementptr inbounds double, ptr [[TMP661]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP663:%.*]] = getelementptr inbounds i32, ptr [[TMP662]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP664:%.*]] = getelementptr inbounds i32, ptr [[TMP663]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP665:%.*]] = getelementptr inbounds double, ptr [[TMP664]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP666:%.*]] = getelementptr inbounds double, ptr [[TMP665]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP667:%.*]] = getelementptr inbounds double, ptr [[TMP666]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP668:%.*]] = getelementptr inbounds double, ptr [[TMP667]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP669:%.*]] = getelementptr inbounds double, ptr [[TMP668]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP670:%.*]] = getelementptr inbounds i32, ptr [[TMP669]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP671:%.*]] = getelementptr inbounds ptr, ptr [[TMP670]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP672:%.*]] = getelementptr inbounds ptr, ptr [[TMP671]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP673:%.*]] = getelementptr inbounds ptr, ptr [[TMP672]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP674:%.*]] = getelementptr inbounds i64, ptr [[TMP673]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP675:%.*]] = getelementptr inbounds i64, ptr [[TMP674]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP676:%.*]] = getelementptr inbounds i32, ptr [[TMP675]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP677:%.*]] = getelementptr inbounds i32, ptr [[TMP676]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP677]], align 4, !invariant.group [[META83]]
; CHECK-NEXT:    [[TMP678:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP679:%.*]] = getelementptr inbounds i64, ptr [[TMP678]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP680:%.*]] = getelementptr inbounds ptr, ptr [[TMP679]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP681:%.*]] = getelementptr inbounds i32, ptr [[TMP680]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP682:%.*]] = getelementptr inbounds i1, ptr [[TMP681]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP683:%.*]] = getelementptr inbounds ptr, ptr [[TMP682]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP684:%.*]] = getelementptr inbounds ptr, ptr [[TMP683]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP685:%.*]] = getelementptr inbounds double, ptr [[TMP684]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP686:%.*]] = getelementptr inbounds i32, ptr [[TMP685]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP687:%.*]] = getelementptr inbounds i32, ptr [[TMP686]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP688:%.*]] = getelementptr inbounds double, ptr [[TMP687]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP689:%.*]] = getelementptr inbounds double, ptr [[TMP688]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP690:%.*]] = getelementptr inbounds double, ptr [[TMP689]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP691:%.*]] = getelementptr inbounds double, ptr [[TMP690]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP692:%.*]] = getelementptr inbounds double, ptr [[TMP691]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP693:%.*]] = getelementptr inbounds i32, ptr [[TMP692]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP694:%.*]] = getelementptr inbounds ptr, ptr [[TMP693]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP695:%.*]] = getelementptr inbounds ptr, ptr [[TMP694]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP696:%.*]] = getelementptr inbounds ptr, ptr [[TMP695]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP697:%.*]] = getelementptr inbounds i64, ptr [[TMP696]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP698:%.*]] = getelementptr inbounds i64, ptr [[TMP697]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP699:%.*]] = getelementptr inbounds i32, ptr [[TMP698]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP700:%.*]] = getelementptr inbounds i32, ptr [[TMP699]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP701:%.*]] = getelementptr inbounds i32, ptr [[TMP700]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP701]], align 4, !invariant.group [[META84]]
; CHECK-NEXT:    [[TMP702:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP703:%.*]] = getelementptr inbounds i64, ptr [[TMP702]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP704:%.*]] = getelementptr inbounds ptr, ptr [[TMP703]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP705:%.*]] = getelementptr inbounds i32, ptr [[TMP704]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP706:%.*]] = getelementptr inbounds i1, ptr [[TMP705]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP707:%.*]] = getelementptr inbounds ptr, ptr [[TMP706]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP708:%.*]] = getelementptr inbounds ptr, ptr [[TMP707]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP709:%.*]] = getelementptr inbounds double, ptr [[TMP708]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP710:%.*]] = getelementptr inbounds i32, ptr [[TMP709]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP711:%.*]] = getelementptr inbounds i32, ptr [[TMP710]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP712:%.*]] = getelementptr inbounds double, ptr [[TMP711]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP713:%.*]] = getelementptr inbounds double, ptr [[TMP712]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP714:%.*]] = getelementptr inbounds double, ptr [[TMP713]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP715:%.*]] = getelementptr inbounds double, ptr [[TMP714]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP716:%.*]] = getelementptr inbounds double, ptr [[TMP715]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP717:%.*]] = getelementptr inbounds i32, ptr [[TMP716]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP718:%.*]] = getelementptr inbounds ptr, ptr [[TMP717]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP719:%.*]] = getelementptr inbounds ptr, ptr [[TMP718]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP720:%.*]] = getelementptr inbounds ptr, ptr [[TMP719]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP721:%.*]] = getelementptr inbounds i64, ptr [[TMP720]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP722:%.*]] = getelementptr inbounds i64, ptr [[TMP721]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP723:%.*]] = getelementptr inbounds i32, ptr [[TMP722]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP724:%.*]] = getelementptr inbounds i32, ptr [[TMP723]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP725:%.*]] = getelementptr inbounds i32, ptr [[TMP724]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP726:%.*]] = getelementptr inbounds i32, ptr [[TMP725]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP726]], align 4, !invariant.group [[META85]]
; CHECK-NEXT:    [[TMP727:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP728:%.*]] = getelementptr inbounds i64, ptr [[TMP727]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP729:%.*]] = getelementptr inbounds ptr, ptr [[TMP728]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP730:%.*]] = getelementptr inbounds i32, ptr [[TMP729]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP731:%.*]] = getelementptr inbounds i1, ptr [[TMP730]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP732:%.*]] = getelementptr inbounds ptr, ptr [[TMP731]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP733:%.*]] = getelementptr inbounds ptr, ptr [[TMP732]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP734:%.*]] = getelementptr inbounds double, ptr [[TMP733]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP735:%.*]] = getelementptr inbounds i32, ptr [[TMP734]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP736:%.*]] = getelementptr inbounds i32, ptr [[TMP735]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP737:%.*]] = getelementptr inbounds double, ptr [[TMP736]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP738:%.*]] = getelementptr inbounds double, ptr [[TMP737]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP739:%.*]] = getelementptr inbounds double, ptr [[TMP738]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP740:%.*]] = getelementptr inbounds double, ptr [[TMP739]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP741:%.*]] = getelementptr inbounds double, ptr [[TMP740]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP742:%.*]] = getelementptr inbounds i32, ptr [[TMP741]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP743:%.*]] = getelementptr inbounds ptr, ptr [[TMP742]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP744:%.*]] = getelementptr inbounds ptr, ptr [[TMP743]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP745:%.*]] = getelementptr inbounds ptr, ptr [[TMP744]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP746:%.*]] = getelementptr inbounds i64, ptr [[TMP745]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP747:%.*]] = getelementptr inbounds i64, ptr [[TMP746]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP748:%.*]] = getelementptr inbounds i32, ptr [[TMP747]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP749:%.*]] = getelementptr inbounds i32, ptr [[TMP748]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP750:%.*]] = getelementptr inbounds i32, ptr [[TMP749]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP751:%.*]] = getelementptr inbounds i32, ptr [[TMP750]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP752:%.*]] = getelementptr inbounds i32, ptr [[TMP751]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP752]], align 4, !invariant.group [[META86]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb197:
; CHECK-NEXT:    [[I198:%.*]] = sext i32 [[I169]] to i64
; CHECK-NEXT:    [[I199:%.*]] = getelementptr i32, ptr [[I148334]], i64 [[I198]]
; CHECK-NEXT:    [[I200:%.*]] = load i32, ptr [[I199]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I201:%.*]] = sext i32 [[I200]] to i64
; CHECK-NEXT:    [[I202:%.*]] = icmp eq i64 [[I149345]], [[I201]]
; CHECK-NEXT:    [[I203:%.*]] = mul nsw i64 [[I106158]], [[I198]]
; CHECK-NEXT:    [[I204:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT:%.*]], ptr [[I111150]], i64 [[I203]]
; CHECK-NEXT:    [[I205:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I204]], i64 [[I201]]
; CHECK-NEXT:    [[I206:%.*]] = select i1 [[I202]], i64 -48, i64 0
; CHECK-NEXT:    [[I207:%.*]] = getelementptr i8, ptr [[I205]], i64 [[I206]]
; CHECK-NEXT:    [[I257:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 48
; CHECK-NEXT:    [[I258:%.*]] = load double, ptr [[I257]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I259:%.*]] = fsub double [[I258]], [[I75268]]
; CHECK-NEXT:    [[I260:%.*]] = load double, ptr [[I207]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I261:%.*]] = fsub double [[I258]], [[I260]]
; CHECK-NEXT:    [[I262:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 56
; CHECK-NEXT:    [[I263:%.*]] = load double, ptr [[I262]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I264:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 8
; CHECK-NEXT:    [[I265:%.*]] = load double, ptr [[I264]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I266:%.*]] = fsub double [[I263]], [[I265]]
; CHECK-NEXT:    [[I267:%.*]] = fneg double [[I259]]
; CHECK-NEXT:    [[I268:%.*]] = fdiv double [[I267]], [[I261]]
; CHECK-NEXT:    [[I269:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I266]], double [[I263]])
; CHECK-NEXT:    [[I270:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 64
; CHECK-NEXT:    [[I271:%.*]] = load double, ptr [[I270]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I272:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 16
; CHECK-NEXT:    [[I273:%.*]] = load double, ptr [[I272]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I274:%.*]] = fsub double [[I271]], [[I273]]
; CHECK-NEXT:    [[I275:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I274]], double [[I271]])
; CHECK-NEXT:    [[I276:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 72
; CHECK-NEXT:    [[I277:%.*]] = load double, ptr [[I276]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I278:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 24
; CHECK-NEXT:    [[I279:%.*]] = load double, ptr [[I278]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I280:%.*]] = fsub double [[I277]], [[I279]]
; CHECK-NEXT:    [[I281:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I280]], double [[I277]])
; CHECK-NEXT:    [[I282:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 80
; CHECK-NEXT:    [[I283:%.*]] = load double, ptr [[I282]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I284:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 32
; CHECK-NEXT:    [[I285:%.*]] = load double, ptr [[I284]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I286:%.*]] = fsub double [[I283]], [[I285]]
; CHECK-NEXT:    [[I287:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I286]], double [[I283]])
; CHECK-NEXT:    [[I288:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 88
; CHECK-NEXT:    [[I289:%.*]] = load double, ptr [[I288]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I290:%.*]] = getelementptr inbounds i8, ptr [[I207]], i64 40
; CHECK-NEXT:    [[I291:%.*]] = load double, ptr [[I290]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I292:%.*]] = fsub double [[I289]], [[I291]]
; CHECK-NEXT:    [[I293:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I292]], double [[I289]])
; CHECK-NEXT:    [[I294]] = tail call double @llvm.fmuladd.f64(double [[I269]], double [[I171]], double [[I164]])
; CHECK-NEXT:    [[I295]] = tail call double @llvm.fmuladd.f64(double [[I275]], double [[I171]], double [[I163]])
; CHECK-NEXT:    [[I296]] = tail call double @llvm.fmuladd.f64(double [[I281]], double [[I171]], double [[I162]])
; CHECK-NEXT:    [[I297]] = tail call double @llvm.fmuladd.f64(double [[I287]], double [[I171]], double [[I161]])
; CHECK-NEXT:    [[I298]] = tail call double @llvm.fmuladd.f64(double [[I293]], double [[I171]], double [[I160]])
; CHECK-NEXT:    [[I299]] = add nuw nsw i32 [[I165]], 1
; CHECK-NEXT:    [[I300:%.*]] = load i32, ptr [[I142328]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I301:%.*]] = icmp slt i32 [[I299]], [[I300]]
; CHECK-NEXT:    br i1 [[I301]], label [[BB159]], label [[BB302]]
; CHECK:       CacheStore2:
; CHECK-NEXT:    [[TMP753:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP754:%.*]] = load ptr, ptr [[TMP753]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR70:%.*]] = getelementptr inbounds i32, ptr [[TMP754]], i32 2
; CHECK-NEXT:    [[CACHEIDX71:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR70]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP755:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP756:%.*]] = load ptr, ptr [[TMP755]], align 8
; CHECK-NEXT:    [[TMP757:%.*]] = getelementptr inbounds ptr, ptr [[TMP756]], i32 2
; CHECK-NEXT:    [[CACHE_OUT_PTR72:%.*]] = load ptr, ptr [[TMP757]], align 8
; CHECK-NEXT:    [[TMP758:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET73:%.*]] = load i32, ptr [[TMP758]], align 4
; CHECK-NEXT:    [[TMP759:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP759]], align 4, !invariant.group [[META94]]
; CHECK-NEXT:    [[TMP760:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP761:%.*]] = getelementptr inbounds i64, ptr [[TMP760]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP761]], align 8, !invariant.group [[META95]]
; CHECK-NEXT:    [[TMP762:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP763:%.*]] = getelementptr inbounds i64, ptr [[TMP762]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP764:%.*]] = getelementptr inbounds ptr, ptr [[TMP763]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP764]], align 8, !invariant.group [[META96]]
; CHECK-NEXT:    [[TMP765:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP766:%.*]] = getelementptr inbounds i64, ptr [[TMP765]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP767:%.*]] = getelementptr inbounds ptr, ptr [[TMP766]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP768:%.*]] = getelementptr inbounds i32, ptr [[TMP767]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP768]], align 4, !invariant.group [[META97]]
; CHECK-NEXT:    [[TMP769:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP770:%.*]] = getelementptr inbounds i64, ptr [[TMP769]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP771:%.*]] = getelementptr inbounds ptr, ptr [[TMP770]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP772:%.*]] = getelementptr inbounds i32, ptr [[TMP771]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP773:%.*]] = getelementptr inbounds i1, ptr [[TMP772]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP773]], align 1, !invariant.group [[META98]]
; CHECK-NEXT:    [[TMP774:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP775:%.*]] = getelementptr inbounds i64, ptr [[TMP774]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP776:%.*]] = getelementptr inbounds ptr, ptr [[TMP775]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP777:%.*]] = getelementptr inbounds i32, ptr [[TMP776]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP778:%.*]] = getelementptr inbounds i1, ptr [[TMP777]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP779:%.*]] = getelementptr inbounds ptr, ptr [[TMP778]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP779]], align 8, !invariant.group [[META99]]
; CHECK-NEXT:    [[TMP780:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP781:%.*]] = getelementptr inbounds i64, ptr [[TMP780]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP782:%.*]] = getelementptr inbounds ptr, ptr [[TMP781]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP783:%.*]] = getelementptr inbounds i32, ptr [[TMP782]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP784:%.*]] = getelementptr inbounds i1, ptr [[TMP783]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP785:%.*]] = getelementptr inbounds ptr, ptr [[TMP784]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP786:%.*]] = getelementptr inbounds ptr, ptr [[TMP785]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP786]], align 8, !invariant.group [[META100]]
; CHECK-NEXT:    [[TMP787:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP788:%.*]] = getelementptr inbounds i64, ptr [[TMP787]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP789:%.*]] = getelementptr inbounds ptr, ptr [[TMP788]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP790:%.*]] = getelementptr inbounds i32, ptr [[TMP789]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP791:%.*]] = getelementptr inbounds i1, ptr [[TMP790]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP792:%.*]] = getelementptr inbounds ptr, ptr [[TMP791]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP793:%.*]] = getelementptr inbounds ptr, ptr [[TMP792]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP794:%.*]] = getelementptr inbounds double, ptr [[TMP793]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP794]], align 8, !invariant.group [[META101]]
; CHECK-NEXT:    [[TMP795:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP796:%.*]] = getelementptr inbounds i64, ptr [[TMP795]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP797:%.*]] = getelementptr inbounds ptr, ptr [[TMP796]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP798:%.*]] = getelementptr inbounds i32, ptr [[TMP797]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP799:%.*]] = getelementptr inbounds i1, ptr [[TMP798]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP800:%.*]] = getelementptr inbounds ptr, ptr [[TMP799]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP801:%.*]] = getelementptr inbounds ptr, ptr [[TMP800]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP802:%.*]] = getelementptr inbounds double, ptr [[TMP801]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP803:%.*]] = getelementptr inbounds i32, ptr [[TMP802]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP803]], align 4, !invariant.group [[META102]]
; CHECK-NEXT:    [[TMP804:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP805:%.*]] = getelementptr inbounds i64, ptr [[TMP804]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP806:%.*]] = getelementptr inbounds ptr, ptr [[TMP805]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP807:%.*]] = getelementptr inbounds i32, ptr [[TMP806]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP808:%.*]] = getelementptr inbounds i1, ptr [[TMP807]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP809:%.*]] = getelementptr inbounds ptr, ptr [[TMP808]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP810:%.*]] = getelementptr inbounds ptr, ptr [[TMP809]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP811:%.*]] = getelementptr inbounds double, ptr [[TMP810]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP812:%.*]] = getelementptr inbounds i32, ptr [[TMP811]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP813:%.*]] = getelementptr inbounds i32, ptr [[TMP812]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP813]], align 4, !invariant.group [[META103]]
; CHECK-NEXT:    [[TMP814:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP815:%.*]] = getelementptr inbounds i64, ptr [[TMP814]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP816:%.*]] = getelementptr inbounds ptr, ptr [[TMP815]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP817:%.*]] = getelementptr inbounds i32, ptr [[TMP816]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP818:%.*]] = getelementptr inbounds i1, ptr [[TMP817]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP819:%.*]] = getelementptr inbounds ptr, ptr [[TMP818]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP820:%.*]] = getelementptr inbounds ptr, ptr [[TMP819]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP821:%.*]] = getelementptr inbounds double, ptr [[TMP820]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP822:%.*]] = getelementptr inbounds i32, ptr [[TMP821]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP823:%.*]] = getelementptr inbounds i32, ptr [[TMP822]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP824:%.*]] = getelementptr inbounds double, ptr [[TMP823]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP824]], align 8, !invariant.group [[META104]]
; CHECK-NEXT:    [[TMP825:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP826:%.*]] = getelementptr inbounds i64, ptr [[TMP825]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP827:%.*]] = getelementptr inbounds ptr, ptr [[TMP826]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP828:%.*]] = getelementptr inbounds i32, ptr [[TMP827]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP829:%.*]] = getelementptr inbounds i1, ptr [[TMP828]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP830:%.*]] = getelementptr inbounds ptr, ptr [[TMP829]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP831:%.*]] = getelementptr inbounds ptr, ptr [[TMP830]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP832:%.*]] = getelementptr inbounds double, ptr [[TMP831]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP833:%.*]] = getelementptr inbounds i32, ptr [[TMP832]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP834:%.*]] = getelementptr inbounds i32, ptr [[TMP833]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP835:%.*]] = getelementptr inbounds double, ptr [[TMP834]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP836:%.*]] = getelementptr inbounds double, ptr [[TMP835]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP836]], align 8, !invariant.group [[META105]]
; CHECK-NEXT:    [[TMP837:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP838:%.*]] = getelementptr inbounds i64, ptr [[TMP837]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP839:%.*]] = getelementptr inbounds ptr, ptr [[TMP838]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP840:%.*]] = getelementptr inbounds i32, ptr [[TMP839]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP841:%.*]] = getelementptr inbounds i1, ptr [[TMP840]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP842:%.*]] = getelementptr inbounds ptr, ptr [[TMP841]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP843:%.*]] = getelementptr inbounds ptr, ptr [[TMP842]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP844:%.*]] = getelementptr inbounds double, ptr [[TMP843]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP845:%.*]] = getelementptr inbounds i32, ptr [[TMP844]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP846:%.*]] = getelementptr inbounds i32, ptr [[TMP845]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP847:%.*]] = getelementptr inbounds double, ptr [[TMP846]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP848:%.*]] = getelementptr inbounds double, ptr [[TMP847]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP849:%.*]] = getelementptr inbounds double, ptr [[TMP848]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP849]], align 8, !invariant.group [[META106]]
; CHECK-NEXT:    [[TMP850:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP851:%.*]] = getelementptr inbounds i64, ptr [[TMP850]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP852:%.*]] = getelementptr inbounds ptr, ptr [[TMP851]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP853:%.*]] = getelementptr inbounds i32, ptr [[TMP852]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP854:%.*]] = getelementptr inbounds i1, ptr [[TMP853]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP855:%.*]] = getelementptr inbounds ptr, ptr [[TMP854]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP856:%.*]] = getelementptr inbounds ptr, ptr [[TMP855]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP857:%.*]] = getelementptr inbounds double, ptr [[TMP856]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP858:%.*]] = getelementptr inbounds i32, ptr [[TMP857]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP859:%.*]] = getelementptr inbounds i32, ptr [[TMP858]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP860:%.*]] = getelementptr inbounds double, ptr [[TMP859]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP861:%.*]] = getelementptr inbounds double, ptr [[TMP860]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP862:%.*]] = getelementptr inbounds double, ptr [[TMP861]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP863:%.*]] = getelementptr inbounds double, ptr [[TMP862]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP863]], align 8, !invariant.group [[META107]]
; CHECK-NEXT:    [[TMP864:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP865:%.*]] = getelementptr inbounds i64, ptr [[TMP864]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP866:%.*]] = getelementptr inbounds ptr, ptr [[TMP865]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP867:%.*]] = getelementptr inbounds i32, ptr [[TMP866]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP868:%.*]] = getelementptr inbounds i1, ptr [[TMP867]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP869:%.*]] = getelementptr inbounds ptr, ptr [[TMP868]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP870:%.*]] = getelementptr inbounds ptr, ptr [[TMP869]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP871:%.*]] = getelementptr inbounds double, ptr [[TMP870]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP872:%.*]] = getelementptr inbounds i32, ptr [[TMP871]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP873:%.*]] = getelementptr inbounds i32, ptr [[TMP872]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP874:%.*]] = getelementptr inbounds double, ptr [[TMP873]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP875:%.*]] = getelementptr inbounds double, ptr [[TMP874]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP876:%.*]] = getelementptr inbounds double, ptr [[TMP875]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP877:%.*]] = getelementptr inbounds double, ptr [[TMP876]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP878:%.*]] = getelementptr inbounds double, ptr [[TMP877]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP878]], align 8, !invariant.group [[META108]]
; CHECK-NEXT:    [[TMP879:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP880:%.*]] = getelementptr inbounds i64, ptr [[TMP879]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP881:%.*]] = getelementptr inbounds ptr, ptr [[TMP880]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP882:%.*]] = getelementptr inbounds i32, ptr [[TMP881]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP883:%.*]] = getelementptr inbounds i1, ptr [[TMP882]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP884:%.*]] = getelementptr inbounds ptr, ptr [[TMP883]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP885:%.*]] = getelementptr inbounds ptr, ptr [[TMP884]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP886:%.*]] = getelementptr inbounds double, ptr [[TMP885]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP887:%.*]] = getelementptr inbounds i32, ptr [[TMP886]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP888:%.*]] = getelementptr inbounds i32, ptr [[TMP887]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP889:%.*]] = getelementptr inbounds double, ptr [[TMP888]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP890:%.*]] = getelementptr inbounds double, ptr [[TMP889]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP891:%.*]] = getelementptr inbounds double, ptr [[TMP890]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP892:%.*]] = getelementptr inbounds double, ptr [[TMP891]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP893:%.*]] = getelementptr inbounds double, ptr [[TMP892]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP894:%.*]] = getelementptr inbounds i32, ptr [[TMP893]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I113144]], ptr [[TMP894]], align 4, !invariant.group [[META109]]
; CHECK-NEXT:    [[TMP895:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP896:%.*]] = getelementptr inbounds i64, ptr [[TMP895]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP897:%.*]] = getelementptr inbounds ptr, ptr [[TMP896]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP898:%.*]] = getelementptr inbounds i32, ptr [[TMP897]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP899:%.*]] = getelementptr inbounds i1, ptr [[TMP898]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP900:%.*]] = getelementptr inbounds ptr, ptr [[TMP899]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP901:%.*]] = getelementptr inbounds ptr, ptr [[TMP900]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP902:%.*]] = getelementptr inbounds double, ptr [[TMP901]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP903:%.*]] = getelementptr inbounds i32, ptr [[TMP902]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP904:%.*]] = getelementptr inbounds i32, ptr [[TMP903]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP905:%.*]] = getelementptr inbounds double, ptr [[TMP904]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP906:%.*]] = getelementptr inbounds double, ptr [[TMP905]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP907:%.*]] = getelementptr inbounds double, ptr [[TMP906]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP908:%.*]] = getelementptr inbounds double, ptr [[TMP907]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP909:%.*]] = getelementptr inbounds double, ptr [[TMP908]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP910:%.*]] = getelementptr inbounds i32, ptr [[TMP909]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP911:%.*]] = getelementptr inbounds ptr, ptr [[TMP910]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP911]], align 8, !invariant.group [[META110]]
; CHECK-NEXT:    [[TMP912:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP913:%.*]] = getelementptr inbounds i64, ptr [[TMP912]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP914:%.*]] = getelementptr inbounds ptr, ptr [[TMP913]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP915:%.*]] = getelementptr inbounds i32, ptr [[TMP914]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP916:%.*]] = getelementptr inbounds i1, ptr [[TMP915]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP917:%.*]] = getelementptr inbounds ptr, ptr [[TMP916]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP918:%.*]] = getelementptr inbounds ptr, ptr [[TMP917]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP919:%.*]] = getelementptr inbounds double, ptr [[TMP918]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP920:%.*]] = getelementptr inbounds i32, ptr [[TMP919]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP921:%.*]] = getelementptr inbounds i32, ptr [[TMP920]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP922:%.*]] = getelementptr inbounds double, ptr [[TMP921]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP923:%.*]] = getelementptr inbounds double, ptr [[TMP922]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP924:%.*]] = getelementptr inbounds double, ptr [[TMP923]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP925:%.*]] = getelementptr inbounds double, ptr [[TMP924]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP926:%.*]] = getelementptr inbounds double, ptr [[TMP925]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP927:%.*]] = getelementptr inbounds i32, ptr [[TMP926]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP928:%.*]] = getelementptr inbounds ptr, ptr [[TMP927]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP929:%.*]] = getelementptr inbounds ptr, ptr [[TMP928]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP929]], align 8, !invariant.group [[META111]]
; CHECK-NEXT:    [[TMP930:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP931:%.*]] = getelementptr inbounds i64, ptr [[TMP930]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP932:%.*]] = getelementptr inbounds ptr, ptr [[TMP931]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP933:%.*]] = getelementptr inbounds i32, ptr [[TMP932]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP934:%.*]] = getelementptr inbounds i1, ptr [[TMP933]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP935:%.*]] = getelementptr inbounds ptr, ptr [[TMP934]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP936:%.*]] = getelementptr inbounds ptr, ptr [[TMP935]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP937:%.*]] = getelementptr inbounds double, ptr [[TMP936]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP938:%.*]] = getelementptr inbounds i32, ptr [[TMP937]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP939:%.*]] = getelementptr inbounds i32, ptr [[TMP938]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP940:%.*]] = getelementptr inbounds double, ptr [[TMP939]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP941:%.*]] = getelementptr inbounds double, ptr [[TMP940]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP942:%.*]] = getelementptr inbounds double, ptr [[TMP941]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP943:%.*]] = getelementptr inbounds double, ptr [[TMP942]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP944:%.*]] = getelementptr inbounds double, ptr [[TMP943]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP945:%.*]] = getelementptr inbounds i32, ptr [[TMP944]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP946:%.*]] = getelementptr inbounds ptr, ptr [[TMP945]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP947:%.*]] = getelementptr inbounds ptr, ptr [[TMP946]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP948:%.*]] = getelementptr inbounds ptr, ptr [[TMP947]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP948]], align 8, !invariant.group [[META112]]
; CHECK-NEXT:    [[TMP949:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP950:%.*]] = getelementptr inbounds i64, ptr [[TMP949]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP951:%.*]] = getelementptr inbounds ptr, ptr [[TMP950]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP952:%.*]] = getelementptr inbounds i32, ptr [[TMP951]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP953:%.*]] = getelementptr inbounds i1, ptr [[TMP952]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP954:%.*]] = getelementptr inbounds ptr, ptr [[TMP953]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP955:%.*]] = getelementptr inbounds ptr, ptr [[TMP954]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP956:%.*]] = getelementptr inbounds double, ptr [[TMP955]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP957:%.*]] = getelementptr inbounds i32, ptr [[TMP956]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP958:%.*]] = getelementptr inbounds i32, ptr [[TMP957]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP959:%.*]] = getelementptr inbounds double, ptr [[TMP958]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP960:%.*]] = getelementptr inbounds double, ptr [[TMP959]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP961:%.*]] = getelementptr inbounds double, ptr [[TMP960]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP962:%.*]] = getelementptr inbounds double, ptr [[TMP961]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP963:%.*]] = getelementptr inbounds double, ptr [[TMP962]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP964:%.*]] = getelementptr inbounds i32, ptr [[TMP963]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP965:%.*]] = getelementptr inbounds ptr, ptr [[TMP964]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP966:%.*]] = getelementptr inbounds ptr, ptr [[TMP965]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP967:%.*]] = getelementptr inbounds ptr, ptr [[TMP966]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP968:%.*]] = getelementptr inbounds i64, ptr [[TMP967]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP968]], align 8, !invariant.group [[META113]]
; CHECK-NEXT:    [[TMP969:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP970:%.*]] = getelementptr inbounds i64, ptr [[TMP969]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP971:%.*]] = getelementptr inbounds ptr, ptr [[TMP970]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP972:%.*]] = getelementptr inbounds i32, ptr [[TMP971]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP973:%.*]] = getelementptr inbounds i1, ptr [[TMP972]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP974:%.*]] = getelementptr inbounds ptr, ptr [[TMP973]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP975:%.*]] = getelementptr inbounds ptr, ptr [[TMP974]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP976:%.*]] = getelementptr inbounds double, ptr [[TMP975]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP977:%.*]] = getelementptr inbounds i32, ptr [[TMP976]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP978:%.*]] = getelementptr inbounds i32, ptr [[TMP977]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP979:%.*]] = getelementptr inbounds double, ptr [[TMP978]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP980:%.*]] = getelementptr inbounds double, ptr [[TMP979]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP981:%.*]] = getelementptr inbounds double, ptr [[TMP980]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP982:%.*]] = getelementptr inbounds double, ptr [[TMP981]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP983:%.*]] = getelementptr inbounds double, ptr [[TMP982]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP984:%.*]] = getelementptr inbounds i32, ptr [[TMP983]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP985:%.*]] = getelementptr inbounds ptr, ptr [[TMP984]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP986:%.*]] = getelementptr inbounds ptr, ptr [[TMP985]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP987:%.*]] = getelementptr inbounds ptr, ptr [[TMP986]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP988:%.*]] = getelementptr inbounds i64, ptr [[TMP987]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP989:%.*]] = getelementptr inbounds i64, ptr [[TMP988]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP989]], align 8, !invariant.group [[META114]]
; CHECK-NEXT:    [[TMP990:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP991:%.*]] = getelementptr inbounds i64, ptr [[TMP990]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP992:%.*]] = getelementptr inbounds ptr, ptr [[TMP991]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP993:%.*]] = getelementptr inbounds i32, ptr [[TMP992]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP994:%.*]] = getelementptr inbounds i1, ptr [[TMP993]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP995:%.*]] = getelementptr inbounds ptr, ptr [[TMP994]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP996:%.*]] = getelementptr inbounds ptr, ptr [[TMP995]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP997:%.*]] = getelementptr inbounds double, ptr [[TMP996]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP998:%.*]] = getelementptr inbounds i32, ptr [[TMP997]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP999:%.*]] = getelementptr inbounds i32, ptr [[TMP998]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1000:%.*]] = getelementptr inbounds double, ptr [[TMP999]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1001:%.*]] = getelementptr inbounds double, ptr [[TMP1000]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1002:%.*]] = getelementptr inbounds double, ptr [[TMP1001]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1003:%.*]] = getelementptr inbounds double, ptr [[TMP1002]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1004:%.*]] = getelementptr inbounds double, ptr [[TMP1003]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1005:%.*]] = getelementptr inbounds i32, ptr [[TMP1004]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1006:%.*]] = getelementptr inbounds ptr, ptr [[TMP1005]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1007:%.*]] = getelementptr inbounds ptr, ptr [[TMP1006]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1008:%.*]] = getelementptr inbounds ptr, ptr [[TMP1007]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1009:%.*]] = getelementptr inbounds i64, ptr [[TMP1008]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1010:%.*]] = getelementptr inbounds i64, ptr [[TMP1009]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1011:%.*]] = getelementptr inbounds i32, ptr [[TMP1010]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP1011]], align 4, !invariant.group [[META115]]
; CHECK-NEXT:    [[TMP1012:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1013:%.*]] = getelementptr inbounds i64, ptr [[TMP1012]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1014:%.*]] = getelementptr inbounds ptr, ptr [[TMP1013]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1015:%.*]] = getelementptr inbounds i32, ptr [[TMP1014]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1016:%.*]] = getelementptr inbounds i1, ptr [[TMP1015]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1017:%.*]] = getelementptr inbounds ptr, ptr [[TMP1016]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1018:%.*]] = getelementptr inbounds ptr, ptr [[TMP1017]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1019:%.*]] = getelementptr inbounds double, ptr [[TMP1018]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1020:%.*]] = getelementptr inbounds i32, ptr [[TMP1019]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1021:%.*]] = getelementptr inbounds i32, ptr [[TMP1020]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1022:%.*]] = getelementptr inbounds double, ptr [[TMP1021]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1023:%.*]] = getelementptr inbounds double, ptr [[TMP1022]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1024:%.*]] = getelementptr inbounds double, ptr [[TMP1023]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1025:%.*]] = getelementptr inbounds double, ptr [[TMP1024]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1026:%.*]] = getelementptr inbounds double, ptr [[TMP1025]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1027:%.*]] = getelementptr inbounds i32, ptr [[TMP1026]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1028:%.*]] = getelementptr inbounds ptr, ptr [[TMP1027]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1029:%.*]] = getelementptr inbounds ptr, ptr [[TMP1028]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1030:%.*]] = getelementptr inbounds ptr, ptr [[TMP1029]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1031:%.*]] = getelementptr inbounds i64, ptr [[TMP1030]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1032:%.*]] = getelementptr inbounds i64, ptr [[TMP1031]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1033:%.*]] = getelementptr inbounds i32, ptr [[TMP1032]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1034:%.*]] = getelementptr inbounds i32, ptr [[TMP1033]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP1034]], align 4, !invariant.group [[META116]]
; CHECK-NEXT:    [[TMP1035:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1036:%.*]] = getelementptr inbounds i64, ptr [[TMP1035]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1037:%.*]] = getelementptr inbounds ptr, ptr [[TMP1036]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1038:%.*]] = getelementptr inbounds i32, ptr [[TMP1037]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1039:%.*]] = getelementptr inbounds i1, ptr [[TMP1038]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1040:%.*]] = getelementptr inbounds ptr, ptr [[TMP1039]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1041:%.*]] = getelementptr inbounds ptr, ptr [[TMP1040]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1042:%.*]] = getelementptr inbounds double, ptr [[TMP1041]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1043:%.*]] = getelementptr inbounds i32, ptr [[TMP1042]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1044:%.*]] = getelementptr inbounds i32, ptr [[TMP1043]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1045:%.*]] = getelementptr inbounds double, ptr [[TMP1044]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1046:%.*]] = getelementptr inbounds double, ptr [[TMP1045]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1047:%.*]] = getelementptr inbounds double, ptr [[TMP1046]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1048:%.*]] = getelementptr inbounds double, ptr [[TMP1047]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1049:%.*]] = getelementptr inbounds double, ptr [[TMP1048]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1050:%.*]] = getelementptr inbounds i32, ptr [[TMP1049]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1051:%.*]] = getelementptr inbounds ptr, ptr [[TMP1050]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1052:%.*]] = getelementptr inbounds ptr, ptr [[TMP1051]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1053:%.*]] = getelementptr inbounds ptr, ptr [[TMP1052]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1054:%.*]] = getelementptr inbounds i64, ptr [[TMP1053]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1055:%.*]] = getelementptr inbounds i64, ptr [[TMP1054]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1056:%.*]] = getelementptr inbounds i32, ptr [[TMP1055]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1057:%.*]] = getelementptr inbounds i32, ptr [[TMP1056]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1058:%.*]] = getelementptr inbounds i32, ptr [[TMP1057]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP1058]], align 4, !invariant.group [[META117]]
; CHECK-NEXT:    [[TMP1059:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1060:%.*]] = getelementptr inbounds i64, ptr [[TMP1059]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1061:%.*]] = getelementptr inbounds ptr, ptr [[TMP1060]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1062:%.*]] = getelementptr inbounds i32, ptr [[TMP1061]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1063:%.*]] = getelementptr inbounds i1, ptr [[TMP1062]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1064:%.*]] = getelementptr inbounds ptr, ptr [[TMP1063]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1065:%.*]] = getelementptr inbounds ptr, ptr [[TMP1064]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1066:%.*]] = getelementptr inbounds double, ptr [[TMP1065]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1067:%.*]] = getelementptr inbounds i32, ptr [[TMP1066]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1068:%.*]] = getelementptr inbounds i32, ptr [[TMP1067]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1069:%.*]] = getelementptr inbounds double, ptr [[TMP1068]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1070:%.*]] = getelementptr inbounds double, ptr [[TMP1069]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1071:%.*]] = getelementptr inbounds double, ptr [[TMP1070]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1072:%.*]] = getelementptr inbounds double, ptr [[TMP1071]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1073:%.*]] = getelementptr inbounds double, ptr [[TMP1072]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1074:%.*]] = getelementptr inbounds i32, ptr [[TMP1073]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1075:%.*]] = getelementptr inbounds ptr, ptr [[TMP1074]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1076:%.*]] = getelementptr inbounds ptr, ptr [[TMP1075]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1077:%.*]] = getelementptr inbounds ptr, ptr [[TMP1076]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1078:%.*]] = getelementptr inbounds i64, ptr [[TMP1077]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1079:%.*]] = getelementptr inbounds i64, ptr [[TMP1078]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1080:%.*]] = getelementptr inbounds i32, ptr [[TMP1079]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1081:%.*]] = getelementptr inbounds i32, ptr [[TMP1080]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1082:%.*]] = getelementptr inbounds i32, ptr [[TMP1081]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1083:%.*]] = getelementptr inbounds i32, ptr [[TMP1082]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP1083]], align 4, !invariant.group [[META118]]
; CHECK-NEXT:    [[TMP1084:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1085:%.*]] = getelementptr inbounds i64, ptr [[TMP1084]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1086:%.*]] = getelementptr inbounds ptr, ptr [[TMP1085]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1087:%.*]] = getelementptr inbounds i32, ptr [[TMP1086]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1088:%.*]] = getelementptr inbounds i1, ptr [[TMP1087]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1089:%.*]] = getelementptr inbounds ptr, ptr [[TMP1088]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1090:%.*]] = getelementptr inbounds ptr, ptr [[TMP1089]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1091:%.*]] = getelementptr inbounds double, ptr [[TMP1090]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1092:%.*]] = getelementptr inbounds i32, ptr [[TMP1091]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1093:%.*]] = getelementptr inbounds i32, ptr [[TMP1092]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1094:%.*]] = getelementptr inbounds double, ptr [[TMP1093]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1095:%.*]] = getelementptr inbounds double, ptr [[TMP1094]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1096:%.*]] = getelementptr inbounds double, ptr [[TMP1095]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1097:%.*]] = getelementptr inbounds double, ptr [[TMP1096]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1098:%.*]] = getelementptr inbounds double, ptr [[TMP1097]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1099:%.*]] = getelementptr inbounds i32, ptr [[TMP1098]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1100:%.*]] = getelementptr inbounds ptr, ptr [[TMP1099]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1101:%.*]] = getelementptr inbounds ptr, ptr [[TMP1100]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1102:%.*]] = getelementptr inbounds ptr, ptr [[TMP1101]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1103:%.*]] = getelementptr inbounds i64, ptr [[TMP1102]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1104:%.*]] = getelementptr inbounds i64, ptr [[TMP1103]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1105:%.*]] = getelementptr inbounds i32, ptr [[TMP1104]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1106:%.*]] = getelementptr inbounds i32, ptr [[TMP1105]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1107:%.*]] = getelementptr inbounds i32, ptr [[TMP1106]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1108:%.*]] = getelementptr inbounds i32, ptr [[TMP1107]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1109:%.*]] = getelementptr inbounds i32, ptr [[TMP1108]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP1109]], align 4, !invariant.group [[META119]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb302:
; CHECK-NEXT:    [[I28323]] = phi ptr [ [[I28322]], [[BB139]] ], [ [[I28324]], [[BB197]] ]
; CHECK-NEXT:    [[I25316]] = phi ptr [ [[I25315]], [[BB139]] ], [ [[I25317]], [[BB197]] ]
; CHECK-NEXT:    [[I24309]] = phi ptr [ [[I24308]], [[BB139]] ], [ [[I24310]], [[BB197]] ]
; CHECK-NEXT:    [[I23302]] = phi ptr [ [[I23301]], [[BB139]] ], [ [[I23303]], [[BB197]] ]
; CHECK-NEXT:    [[I22295]] = phi ptr [ [[I22294]], [[BB139]] ], [ [[I22296]], [[BB197]] ]
; CHECK-NEXT:    [[I21288]] = phi ptr [ [[I21287]], [[BB139]] ], [ [[I21289]], [[BB197]] ]
; CHECK-NEXT:    [[I6280]] = phi i32 [ [[I6279]], [[BB139]] ], [ [[I6281]], [[BB197]] ]
; CHECK-NEXT:    [[I32275]] = phi i64 [ [[I32274]], [[BB139]] ], [ [[I32276]], [[BB197]] ]
; CHECK-NEXT:    [[I41271:%.*]] = phi i32 [ [[I41270]], [[BB139]] ], [ [[I41272]], [[BB197]] ]
; CHECK-NEXT:    [[I27262]] = phi ptr [ [[I27261]], [[BB139]] ], [ [[I27263]], [[BB197]] ]
; CHECK-NEXT:    [[I26255]] = phi ptr [ [[I26254]], [[BB139]] ], [ [[I26256]], [[BB197]] ]
; CHECK-NEXT:    [[I20248]] = phi ptr [ [[I20247]], [[BB139]] ], [ [[I20249]], [[BB197]] ]
; CHECK-NEXT:    [[I19241]] = phi ptr [ [[I19240]], [[BB139]] ], [ [[I19242]], [[BB197]] ]
; CHECK-NEXT:    [[I4233]] = phi ptr [ [[I4232]], [[BB139]] ], [ [[I4234]], [[BB197]] ]
; CHECK-NEXT:    [[I13227]] = phi i32 [ [[I13225]], [[BB139]] ], [ [[I13228]], [[BB197]] ]
; CHECK-NEXT:    [[I18219]] = phi i32 [ [[I18218]], [[BB139]] ], [ [[I18220]], [[BB197]] ]
; CHECK-NEXT:    [[I195]] = phi i32 [ [[I192]], [[BB139]] ], [ [[I197]], [[BB197]] ]
; CHECK-NEXT:    [[I5179]] = phi i32 [ [[I5178]], [[BB139]] ], [ [[I5180]], [[BB197]] ]
; CHECK-NEXT:    [[I30173]] = phi i32 [ [[I30172]], [[BB139]] ], [ [[I30174]], [[BB197]] ]
; CHECK-NEXT:    [[I31167]] = phi i32 [ [[I31166]], [[BB139]] ], [ [[I31168]], [[BB197]] ]
; CHECK-NEXT:    [[I40163:%.*]] = phi i64 [ [[I40162]], [[BB139]] ], [ [[I40164]], [[BB197]] ]
; CHECK-NEXT:    [[I10132]] = phi i32 [ [[I10131]], [[BB139]] ], [ [[I10133]], [[BB197]] ]
; CHECK-NEXT:    [[I303:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I294]], [[BB197]] ]
; CHECK-NEXT:    [[I304:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I295]], [[BB197]] ]
; CHECK-NEXT:    [[I305:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I296]], [[BB197]] ]
; CHECK-NEXT:    [[I306:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I297]], [[BB197]] ]
; CHECK-NEXT:    [[I307:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I298]], [[BB197]] ]
; CHECK-NEXT:    [[I308:%.*]] = fcmp ogt double [[I303]], -1.000000e+00
; CHECK-NEXT:    [[I309:%.*]] = select i1 [[I308]], double [[I303]], double -1.000000e+00
; CHECK-NEXT:    [[I310:%.*]] = fcmp ogt double [[I304]], [[I309]]
; CHECK-NEXT:    [[I311:%.*]] = select i1 [[I310]], double [[I304]], double [[I309]]
; CHECK-NEXT:    [[I312:%.*]] = fcmp ogt double [[I305]], [[I311]]
; CHECK-NEXT:    [[I313:%.*]] = select i1 [[I312]], double [[I305]], double [[I311]]
; CHECK-NEXT:    [[I314:%.*]] = fcmp ogt double [[I306]], [[I313]]
; CHECK-NEXT:    [[I315:%.*]] = select i1 [[I314]], double [[I306]], double [[I313]]
; CHECK-NEXT:    [[I316:%.*]] = select i1 [[I310]], i64 2, i64 1
; CHECK-NEXT:    [[I317:%.*]] = fcmp ogt double [[I307]], [[I315]]
; CHECK-NEXT:    [[I318:%.*]] = select i1 [[I312]], i64 3, i64 [[I316]]
; CHECK-NEXT:    [[I319:%.*]] = select i1 [[I314]], i64 4, i64 [[I318]]
; CHECK-NEXT:    [[I320:%.*]] = select i1 [[I317]], i64 5, i64 [[I319]]
; CHECK-NEXT:    [[I321:%.*]] = getelementptr inbounds i64, ptr [[ARG3]], i64 [[I40163]]
; CHECK-NEXT:    store i64 [[I320]], ptr [[I321]], align 8, !tbaa [[TBAA120]]
; CHECK-NEXT:    [[I322:%.*]] = add nsw i32 [[I18219]], [[I41271]]
; CHECK-NEXT:    [[I323]] = sext i32 [[I322]] to i64
; CHECK-NEXT:    [[I324:%.*]] = icmp ugt i64 [[I323]], [[I32275]]
; CHECK-NEXT:    br i1 [[I324]], label [[BB325]], label [[BB39]]
; CHECK:       bb325:
; CHECK-NEXT:    [[I28325]] = phi ptr [ [[I28323]], [[BB302]] ], [ [[I28325]], [[BB35]] ], [ [[I28325]], [[BB29_FROM_BB325:%.*]] ]
; CHECK-NEXT:    [[I25318]] = phi ptr [ [[I25316]], [[BB302]] ], [ [[I25318]], [[BB35]] ], [ [[I25318]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I24311]] = phi ptr [ [[I24309]], [[BB302]] ], [ [[I24311]], [[BB35]] ], [ [[I24311]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I23304]] = phi ptr [ [[I23302]], [[BB302]] ], [ [[I23304]], [[BB35]] ], [ [[I23304]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I22297]] = phi ptr [ [[I22295]], [[BB302]] ], [ [[I22297]], [[BB35]] ], [ [[I22297]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I21290]] = phi ptr [ [[I21288]], [[BB302]] ], [ [[I21290]], [[BB35]] ], [ [[I21290]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I6282]] = phi i32 [ [[I6280]], [[BB302]] ], [ [[I6282]], [[BB35]] ], [ [[I6282]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I27264]] = phi ptr [ [[I27262]], [[BB302]] ], [ [[I27264]], [[BB35]] ], [ [[I27264]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I26257]] = phi ptr [ [[I26255]], [[BB302]] ], [ [[I26257]], [[BB35]] ], [ [[I26257]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I20250]] = phi ptr [ [[I20248]], [[BB302]] ], [ [[I20250]], [[BB35]] ], [ [[I20250]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I19243]] = phi ptr [ [[I19241]], [[BB302]] ], [ [[I19243]], [[BB35]] ], [ [[I19243]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I4235]] = phi ptr [ [[I4233]], [[BB302]] ], [ [[I4235]], [[BB35]] ], [ [[I4235]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I13229]] = phi i32 [ [[I13227]], [[BB302]] ], [ [[I13229]], [[BB35]] ], [ [[I13229]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I18221]] = phi i32 [ [[I18219]], [[BB302]] ], [ [[I18221]], [[BB35]] ], [ [[I18221]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I208]] = phi i32 [ [[I195]], [[BB302]] ], [ [[I208]], [[BB35]] ], [ [[I208]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I5181]] = phi i32 [ [[I5179]], [[BB302]] ], [ [[I5181]], [[BB35]] ], [ [[I5181]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I30175:%.*]] = phi i32 [ [[I30173]], [[BB302]] ], [ [[I328_BB29]], [[BB35]] ], [ [[I328_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I31169:%.*]] = phi i32 [ [[I31167]], [[BB302]] ], [ [[I326_BB29]], [[BB35]] ], [ [[I326_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I10134]] = phi i32 [ [[I10132]], [[BB302]] ], [ [[I10134]], [[BB35]] ], [ [[I10134]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I326:%.*]] = add nsw i32 [[I31169]], [[I13229]]
; CHECK-NEXT:    [[I327:%.*]] = add nsw i32 [[I30175]], [[I13229]]
; CHECK-NEXT:    [[I328:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I327]], i32 [[I6282]])
; CHECK-NEXT:    [[I329:%.*]] = icmp slt i32 [[I326]], [[I5181]]
; CHECK-NEXT:    br i1 [[I329]], label [[BB29_FROM_BB325]], label [[BB330:%.*]]
; CHECK:       bb29.from.bb325:
; CHECK-NEXT:    [[I326_BB29]] = phi i32 [ [[I326]], [[BB325]] ]
; CHECK-NEXT:    [[I328_BB29]] = phi i32 [ [[I328]], [[BB325]] ]
; CHECK-NEXT:    [[I32]] = zext i32 [[I328_BB29]] to i64
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I33:%.*]] = load i32, ptr [[I4235]], align 8, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[I34:%.*]] = icmp sgt i32 [[I33]], 0
; CHECK-NEXT:    br i1 [[I34]], label [[BB35]], label [[BB325]]
; CHECK:       bb330:
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define weak_odr protected void @__omp_offloading_run_event_based_simulation_contd_1(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef nonnull align 8 dereferenceable(64) [[ARG1:%.*]], ptr noundef nonnull align 8 dereferenceable(112) [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[GTID31:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CONTCOUNT_IN_PTR32:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 3
; CHECK-NEXT:    [[CONTCOUNT_IN33:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR32]], align 4
; CHECK-NEXT:    [[MASKTHREAD34:%.*]] = icmp ult i32 [[GTID31]], [[CONTCOUNT_IN33]]
; CHECK-NEXT:    br i1 [[MASKTHREAD34]], label [[CACHEREMAT1:%.*]], label [[THREADEXIT:%.*]]
; CHECK:       bb35:
; CHECK-NEXT:    [[I36:%.*]] = add nsw i32 [[I326_BB29:%.*]], [[I208:%.*]]
; CHECK-NEXT:    [[I37:%.*]] = sext i32 [[I36]] to i64
; CHECK-NEXT:    [[I38:%.*]] = icmp ugt i64 [[I37]], [[I32:%.*]]
; CHECK-NEXT:    br i1 [[I38]], label [[BB325:%.*]], label [[BB39:%.*]]
; CHECK:       bb39:
; CHECK-NEXT:    [[I28326:%.*]] = phi ptr [ [[I28325:%.*]], [[BB35:%.*]] ], [ [[I28323:%.*]], [[BB302:%.*]] ]
; CHECK-NEXT:    [[I25319:%.*]] = phi ptr [ [[I25318:%.*]], [[BB35]] ], [ [[I25316:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I24312:%.*]] = phi ptr [ [[I24311:%.*]], [[BB35]] ], [ [[I24309:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I23305:%.*]] = phi ptr [ [[I23304:%.*]], [[BB35]] ], [ [[I23302:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I22298:%.*]] = phi ptr [ [[I22297:%.*]], [[BB35]] ], [ [[I22295:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I21291:%.*]] = phi ptr [ [[I21290:%.*]], [[BB35]] ], [ [[I21288:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I6283:%.*]] = phi i32 [ [[I6282:%.*]], [[BB35]] ], [ [[I6280:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I32277:%.*]] = phi i64 [ [[I32]], [[BB35]] ], [ [[I32275:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I27265:%.*]] = phi ptr [ [[I27264:%.*]], [[BB35]] ], [ [[I27262:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I26258:%.*]] = phi ptr [ [[I26257:%.*]], [[BB35]] ], [ [[I26255:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I20251:%.*]] = phi ptr [ [[I20250:%.*]], [[BB35]] ], [ [[I20248:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I19244:%.*]] = phi ptr [ [[I19243:%.*]], [[BB35]] ], [ [[I19241:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I4236:%.*]] = phi ptr [ [[I4235:%.*]], [[BB35]] ], [ [[I4233:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I13230:%.*]] = phi i32 [ [[I13229:%.*]], [[BB35]] ], [ [[I13227:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I18222:%.*]] = phi i32 [ [[I18221:%.*]], [[BB35]] ], [ [[I18219:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I212:%.*]] = phi i32 [ [[I208]], [[BB35]] ], [ [[I195:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I5182:%.*]] = phi i32 [ [[I5181:%.*]], [[BB35]] ], [ [[I5179:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I30176:%.*]] = phi i32 [ [[I328_BB29:%.*]], [[BB35]] ], [ [[I30173:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I31170:%.*]] = phi i32 [ [[I326_BB29]], [[BB35]] ], [ [[I31167:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I10135:%.*]] = phi i32 [ [[I10134:%.*]], [[BB35]] ], [ [[I10132:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I40:%.*]] = phi i64 [ [[I37]], [[BB35]] ], [ [[I323:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I41:%.*]] = trunc i64 [[I40]] to i32
; CHECK-NEXT:    [[I42:%.*]] = shl nsw i32 [[I41]], 1
; CHECK-NEXT:    [[I43:%.*]] = sext i32 [[I42]] to i64
; CHECK-NEXT:    [[I44:%.*]] = and i64 [[I43]], 9223372036854775806
; CHECK-NEXT:    [[I45:%.*]] = icmp eq i64 [[I44]], 0
; CHECK-NEXT:    br i1 [[I45]], label [[BB69:%.*]], label [[BB46:%.*]]
; CHECK:       bb46:
; CHECK-NEXT:    [[I47:%.*]] = phi i64 [ 0, [[BB39]] ], [ [[I58:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I48:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I57:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I49:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I60:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I50:%.*]] = phi i64 [ 2806196910506780709, [[BB39]] ], [ [[I61:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I51:%.*]] = phi i64 [ [[I44]], [[BB39]] ], [ [[I62:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I52:%.*]] = and i64 [[I51]], 1
; CHECK-NEXT:    [[I53:%.*]] = icmp eq i64 [[I52]], 0
; CHECK-NEXT:    [[I54:%.*]] = mul i64 [[I50]], [[I47]]
; CHECK-NEXT:    [[I55:%.*]] = add i64 [[I54]], [[I49]]
; CHECK-NEXT:    [[I56:%.*]] = select i1 [[I53]], i64 1, i64 [[I50]]
; CHECK-NEXT:    [[I57]] = mul i64 [[I56]], [[I48]]
; CHECK-NEXT:    [[I58]] = select i1 [[I53]], i64 [[I47]], i64 [[I55]]
; CHECK-NEXT:    [[I59:%.*]] = add i64 [[I50]], 1
; CHECK-NEXT:    [[I60]] = mul i64 [[I59]], [[I49]]
; CHECK-NEXT:    [[I61]] = mul i64 [[I50]], [[I50]]
; CHECK-NEXT:    [[I62]] = lshr i64 [[I51]], 1
; CHECK-NEXT:    [[I63:%.*]] = icmp ult i64 [[I51]], 2
; CHECK-NEXT:    br i1 [[I63]], label [[BB64:%.*]], label [[BB46]]
; CHECK:       bb64:
; CHECK-NEXT:    [[I67:%.*]] = mul i64 [[I57]], 1070
; CHECK-NEXT:    [[I68:%.*]] = add i64 [[I67]], [[I58]]
; CHECK-NEXT:    br label [[BB69]]
; CHECK:       bb69:
; CHECK-NEXT:    [[I70:%.*]] = phi i64 [ [[I68]], [[BB64]] ], [ 1070, [[BB39]] ]
; CHECK-NEXT:    [[I71:%.*]] = mul i64 [[I70]], 2806196910506780709
; CHECK-NEXT:    [[I72:%.*]] = add i64 [[I71]], 1
; CHECK-NEXT:    [[I73:%.*]] = and i64 [[I72]], 9223372036854775807
; CHECK-NEXT:    [[I74:%.*]] = uitofp i64 [[I73]] to double
; CHECK-NEXT:    [[I75:%.*]] = fmul double [[I74]], 0x3C00000000000000
; CHECK-NEXT:    [[I76:%.*]] = mul i64 [[I72]], 2806196910506780709
; CHECK-NEXT:    [[I77:%.*]] = add i64 [[I76]], 1
; CHECK-NEXT:    [[I78:%.*]] = and i64 [[I77]], 9223372036854775807
; CHECK-NEXT:    [[I79:%.*]] = uitofp i64 [[I78]] to double
; CHECK-NEXT:    [[I80:%.*]] = fmul double [[I79]], 0x3C00000000000000
; CHECK-NEXT:    [[I81:%.*]] = fcmp uge double [[I80]], 5.200000e-02
; CHECK-NEXT:    br i1 [[I81]], label [[BB82:%.*]], label [[BB103:%.*]]
; CHECK:       bb82:
; CHECK-NEXT:    [[I83:%.*]] = fcmp uge double [[I80]], 3.270000e-01
; CHECK-NEXT:    br i1 [[I83]], label [[BB84:%.*]], label [[BB103]]
; CHECK:       bb84:
; CHECK-NEXT:    [[I85:%.*]] = fcmp uge double [[I80]], 4.610000e-01
; CHECK-NEXT:    br i1 [[I85]], label [[BB86:%.*]], label [[BB103]]
; CHECK:       bb86:
; CHECK-NEXT:    [[I87:%.*]] = fcmp uge double [[I80]], 0x3FE3AE147AE147AF
; CHECK-NEXT:    br i1 [[I87]], label [[BB88:%.*]], label [[BB103]]
; CHECK:       bb88:
; CHECK-NEXT:    [[I89:%.*]] = fcmp uge double [[I80]], 6.790000e-01
; CHECK-NEXT:    br i1 [[I89]], label [[BB90:%.*]], label [[BB103]]
; CHECK:       bb90:
; CHECK-NEXT:    [[I91:%.*]] = fcmp uge double [[I80]], 0x3FE7D70A3D70A3D8
; CHECK-NEXT:    br i1 [[I91]], label [[BB92:%.*]], label [[BB103]]
; CHECK:       bb92:
; CHECK-NEXT:    [[I93:%.*]] = fcmp uge double [[I80]], 8.000000e-01
; CHECK-NEXT:    br i1 [[I93]], label [[BB94:%.*]], label [[BB103]]
; CHECK:       bb94:
; CHECK-NEXT:    [[I95:%.*]] = fcmp uge double [[I80]], 8.080000e-01
; CHECK-NEXT:    br i1 [[I95]], label [[BB96:%.*]], label [[BB103]]
; CHECK:       bb96:
; CHECK-NEXT:    [[I97:%.*]] = fcmp uge double [[I80]], 0x3FEA5604189374BD
; CHECK-NEXT:    br i1 [[I97]], label [[BB98:%.*]], label [[BB103]]
; CHECK:       bb98:
; CHECK-NEXT:    [[I99:%.*]] = fcmp uge double [[I80]], 0x3FEB22D0E560418A
; CHECK-NEXT:    br i1 [[I99]], label [[BB100:%.*]], label [[BB103]]
; CHECK:       bb100:
; CHECK-NEXT:    [[I101:%.*]] = fcmp uge double [[I80]], 0x3FEB8D4FDF3B645B
; CHECK-NEXT:    br i1 [[I101]], label [[BB103_FROM_BB102:%.*]], label [[BB103]]
; CHECK:       bb103.from.bb102:
; CHECK-NEXT:    br label [[BB103]]
; CHECK:       bb103:
; CHECK-NEXT:    [[I104:%.*]] = phi i32 [ 0, [[BB103_FROM_BB102]] ], [ 1, [[BB69]] ], [ 2, [[BB82]] ], [ 3, [[BB84]] ], [ 4, [[BB86]] ], [ 5, [[BB88]] ], [ 6, [[BB90]] ], [ 7, [[BB92]] ], [ 8, [[BB94]] ], [ 9, [[BB96]] ], [ 10, [[BB98]] ], [ 11, [[BB100]] ]
; CHECK-NEXT:    [[I105:%.*]] = load i64, ptr [[I19244]], align 8, !tbaa [[TBAA27]]
; CHECK-NEXT:    [[I106:%.*]] = load i64, ptr [[I20251]], align 8, !tbaa [[TBAA28]]
; CHECK-NEXT:    [[I107:%.*]] = load ptr, ptr [[ARG2]], align 8, !tbaa [[TBAA29]]
; CHECK-NEXT:    [[I108:%.*]] = load ptr, ptr [[I21291]], align 8, !tbaa [[TBAA31]]
; CHECK-NEXT:    [[I109:%.*]] = load ptr, ptr [[I22298]], align 8, !tbaa [[TBAA32]]
; CHECK-NEXT:    [[I110:%.*]] = load ptr, ptr [[I23305]], align 8, !tbaa [[TBAA33]]
; CHECK-NEXT:    [[I111:%.*]] = load ptr, ptr [[I24312]], align 8, !tbaa [[TBAA34]]
; CHECK-NEXT:    [[I112:%.*]] = load ptr, ptr [[I25319]], align 8, !tbaa [[TBAA35]]
; CHECK-NEXT:    [[I113:%.*]] = load i32, ptr [[I26258]], align 8, !tbaa [[TBAA36]]
; CHECK-NEXT:    [[I114:%.*]] = load i32, ptr [[I27265]], align 4, !tbaa [[TBAA37]]
; CHECK-NEXT:    [[I115:%.*]] = load i32, ptr [[I28326]], align 4, !tbaa [[TBAA38]]
; CHECK-NEXT:    switch i32 [[I113]], label [[BB139:%.*]] [
; CHECK-NEXT:      i32 0, label [[BB116:%.*]]
; CHECK-NEXT:      i32 2, label [[CACHESTORE0:%.*]]
; CHECK-NEXT:    ]
; CHECK:       bb116:
; CHECK-NEXT:    [[I117:%.*]] = mul nsw i64 [[I106]], [[I105]]
; CHECK-NEXT:    [[I118:%.*]] = icmp sgt i64 [[I117]], 2
; CHECK-NEXT:    br i1 [[I118]], label [[BB119:%.*]], label [[BB139]]
; CHECK:       bb119:
; CHECK-NEXT:    [[I120:%.*]] = add nsw i64 [[I117]], -1
; CHECK-NEXT:    br label [[BB121:%.*]]
; CHECK:       bb121:
; CHECK-NEXT:    [[I122:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I132:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I123:%.*]] = phi i64 [ 0, [[BB119]] ], [ [[I131:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I124:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I130:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I125:%.*]] = lshr i64 [[I122]], 1
; CHECK-NEXT:    [[I126:%.*]] = add nuw nsw i64 [[I125]], [[I123]]
; CHECK-NEXT:    [[I127:%.*]] = getelementptr inbounds double, ptr [[I109]], i64 [[I126]]
; CHECK-NEXT:    [[I128:%.*]] = load double, ptr [[I127]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    [[I129:%.*]] = fcmp ogt double [[I128]], [[I75]]
; CHECK-NEXT:    [[I130]] = select i1 [[I129]], i64 [[I126]], i64 [[I124]]
; CHECK-NEXT:    [[I131]] = select i1 [[I129]], i64 [[I123]], i64 [[I126]]
; CHECK-NEXT:    [[I132]] = sub nsw i64 [[I130]], [[I131]]
; CHECK-NEXT:    [[I133:%.*]] = icmp sgt i64 [[I132]], 1
; CHECK-NEXT:    br i1 [[I133]], label [[BB121]], label [[BB139]]
; CHECK:       CacheStore0:
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[TMP9]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP10]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET:%.*]] = load i32, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I10135]], ptr [[TMP12]], align 4, !invariant.group [[META41]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[TMP13]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I70]], ptr [[TMP14]], align 8, !invariant.group [[META42]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[TMP15]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I115]], ptr [[TMP17]], align 4, !invariant.group [[META43]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[TMP18]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP19]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP20]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I114]], ptr [[TMP21]], align 4, !invariant.group [[META44]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i64, ptr [[TMP22]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP23]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP25]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 2, ptr [[TMP26]], align 4, !invariant.group [[META45]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP27]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP29]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i32, ptr [[TMP30]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds ptr, ptr [[TMP31]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I112]], ptr [[TMP32]], align 8, !invariant.group [[META46]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i64, ptr [[TMP33]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i32, ptr [[TMP34]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i32, ptr [[TMP35]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i32, ptr [[TMP36]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds ptr, ptr [[TMP37]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds ptr, ptr [[TMP38]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I111]], ptr [[TMP39]], align 8, !invariant.group [[META47]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds i64, ptr [[TMP40]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds i32, ptr [[TMP41]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i32, ptr [[TMP42]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, ptr [[TMP43]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds ptr, ptr [[TMP44]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds ptr, ptr [[TMP45]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP47:%.*]] = getelementptr inbounds ptr, ptr [[TMP46]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I110]], ptr [[TMP47]], align 8, !invariant.group [[META48]]
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds i64, ptr [[TMP48]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP50:%.*]] = getelementptr inbounds i32, ptr [[TMP49]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP51:%.*]] = getelementptr inbounds i32, ptr [[TMP50]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i32, ptr [[TMP51]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds ptr, ptr [[TMP52]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds ptr, ptr [[TMP53]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds ptr, ptr [[TMP54]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP56:%.*]] = getelementptr inbounds ptr, ptr [[TMP55]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I108]], ptr [[TMP56]], align 8, !invariant.group [[META49]]
; CHECK-NEXT:    [[TMP57:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP58:%.*]] = getelementptr inbounds i64, ptr [[TMP57]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i32, ptr [[TMP58]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds i32, ptr [[TMP59]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP61:%.*]] = getelementptr inbounds i32, ptr [[TMP60]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP62:%.*]] = getelementptr inbounds ptr, ptr [[TMP61]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds ptr, ptr [[TMP62]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds ptr, ptr [[TMP63]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds ptr, ptr [[TMP64]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP66:%.*]] = getelementptr inbounds ptr, ptr [[TMP65]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I107]], ptr [[TMP66]], align 8, !invariant.group [[META50]]
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr inbounds i64, ptr [[TMP67]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP69:%.*]] = getelementptr inbounds i32, ptr [[TMP68]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP70:%.*]] = getelementptr inbounds i32, ptr [[TMP69]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP71:%.*]] = getelementptr inbounds i32, ptr [[TMP70]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP72:%.*]] = getelementptr inbounds ptr, ptr [[TMP71]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP73:%.*]] = getelementptr inbounds ptr, ptr [[TMP72]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds ptr, ptr [[TMP73]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP75:%.*]] = getelementptr inbounds ptr, ptr [[TMP74]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP76:%.*]] = getelementptr inbounds ptr, ptr [[TMP75]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP77:%.*]] = getelementptr inbounds i64, ptr [[TMP76]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I106]], ptr [[TMP77]], align 8, !invariant.group [[META51]]
; CHECK-NEXT:    [[TMP78:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP79:%.*]] = getelementptr inbounds i64, ptr [[TMP78]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP80:%.*]] = getelementptr inbounds i32, ptr [[TMP79]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP81:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP82:%.*]] = getelementptr inbounds i32, ptr [[TMP81]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP83:%.*]] = getelementptr inbounds ptr, ptr [[TMP82]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP84:%.*]] = getelementptr inbounds ptr, ptr [[TMP83]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP85:%.*]] = getelementptr inbounds ptr, ptr [[TMP84]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP86:%.*]] = getelementptr inbounds ptr, ptr [[TMP85]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP87:%.*]] = getelementptr inbounds ptr, ptr [[TMP86]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP88:%.*]] = getelementptr inbounds i64, ptr [[TMP87]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP89:%.*]] = getelementptr inbounds i64, ptr [[TMP88]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I105]], ptr [[TMP89]], align 8, !invariant.group [[META52]]
; CHECK-NEXT:    [[TMP90:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP91:%.*]] = getelementptr inbounds i64, ptr [[TMP90]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr inbounds i32, ptr [[TMP91]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP93:%.*]] = getelementptr inbounds i32, ptr [[TMP92]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP94:%.*]] = getelementptr inbounds i32, ptr [[TMP93]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP95:%.*]] = getelementptr inbounds ptr, ptr [[TMP94]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP96:%.*]] = getelementptr inbounds ptr, ptr [[TMP95]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP97:%.*]] = getelementptr inbounds ptr, ptr [[TMP96]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP98:%.*]] = getelementptr inbounds ptr, ptr [[TMP97]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP99:%.*]] = getelementptr inbounds ptr, ptr [[TMP98]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP100:%.*]] = getelementptr inbounds i64, ptr [[TMP99]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i64, ptr [[TMP100]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP102:%.*]] = getelementptr inbounds i32, ptr [[TMP101]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I104]], ptr [[TMP102]], align 4, !invariant.group [[META53]]
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds i64, ptr [[TMP103]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds i32, ptr [[TMP104]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds i32, ptr [[TMP105]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i32, ptr [[TMP106]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds ptr, ptr [[TMP107]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds ptr, ptr [[TMP108]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP110:%.*]] = getelementptr inbounds ptr, ptr [[TMP109]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP111:%.*]] = getelementptr inbounds ptr, ptr [[TMP110]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP112:%.*]] = getelementptr inbounds ptr, ptr [[TMP111]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP113:%.*]] = getelementptr inbounds i64, ptr [[TMP112]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP114:%.*]] = getelementptr inbounds i64, ptr [[TMP113]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP115:%.*]] = getelementptr inbounds i32, ptr [[TMP114]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP116:%.*]] = getelementptr inbounds i64, ptr [[TMP115]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I40]], ptr [[TMP116]], align 8, !invariant.group [[META54]]
; CHECK-NEXT:    [[TMP117:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP118:%.*]] = getelementptr inbounds i64, ptr [[TMP117]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP119:%.*]] = getelementptr inbounds i32, ptr [[TMP118]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds i32, ptr [[TMP119]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP121:%.*]] = getelementptr inbounds i32, ptr [[TMP120]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP122:%.*]] = getelementptr inbounds ptr, ptr [[TMP121]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP123:%.*]] = getelementptr inbounds ptr, ptr [[TMP122]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP124:%.*]] = getelementptr inbounds ptr, ptr [[TMP123]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr inbounds ptr, ptr [[TMP124]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr inbounds ptr, ptr [[TMP125]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP127:%.*]] = getelementptr inbounds i64, ptr [[TMP126]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP128:%.*]] = getelementptr inbounds i64, ptr [[TMP127]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP129:%.*]] = getelementptr inbounds i32, ptr [[TMP128]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP130:%.*]] = getelementptr inbounds i64, ptr [[TMP129]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP131:%.*]] = getelementptr inbounds i32, ptr [[TMP130]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I31170]], ptr [[TMP131]], align 4, !invariant.group [[META55]]
; CHECK-NEXT:    [[TMP132:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP133:%.*]] = getelementptr inbounds i64, ptr [[TMP132]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP134:%.*]] = getelementptr inbounds i32, ptr [[TMP133]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP135:%.*]] = getelementptr inbounds i32, ptr [[TMP134]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP136:%.*]] = getelementptr inbounds i32, ptr [[TMP135]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP137:%.*]] = getelementptr inbounds ptr, ptr [[TMP136]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP138:%.*]] = getelementptr inbounds ptr, ptr [[TMP137]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP139:%.*]] = getelementptr inbounds ptr, ptr [[TMP138]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP140:%.*]] = getelementptr inbounds ptr, ptr [[TMP139]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP141:%.*]] = getelementptr inbounds ptr, ptr [[TMP140]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP142:%.*]] = getelementptr inbounds i64, ptr [[TMP141]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP143:%.*]] = getelementptr inbounds i64, ptr [[TMP142]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP144:%.*]] = getelementptr inbounds i32, ptr [[TMP143]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP145:%.*]] = getelementptr inbounds i64, ptr [[TMP144]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP146:%.*]] = getelementptr inbounds i32, ptr [[TMP145]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP147:%.*]] = getelementptr inbounds i32, ptr [[TMP146]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I30176]], ptr [[TMP147]], align 4, !invariant.group [[META56]]
; CHECK-NEXT:    [[TMP148:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP149:%.*]] = getelementptr inbounds i64, ptr [[TMP148]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP150:%.*]] = getelementptr inbounds i32, ptr [[TMP149]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP151:%.*]] = getelementptr inbounds i32, ptr [[TMP150]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP152:%.*]] = getelementptr inbounds i32, ptr [[TMP151]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP153:%.*]] = getelementptr inbounds ptr, ptr [[TMP152]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP154:%.*]] = getelementptr inbounds ptr, ptr [[TMP153]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP155:%.*]] = getelementptr inbounds ptr, ptr [[TMP154]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP156:%.*]] = getelementptr inbounds ptr, ptr [[TMP155]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP157:%.*]] = getelementptr inbounds ptr, ptr [[TMP156]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP158:%.*]] = getelementptr inbounds i64, ptr [[TMP157]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP159:%.*]] = getelementptr inbounds i64, ptr [[TMP158]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP160:%.*]] = getelementptr inbounds i32, ptr [[TMP159]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP161:%.*]] = getelementptr inbounds i64, ptr [[TMP160]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP162:%.*]] = getelementptr inbounds i32, ptr [[TMP161]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP163:%.*]] = getelementptr inbounds i32, ptr [[TMP162]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP164:%.*]] = getelementptr inbounds i32, ptr [[TMP163]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I5182]], ptr [[TMP164]], align 4, !invariant.group [[META57]]
; CHECK-NEXT:    [[TMP165:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP166:%.*]] = getelementptr inbounds i64, ptr [[TMP165]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP167:%.*]] = getelementptr inbounds i32, ptr [[TMP166]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP168:%.*]] = getelementptr inbounds i32, ptr [[TMP167]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP169:%.*]] = getelementptr inbounds i32, ptr [[TMP168]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP170:%.*]] = getelementptr inbounds ptr, ptr [[TMP169]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP171:%.*]] = getelementptr inbounds ptr, ptr [[TMP170]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP172:%.*]] = getelementptr inbounds ptr, ptr [[TMP171]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP173:%.*]] = getelementptr inbounds ptr, ptr [[TMP172]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP174:%.*]] = getelementptr inbounds ptr, ptr [[TMP173]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP175:%.*]] = getelementptr inbounds i64, ptr [[TMP174]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP176:%.*]] = getelementptr inbounds i64, ptr [[TMP175]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP177:%.*]] = getelementptr inbounds i32, ptr [[TMP176]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP178:%.*]] = getelementptr inbounds i64, ptr [[TMP177]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP179:%.*]] = getelementptr inbounds i32, ptr [[TMP178]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP180:%.*]] = getelementptr inbounds i32, ptr [[TMP179]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP181:%.*]] = getelementptr inbounds i32, ptr [[TMP180]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP182:%.*]] = getelementptr inbounds i32, ptr [[TMP181]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I212]], ptr [[TMP182]], align 4, !invariant.group [[META58]]
; CHECK-NEXT:    [[TMP183:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP184:%.*]] = getelementptr inbounds i64, ptr [[TMP183]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP185:%.*]] = getelementptr inbounds i32, ptr [[TMP184]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP186:%.*]] = getelementptr inbounds i32, ptr [[TMP185]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP187:%.*]] = getelementptr inbounds i32, ptr [[TMP186]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP188:%.*]] = getelementptr inbounds ptr, ptr [[TMP187]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP189:%.*]] = getelementptr inbounds ptr, ptr [[TMP188]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP190:%.*]] = getelementptr inbounds ptr, ptr [[TMP189]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP191:%.*]] = getelementptr inbounds ptr, ptr [[TMP190]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP192:%.*]] = getelementptr inbounds ptr, ptr [[TMP191]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP193:%.*]] = getelementptr inbounds i64, ptr [[TMP192]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP194:%.*]] = getelementptr inbounds i64, ptr [[TMP193]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP195:%.*]] = getelementptr inbounds i32, ptr [[TMP194]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP196:%.*]] = getelementptr inbounds i64, ptr [[TMP195]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP197:%.*]] = getelementptr inbounds i32, ptr [[TMP196]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP198:%.*]] = getelementptr inbounds i32, ptr [[TMP197]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP199:%.*]] = getelementptr inbounds i32, ptr [[TMP198]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP200:%.*]] = getelementptr inbounds i32, ptr [[TMP199]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP201:%.*]] = getelementptr inbounds i32, ptr [[TMP200]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I18222]], ptr [[TMP201]], align 4, !invariant.group [[META59]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb139:
; CHECK-NEXT:    [[I140:%.*]] = phi i64 [ -1, [[BB103]] ], [ 0, [[BB116]] ], [ [[I131]], [[BB121]] ]
; CHECK-NEXT:    [[I141:%.*]] = zext nneg i32 [[I104]] to i64
; CHECK-NEXT:    [[I142:%.*]] = getelementptr inbounds i32, ptr [[I107]], i64 [[I141]]
; CHECK-NEXT:    [[I143:%.*]] = load i32, ptr [[I142]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I144:%.*]] = icmp sgt i32 [[I143]], 0
; CHECK-NEXT:    br i1 [[I144]], label [[BB145:%.*]], label [[BB302]]
; CHECK:       bb145:
; CHECK-NEXT:    [[I146:%.*]] = mul nsw i32 [[I115]], [[I104]]
; CHECK-NEXT:    [[I147:%.*]] = mul nsw i64 [[I140]], [[I105]]
; CHECK-NEXT:    [[I148:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I147]]
; CHECK-NEXT:    [[I149:%.*]] = add i64 [[I106]], -1
; CHECK-NEXT:    [[I150:%.*]] = icmp sgt i64 [[I106]], 2
; CHECK-NEXT:    [[I151:%.*]] = add nsw i32 [[I114]], -1
; CHECK-NEXT:    [[I152:%.*]] = sext i32 [[I151]] to i64
; CHECK-NEXT:    [[I153:%.*]] = icmp eq i64 [[I140]], [[I152]]
; CHECK-NEXT:    [[I154:%.*]] = add nsw i64 [[I140]], 1
; CHECK-NEXT:    [[I155:%.*]] = mul nsw i64 [[I154]], [[I105]]
; CHECK-NEXT:    [[I156:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I155]]
; CHECK-NEXT:    [[I157:%.*]] = trunc i64 [[I106]] to i32
; CHECK-NEXT:    [[I158:%.*]] = add i32 [[I157]], -1
; CHECK-NEXT:    br label [[BB159:%.*]]
; CHECK:       bb159:
; CHECK-NEXT:    [[I149345:%.*]] = phi i64 [ [[I149]], [[BB145]] ], [ [[I149344:%.*]], [[BB255:%.*]] ]
; CHECK-NEXT:    [[I156336:%.*]] = phi ptr [ [[I156]], [[BB145]] ], [ [[I156335:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I148334:%.*]] = phi ptr [ [[I148]], [[BB145]] ], [ [[I148333:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I153332:%.*]] = phi i1 [ [[I153]], [[BB145]] ], [ [[I153331:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I146330:%.*]] = phi i32 [ [[I146]], [[BB145]] ], [ [[I146329:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I142328:%.*]] = phi ptr [ [[I142]], [[BB145]] ], [ [[I142327:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I28324:%.*]] = phi ptr [ [[I28326]], [[BB145]] ], [ [[I28321:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I25317:%.*]] = phi ptr [ [[I25319]], [[BB145]] ], [ [[I25314:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I24310:%.*]] = phi ptr [ [[I24312]], [[BB145]] ], [ [[I24307:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I23303:%.*]] = phi ptr [ [[I23305]], [[BB145]] ], [ [[I23300:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I22296:%.*]] = phi ptr [ [[I22298]], [[BB145]] ], [ [[I22293:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I21289:%.*]] = phi ptr [ [[I21291]], [[BB145]] ], [ [[I21286:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I6281:%.*]] = phi i32 [ [[I6283]], [[BB145]] ], [ [[I6278:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I32276:%.*]] = phi i64 [ [[I32277]], [[BB145]] ], [ [[I32273:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I41272:%.*]] = phi i32 [ [[I41]], [[BB145]] ], [ [[I41269:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I75268:%.*]] = phi double [ [[I75]], [[BB145]] ], [ [[I75266:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I27263:%.*]] = phi ptr [ [[I27265]], [[BB145]] ], [ [[I27260:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I26256:%.*]] = phi ptr [ [[I26258]], [[BB145]] ], [ [[I26253:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I20249:%.*]] = phi ptr [ [[I20251]], [[BB145]] ], [ [[I20246:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I19242:%.*]] = phi ptr [ [[I19244]], [[BB145]] ], [ [[I19239:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I4234:%.*]] = phi ptr [ [[I4236]], [[BB145]] ], [ [[I4231:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I13228:%.*]] = phi i32 [ [[I13230]], [[BB145]] ], [ [[I13224:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I18220:%.*]] = phi i32 [ [[I18222]], [[BB145]] ], [ [[I18217:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I197:%.*]] = phi i32 [ [[I212]], [[BB145]] ], [ [[I189:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I5180:%.*]] = phi i32 [ [[I5182]], [[BB145]] ], [ [[I5177:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I30174:%.*]] = phi i32 [ [[I30176]], [[BB145]] ], [ [[I30171:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I31168:%.*]] = phi i32 [ [[I31170]], [[BB145]] ], [ [[I31165:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I40164:%.*]] = phi i64 [ [[I40]], [[BB145]] ], [ [[I40161:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I106158:%.*]] = phi i64 [ [[I106]], [[BB145]] ], [ [[I106157:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I108154:%.*]] = phi ptr [ [[I108]], [[BB145]] ], [ [[I108153:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I111150:%.*]] = phi ptr [ [[I111]], [[BB145]] ], [ [[I111149:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I112147:%.*]] = phi ptr [ [[I112]], [[BB145]] ], [ [[I112146:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I113144:%.*]] = phi i32 [ [[I113]], [[BB145]] ], [ [[I113143:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I70139:%.*]] = phi i64 [ [[I70]], [[BB145]] ], [ [[I70137:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I10133:%.*]] = phi i32 [ [[I10135]], [[BB145]] ], [ [[I10130:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I160:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I298:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I161:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I297:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I162:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I296:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I163:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I295:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I164:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I294:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I165:%.*]] = phi i32 [ 0, [[BB145]] ], [ [[I299:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I166:%.*]] = add nsw i32 [[I165]], [[I146330]]
; CHECK-NEXT:    [[I167:%.*]] = sext i32 [[I166]] to i64
; CHECK-NEXT:    [[I168:%.*]] = getelementptr inbounds i32, ptr [[I112147]], i64 [[I167]]
; CHECK-NEXT:    [[I169:%.*]] = load i32, ptr [[I168]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I170:%.*]] = getelementptr inbounds double, ptr [[I108154]], i64 [[I167]]
; CHECK-NEXT:    [[I171:%.*]] = load double, ptr [[I170]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    switch i32 [[I113144]], label [[CACHESTORE2:%.*]] [
; CHECK-NEXT:      i32 1, label [[CACHESTORE1:%.*]]
; CHECK-NEXT:      i32 0, label [[BB197:%.*]]
; CHECK-NEXT:    ]
; CHECK:       CacheStore1:
; CHECK-NEXT:    [[TMP202:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP203:%.*]] = load ptr, ptr [[TMP202]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR27:%.*]] = getelementptr inbounds i32, ptr [[TMP203]], i32 1
; CHECK-NEXT:    [[CACHEIDX28:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR27]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP204:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP205:%.*]] = load ptr, ptr [[TMP204]], align 8
; CHECK-NEXT:    [[TMP206:%.*]] = getelementptr inbounds ptr, ptr [[TMP205]], i32 1
; CHECK-NEXT:    [[CACHE_OUT_PTR29:%.*]] = load ptr, ptr [[TMP206]], align 8
; CHECK-NEXT:    [[TMP207:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET30:%.*]] = load i32, ptr [[TMP207]], align 4
; CHECK-NEXT:    [[TMP208:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP208]], align 4, !invariant.group [[META61]]
; CHECK-NEXT:    [[TMP209:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP210:%.*]] = getelementptr inbounds i64, ptr [[TMP209]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP210]], align 8, !invariant.group [[META62]]
; CHECK-NEXT:    [[TMP211:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP212:%.*]] = getelementptr inbounds i64, ptr [[TMP211]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP213:%.*]] = getelementptr inbounds ptr, ptr [[TMP212]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP213]], align 8, !invariant.group [[META63]]
; CHECK-NEXT:    [[TMP214:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP215:%.*]] = getelementptr inbounds i64, ptr [[TMP214]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP216:%.*]] = getelementptr inbounds ptr, ptr [[TMP215]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP217:%.*]] = getelementptr inbounds i32, ptr [[TMP216]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP217]], align 4, !invariant.group [[META64]]
; CHECK-NEXT:    [[TMP218:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP219:%.*]] = getelementptr inbounds i64, ptr [[TMP218]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP220:%.*]] = getelementptr inbounds ptr, ptr [[TMP219]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP221:%.*]] = getelementptr inbounds i32, ptr [[TMP220]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP222:%.*]] = getelementptr inbounds i1, ptr [[TMP221]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP222]], align 1, !invariant.group [[META65]]
; CHECK-NEXT:    [[TMP223:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP224:%.*]] = getelementptr inbounds i64, ptr [[TMP223]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP225:%.*]] = getelementptr inbounds ptr, ptr [[TMP224]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP226:%.*]] = getelementptr inbounds i32, ptr [[TMP225]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP227:%.*]] = getelementptr inbounds i1, ptr [[TMP226]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP228:%.*]] = getelementptr inbounds ptr, ptr [[TMP227]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP228]], align 8, !invariant.group [[META66]]
; CHECK-NEXT:    [[TMP229:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP230:%.*]] = getelementptr inbounds i64, ptr [[TMP229]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP231:%.*]] = getelementptr inbounds ptr, ptr [[TMP230]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP232:%.*]] = getelementptr inbounds i32, ptr [[TMP231]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP233:%.*]] = getelementptr inbounds i1, ptr [[TMP232]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP234:%.*]] = getelementptr inbounds ptr, ptr [[TMP233]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP235:%.*]] = getelementptr inbounds ptr, ptr [[TMP234]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP235]], align 8, !invariant.group [[META67]]
; CHECK-NEXT:    [[TMP236:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP237:%.*]] = getelementptr inbounds i64, ptr [[TMP236]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP238:%.*]] = getelementptr inbounds ptr, ptr [[TMP237]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP239:%.*]] = getelementptr inbounds i32, ptr [[TMP238]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP240:%.*]] = getelementptr inbounds i1, ptr [[TMP239]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP241:%.*]] = getelementptr inbounds ptr, ptr [[TMP240]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP242:%.*]] = getelementptr inbounds ptr, ptr [[TMP241]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP243:%.*]] = getelementptr inbounds double, ptr [[TMP242]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP243]], align 8, !invariant.group [[META68]]
; CHECK-NEXT:    [[TMP244:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP245:%.*]] = getelementptr inbounds i64, ptr [[TMP244]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP246:%.*]] = getelementptr inbounds ptr, ptr [[TMP245]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP247:%.*]] = getelementptr inbounds i32, ptr [[TMP246]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP248:%.*]] = getelementptr inbounds i1, ptr [[TMP247]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP249:%.*]] = getelementptr inbounds ptr, ptr [[TMP248]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP250:%.*]] = getelementptr inbounds ptr, ptr [[TMP249]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr inbounds double, ptr [[TMP250]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr inbounds i32, ptr [[TMP251]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP252]], align 4, !invariant.group [[META69]]
; CHECK-NEXT:    [[TMP253:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP254:%.*]] = getelementptr inbounds i64, ptr [[TMP253]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP255:%.*]] = getelementptr inbounds ptr, ptr [[TMP254]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr inbounds i32, ptr [[TMP255]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr inbounds i1, ptr [[TMP256]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP258:%.*]] = getelementptr inbounds ptr, ptr [[TMP257]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr inbounds ptr, ptr [[TMP258]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr inbounds double, ptr [[TMP259]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP261:%.*]] = getelementptr inbounds i32, ptr [[TMP260]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP262:%.*]] = getelementptr inbounds i32, ptr [[TMP261]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP262]], align 4, !invariant.group [[META70]]
; CHECK-NEXT:    [[TMP263:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP264:%.*]] = getelementptr inbounds i64, ptr [[TMP263]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP265:%.*]] = getelementptr inbounds ptr, ptr [[TMP264]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP266:%.*]] = getelementptr inbounds i32, ptr [[TMP265]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP267:%.*]] = getelementptr inbounds i1, ptr [[TMP266]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP268:%.*]] = getelementptr inbounds ptr, ptr [[TMP267]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP269:%.*]] = getelementptr inbounds ptr, ptr [[TMP268]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP270:%.*]] = getelementptr inbounds double, ptr [[TMP269]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP271:%.*]] = getelementptr inbounds i32, ptr [[TMP270]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP272:%.*]] = getelementptr inbounds i32, ptr [[TMP271]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP273:%.*]] = getelementptr inbounds double, ptr [[TMP272]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP273]], align 8, !invariant.group [[META71]]
; CHECK-NEXT:    [[TMP274:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP275:%.*]] = getelementptr inbounds i64, ptr [[TMP274]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP276:%.*]] = getelementptr inbounds ptr, ptr [[TMP275]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP277:%.*]] = getelementptr inbounds i32, ptr [[TMP276]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP278:%.*]] = getelementptr inbounds i1, ptr [[TMP277]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP279:%.*]] = getelementptr inbounds ptr, ptr [[TMP278]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP280:%.*]] = getelementptr inbounds ptr, ptr [[TMP279]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP281:%.*]] = getelementptr inbounds double, ptr [[TMP280]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP282:%.*]] = getelementptr inbounds i32, ptr [[TMP281]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP283:%.*]] = getelementptr inbounds i32, ptr [[TMP282]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP284:%.*]] = getelementptr inbounds double, ptr [[TMP283]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP285:%.*]] = getelementptr inbounds double, ptr [[TMP284]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP285]], align 8, !invariant.group [[META72]]
; CHECK-NEXT:    [[TMP286:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP287:%.*]] = getelementptr inbounds i64, ptr [[TMP286]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP288:%.*]] = getelementptr inbounds ptr, ptr [[TMP287]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP289:%.*]] = getelementptr inbounds i32, ptr [[TMP288]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP290:%.*]] = getelementptr inbounds i1, ptr [[TMP289]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP291:%.*]] = getelementptr inbounds ptr, ptr [[TMP290]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP292:%.*]] = getelementptr inbounds ptr, ptr [[TMP291]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP293:%.*]] = getelementptr inbounds double, ptr [[TMP292]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP294:%.*]] = getelementptr inbounds i32, ptr [[TMP293]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP295:%.*]] = getelementptr inbounds i32, ptr [[TMP294]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP296:%.*]] = getelementptr inbounds double, ptr [[TMP295]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP297:%.*]] = getelementptr inbounds double, ptr [[TMP296]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP298:%.*]] = getelementptr inbounds double, ptr [[TMP297]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP298]], align 8, !invariant.group [[META73]]
; CHECK-NEXT:    [[TMP299:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP300:%.*]] = getelementptr inbounds i64, ptr [[TMP299]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP301:%.*]] = getelementptr inbounds ptr, ptr [[TMP300]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP302:%.*]] = getelementptr inbounds i32, ptr [[TMP301]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP303:%.*]] = getelementptr inbounds i1, ptr [[TMP302]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP304:%.*]] = getelementptr inbounds ptr, ptr [[TMP303]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP305:%.*]] = getelementptr inbounds ptr, ptr [[TMP304]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP306:%.*]] = getelementptr inbounds double, ptr [[TMP305]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP307:%.*]] = getelementptr inbounds i32, ptr [[TMP306]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP308:%.*]] = getelementptr inbounds i32, ptr [[TMP307]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP309:%.*]] = getelementptr inbounds double, ptr [[TMP308]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP310:%.*]] = getelementptr inbounds double, ptr [[TMP309]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP311:%.*]] = getelementptr inbounds double, ptr [[TMP310]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP312:%.*]] = getelementptr inbounds double, ptr [[TMP311]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP312]], align 8, !invariant.group [[META74]]
; CHECK-NEXT:    [[TMP313:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP314:%.*]] = getelementptr inbounds i64, ptr [[TMP313]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP315:%.*]] = getelementptr inbounds ptr, ptr [[TMP314]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP316:%.*]] = getelementptr inbounds i32, ptr [[TMP315]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP317:%.*]] = getelementptr inbounds i1, ptr [[TMP316]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP318:%.*]] = getelementptr inbounds ptr, ptr [[TMP317]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP319:%.*]] = getelementptr inbounds ptr, ptr [[TMP318]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP320:%.*]] = getelementptr inbounds double, ptr [[TMP319]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP321:%.*]] = getelementptr inbounds i32, ptr [[TMP320]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP322:%.*]] = getelementptr inbounds i32, ptr [[TMP321]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP323:%.*]] = getelementptr inbounds double, ptr [[TMP322]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP324:%.*]] = getelementptr inbounds double, ptr [[TMP323]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP325:%.*]] = getelementptr inbounds double, ptr [[TMP324]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP326:%.*]] = getelementptr inbounds double, ptr [[TMP325]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP327:%.*]] = getelementptr inbounds double, ptr [[TMP326]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP327]], align 8, !invariant.group [[META75]]
; CHECK-NEXT:    [[TMP328:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP329:%.*]] = getelementptr inbounds i64, ptr [[TMP328]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP330:%.*]] = getelementptr inbounds ptr, ptr [[TMP329]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP331:%.*]] = getelementptr inbounds i32, ptr [[TMP330]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP332:%.*]] = getelementptr inbounds i1, ptr [[TMP331]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP333:%.*]] = getelementptr inbounds ptr, ptr [[TMP332]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP334:%.*]] = getelementptr inbounds ptr, ptr [[TMP333]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP335:%.*]] = getelementptr inbounds double, ptr [[TMP334]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP336:%.*]] = getelementptr inbounds i32, ptr [[TMP335]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP337:%.*]] = getelementptr inbounds i32, ptr [[TMP336]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP338:%.*]] = getelementptr inbounds double, ptr [[TMP337]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP339:%.*]] = getelementptr inbounds double, ptr [[TMP338]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP340:%.*]] = getelementptr inbounds double, ptr [[TMP339]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP341:%.*]] = getelementptr inbounds double, ptr [[TMP340]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP342:%.*]] = getelementptr inbounds double, ptr [[TMP341]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP343:%.*]] = getelementptr inbounds i32, ptr [[TMP342]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 1, ptr [[TMP343]], align 4, !invariant.group [[META76]]
; CHECK-NEXT:    [[TMP344:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP345:%.*]] = getelementptr inbounds i64, ptr [[TMP344]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP346:%.*]] = getelementptr inbounds ptr, ptr [[TMP345]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP347:%.*]] = getelementptr inbounds i32, ptr [[TMP346]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP348:%.*]] = getelementptr inbounds i1, ptr [[TMP347]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP349:%.*]] = getelementptr inbounds ptr, ptr [[TMP348]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP350:%.*]] = getelementptr inbounds ptr, ptr [[TMP349]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP351:%.*]] = getelementptr inbounds double, ptr [[TMP350]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP352:%.*]] = getelementptr inbounds i32, ptr [[TMP351]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP353:%.*]] = getelementptr inbounds i32, ptr [[TMP352]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP354:%.*]] = getelementptr inbounds double, ptr [[TMP353]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP355:%.*]] = getelementptr inbounds double, ptr [[TMP354]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP356:%.*]] = getelementptr inbounds double, ptr [[TMP355]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP357:%.*]] = getelementptr inbounds double, ptr [[TMP356]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP358:%.*]] = getelementptr inbounds double, ptr [[TMP357]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP359:%.*]] = getelementptr inbounds i32, ptr [[TMP358]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP360:%.*]] = getelementptr inbounds ptr, ptr [[TMP359]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP360]], align 8, !invariant.group [[META77]]
; CHECK-NEXT:    [[TMP361:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP362:%.*]] = getelementptr inbounds i64, ptr [[TMP361]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP363:%.*]] = getelementptr inbounds ptr, ptr [[TMP362]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP364:%.*]] = getelementptr inbounds i32, ptr [[TMP363]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP365:%.*]] = getelementptr inbounds i1, ptr [[TMP364]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP366:%.*]] = getelementptr inbounds ptr, ptr [[TMP365]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP367:%.*]] = getelementptr inbounds ptr, ptr [[TMP366]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP368:%.*]] = getelementptr inbounds double, ptr [[TMP367]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP369:%.*]] = getelementptr inbounds i32, ptr [[TMP368]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP370:%.*]] = getelementptr inbounds i32, ptr [[TMP369]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP371:%.*]] = getelementptr inbounds double, ptr [[TMP370]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP372:%.*]] = getelementptr inbounds double, ptr [[TMP371]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP373:%.*]] = getelementptr inbounds double, ptr [[TMP372]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP374:%.*]] = getelementptr inbounds double, ptr [[TMP373]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP375:%.*]] = getelementptr inbounds double, ptr [[TMP374]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP376:%.*]] = getelementptr inbounds i32, ptr [[TMP375]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP377:%.*]] = getelementptr inbounds ptr, ptr [[TMP376]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP378:%.*]] = getelementptr inbounds ptr, ptr [[TMP377]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP378]], align 8, !invariant.group [[META78]]
; CHECK-NEXT:    [[TMP379:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP380:%.*]] = getelementptr inbounds i64, ptr [[TMP379]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP381:%.*]] = getelementptr inbounds ptr, ptr [[TMP380]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP382:%.*]] = getelementptr inbounds i32, ptr [[TMP381]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP383:%.*]] = getelementptr inbounds i1, ptr [[TMP382]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP384:%.*]] = getelementptr inbounds ptr, ptr [[TMP383]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP385:%.*]] = getelementptr inbounds ptr, ptr [[TMP384]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP386:%.*]] = getelementptr inbounds double, ptr [[TMP385]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP387:%.*]] = getelementptr inbounds i32, ptr [[TMP386]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP388:%.*]] = getelementptr inbounds i32, ptr [[TMP387]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP389:%.*]] = getelementptr inbounds double, ptr [[TMP388]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP390:%.*]] = getelementptr inbounds double, ptr [[TMP389]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP391:%.*]] = getelementptr inbounds double, ptr [[TMP390]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP392:%.*]] = getelementptr inbounds double, ptr [[TMP391]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP393:%.*]] = getelementptr inbounds double, ptr [[TMP392]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP394:%.*]] = getelementptr inbounds i32, ptr [[TMP393]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP395:%.*]] = getelementptr inbounds ptr, ptr [[TMP394]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP396:%.*]] = getelementptr inbounds ptr, ptr [[TMP395]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP397:%.*]] = getelementptr inbounds ptr, ptr [[TMP396]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP397]], align 8, !invariant.group [[META79]]
; CHECK-NEXT:    [[TMP398:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP399:%.*]] = getelementptr inbounds i64, ptr [[TMP398]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP400:%.*]] = getelementptr inbounds ptr, ptr [[TMP399]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP401:%.*]] = getelementptr inbounds i32, ptr [[TMP400]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP402:%.*]] = getelementptr inbounds i1, ptr [[TMP401]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP403:%.*]] = getelementptr inbounds ptr, ptr [[TMP402]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP404:%.*]] = getelementptr inbounds ptr, ptr [[TMP403]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP405:%.*]] = getelementptr inbounds double, ptr [[TMP404]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP406:%.*]] = getelementptr inbounds i32, ptr [[TMP405]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP407:%.*]] = getelementptr inbounds i32, ptr [[TMP406]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP408:%.*]] = getelementptr inbounds double, ptr [[TMP407]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP409:%.*]] = getelementptr inbounds double, ptr [[TMP408]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP410:%.*]] = getelementptr inbounds double, ptr [[TMP409]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP411:%.*]] = getelementptr inbounds double, ptr [[TMP410]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP412:%.*]] = getelementptr inbounds double, ptr [[TMP411]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP413:%.*]] = getelementptr inbounds i32, ptr [[TMP412]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP414:%.*]] = getelementptr inbounds ptr, ptr [[TMP413]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP415:%.*]] = getelementptr inbounds ptr, ptr [[TMP414]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP416:%.*]] = getelementptr inbounds ptr, ptr [[TMP415]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP417:%.*]] = getelementptr inbounds i64, ptr [[TMP416]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP417]], align 8, !invariant.group [[META80]]
; CHECK-NEXT:    [[TMP418:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP419:%.*]] = getelementptr inbounds i64, ptr [[TMP418]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP420:%.*]] = getelementptr inbounds ptr, ptr [[TMP419]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP421:%.*]] = getelementptr inbounds i32, ptr [[TMP420]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP422:%.*]] = getelementptr inbounds i1, ptr [[TMP421]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP423:%.*]] = getelementptr inbounds ptr, ptr [[TMP422]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP424:%.*]] = getelementptr inbounds ptr, ptr [[TMP423]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP425:%.*]] = getelementptr inbounds double, ptr [[TMP424]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP426:%.*]] = getelementptr inbounds i32, ptr [[TMP425]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP427:%.*]] = getelementptr inbounds i32, ptr [[TMP426]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP428:%.*]] = getelementptr inbounds double, ptr [[TMP427]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP429:%.*]] = getelementptr inbounds double, ptr [[TMP428]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP430:%.*]] = getelementptr inbounds double, ptr [[TMP429]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP431:%.*]] = getelementptr inbounds double, ptr [[TMP430]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP432:%.*]] = getelementptr inbounds double, ptr [[TMP431]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP433:%.*]] = getelementptr inbounds i32, ptr [[TMP432]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP434:%.*]] = getelementptr inbounds ptr, ptr [[TMP433]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP435:%.*]] = getelementptr inbounds ptr, ptr [[TMP434]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP436:%.*]] = getelementptr inbounds ptr, ptr [[TMP435]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP437:%.*]] = getelementptr inbounds i64, ptr [[TMP436]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP438:%.*]] = getelementptr inbounds i64, ptr [[TMP437]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP438]], align 8, !invariant.group [[META81]]
; CHECK-NEXT:    [[TMP439:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP440:%.*]] = getelementptr inbounds i64, ptr [[TMP439]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP441:%.*]] = getelementptr inbounds ptr, ptr [[TMP440]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP442:%.*]] = getelementptr inbounds i32, ptr [[TMP441]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP443:%.*]] = getelementptr inbounds i1, ptr [[TMP442]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP444:%.*]] = getelementptr inbounds ptr, ptr [[TMP443]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP445:%.*]] = getelementptr inbounds ptr, ptr [[TMP444]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP446:%.*]] = getelementptr inbounds double, ptr [[TMP445]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP447:%.*]] = getelementptr inbounds i32, ptr [[TMP446]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP448:%.*]] = getelementptr inbounds i32, ptr [[TMP447]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP449:%.*]] = getelementptr inbounds double, ptr [[TMP448]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP450:%.*]] = getelementptr inbounds double, ptr [[TMP449]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP451:%.*]] = getelementptr inbounds double, ptr [[TMP450]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP452:%.*]] = getelementptr inbounds double, ptr [[TMP451]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP453:%.*]] = getelementptr inbounds double, ptr [[TMP452]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP454:%.*]] = getelementptr inbounds i32, ptr [[TMP453]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP455:%.*]] = getelementptr inbounds ptr, ptr [[TMP454]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP456:%.*]] = getelementptr inbounds ptr, ptr [[TMP455]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP457:%.*]] = getelementptr inbounds ptr, ptr [[TMP456]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP458:%.*]] = getelementptr inbounds i64, ptr [[TMP457]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP459:%.*]] = getelementptr inbounds i64, ptr [[TMP458]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP460:%.*]] = getelementptr inbounds i32, ptr [[TMP459]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP460]], align 4, !invariant.group [[META82]]
; CHECK-NEXT:    [[TMP461:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP462:%.*]] = getelementptr inbounds i64, ptr [[TMP461]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP463:%.*]] = getelementptr inbounds ptr, ptr [[TMP462]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP464:%.*]] = getelementptr inbounds i32, ptr [[TMP463]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP465:%.*]] = getelementptr inbounds i1, ptr [[TMP464]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP466:%.*]] = getelementptr inbounds ptr, ptr [[TMP465]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP467:%.*]] = getelementptr inbounds ptr, ptr [[TMP466]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP468:%.*]] = getelementptr inbounds double, ptr [[TMP467]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP469:%.*]] = getelementptr inbounds i32, ptr [[TMP468]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP470:%.*]] = getelementptr inbounds i32, ptr [[TMP469]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP471:%.*]] = getelementptr inbounds double, ptr [[TMP470]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP472:%.*]] = getelementptr inbounds double, ptr [[TMP471]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP473:%.*]] = getelementptr inbounds double, ptr [[TMP472]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP474:%.*]] = getelementptr inbounds double, ptr [[TMP473]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP475:%.*]] = getelementptr inbounds double, ptr [[TMP474]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP476:%.*]] = getelementptr inbounds i32, ptr [[TMP475]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP477:%.*]] = getelementptr inbounds ptr, ptr [[TMP476]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP478:%.*]] = getelementptr inbounds ptr, ptr [[TMP477]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP479:%.*]] = getelementptr inbounds ptr, ptr [[TMP478]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP480:%.*]] = getelementptr inbounds i64, ptr [[TMP479]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP481:%.*]] = getelementptr inbounds i64, ptr [[TMP480]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP482:%.*]] = getelementptr inbounds i32, ptr [[TMP481]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP483:%.*]] = getelementptr inbounds i32, ptr [[TMP482]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP483]], align 4, !invariant.group [[META83]]
; CHECK-NEXT:    [[TMP484:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP485:%.*]] = getelementptr inbounds i64, ptr [[TMP484]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP486:%.*]] = getelementptr inbounds ptr, ptr [[TMP485]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP487:%.*]] = getelementptr inbounds i32, ptr [[TMP486]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP488:%.*]] = getelementptr inbounds i1, ptr [[TMP487]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP489:%.*]] = getelementptr inbounds ptr, ptr [[TMP488]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP490:%.*]] = getelementptr inbounds ptr, ptr [[TMP489]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP491:%.*]] = getelementptr inbounds double, ptr [[TMP490]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP492:%.*]] = getelementptr inbounds i32, ptr [[TMP491]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP493:%.*]] = getelementptr inbounds i32, ptr [[TMP492]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP494:%.*]] = getelementptr inbounds double, ptr [[TMP493]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP495:%.*]] = getelementptr inbounds double, ptr [[TMP494]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP496:%.*]] = getelementptr inbounds double, ptr [[TMP495]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP497:%.*]] = getelementptr inbounds double, ptr [[TMP496]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP498:%.*]] = getelementptr inbounds double, ptr [[TMP497]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP499:%.*]] = getelementptr inbounds i32, ptr [[TMP498]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP500:%.*]] = getelementptr inbounds ptr, ptr [[TMP499]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP501:%.*]] = getelementptr inbounds ptr, ptr [[TMP500]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP502:%.*]] = getelementptr inbounds ptr, ptr [[TMP501]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP503:%.*]] = getelementptr inbounds i64, ptr [[TMP502]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP504:%.*]] = getelementptr inbounds i64, ptr [[TMP503]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP505:%.*]] = getelementptr inbounds i32, ptr [[TMP504]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP506:%.*]] = getelementptr inbounds i32, ptr [[TMP505]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP507:%.*]] = getelementptr inbounds i32, ptr [[TMP506]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP507]], align 4, !invariant.group [[META84]]
; CHECK-NEXT:    [[TMP508:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP509:%.*]] = getelementptr inbounds i64, ptr [[TMP508]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP510:%.*]] = getelementptr inbounds ptr, ptr [[TMP509]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP511:%.*]] = getelementptr inbounds i32, ptr [[TMP510]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP512:%.*]] = getelementptr inbounds i1, ptr [[TMP511]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP513:%.*]] = getelementptr inbounds ptr, ptr [[TMP512]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP514:%.*]] = getelementptr inbounds ptr, ptr [[TMP513]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP515:%.*]] = getelementptr inbounds double, ptr [[TMP514]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP516:%.*]] = getelementptr inbounds i32, ptr [[TMP515]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP517:%.*]] = getelementptr inbounds i32, ptr [[TMP516]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP518:%.*]] = getelementptr inbounds double, ptr [[TMP517]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP519:%.*]] = getelementptr inbounds double, ptr [[TMP518]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP520:%.*]] = getelementptr inbounds double, ptr [[TMP519]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP521:%.*]] = getelementptr inbounds double, ptr [[TMP520]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP522:%.*]] = getelementptr inbounds double, ptr [[TMP521]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP523:%.*]] = getelementptr inbounds i32, ptr [[TMP522]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP524:%.*]] = getelementptr inbounds ptr, ptr [[TMP523]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP525:%.*]] = getelementptr inbounds ptr, ptr [[TMP524]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP526:%.*]] = getelementptr inbounds ptr, ptr [[TMP525]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP527:%.*]] = getelementptr inbounds i64, ptr [[TMP526]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP528:%.*]] = getelementptr inbounds i64, ptr [[TMP527]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP529:%.*]] = getelementptr inbounds i32, ptr [[TMP528]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP530:%.*]] = getelementptr inbounds i32, ptr [[TMP529]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP531:%.*]] = getelementptr inbounds i32, ptr [[TMP530]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP532:%.*]] = getelementptr inbounds i32, ptr [[TMP531]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP532]], align 4, !invariant.group [[META85]]
; CHECK-NEXT:    [[TMP533:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP534:%.*]] = getelementptr inbounds i64, ptr [[TMP533]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP535:%.*]] = getelementptr inbounds ptr, ptr [[TMP534]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP536:%.*]] = getelementptr inbounds i32, ptr [[TMP535]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP537:%.*]] = getelementptr inbounds i1, ptr [[TMP536]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP538:%.*]] = getelementptr inbounds ptr, ptr [[TMP537]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP539:%.*]] = getelementptr inbounds ptr, ptr [[TMP538]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP540:%.*]] = getelementptr inbounds double, ptr [[TMP539]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP541:%.*]] = getelementptr inbounds i32, ptr [[TMP540]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP542:%.*]] = getelementptr inbounds i32, ptr [[TMP541]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP543:%.*]] = getelementptr inbounds double, ptr [[TMP542]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP544:%.*]] = getelementptr inbounds double, ptr [[TMP543]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP545:%.*]] = getelementptr inbounds double, ptr [[TMP544]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP546:%.*]] = getelementptr inbounds double, ptr [[TMP545]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP547:%.*]] = getelementptr inbounds double, ptr [[TMP546]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP548:%.*]] = getelementptr inbounds i32, ptr [[TMP547]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP549:%.*]] = getelementptr inbounds ptr, ptr [[TMP548]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP550:%.*]] = getelementptr inbounds ptr, ptr [[TMP549]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP551:%.*]] = getelementptr inbounds ptr, ptr [[TMP550]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP552:%.*]] = getelementptr inbounds i64, ptr [[TMP551]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP553:%.*]] = getelementptr inbounds i64, ptr [[TMP552]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP554:%.*]] = getelementptr inbounds i32, ptr [[TMP553]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP555:%.*]] = getelementptr inbounds i32, ptr [[TMP554]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP556:%.*]] = getelementptr inbounds i32, ptr [[TMP555]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP557:%.*]] = getelementptr inbounds i32, ptr [[TMP556]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP558:%.*]] = getelementptr inbounds i32, ptr [[TMP557]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP558]], align 4, !invariant.group [[META86]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       CacheRemat1:
; CHECK-NEXT:    [[TMP559:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP560:%.*]] = load ptr, ptr [[TMP559]], align 8
; CHECK-NEXT:    [[TMP561:%.*]] = getelementptr inbounds ptr, ptr [[TMP560]], i32 4
; CHECK-NEXT:    [[CACHE_IN_PTR35:%.*]] = load ptr, ptr [[TMP561]], align 8
; CHECK-NEXT:    [[TMP562:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_IN_OFFSET36:%.*]] = load i32, ptr [[TMP562]], align 4
; CHECK-NEXT:    [[TMP563:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[GTID31]]
; CHECK-NEXT:    [[I10_CACHE37:%.*]] = load i32, ptr [[TMP563]], align 4, !invariant.group [[META61]]
; CHECK-NEXT:    [[TMP564:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP565:%.*]] = getelementptr inbounds i64, ptr [[TMP564]], i32 [[GTID31]]
; CHECK-NEXT:    [[I70_CACHE38:%.*]] = load i64, ptr [[TMP565]], align 8, !invariant.group [[META62]]
; CHECK-NEXT:    [[TMP566:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP567:%.*]] = getelementptr inbounds i64, ptr [[TMP566]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP568:%.*]] = getelementptr inbounds ptr, ptr [[TMP567]], i32 [[GTID31]]
; CHECK-NEXT:    [[I142_CACHE:%.*]] = load ptr, ptr [[TMP568]], align 8, !invariant.group [[META63]]
; CHECK-NEXT:    [[TMP569:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP570:%.*]] = getelementptr inbounds i64, ptr [[TMP569]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP571:%.*]] = getelementptr inbounds ptr, ptr [[TMP570]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP572:%.*]] = getelementptr inbounds i32, ptr [[TMP571]], i32 [[GTID31]]
; CHECK-NEXT:    [[I146_CACHE:%.*]] = load i32, ptr [[TMP572]], align 4, !invariant.group [[META64]]
; CHECK-NEXT:    [[TMP573:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP574:%.*]] = getelementptr inbounds i64, ptr [[TMP573]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP575:%.*]] = getelementptr inbounds ptr, ptr [[TMP574]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP576:%.*]] = getelementptr inbounds i32, ptr [[TMP575]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP577:%.*]] = getelementptr inbounds i1, ptr [[TMP576]], i32 [[GTID31]]
; CHECK-NEXT:    [[I153_CACHE:%.*]] = load i1, ptr [[TMP577]], align 1, !invariant.group [[META65]]
; CHECK-NEXT:    [[TMP578:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP579:%.*]] = getelementptr inbounds i64, ptr [[TMP578]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP580:%.*]] = getelementptr inbounds ptr, ptr [[TMP579]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP581:%.*]] = getelementptr inbounds i32, ptr [[TMP580]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP582:%.*]] = getelementptr inbounds i1, ptr [[TMP581]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP583:%.*]] = getelementptr inbounds ptr, ptr [[TMP582]], i32 [[GTID31]]
; CHECK-NEXT:    [[I148_CACHE:%.*]] = load ptr, ptr [[TMP583]], align 8, !invariant.group [[META66]]
; CHECK-NEXT:    [[TMP584:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP585:%.*]] = getelementptr inbounds i64, ptr [[TMP584]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP586:%.*]] = getelementptr inbounds ptr, ptr [[TMP585]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP587:%.*]] = getelementptr inbounds i32, ptr [[TMP586]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP588:%.*]] = getelementptr inbounds i1, ptr [[TMP587]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP589:%.*]] = getelementptr inbounds ptr, ptr [[TMP588]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP590:%.*]] = getelementptr inbounds ptr, ptr [[TMP589]], i32 [[GTID31]]
; CHECK-NEXT:    [[I156_CACHE:%.*]] = load ptr, ptr [[TMP590]], align 8, !invariant.group [[META67]]
; CHECK-NEXT:    [[TMP591:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP592:%.*]] = getelementptr inbounds i64, ptr [[TMP591]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP593:%.*]] = getelementptr inbounds ptr, ptr [[TMP592]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP594:%.*]] = getelementptr inbounds i32, ptr [[TMP593]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP595:%.*]] = getelementptr inbounds i1, ptr [[TMP594]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP596:%.*]] = getelementptr inbounds ptr, ptr [[TMP595]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP597:%.*]] = getelementptr inbounds ptr, ptr [[TMP596]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP598:%.*]] = getelementptr inbounds double, ptr [[TMP597]], i32 [[GTID31]]
; CHECK-NEXT:    [[I171_CACHE:%.*]] = load double, ptr [[TMP598]], align 8, !invariant.group [[META68]]
; CHECK-NEXT:    [[TMP599:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP600:%.*]] = getelementptr inbounds i64, ptr [[TMP599]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP601:%.*]] = getelementptr inbounds ptr, ptr [[TMP600]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP602:%.*]] = getelementptr inbounds i32, ptr [[TMP601]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP603:%.*]] = getelementptr inbounds i1, ptr [[TMP602]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP604:%.*]] = getelementptr inbounds ptr, ptr [[TMP603]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP605:%.*]] = getelementptr inbounds ptr, ptr [[TMP604]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP606:%.*]] = getelementptr inbounds double, ptr [[TMP605]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP607:%.*]] = getelementptr inbounds i32, ptr [[TMP606]], i32 [[GTID31]]
; CHECK-NEXT:    [[I169_CACHE:%.*]] = load i32, ptr [[TMP607]], align 4, !invariant.group [[META69]]
; CHECK-NEXT:    [[TMP608:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP609:%.*]] = getelementptr inbounds i64, ptr [[TMP608]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP610:%.*]] = getelementptr inbounds ptr, ptr [[TMP609]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP611:%.*]] = getelementptr inbounds i32, ptr [[TMP610]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP612:%.*]] = getelementptr inbounds i1, ptr [[TMP611]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP613:%.*]] = getelementptr inbounds ptr, ptr [[TMP612]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP614:%.*]] = getelementptr inbounds ptr, ptr [[TMP613]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP615:%.*]] = getelementptr inbounds double, ptr [[TMP614]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP616:%.*]] = getelementptr inbounds i32, ptr [[TMP615]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP617:%.*]] = getelementptr inbounds i32, ptr [[TMP616]], i32 [[GTID31]]
; CHECK-NEXT:    [[I165_CACHE:%.*]] = load i32, ptr [[TMP617]], align 4, !invariant.group [[META70]]
; CHECK-NEXT:    [[TMP618:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP619:%.*]] = getelementptr inbounds i64, ptr [[TMP618]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP620:%.*]] = getelementptr inbounds ptr, ptr [[TMP619]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP621:%.*]] = getelementptr inbounds i32, ptr [[TMP620]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP622:%.*]] = getelementptr inbounds i1, ptr [[TMP621]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP623:%.*]] = getelementptr inbounds ptr, ptr [[TMP622]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP624:%.*]] = getelementptr inbounds ptr, ptr [[TMP623]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP625:%.*]] = getelementptr inbounds double, ptr [[TMP624]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP626:%.*]] = getelementptr inbounds i32, ptr [[TMP625]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP627:%.*]] = getelementptr inbounds i32, ptr [[TMP626]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP628:%.*]] = getelementptr inbounds double, ptr [[TMP627]], i32 [[GTID31]]
; CHECK-NEXT:    [[I164_CACHE:%.*]] = load double, ptr [[TMP628]], align 8, !invariant.group [[META71]]
; CHECK-NEXT:    [[TMP629:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP630:%.*]] = getelementptr inbounds i64, ptr [[TMP629]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP631:%.*]] = getelementptr inbounds ptr, ptr [[TMP630]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP632:%.*]] = getelementptr inbounds i32, ptr [[TMP631]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP633:%.*]] = getelementptr inbounds i1, ptr [[TMP632]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP634:%.*]] = getelementptr inbounds ptr, ptr [[TMP633]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP635:%.*]] = getelementptr inbounds ptr, ptr [[TMP634]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP636:%.*]] = getelementptr inbounds double, ptr [[TMP635]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP637:%.*]] = getelementptr inbounds i32, ptr [[TMP636]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP638:%.*]] = getelementptr inbounds i32, ptr [[TMP637]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP639:%.*]] = getelementptr inbounds double, ptr [[TMP638]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP640:%.*]] = getelementptr inbounds double, ptr [[TMP639]], i32 [[GTID31]]
; CHECK-NEXT:    [[I163_CACHE:%.*]] = load double, ptr [[TMP640]], align 8, !invariant.group [[META72]]
; CHECK-NEXT:    [[TMP641:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP642:%.*]] = getelementptr inbounds i64, ptr [[TMP641]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP643:%.*]] = getelementptr inbounds ptr, ptr [[TMP642]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP644:%.*]] = getelementptr inbounds i32, ptr [[TMP643]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP645:%.*]] = getelementptr inbounds i1, ptr [[TMP644]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP646:%.*]] = getelementptr inbounds ptr, ptr [[TMP645]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP647:%.*]] = getelementptr inbounds ptr, ptr [[TMP646]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP648:%.*]] = getelementptr inbounds double, ptr [[TMP647]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP649:%.*]] = getelementptr inbounds i32, ptr [[TMP648]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP650:%.*]] = getelementptr inbounds i32, ptr [[TMP649]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP651:%.*]] = getelementptr inbounds double, ptr [[TMP650]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP652:%.*]] = getelementptr inbounds double, ptr [[TMP651]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP653:%.*]] = getelementptr inbounds double, ptr [[TMP652]], i32 [[GTID31]]
; CHECK-NEXT:    [[I162_CACHE:%.*]] = load double, ptr [[TMP653]], align 8, !invariant.group [[META73]]
; CHECK-NEXT:    [[TMP654:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP655:%.*]] = getelementptr inbounds i64, ptr [[TMP654]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP656:%.*]] = getelementptr inbounds ptr, ptr [[TMP655]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP657:%.*]] = getelementptr inbounds i32, ptr [[TMP656]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP658:%.*]] = getelementptr inbounds i1, ptr [[TMP657]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP659:%.*]] = getelementptr inbounds ptr, ptr [[TMP658]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP660:%.*]] = getelementptr inbounds ptr, ptr [[TMP659]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP661:%.*]] = getelementptr inbounds double, ptr [[TMP660]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP662:%.*]] = getelementptr inbounds i32, ptr [[TMP661]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP663:%.*]] = getelementptr inbounds i32, ptr [[TMP662]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP664:%.*]] = getelementptr inbounds double, ptr [[TMP663]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP665:%.*]] = getelementptr inbounds double, ptr [[TMP664]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP666:%.*]] = getelementptr inbounds double, ptr [[TMP665]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP667:%.*]] = getelementptr inbounds double, ptr [[TMP666]], i32 [[GTID31]]
; CHECK-NEXT:    [[I161_CACHE:%.*]] = load double, ptr [[TMP667]], align 8, !invariant.group [[META74]]
; CHECK-NEXT:    [[TMP668:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP669:%.*]] = getelementptr inbounds i64, ptr [[TMP668]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP670:%.*]] = getelementptr inbounds ptr, ptr [[TMP669]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP671:%.*]] = getelementptr inbounds i32, ptr [[TMP670]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP672:%.*]] = getelementptr inbounds i1, ptr [[TMP671]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP673:%.*]] = getelementptr inbounds ptr, ptr [[TMP672]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP674:%.*]] = getelementptr inbounds ptr, ptr [[TMP673]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP675:%.*]] = getelementptr inbounds double, ptr [[TMP674]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP676:%.*]] = getelementptr inbounds i32, ptr [[TMP675]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP677:%.*]] = getelementptr inbounds i32, ptr [[TMP676]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP678:%.*]] = getelementptr inbounds double, ptr [[TMP677]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP679:%.*]] = getelementptr inbounds double, ptr [[TMP678]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP680:%.*]] = getelementptr inbounds double, ptr [[TMP679]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP681:%.*]] = getelementptr inbounds double, ptr [[TMP680]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP682:%.*]] = getelementptr inbounds double, ptr [[TMP681]], i32 [[GTID31]]
; CHECK-NEXT:    [[I160_CACHE:%.*]] = load double, ptr [[TMP682]], align 8, !invariant.group [[META75]]
; CHECK-NEXT:    [[TMP683:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP684:%.*]] = getelementptr inbounds i64, ptr [[TMP683]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP685:%.*]] = getelementptr inbounds ptr, ptr [[TMP684]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP686:%.*]] = getelementptr inbounds i32, ptr [[TMP685]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP687:%.*]] = getelementptr inbounds i1, ptr [[TMP686]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP688:%.*]] = getelementptr inbounds ptr, ptr [[TMP687]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP689:%.*]] = getelementptr inbounds ptr, ptr [[TMP688]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP690:%.*]] = getelementptr inbounds double, ptr [[TMP689]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP691:%.*]] = getelementptr inbounds i32, ptr [[TMP690]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP692:%.*]] = getelementptr inbounds i32, ptr [[TMP691]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP693:%.*]] = getelementptr inbounds double, ptr [[TMP692]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP694:%.*]] = getelementptr inbounds double, ptr [[TMP693]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP695:%.*]] = getelementptr inbounds double, ptr [[TMP694]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP696:%.*]] = getelementptr inbounds double, ptr [[TMP695]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP697:%.*]] = getelementptr inbounds double, ptr [[TMP696]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP698:%.*]] = getelementptr inbounds i32, ptr [[TMP697]], i32 [[GTID31]]
; CHECK-NEXT:    [[I113_CACHE39:%.*]] = load i32, ptr [[TMP698]], align 4, !invariant.group [[META76]]
; CHECK-NEXT:    [[TMP699:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP700:%.*]] = getelementptr inbounds i64, ptr [[TMP699]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP701:%.*]] = getelementptr inbounds ptr, ptr [[TMP700]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP702:%.*]] = getelementptr inbounds i32, ptr [[TMP701]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP703:%.*]] = getelementptr inbounds i1, ptr [[TMP702]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP704:%.*]] = getelementptr inbounds ptr, ptr [[TMP703]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP705:%.*]] = getelementptr inbounds ptr, ptr [[TMP704]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP706:%.*]] = getelementptr inbounds double, ptr [[TMP705]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP707:%.*]] = getelementptr inbounds i32, ptr [[TMP706]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP708:%.*]] = getelementptr inbounds i32, ptr [[TMP707]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP709:%.*]] = getelementptr inbounds double, ptr [[TMP708]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP710:%.*]] = getelementptr inbounds double, ptr [[TMP709]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP711:%.*]] = getelementptr inbounds double, ptr [[TMP710]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP712:%.*]] = getelementptr inbounds double, ptr [[TMP711]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP713:%.*]] = getelementptr inbounds double, ptr [[TMP712]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP714:%.*]] = getelementptr inbounds i32, ptr [[TMP713]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP715:%.*]] = getelementptr inbounds ptr, ptr [[TMP714]], i32 [[GTID31]]
; CHECK-NEXT:    [[I112_CACHE40:%.*]] = load ptr, ptr [[TMP715]], align 8, !invariant.group [[META77]]
; CHECK-NEXT:    [[TMP716:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP717:%.*]] = getelementptr inbounds i64, ptr [[TMP716]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP718:%.*]] = getelementptr inbounds ptr, ptr [[TMP717]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP719:%.*]] = getelementptr inbounds i32, ptr [[TMP718]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP720:%.*]] = getelementptr inbounds i1, ptr [[TMP719]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP721:%.*]] = getelementptr inbounds ptr, ptr [[TMP720]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP722:%.*]] = getelementptr inbounds ptr, ptr [[TMP721]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP723:%.*]] = getelementptr inbounds double, ptr [[TMP722]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP724:%.*]] = getelementptr inbounds i32, ptr [[TMP723]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP725:%.*]] = getelementptr inbounds i32, ptr [[TMP724]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP726:%.*]] = getelementptr inbounds double, ptr [[TMP725]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP727:%.*]] = getelementptr inbounds double, ptr [[TMP726]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP728:%.*]] = getelementptr inbounds double, ptr [[TMP727]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP729:%.*]] = getelementptr inbounds double, ptr [[TMP728]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP730:%.*]] = getelementptr inbounds double, ptr [[TMP729]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP731:%.*]] = getelementptr inbounds i32, ptr [[TMP730]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP732:%.*]] = getelementptr inbounds ptr, ptr [[TMP731]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP733:%.*]] = getelementptr inbounds ptr, ptr [[TMP732]], i32 [[GTID31]]
; CHECK-NEXT:    [[I111_CACHE41:%.*]] = load ptr, ptr [[TMP733]], align 8, !invariant.group [[META78]]
; CHECK-NEXT:    [[TMP734:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP735:%.*]] = getelementptr inbounds i64, ptr [[TMP734]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP736:%.*]] = getelementptr inbounds ptr, ptr [[TMP735]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP737:%.*]] = getelementptr inbounds i32, ptr [[TMP736]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP738:%.*]] = getelementptr inbounds i1, ptr [[TMP737]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP739:%.*]] = getelementptr inbounds ptr, ptr [[TMP738]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP740:%.*]] = getelementptr inbounds ptr, ptr [[TMP739]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP741:%.*]] = getelementptr inbounds double, ptr [[TMP740]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP742:%.*]] = getelementptr inbounds i32, ptr [[TMP741]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP743:%.*]] = getelementptr inbounds i32, ptr [[TMP742]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP744:%.*]] = getelementptr inbounds double, ptr [[TMP743]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP745:%.*]] = getelementptr inbounds double, ptr [[TMP744]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP746:%.*]] = getelementptr inbounds double, ptr [[TMP745]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP747:%.*]] = getelementptr inbounds double, ptr [[TMP746]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP748:%.*]] = getelementptr inbounds double, ptr [[TMP747]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP749:%.*]] = getelementptr inbounds i32, ptr [[TMP748]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP750:%.*]] = getelementptr inbounds ptr, ptr [[TMP749]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP751:%.*]] = getelementptr inbounds ptr, ptr [[TMP750]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP752:%.*]] = getelementptr inbounds ptr, ptr [[TMP751]], i32 [[GTID31]]
; CHECK-NEXT:    [[I108_CACHE42:%.*]] = load ptr, ptr [[TMP752]], align 8, !invariant.group [[META79]]
; CHECK-NEXT:    [[TMP753:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP754:%.*]] = getelementptr inbounds i64, ptr [[TMP753]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP755:%.*]] = getelementptr inbounds ptr, ptr [[TMP754]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP756:%.*]] = getelementptr inbounds i32, ptr [[TMP755]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP757:%.*]] = getelementptr inbounds i1, ptr [[TMP756]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP758:%.*]] = getelementptr inbounds ptr, ptr [[TMP757]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP759:%.*]] = getelementptr inbounds ptr, ptr [[TMP758]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP760:%.*]] = getelementptr inbounds double, ptr [[TMP759]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP761:%.*]] = getelementptr inbounds i32, ptr [[TMP760]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP762:%.*]] = getelementptr inbounds i32, ptr [[TMP761]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP763:%.*]] = getelementptr inbounds double, ptr [[TMP762]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP764:%.*]] = getelementptr inbounds double, ptr [[TMP763]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP765:%.*]] = getelementptr inbounds double, ptr [[TMP764]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP766:%.*]] = getelementptr inbounds double, ptr [[TMP765]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP767:%.*]] = getelementptr inbounds double, ptr [[TMP766]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP768:%.*]] = getelementptr inbounds i32, ptr [[TMP767]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP769:%.*]] = getelementptr inbounds ptr, ptr [[TMP768]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP770:%.*]] = getelementptr inbounds ptr, ptr [[TMP769]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP771:%.*]] = getelementptr inbounds ptr, ptr [[TMP770]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP772:%.*]] = getelementptr inbounds i64, ptr [[TMP771]], i32 [[GTID31]]
; CHECK-NEXT:    [[I106_CACHE43:%.*]] = load i64, ptr [[TMP772]], align 8, !invariant.group [[META80]]
; CHECK-NEXT:    [[TMP773:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP774:%.*]] = getelementptr inbounds i64, ptr [[TMP773]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP775:%.*]] = getelementptr inbounds ptr, ptr [[TMP774]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP776:%.*]] = getelementptr inbounds i32, ptr [[TMP775]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP777:%.*]] = getelementptr inbounds i1, ptr [[TMP776]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP778:%.*]] = getelementptr inbounds ptr, ptr [[TMP777]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP779:%.*]] = getelementptr inbounds ptr, ptr [[TMP778]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP780:%.*]] = getelementptr inbounds double, ptr [[TMP779]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP781:%.*]] = getelementptr inbounds i32, ptr [[TMP780]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP782:%.*]] = getelementptr inbounds i32, ptr [[TMP781]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP783:%.*]] = getelementptr inbounds double, ptr [[TMP782]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP784:%.*]] = getelementptr inbounds double, ptr [[TMP783]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP785:%.*]] = getelementptr inbounds double, ptr [[TMP784]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP786:%.*]] = getelementptr inbounds double, ptr [[TMP785]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP787:%.*]] = getelementptr inbounds double, ptr [[TMP786]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP788:%.*]] = getelementptr inbounds i32, ptr [[TMP787]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP789:%.*]] = getelementptr inbounds ptr, ptr [[TMP788]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP790:%.*]] = getelementptr inbounds ptr, ptr [[TMP789]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP791:%.*]] = getelementptr inbounds ptr, ptr [[TMP790]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP792:%.*]] = getelementptr inbounds i64, ptr [[TMP791]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP793:%.*]] = getelementptr inbounds i64, ptr [[TMP792]], i32 [[GTID31]]
; CHECK-NEXT:    [[I40_CACHE44:%.*]] = load i64, ptr [[TMP793]], align 8, !invariant.group [[META81]]
; CHECK-NEXT:    [[TMP794:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP795:%.*]] = getelementptr inbounds i64, ptr [[TMP794]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP796:%.*]] = getelementptr inbounds ptr, ptr [[TMP795]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP797:%.*]] = getelementptr inbounds i32, ptr [[TMP796]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP798:%.*]] = getelementptr inbounds i1, ptr [[TMP797]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP799:%.*]] = getelementptr inbounds ptr, ptr [[TMP798]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP800:%.*]] = getelementptr inbounds ptr, ptr [[TMP799]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP801:%.*]] = getelementptr inbounds double, ptr [[TMP800]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP802:%.*]] = getelementptr inbounds i32, ptr [[TMP801]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP803:%.*]] = getelementptr inbounds i32, ptr [[TMP802]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP804:%.*]] = getelementptr inbounds double, ptr [[TMP803]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP805:%.*]] = getelementptr inbounds double, ptr [[TMP804]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP806:%.*]] = getelementptr inbounds double, ptr [[TMP805]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP807:%.*]] = getelementptr inbounds double, ptr [[TMP806]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP808:%.*]] = getelementptr inbounds double, ptr [[TMP807]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP809:%.*]] = getelementptr inbounds i32, ptr [[TMP808]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP810:%.*]] = getelementptr inbounds ptr, ptr [[TMP809]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP811:%.*]] = getelementptr inbounds ptr, ptr [[TMP810]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP812:%.*]] = getelementptr inbounds ptr, ptr [[TMP811]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP813:%.*]] = getelementptr inbounds i64, ptr [[TMP812]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP814:%.*]] = getelementptr inbounds i64, ptr [[TMP813]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP815:%.*]] = getelementptr inbounds i32, ptr [[TMP814]], i32 [[GTID31]]
; CHECK-NEXT:    [[I31_CACHE45:%.*]] = load i32, ptr [[TMP815]], align 4, !invariant.group [[META82]]
; CHECK-NEXT:    [[TMP816:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP817:%.*]] = getelementptr inbounds i64, ptr [[TMP816]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP818:%.*]] = getelementptr inbounds ptr, ptr [[TMP817]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP819:%.*]] = getelementptr inbounds i32, ptr [[TMP818]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP820:%.*]] = getelementptr inbounds i1, ptr [[TMP819]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP821:%.*]] = getelementptr inbounds ptr, ptr [[TMP820]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP822:%.*]] = getelementptr inbounds ptr, ptr [[TMP821]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP823:%.*]] = getelementptr inbounds double, ptr [[TMP822]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP824:%.*]] = getelementptr inbounds i32, ptr [[TMP823]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP825:%.*]] = getelementptr inbounds i32, ptr [[TMP824]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP826:%.*]] = getelementptr inbounds double, ptr [[TMP825]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP827:%.*]] = getelementptr inbounds double, ptr [[TMP826]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP828:%.*]] = getelementptr inbounds double, ptr [[TMP827]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP829:%.*]] = getelementptr inbounds double, ptr [[TMP828]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP830:%.*]] = getelementptr inbounds double, ptr [[TMP829]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP831:%.*]] = getelementptr inbounds i32, ptr [[TMP830]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP832:%.*]] = getelementptr inbounds ptr, ptr [[TMP831]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP833:%.*]] = getelementptr inbounds ptr, ptr [[TMP832]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP834:%.*]] = getelementptr inbounds ptr, ptr [[TMP833]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP835:%.*]] = getelementptr inbounds i64, ptr [[TMP834]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP836:%.*]] = getelementptr inbounds i64, ptr [[TMP835]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP837:%.*]] = getelementptr inbounds i32, ptr [[TMP836]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP838:%.*]] = getelementptr inbounds i32, ptr [[TMP837]], i32 [[GTID31]]
; CHECK-NEXT:    [[I30_CACHE46:%.*]] = load i32, ptr [[TMP838]], align 4, !invariant.group [[META83]]
; CHECK-NEXT:    [[TMP839:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP840:%.*]] = getelementptr inbounds i64, ptr [[TMP839]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP841:%.*]] = getelementptr inbounds ptr, ptr [[TMP840]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP842:%.*]] = getelementptr inbounds i32, ptr [[TMP841]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP843:%.*]] = getelementptr inbounds i1, ptr [[TMP842]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP844:%.*]] = getelementptr inbounds ptr, ptr [[TMP843]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP845:%.*]] = getelementptr inbounds ptr, ptr [[TMP844]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP846:%.*]] = getelementptr inbounds double, ptr [[TMP845]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP847:%.*]] = getelementptr inbounds i32, ptr [[TMP846]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP848:%.*]] = getelementptr inbounds i32, ptr [[TMP847]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP849:%.*]] = getelementptr inbounds double, ptr [[TMP848]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP850:%.*]] = getelementptr inbounds double, ptr [[TMP849]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP851:%.*]] = getelementptr inbounds double, ptr [[TMP850]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP852:%.*]] = getelementptr inbounds double, ptr [[TMP851]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP853:%.*]] = getelementptr inbounds double, ptr [[TMP852]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP854:%.*]] = getelementptr inbounds i32, ptr [[TMP853]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP855:%.*]] = getelementptr inbounds ptr, ptr [[TMP854]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP856:%.*]] = getelementptr inbounds ptr, ptr [[TMP855]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP857:%.*]] = getelementptr inbounds ptr, ptr [[TMP856]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP858:%.*]] = getelementptr inbounds i64, ptr [[TMP857]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP859:%.*]] = getelementptr inbounds i64, ptr [[TMP858]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP860:%.*]] = getelementptr inbounds i32, ptr [[TMP859]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP861:%.*]] = getelementptr inbounds i32, ptr [[TMP860]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP862:%.*]] = getelementptr inbounds i32, ptr [[TMP861]], i32 [[GTID31]]
; CHECK-NEXT:    [[I5_CACHE47:%.*]] = load i32, ptr [[TMP862]], align 4, !invariant.group [[META84]]
; CHECK-NEXT:    [[TMP863:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP864:%.*]] = getelementptr inbounds i64, ptr [[TMP863]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP865:%.*]] = getelementptr inbounds ptr, ptr [[TMP864]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP866:%.*]] = getelementptr inbounds i32, ptr [[TMP865]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP867:%.*]] = getelementptr inbounds i1, ptr [[TMP866]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP868:%.*]] = getelementptr inbounds ptr, ptr [[TMP867]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP869:%.*]] = getelementptr inbounds ptr, ptr [[TMP868]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP870:%.*]] = getelementptr inbounds double, ptr [[TMP869]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP871:%.*]] = getelementptr inbounds i32, ptr [[TMP870]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP872:%.*]] = getelementptr inbounds i32, ptr [[TMP871]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP873:%.*]] = getelementptr inbounds double, ptr [[TMP872]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP874:%.*]] = getelementptr inbounds double, ptr [[TMP873]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP875:%.*]] = getelementptr inbounds double, ptr [[TMP874]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP876:%.*]] = getelementptr inbounds double, ptr [[TMP875]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP877:%.*]] = getelementptr inbounds double, ptr [[TMP876]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP878:%.*]] = getelementptr inbounds i32, ptr [[TMP877]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP879:%.*]] = getelementptr inbounds ptr, ptr [[TMP878]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP880:%.*]] = getelementptr inbounds ptr, ptr [[TMP879]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP881:%.*]] = getelementptr inbounds ptr, ptr [[TMP880]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP882:%.*]] = getelementptr inbounds i64, ptr [[TMP881]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP883:%.*]] = getelementptr inbounds i64, ptr [[TMP882]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP884:%.*]] = getelementptr inbounds i32, ptr [[TMP883]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP885:%.*]] = getelementptr inbounds i32, ptr [[TMP884]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP886:%.*]] = getelementptr inbounds i32, ptr [[TMP885]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP887:%.*]] = getelementptr inbounds i32, ptr [[TMP886]], i32 [[GTID31]]
; CHECK-NEXT:    [[I_CACHE48:%.*]] = load i32, ptr [[TMP887]], align 4, !invariant.group [[META85]]
; CHECK-NEXT:    [[TMP888:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR35]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP889:%.*]] = getelementptr inbounds i64, ptr [[TMP888]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP890:%.*]] = getelementptr inbounds ptr, ptr [[TMP889]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP891:%.*]] = getelementptr inbounds i32, ptr [[TMP890]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP892:%.*]] = getelementptr inbounds i1, ptr [[TMP891]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP893:%.*]] = getelementptr inbounds ptr, ptr [[TMP892]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP894:%.*]] = getelementptr inbounds ptr, ptr [[TMP893]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP895:%.*]] = getelementptr inbounds double, ptr [[TMP894]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP896:%.*]] = getelementptr inbounds i32, ptr [[TMP895]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP897:%.*]] = getelementptr inbounds i32, ptr [[TMP896]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP898:%.*]] = getelementptr inbounds double, ptr [[TMP897]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP899:%.*]] = getelementptr inbounds double, ptr [[TMP898]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP900:%.*]] = getelementptr inbounds double, ptr [[TMP899]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP901:%.*]] = getelementptr inbounds double, ptr [[TMP900]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP902:%.*]] = getelementptr inbounds double, ptr [[TMP901]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP903:%.*]] = getelementptr inbounds i32, ptr [[TMP902]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP904:%.*]] = getelementptr inbounds ptr, ptr [[TMP903]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP905:%.*]] = getelementptr inbounds ptr, ptr [[TMP904]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP906:%.*]] = getelementptr inbounds ptr, ptr [[TMP905]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP907:%.*]] = getelementptr inbounds i64, ptr [[TMP906]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP908:%.*]] = getelementptr inbounds i64, ptr [[TMP907]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP909:%.*]] = getelementptr inbounds i32, ptr [[TMP908]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP910:%.*]] = getelementptr inbounds i32, ptr [[TMP909]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP911:%.*]] = getelementptr inbounds i32, ptr [[TMP910]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP912:%.*]] = getelementptr inbounds i32, ptr [[TMP911]], i32 [[CACHE_IN_OFFSET36]]
; CHECK-NEXT:    [[TMP913:%.*]] = getelementptr inbounds i32, ptr [[TMP912]], i32 [[GTID31]]
; CHECK-NEXT:    [[I18_CACHE49:%.*]] = load i32, ptr [[TMP913]], align 4, !invariant.group [[META86]]
; CHECK-NEXT:    [[I13_RECOMPUTE50:%.*]] = shl nsw i32 [[I10_CACHE37]], 7
; CHECK-NEXT:    [[I4_RECOMPUTE51:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I19_RECOMPUTE52:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 8
; CHECK-NEXT:    [[I20_RECOMPUTE53:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 16
; CHECK-NEXT:    [[I26_RECOMPUTE54:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 40
; CHECK-NEXT:    [[I27_RECOMPUTE55:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 44
; CHECK-NEXT:    [[I71_RECOMPUTE56:%.*]] = mul i64 [[I70_CACHE38]], 2806196910506780709
; CHECK-NEXT:    [[I72_RECOMPUTE57:%.*]] = add i64 [[I71_RECOMPUTE56]], 1
; CHECK-NEXT:    [[I73_RECOMPUTE58:%.*]] = and i64 [[I72_RECOMPUTE57]], 9223372036854775807
; CHECK-NEXT:    [[I74_RECOMPUTE59:%.*]] = uitofp i64 [[I73_RECOMPUTE58]] to double
; CHECK-NEXT:    [[I75_RECOMPUTE60:%.*]] = fmul double [[I74_RECOMPUTE59]], 0x3C00000000000000
; CHECK-NEXT:    [[I149_RECOMPUTE:%.*]] = add i64 [[I106_CACHE43]], -1
; CHECK-NEXT:    [[I150_RECOMPUTE:%.*]] = icmp sgt i64 [[I106_CACHE43]], 2
; CHECK-NEXT:    [[I157_RECOMPUTE:%.*]] = trunc i64 [[I106_CACHE43]] to i32
; CHECK-NEXT:    [[I158_RECOMPUTE:%.*]] = add i32 [[I157_RECOMPUTE]], -1
; CHECK-NEXT:    [[I41_RECOMPUTE61:%.*]] = trunc i64 [[I40_CACHE44]] to i32
; CHECK-NEXT:    [[I32_RECOMPUTE62:%.*]] = zext i32 [[I30_CACHE46]] to i64
; CHECK-NEXT:    [[I6_RECOMPUTE63:%.*]] = add nsw i32 [[I5_CACHE47]], -1
; CHECK-NEXT:    [[I21_RECOMPUTE64:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 8
; CHECK-NEXT:    [[I22_RECOMPUTE65:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 24
; CHECK-NEXT:    [[I23_RECOMPUTE66:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 32
; CHECK-NEXT:    [[I24_RECOMPUTE67:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 40
; CHECK-NEXT:    [[I25_RECOMPUTE68:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 16
; CHECK-NEXT:    [[I28_RECOMPUTE69:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 76
; CHECK-NEXT:    [[I173:%.*]] = sext i32 [[I169_CACHE]] to i64
; CHECK-NEXT:    [[I174:%.*]] = mul nsw i64 [[I106_CACHE43]], [[I173]]
; CHECK-NEXT:    [[I175:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT:%.*]], ptr [[I111_CACHE41]], i64 [[I174]]
; CHECK-NEXT:    br i1 [[I150_RECOMPUTE]], label [[BB176:%.*]], label [[BB189:%.*]]
; CHECK:       bb176:
; CHECK-NEXT:    [[I177:%.*]] = phi i64 [ [[I149_RECOMPUTE]], [[CACHEREMAT1]] ], [ [[I187:%.*]], [[BB176]] ]
; CHECK-NEXT:    [[I178:%.*]] = phi i64 [ 0, [[CACHEREMAT1]] ], [ [[I186:%.*]], [[BB176]] ]
; CHECK-NEXT:    [[I179:%.*]] = phi i64 [ [[I149_RECOMPUTE]], [[CACHEREMAT1]] ], [ [[I185:%.*]], [[BB176]] ]
; CHECK-NEXT:    [[I180:%.*]] = lshr i64 [[I177]], 1
; CHECK-NEXT:    [[I181:%.*]] = add nuw nsw i64 [[I180]], [[I178]]
; CHECK-NEXT:    [[I182:%.*]] = getelementptr inbounds [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I175]], i64 [[I181]]
; CHECK-NEXT:    [[I183:%.*]] = load double, ptr [[I182]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I184:%.*]] = fcmp ogt double [[I183]], [[I75_RECOMPUTE60]]
; CHECK-NEXT:    [[I185]] = select i1 [[I184]], i64 [[I181]], i64 [[I179]]
; CHECK-NEXT:    [[I186]] = select i1 [[I184]], i64 [[I178]], i64 [[I181]]
; CHECK-NEXT:    [[I187]] = sub nsw i64 [[I185]], [[I186]]
; CHECK-NEXT:    [[I188:%.*]] = icmp sgt i64 [[I187]], 1
; CHECK-NEXT:    br i1 [[I188]], label [[BB176]], label [[BB189]]
; CHECK:       bb189:
; CHECK-NEXT:    [[I190:%.*]] = phi i64 [ 0, [[CACHEREMAT1]] ], [ [[I186]], [[BB176]] ]
; CHECK-NEXT:    [[I191:%.*]] = icmp eq i64 [[I190]], [[I149_RECOMPUTE]]
; CHECK-NEXT:    br i1 [[I191]], label [[BB192:%.*]], label [[BB195:%.*]]
; CHECK:       bb192:
; CHECK-NEXT:    [[I193:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I175]], i64 [[I149_RECOMPUTE]]
; CHECK-NEXT:    [[I194:%.*]] = getelementptr i8, ptr [[I193]], i64 -48
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       bb195:
; CHECK-NEXT:    [[I196:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I175]], i64 [[I190]]
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       bb197:
; CHECK-NEXT:    [[I198:%.*]] = sext i32 [[I169]] to i64
; CHECK-NEXT:    [[I199:%.*]] = getelementptr i32, ptr [[I148334]], i64 [[I198]]
; CHECK-NEXT:    [[I200:%.*]] = load i32, ptr [[I199]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I201:%.*]] = sext i32 [[I200]] to i64
; CHECK-NEXT:    [[I202:%.*]] = icmp eq i64 [[I149345]], [[I201]]
; CHECK-NEXT:    [[I203:%.*]] = mul nsw i64 [[I106158]], [[I198]]
; CHECK-NEXT:    [[I204:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I111150]], i64 [[I203]]
; CHECK-NEXT:    [[I205:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I204]], i64 [[I201]]
; CHECK-NEXT:    [[I206:%.*]] = select i1 [[I202]], i64 -48, i64 0
; CHECK-NEXT:    [[I207:%.*]] = getelementptr i8, ptr [[I205]], i64 [[I206]]
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       CacheStore2:
; CHECK-NEXT:    [[TMP914:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP915:%.*]] = load ptr, ptr [[TMP914]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR70:%.*]] = getelementptr inbounds i32, ptr [[TMP915]], i32 2
; CHECK-NEXT:    [[CACHEIDX71:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR70]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP916:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP917:%.*]] = load ptr, ptr [[TMP916]], align 8
; CHECK-NEXT:    [[TMP918:%.*]] = getelementptr inbounds ptr, ptr [[TMP917]], i32 2
; CHECK-NEXT:    [[CACHE_OUT_PTR72:%.*]] = load ptr, ptr [[TMP918]], align 8
; CHECK-NEXT:    [[TMP919:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET73:%.*]] = load i32, ptr [[TMP919]], align 4
; CHECK-NEXT:    [[TMP920:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP920]], align 4, !invariant.group [[META94]]
; CHECK-NEXT:    [[TMP921:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP922:%.*]] = getelementptr inbounds i64, ptr [[TMP921]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP922]], align 8, !invariant.group [[META95]]
; CHECK-NEXT:    [[TMP923:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP924:%.*]] = getelementptr inbounds i64, ptr [[TMP923]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP925:%.*]] = getelementptr inbounds ptr, ptr [[TMP924]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP925]], align 8, !invariant.group [[META96]]
; CHECK-NEXT:    [[TMP926:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP927:%.*]] = getelementptr inbounds i64, ptr [[TMP926]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP928:%.*]] = getelementptr inbounds ptr, ptr [[TMP927]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP929:%.*]] = getelementptr inbounds i32, ptr [[TMP928]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP929]], align 4, !invariant.group [[META97]]
; CHECK-NEXT:    [[TMP930:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP931:%.*]] = getelementptr inbounds i64, ptr [[TMP930]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP932:%.*]] = getelementptr inbounds ptr, ptr [[TMP931]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP933:%.*]] = getelementptr inbounds i32, ptr [[TMP932]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP934:%.*]] = getelementptr inbounds i1, ptr [[TMP933]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP934]], align 1, !invariant.group [[META98]]
; CHECK-NEXT:    [[TMP935:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP936:%.*]] = getelementptr inbounds i64, ptr [[TMP935]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP937:%.*]] = getelementptr inbounds ptr, ptr [[TMP936]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP938:%.*]] = getelementptr inbounds i32, ptr [[TMP937]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP939:%.*]] = getelementptr inbounds i1, ptr [[TMP938]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP940:%.*]] = getelementptr inbounds ptr, ptr [[TMP939]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP940]], align 8, !invariant.group [[META99]]
; CHECK-NEXT:    [[TMP941:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP942:%.*]] = getelementptr inbounds i64, ptr [[TMP941]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP943:%.*]] = getelementptr inbounds ptr, ptr [[TMP942]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP944:%.*]] = getelementptr inbounds i32, ptr [[TMP943]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP945:%.*]] = getelementptr inbounds i1, ptr [[TMP944]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP946:%.*]] = getelementptr inbounds ptr, ptr [[TMP945]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP947:%.*]] = getelementptr inbounds ptr, ptr [[TMP946]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP947]], align 8, !invariant.group [[META100]]
; CHECK-NEXT:    [[TMP948:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP949:%.*]] = getelementptr inbounds i64, ptr [[TMP948]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP950:%.*]] = getelementptr inbounds ptr, ptr [[TMP949]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP951:%.*]] = getelementptr inbounds i32, ptr [[TMP950]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP952:%.*]] = getelementptr inbounds i1, ptr [[TMP951]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP953:%.*]] = getelementptr inbounds ptr, ptr [[TMP952]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP954:%.*]] = getelementptr inbounds ptr, ptr [[TMP953]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP955:%.*]] = getelementptr inbounds double, ptr [[TMP954]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP955]], align 8, !invariant.group [[META101]]
; CHECK-NEXT:    [[TMP956:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP957:%.*]] = getelementptr inbounds i64, ptr [[TMP956]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP958:%.*]] = getelementptr inbounds ptr, ptr [[TMP957]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP959:%.*]] = getelementptr inbounds i32, ptr [[TMP958]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP960:%.*]] = getelementptr inbounds i1, ptr [[TMP959]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP961:%.*]] = getelementptr inbounds ptr, ptr [[TMP960]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP962:%.*]] = getelementptr inbounds ptr, ptr [[TMP961]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP963:%.*]] = getelementptr inbounds double, ptr [[TMP962]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP964:%.*]] = getelementptr inbounds i32, ptr [[TMP963]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP964]], align 4, !invariant.group [[META102]]
; CHECK-NEXT:    [[TMP965:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP966:%.*]] = getelementptr inbounds i64, ptr [[TMP965]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP967:%.*]] = getelementptr inbounds ptr, ptr [[TMP966]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP968:%.*]] = getelementptr inbounds i32, ptr [[TMP967]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP969:%.*]] = getelementptr inbounds i1, ptr [[TMP968]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP970:%.*]] = getelementptr inbounds ptr, ptr [[TMP969]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP971:%.*]] = getelementptr inbounds ptr, ptr [[TMP970]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP972:%.*]] = getelementptr inbounds double, ptr [[TMP971]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP973:%.*]] = getelementptr inbounds i32, ptr [[TMP972]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP974:%.*]] = getelementptr inbounds i32, ptr [[TMP973]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP974]], align 4, !invariant.group [[META103]]
; CHECK-NEXT:    [[TMP975:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP976:%.*]] = getelementptr inbounds i64, ptr [[TMP975]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP977:%.*]] = getelementptr inbounds ptr, ptr [[TMP976]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP978:%.*]] = getelementptr inbounds i32, ptr [[TMP977]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP979:%.*]] = getelementptr inbounds i1, ptr [[TMP978]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP980:%.*]] = getelementptr inbounds ptr, ptr [[TMP979]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP981:%.*]] = getelementptr inbounds ptr, ptr [[TMP980]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP982:%.*]] = getelementptr inbounds double, ptr [[TMP981]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP983:%.*]] = getelementptr inbounds i32, ptr [[TMP982]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP984:%.*]] = getelementptr inbounds i32, ptr [[TMP983]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP985:%.*]] = getelementptr inbounds double, ptr [[TMP984]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP985]], align 8, !invariant.group [[META104]]
; CHECK-NEXT:    [[TMP986:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP987:%.*]] = getelementptr inbounds i64, ptr [[TMP986]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP988:%.*]] = getelementptr inbounds ptr, ptr [[TMP987]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP989:%.*]] = getelementptr inbounds i32, ptr [[TMP988]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP990:%.*]] = getelementptr inbounds i1, ptr [[TMP989]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP991:%.*]] = getelementptr inbounds ptr, ptr [[TMP990]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP992:%.*]] = getelementptr inbounds ptr, ptr [[TMP991]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP993:%.*]] = getelementptr inbounds double, ptr [[TMP992]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP994:%.*]] = getelementptr inbounds i32, ptr [[TMP993]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP995:%.*]] = getelementptr inbounds i32, ptr [[TMP994]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP996:%.*]] = getelementptr inbounds double, ptr [[TMP995]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP997:%.*]] = getelementptr inbounds double, ptr [[TMP996]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP997]], align 8, !invariant.group [[META105]]
; CHECK-NEXT:    [[TMP998:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP999:%.*]] = getelementptr inbounds i64, ptr [[TMP998]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1000:%.*]] = getelementptr inbounds ptr, ptr [[TMP999]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1001:%.*]] = getelementptr inbounds i32, ptr [[TMP1000]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1002:%.*]] = getelementptr inbounds i1, ptr [[TMP1001]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1003:%.*]] = getelementptr inbounds ptr, ptr [[TMP1002]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1004:%.*]] = getelementptr inbounds ptr, ptr [[TMP1003]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1005:%.*]] = getelementptr inbounds double, ptr [[TMP1004]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1006:%.*]] = getelementptr inbounds i32, ptr [[TMP1005]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1007:%.*]] = getelementptr inbounds i32, ptr [[TMP1006]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1008:%.*]] = getelementptr inbounds double, ptr [[TMP1007]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1009:%.*]] = getelementptr inbounds double, ptr [[TMP1008]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1010:%.*]] = getelementptr inbounds double, ptr [[TMP1009]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP1010]], align 8, !invariant.group [[META106]]
; CHECK-NEXT:    [[TMP1011:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1012:%.*]] = getelementptr inbounds i64, ptr [[TMP1011]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1013:%.*]] = getelementptr inbounds ptr, ptr [[TMP1012]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1014:%.*]] = getelementptr inbounds i32, ptr [[TMP1013]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1015:%.*]] = getelementptr inbounds i1, ptr [[TMP1014]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1016:%.*]] = getelementptr inbounds ptr, ptr [[TMP1015]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1017:%.*]] = getelementptr inbounds ptr, ptr [[TMP1016]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1018:%.*]] = getelementptr inbounds double, ptr [[TMP1017]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1019:%.*]] = getelementptr inbounds i32, ptr [[TMP1018]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1020:%.*]] = getelementptr inbounds i32, ptr [[TMP1019]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1021:%.*]] = getelementptr inbounds double, ptr [[TMP1020]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1022:%.*]] = getelementptr inbounds double, ptr [[TMP1021]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1023:%.*]] = getelementptr inbounds double, ptr [[TMP1022]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1024:%.*]] = getelementptr inbounds double, ptr [[TMP1023]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP1024]], align 8, !invariant.group [[META107]]
; CHECK-NEXT:    [[TMP1025:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1026:%.*]] = getelementptr inbounds i64, ptr [[TMP1025]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1027:%.*]] = getelementptr inbounds ptr, ptr [[TMP1026]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1028:%.*]] = getelementptr inbounds i32, ptr [[TMP1027]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1029:%.*]] = getelementptr inbounds i1, ptr [[TMP1028]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1030:%.*]] = getelementptr inbounds ptr, ptr [[TMP1029]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1031:%.*]] = getelementptr inbounds ptr, ptr [[TMP1030]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1032:%.*]] = getelementptr inbounds double, ptr [[TMP1031]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1033:%.*]] = getelementptr inbounds i32, ptr [[TMP1032]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1034:%.*]] = getelementptr inbounds i32, ptr [[TMP1033]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1035:%.*]] = getelementptr inbounds double, ptr [[TMP1034]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1036:%.*]] = getelementptr inbounds double, ptr [[TMP1035]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1037:%.*]] = getelementptr inbounds double, ptr [[TMP1036]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1038:%.*]] = getelementptr inbounds double, ptr [[TMP1037]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1039:%.*]] = getelementptr inbounds double, ptr [[TMP1038]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP1039]], align 8, !invariant.group [[META108]]
; CHECK-NEXT:    [[TMP1040:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1041:%.*]] = getelementptr inbounds i64, ptr [[TMP1040]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1042:%.*]] = getelementptr inbounds ptr, ptr [[TMP1041]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1043:%.*]] = getelementptr inbounds i32, ptr [[TMP1042]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1044:%.*]] = getelementptr inbounds i1, ptr [[TMP1043]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1045:%.*]] = getelementptr inbounds ptr, ptr [[TMP1044]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1046:%.*]] = getelementptr inbounds ptr, ptr [[TMP1045]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1047:%.*]] = getelementptr inbounds double, ptr [[TMP1046]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1048:%.*]] = getelementptr inbounds i32, ptr [[TMP1047]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1049:%.*]] = getelementptr inbounds i32, ptr [[TMP1048]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1050:%.*]] = getelementptr inbounds double, ptr [[TMP1049]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1051:%.*]] = getelementptr inbounds double, ptr [[TMP1050]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1052:%.*]] = getelementptr inbounds double, ptr [[TMP1051]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1053:%.*]] = getelementptr inbounds double, ptr [[TMP1052]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1054:%.*]] = getelementptr inbounds double, ptr [[TMP1053]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1055:%.*]] = getelementptr inbounds i32, ptr [[TMP1054]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I113144]], ptr [[TMP1055]], align 4, !invariant.group [[META109]]
; CHECK-NEXT:    [[TMP1056:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1057:%.*]] = getelementptr inbounds i64, ptr [[TMP1056]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1058:%.*]] = getelementptr inbounds ptr, ptr [[TMP1057]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1059:%.*]] = getelementptr inbounds i32, ptr [[TMP1058]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1060:%.*]] = getelementptr inbounds i1, ptr [[TMP1059]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1061:%.*]] = getelementptr inbounds ptr, ptr [[TMP1060]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1062:%.*]] = getelementptr inbounds ptr, ptr [[TMP1061]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1063:%.*]] = getelementptr inbounds double, ptr [[TMP1062]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1064:%.*]] = getelementptr inbounds i32, ptr [[TMP1063]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1065:%.*]] = getelementptr inbounds i32, ptr [[TMP1064]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1066:%.*]] = getelementptr inbounds double, ptr [[TMP1065]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1067:%.*]] = getelementptr inbounds double, ptr [[TMP1066]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1068:%.*]] = getelementptr inbounds double, ptr [[TMP1067]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1069:%.*]] = getelementptr inbounds double, ptr [[TMP1068]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1070:%.*]] = getelementptr inbounds double, ptr [[TMP1069]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1071:%.*]] = getelementptr inbounds i32, ptr [[TMP1070]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1072:%.*]] = getelementptr inbounds ptr, ptr [[TMP1071]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP1072]], align 8, !invariant.group [[META110]]
; CHECK-NEXT:    [[TMP1073:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1074:%.*]] = getelementptr inbounds i64, ptr [[TMP1073]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1075:%.*]] = getelementptr inbounds ptr, ptr [[TMP1074]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1076:%.*]] = getelementptr inbounds i32, ptr [[TMP1075]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1077:%.*]] = getelementptr inbounds i1, ptr [[TMP1076]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1078:%.*]] = getelementptr inbounds ptr, ptr [[TMP1077]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1079:%.*]] = getelementptr inbounds ptr, ptr [[TMP1078]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1080:%.*]] = getelementptr inbounds double, ptr [[TMP1079]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1081:%.*]] = getelementptr inbounds i32, ptr [[TMP1080]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1082:%.*]] = getelementptr inbounds i32, ptr [[TMP1081]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1083:%.*]] = getelementptr inbounds double, ptr [[TMP1082]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1084:%.*]] = getelementptr inbounds double, ptr [[TMP1083]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1085:%.*]] = getelementptr inbounds double, ptr [[TMP1084]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1086:%.*]] = getelementptr inbounds double, ptr [[TMP1085]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1087:%.*]] = getelementptr inbounds double, ptr [[TMP1086]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1088:%.*]] = getelementptr inbounds i32, ptr [[TMP1087]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1089:%.*]] = getelementptr inbounds ptr, ptr [[TMP1088]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1090:%.*]] = getelementptr inbounds ptr, ptr [[TMP1089]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP1090]], align 8, !invariant.group [[META111]]
; CHECK-NEXT:    [[TMP1091:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1092:%.*]] = getelementptr inbounds i64, ptr [[TMP1091]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1093:%.*]] = getelementptr inbounds ptr, ptr [[TMP1092]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1094:%.*]] = getelementptr inbounds i32, ptr [[TMP1093]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1095:%.*]] = getelementptr inbounds i1, ptr [[TMP1094]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1096:%.*]] = getelementptr inbounds ptr, ptr [[TMP1095]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1097:%.*]] = getelementptr inbounds ptr, ptr [[TMP1096]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1098:%.*]] = getelementptr inbounds double, ptr [[TMP1097]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1099:%.*]] = getelementptr inbounds i32, ptr [[TMP1098]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1100:%.*]] = getelementptr inbounds i32, ptr [[TMP1099]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1101:%.*]] = getelementptr inbounds double, ptr [[TMP1100]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1102:%.*]] = getelementptr inbounds double, ptr [[TMP1101]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1103:%.*]] = getelementptr inbounds double, ptr [[TMP1102]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1104:%.*]] = getelementptr inbounds double, ptr [[TMP1103]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1105:%.*]] = getelementptr inbounds double, ptr [[TMP1104]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1106:%.*]] = getelementptr inbounds i32, ptr [[TMP1105]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1107:%.*]] = getelementptr inbounds ptr, ptr [[TMP1106]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1108:%.*]] = getelementptr inbounds ptr, ptr [[TMP1107]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1109:%.*]] = getelementptr inbounds ptr, ptr [[TMP1108]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP1109]], align 8, !invariant.group [[META112]]
; CHECK-NEXT:    [[TMP1110:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1111:%.*]] = getelementptr inbounds i64, ptr [[TMP1110]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1112:%.*]] = getelementptr inbounds ptr, ptr [[TMP1111]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1113:%.*]] = getelementptr inbounds i32, ptr [[TMP1112]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1114:%.*]] = getelementptr inbounds i1, ptr [[TMP1113]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1115:%.*]] = getelementptr inbounds ptr, ptr [[TMP1114]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1116:%.*]] = getelementptr inbounds ptr, ptr [[TMP1115]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1117:%.*]] = getelementptr inbounds double, ptr [[TMP1116]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1118:%.*]] = getelementptr inbounds i32, ptr [[TMP1117]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1119:%.*]] = getelementptr inbounds i32, ptr [[TMP1118]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1120:%.*]] = getelementptr inbounds double, ptr [[TMP1119]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1121:%.*]] = getelementptr inbounds double, ptr [[TMP1120]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1122:%.*]] = getelementptr inbounds double, ptr [[TMP1121]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1123:%.*]] = getelementptr inbounds double, ptr [[TMP1122]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1124:%.*]] = getelementptr inbounds double, ptr [[TMP1123]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1125:%.*]] = getelementptr inbounds i32, ptr [[TMP1124]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1126:%.*]] = getelementptr inbounds ptr, ptr [[TMP1125]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1127:%.*]] = getelementptr inbounds ptr, ptr [[TMP1126]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1128:%.*]] = getelementptr inbounds ptr, ptr [[TMP1127]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1129:%.*]] = getelementptr inbounds i64, ptr [[TMP1128]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP1129]], align 8, !invariant.group [[META113]]
; CHECK-NEXT:    [[TMP1130:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1131:%.*]] = getelementptr inbounds i64, ptr [[TMP1130]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1132:%.*]] = getelementptr inbounds ptr, ptr [[TMP1131]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1133:%.*]] = getelementptr inbounds i32, ptr [[TMP1132]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1134:%.*]] = getelementptr inbounds i1, ptr [[TMP1133]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1135:%.*]] = getelementptr inbounds ptr, ptr [[TMP1134]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1136:%.*]] = getelementptr inbounds ptr, ptr [[TMP1135]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1137:%.*]] = getelementptr inbounds double, ptr [[TMP1136]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1138:%.*]] = getelementptr inbounds i32, ptr [[TMP1137]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1139:%.*]] = getelementptr inbounds i32, ptr [[TMP1138]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1140:%.*]] = getelementptr inbounds double, ptr [[TMP1139]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1141:%.*]] = getelementptr inbounds double, ptr [[TMP1140]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1142:%.*]] = getelementptr inbounds double, ptr [[TMP1141]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1143:%.*]] = getelementptr inbounds double, ptr [[TMP1142]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1144:%.*]] = getelementptr inbounds double, ptr [[TMP1143]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1145:%.*]] = getelementptr inbounds i32, ptr [[TMP1144]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1146:%.*]] = getelementptr inbounds ptr, ptr [[TMP1145]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1147:%.*]] = getelementptr inbounds ptr, ptr [[TMP1146]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1148:%.*]] = getelementptr inbounds ptr, ptr [[TMP1147]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1149:%.*]] = getelementptr inbounds i64, ptr [[TMP1148]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1150:%.*]] = getelementptr inbounds i64, ptr [[TMP1149]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP1150]], align 8, !invariant.group [[META114]]
; CHECK-NEXT:    [[TMP1151:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1152:%.*]] = getelementptr inbounds i64, ptr [[TMP1151]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1153:%.*]] = getelementptr inbounds ptr, ptr [[TMP1152]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1154:%.*]] = getelementptr inbounds i32, ptr [[TMP1153]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1155:%.*]] = getelementptr inbounds i1, ptr [[TMP1154]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1156:%.*]] = getelementptr inbounds ptr, ptr [[TMP1155]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1157:%.*]] = getelementptr inbounds ptr, ptr [[TMP1156]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1158:%.*]] = getelementptr inbounds double, ptr [[TMP1157]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1159:%.*]] = getelementptr inbounds i32, ptr [[TMP1158]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1160:%.*]] = getelementptr inbounds i32, ptr [[TMP1159]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1161:%.*]] = getelementptr inbounds double, ptr [[TMP1160]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1162:%.*]] = getelementptr inbounds double, ptr [[TMP1161]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1163:%.*]] = getelementptr inbounds double, ptr [[TMP1162]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1164:%.*]] = getelementptr inbounds double, ptr [[TMP1163]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1165:%.*]] = getelementptr inbounds double, ptr [[TMP1164]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1166:%.*]] = getelementptr inbounds i32, ptr [[TMP1165]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1167:%.*]] = getelementptr inbounds ptr, ptr [[TMP1166]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1168:%.*]] = getelementptr inbounds ptr, ptr [[TMP1167]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1169:%.*]] = getelementptr inbounds ptr, ptr [[TMP1168]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1170:%.*]] = getelementptr inbounds i64, ptr [[TMP1169]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1171:%.*]] = getelementptr inbounds i64, ptr [[TMP1170]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1172:%.*]] = getelementptr inbounds i32, ptr [[TMP1171]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP1172]], align 4, !invariant.group [[META115]]
; CHECK-NEXT:    [[TMP1173:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1174:%.*]] = getelementptr inbounds i64, ptr [[TMP1173]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1175:%.*]] = getelementptr inbounds ptr, ptr [[TMP1174]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1176:%.*]] = getelementptr inbounds i32, ptr [[TMP1175]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1177:%.*]] = getelementptr inbounds i1, ptr [[TMP1176]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1178:%.*]] = getelementptr inbounds ptr, ptr [[TMP1177]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1179:%.*]] = getelementptr inbounds ptr, ptr [[TMP1178]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1180:%.*]] = getelementptr inbounds double, ptr [[TMP1179]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1181:%.*]] = getelementptr inbounds i32, ptr [[TMP1180]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1182:%.*]] = getelementptr inbounds i32, ptr [[TMP1181]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1183:%.*]] = getelementptr inbounds double, ptr [[TMP1182]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1184:%.*]] = getelementptr inbounds double, ptr [[TMP1183]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1185:%.*]] = getelementptr inbounds double, ptr [[TMP1184]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1186:%.*]] = getelementptr inbounds double, ptr [[TMP1185]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1187:%.*]] = getelementptr inbounds double, ptr [[TMP1186]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1188:%.*]] = getelementptr inbounds i32, ptr [[TMP1187]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1189:%.*]] = getelementptr inbounds ptr, ptr [[TMP1188]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1190:%.*]] = getelementptr inbounds ptr, ptr [[TMP1189]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1191:%.*]] = getelementptr inbounds ptr, ptr [[TMP1190]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1192:%.*]] = getelementptr inbounds i64, ptr [[TMP1191]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1193:%.*]] = getelementptr inbounds i64, ptr [[TMP1192]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1194:%.*]] = getelementptr inbounds i32, ptr [[TMP1193]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1195:%.*]] = getelementptr inbounds i32, ptr [[TMP1194]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP1195]], align 4, !invariant.group [[META116]]
; CHECK-NEXT:    [[TMP1196:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1197:%.*]] = getelementptr inbounds i64, ptr [[TMP1196]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1198:%.*]] = getelementptr inbounds ptr, ptr [[TMP1197]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1199:%.*]] = getelementptr inbounds i32, ptr [[TMP1198]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1200:%.*]] = getelementptr inbounds i1, ptr [[TMP1199]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1201:%.*]] = getelementptr inbounds ptr, ptr [[TMP1200]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1202:%.*]] = getelementptr inbounds ptr, ptr [[TMP1201]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1203:%.*]] = getelementptr inbounds double, ptr [[TMP1202]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1204:%.*]] = getelementptr inbounds i32, ptr [[TMP1203]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1205:%.*]] = getelementptr inbounds i32, ptr [[TMP1204]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1206:%.*]] = getelementptr inbounds double, ptr [[TMP1205]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1207:%.*]] = getelementptr inbounds double, ptr [[TMP1206]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1208:%.*]] = getelementptr inbounds double, ptr [[TMP1207]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1209:%.*]] = getelementptr inbounds double, ptr [[TMP1208]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1210:%.*]] = getelementptr inbounds double, ptr [[TMP1209]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1211:%.*]] = getelementptr inbounds i32, ptr [[TMP1210]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1212:%.*]] = getelementptr inbounds ptr, ptr [[TMP1211]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1213:%.*]] = getelementptr inbounds ptr, ptr [[TMP1212]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1214:%.*]] = getelementptr inbounds ptr, ptr [[TMP1213]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1215:%.*]] = getelementptr inbounds i64, ptr [[TMP1214]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1216:%.*]] = getelementptr inbounds i64, ptr [[TMP1215]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1217:%.*]] = getelementptr inbounds i32, ptr [[TMP1216]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1218:%.*]] = getelementptr inbounds i32, ptr [[TMP1217]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1219:%.*]] = getelementptr inbounds i32, ptr [[TMP1218]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP1219]], align 4, !invariant.group [[META117]]
; CHECK-NEXT:    [[TMP1220:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1221:%.*]] = getelementptr inbounds i64, ptr [[TMP1220]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1222:%.*]] = getelementptr inbounds ptr, ptr [[TMP1221]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1223:%.*]] = getelementptr inbounds i32, ptr [[TMP1222]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1224:%.*]] = getelementptr inbounds i1, ptr [[TMP1223]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1225:%.*]] = getelementptr inbounds ptr, ptr [[TMP1224]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1226:%.*]] = getelementptr inbounds ptr, ptr [[TMP1225]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1227:%.*]] = getelementptr inbounds double, ptr [[TMP1226]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1228:%.*]] = getelementptr inbounds i32, ptr [[TMP1227]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1229:%.*]] = getelementptr inbounds i32, ptr [[TMP1228]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1230:%.*]] = getelementptr inbounds double, ptr [[TMP1229]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1231:%.*]] = getelementptr inbounds double, ptr [[TMP1230]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1232:%.*]] = getelementptr inbounds double, ptr [[TMP1231]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1233:%.*]] = getelementptr inbounds double, ptr [[TMP1232]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1234:%.*]] = getelementptr inbounds double, ptr [[TMP1233]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1235:%.*]] = getelementptr inbounds i32, ptr [[TMP1234]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1236:%.*]] = getelementptr inbounds ptr, ptr [[TMP1235]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1237:%.*]] = getelementptr inbounds ptr, ptr [[TMP1236]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1238:%.*]] = getelementptr inbounds ptr, ptr [[TMP1237]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1239:%.*]] = getelementptr inbounds i64, ptr [[TMP1238]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1240:%.*]] = getelementptr inbounds i64, ptr [[TMP1239]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1241:%.*]] = getelementptr inbounds i32, ptr [[TMP1240]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1242:%.*]] = getelementptr inbounds i32, ptr [[TMP1241]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1243:%.*]] = getelementptr inbounds i32, ptr [[TMP1242]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1244:%.*]] = getelementptr inbounds i32, ptr [[TMP1243]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP1244]], align 4, !invariant.group [[META118]]
; CHECK-NEXT:    [[TMP1245:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1246:%.*]] = getelementptr inbounds i64, ptr [[TMP1245]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1247:%.*]] = getelementptr inbounds ptr, ptr [[TMP1246]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1248:%.*]] = getelementptr inbounds i32, ptr [[TMP1247]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1249:%.*]] = getelementptr inbounds i1, ptr [[TMP1248]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1250:%.*]] = getelementptr inbounds ptr, ptr [[TMP1249]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1251:%.*]] = getelementptr inbounds ptr, ptr [[TMP1250]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1252:%.*]] = getelementptr inbounds double, ptr [[TMP1251]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1253:%.*]] = getelementptr inbounds i32, ptr [[TMP1252]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1254:%.*]] = getelementptr inbounds i32, ptr [[TMP1253]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1255:%.*]] = getelementptr inbounds double, ptr [[TMP1254]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1256:%.*]] = getelementptr inbounds double, ptr [[TMP1255]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1257:%.*]] = getelementptr inbounds double, ptr [[TMP1256]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1258:%.*]] = getelementptr inbounds double, ptr [[TMP1257]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1259:%.*]] = getelementptr inbounds double, ptr [[TMP1258]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1260:%.*]] = getelementptr inbounds i32, ptr [[TMP1259]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1261:%.*]] = getelementptr inbounds ptr, ptr [[TMP1260]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1262:%.*]] = getelementptr inbounds ptr, ptr [[TMP1261]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1263:%.*]] = getelementptr inbounds ptr, ptr [[TMP1262]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1264:%.*]] = getelementptr inbounds i64, ptr [[TMP1263]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1265:%.*]] = getelementptr inbounds i64, ptr [[TMP1264]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1266:%.*]] = getelementptr inbounds i32, ptr [[TMP1265]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1267:%.*]] = getelementptr inbounds i32, ptr [[TMP1266]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1268:%.*]] = getelementptr inbounds i32, ptr [[TMP1267]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1269:%.*]] = getelementptr inbounds i32, ptr [[TMP1268]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP1270:%.*]] = getelementptr inbounds i32, ptr [[TMP1269]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP1270]], align 4, !invariant.group [[META119]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb255:
; CHECK-NEXT:    [[I149344]] = phi i64 [ [[I149345]], [[BB197]] ], [ [[I149_RECOMPUTE]], [[BB195]] ], [ [[I149_RECOMPUTE]], [[BB192]] ]
; CHECK-NEXT:    [[I160343:%.*]] = phi double [ [[I160]], [[BB197]] ], [ [[I160_CACHE]], [[BB195]] ], [ [[I160_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I161342:%.*]] = phi double [ [[I161]], [[BB197]] ], [ [[I161_CACHE]], [[BB195]] ], [ [[I161_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I162341:%.*]] = phi double [ [[I162]], [[BB197]] ], [ [[I162_CACHE]], [[BB195]] ], [ [[I162_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I163340:%.*]] = phi double [ [[I163]], [[BB197]] ], [ [[I163_CACHE]], [[BB195]] ], [ [[I163_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I164339:%.*]] = phi double [ [[I164]], [[BB197]] ], [ [[I164_CACHE]], [[BB195]] ], [ [[I164_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I165338:%.*]] = phi i32 [ [[I165]], [[BB197]] ], [ [[I165_CACHE]], [[BB195]] ], [ [[I165_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I171337:%.*]] = phi double [ [[I171]], [[BB197]] ], [ [[I171_CACHE]], [[BB195]] ], [ [[I171_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I156335]] = phi ptr [ [[I156336]], [[BB197]] ], [ [[I156_CACHE]], [[BB195]] ], [ [[I156_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I148333]] = phi ptr [ [[I148334]], [[BB197]] ], [ [[I148_CACHE]], [[BB195]] ], [ [[I148_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I153331]] = phi i1 [ [[I153332]], [[BB197]] ], [ [[I153_CACHE]], [[BB195]] ], [ [[I153_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I146329]] = phi i32 [ [[I146330]], [[BB197]] ], [ [[I146_CACHE]], [[BB195]] ], [ [[I146_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I142327]] = phi ptr [ [[I142328]], [[BB197]] ], [ [[I142_CACHE]], [[BB195]] ], [ [[I142_CACHE]], [[BB192]] ]
; CHECK-NEXT:    [[I28321]] = phi ptr [ [[I28324]], [[BB197]] ], [ [[I28_RECOMPUTE69]], [[BB195]] ], [ [[I28_RECOMPUTE69]], [[BB192]] ]
; CHECK-NEXT:    [[I25314]] = phi ptr [ [[I25317]], [[BB197]] ], [ [[I25_RECOMPUTE68]], [[BB195]] ], [ [[I25_RECOMPUTE68]], [[BB192]] ]
; CHECK-NEXT:    [[I24307]] = phi ptr [ [[I24310]], [[BB197]] ], [ [[I24_RECOMPUTE67]], [[BB195]] ], [ [[I24_RECOMPUTE67]], [[BB192]] ]
; CHECK-NEXT:    [[I23300]] = phi ptr [ [[I23303]], [[BB197]] ], [ [[I23_RECOMPUTE66]], [[BB195]] ], [ [[I23_RECOMPUTE66]], [[BB192]] ]
; CHECK-NEXT:    [[I22293]] = phi ptr [ [[I22296]], [[BB197]] ], [ [[I22_RECOMPUTE65]], [[BB195]] ], [ [[I22_RECOMPUTE65]], [[BB192]] ]
; CHECK-NEXT:    [[I21286]] = phi ptr [ [[I21289]], [[BB197]] ], [ [[I21_RECOMPUTE64]], [[BB195]] ], [ [[I21_RECOMPUTE64]], [[BB192]] ]
; CHECK-NEXT:    [[I6278]] = phi i32 [ [[I6281]], [[BB197]] ], [ [[I6_RECOMPUTE63]], [[BB195]] ], [ [[I6_RECOMPUTE63]], [[BB192]] ]
; CHECK-NEXT:    [[I32273]] = phi i64 [ [[I32276]], [[BB197]] ], [ [[I32_RECOMPUTE62]], [[BB195]] ], [ [[I32_RECOMPUTE62]], [[BB192]] ]
; CHECK-NEXT:    [[I41269]] = phi i32 [ [[I41272]], [[BB197]] ], [ [[I41_RECOMPUTE61]], [[BB195]] ], [ [[I41_RECOMPUTE61]], [[BB192]] ]
; CHECK-NEXT:    [[I75266]] = phi double [ [[I75268]], [[BB197]] ], [ [[I75_RECOMPUTE60]], [[BB195]] ], [ [[I75_RECOMPUTE60]], [[BB192]] ]
; CHECK-NEXT:    [[I27260]] = phi ptr [ [[I27263]], [[BB197]] ], [ [[I27_RECOMPUTE55]], [[BB195]] ], [ [[I27_RECOMPUTE55]], [[BB192]] ]
; CHECK-NEXT:    [[I26253]] = phi ptr [ [[I26256]], [[BB197]] ], [ [[I26_RECOMPUTE54]], [[BB195]] ], [ [[I26_RECOMPUTE54]], [[BB192]] ]
; CHECK-NEXT:    [[I20246]] = phi ptr [ [[I20249]], [[BB197]] ], [ [[I20_RECOMPUTE53]], [[BB195]] ], [ [[I20_RECOMPUTE53]], [[BB192]] ]
; CHECK-NEXT:    [[I19239]] = phi ptr [ [[I19242]], [[BB197]] ], [ [[I19_RECOMPUTE52]], [[BB195]] ], [ [[I19_RECOMPUTE52]], [[BB192]] ]
; CHECK-NEXT:    [[I4231]] = phi ptr [ [[I4234]], [[BB197]] ], [ [[I4_RECOMPUTE51]], [[BB195]] ], [ [[I4_RECOMPUTE51]], [[BB192]] ]
; CHECK-NEXT:    [[I13224]] = phi i32 [ [[I13228]], [[BB197]] ], [ [[I13_RECOMPUTE50]], [[BB195]] ], [ [[I13_RECOMPUTE50]], [[BB192]] ]
; CHECK-NEXT:    [[I18217]] = phi i32 [ [[I18220]], [[BB197]] ], [ [[I18_CACHE49]], [[BB195]] ], [ [[I18_CACHE49]], [[BB192]] ]
; CHECK-NEXT:    [[I189]] = phi i32 [ [[I197]], [[BB197]] ], [ [[I_CACHE48]], [[BB195]] ], [ [[I_CACHE48]], [[BB192]] ]
; CHECK-NEXT:    [[I5177]] = phi i32 [ [[I5180]], [[BB197]] ], [ [[I5_CACHE47]], [[BB195]] ], [ [[I5_CACHE47]], [[BB192]] ]
; CHECK-NEXT:    [[I30171]] = phi i32 [ [[I30174]], [[BB197]] ], [ [[I30_CACHE46]], [[BB195]] ], [ [[I30_CACHE46]], [[BB192]] ]
; CHECK-NEXT:    [[I31165]] = phi i32 [ [[I31168]], [[BB197]] ], [ [[I31_CACHE45]], [[BB195]] ], [ [[I31_CACHE45]], [[BB192]] ]
; CHECK-NEXT:    [[I40161]] = phi i64 [ [[I40164]], [[BB197]] ], [ [[I40_CACHE44]], [[BB195]] ], [ [[I40_CACHE44]], [[BB192]] ]
; CHECK-NEXT:    [[I106157]] = phi i64 [ [[I106158]], [[BB197]] ], [ [[I106_CACHE43]], [[BB195]] ], [ [[I106_CACHE43]], [[BB192]] ]
; CHECK-NEXT:    [[I108153]] = phi ptr [ [[I108154]], [[BB197]] ], [ [[I108_CACHE42]], [[BB195]] ], [ [[I108_CACHE42]], [[BB192]] ]
; CHECK-NEXT:    [[I111149]] = phi ptr [ [[I111150]], [[BB197]] ], [ [[I111_CACHE41]], [[BB195]] ], [ [[I111_CACHE41]], [[BB192]] ]
; CHECK-NEXT:    [[I112146]] = phi ptr [ [[I112147]], [[BB197]] ], [ [[I112_CACHE40]], [[BB195]] ], [ [[I112_CACHE40]], [[BB192]] ]
; CHECK-NEXT:    [[I113143]] = phi i32 [ 0, [[BB197]] ], [ [[I113_CACHE39]], [[BB195]] ], [ [[I113_CACHE39]], [[BB192]] ]
; CHECK-NEXT:    [[I70137]] = phi i64 [ [[I70139]], [[BB197]] ], [ [[I70_CACHE38]], [[BB195]] ], [ [[I70_CACHE38]], [[BB192]] ]
; CHECK-NEXT:    [[I10130]] = phi i32 [ [[I10133]], [[BB197]] ], [ [[I10_CACHE37]], [[BB195]] ], [ [[I10_CACHE37]], [[BB192]] ]
; CHECK-NEXT:    [[I256:%.*]] = phi ptr [ [[I194]], [[BB192]] ], [ [[I196]], [[BB195]] ], [ [[I207]], [[BB197]] ]
; CHECK-NEXT:    [[I257:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 48
; CHECK-NEXT:    [[I258:%.*]] = load double, ptr [[I257]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I259:%.*]] = fsub double [[I258]], [[I75266]]
; CHECK-NEXT:    [[I260:%.*]] = load double, ptr [[I256]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I261:%.*]] = fsub double [[I258]], [[I260]]
; CHECK-NEXT:    [[I262:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 56
; CHECK-NEXT:    [[I263:%.*]] = load double, ptr [[I262]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I264:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 8
; CHECK-NEXT:    [[I265:%.*]] = load double, ptr [[I264]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I266:%.*]] = fsub double [[I263]], [[I265]]
; CHECK-NEXT:    [[I267:%.*]] = fneg double [[I259]]
; CHECK-NEXT:    [[I268:%.*]] = fdiv double [[I267]], [[I261]]
; CHECK-NEXT:    [[I269:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I266]], double [[I263]])
; CHECK-NEXT:    [[I270:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 64
; CHECK-NEXT:    [[I271:%.*]] = load double, ptr [[I270]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I272:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 16
; CHECK-NEXT:    [[I273:%.*]] = load double, ptr [[I272]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I274:%.*]] = fsub double [[I271]], [[I273]]
; CHECK-NEXT:    [[I275:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I274]], double [[I271]])
; CHECK-NEXT:    [[I276:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 72
; CHECK-NEXT:    [[I277:%.*]] = load double, ptr [[I276]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I278:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 24
; CHECK-NEXT:    [[I279:%.*]] = load double, ptr [[I278]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I280:%.*]] = fsub double [[I277]], [[I279]]
; CHECK-NEXT:    [[I281:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I280]], double [[I277]])
; CHECK-NEXT:    [[I282:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 80
; CHECK-NEXT:    [[I283:%.*]] = load double, ptr [[I282]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I284:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 32
; CHECK-NEXT:    [[I285:%.*]] = load double, ptr [[I284]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I286:%.*]] = fsub double [[I283]], [[I285]]
; CHECK-NEXT:    [[I287:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I286]], double [[I283]])
; CHECK-NEXT:    [[I288:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 88
; CHECK-NEXT:    [[I289:%.*]] = load double, ptr [[I288]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I290:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 40
; CHECK-NEXT:    [[I291:%.*]] = load double, ptr [[I290]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I292:%.*]] = fsub double [[I289]], [[I291]]
; CHECK-NEXT:    [[I293:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I292]], double [[I289]])
; CHECK-NEXT:    [[I294]] = tail call double @llvm.fmuladd.f64(double [[I269]], double [[I171337]], double [[I164339]])
; CHECK-NEXT:    [[I295]] = tail call double @llvm.fmuladd.f64(double [[I275]], double [[I171337]], double [[I163340]])
; CHECK-NEXT:    [[I296]] = tail call double @llvm.fmuladd.f64(double [[I281]], double [[I171337]], double [[I162341]])
; CHECK-NEXT:    [[I297]] = tail call double @llvm.fmuladd.f64(double [[I287]], double [[I171337]], double [[I161342]])
; CHECK-NEXT:    [[I298]] = tail call double @llvm.fmuladd.f64(double [[I293]], double [[I171337]], double [[I160343]])
; CHECK-NEXT:    [[I299]] = add nuw nsw i32 [[I165338]], 1
; CHECK-NEXT:    [[I300:%.*]] = load i32, ptr [[I142327]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I301:%.*]] = icmp slt i32 [[I299]], [[I300]]
; CHECK-NEXT:    br i1 [[I301]], label [[BB159]], label [[BB302]]
; CHECK:       bb302:
; CHECK-NEXT:    [[I28323]] = phi ptr [ [[I28326]], [[BB139]] ], [ [[I28321]], [[BB255]] ]
; CHECK-NEXT:    [[I25316]] = phi ptr [ [[I25319]], [[BB139]] ], [ [[I25314]], [[BB255]] ]
; CHECK-NEXT:    [[I24309]] = phi ptr [ [[I24312]], [[BB139]] ], [ [[I24307]], [[BB255]] ]
; CHECK-NEXT:    [[I23302]] = phi ptr [ [[I23305]], [[BB139]] ], [ [[I23300]], [[BB255]] ]
; CHECK-NEXT:    [[I22295]] = phi ptr [ [[I22298]], [[BB139]] ], [ [[I22293]], [[BB255]] ]
; CHECK-NEXT:    [[I21288]] = phi ptr [ [[I21291]], [[BB139]] ], [ [[I21286]], [[BB255]] ]
; CHECK-NEXT:    [[I6280]] = phi i32 [ [[I6283]], [[BB139]] ], [ [[I6278]], [[BB255]] ]
; CHECK-NEXT:    [[I32275]] = phi i64 [ [[I32277]], [[BB139]] ], [ [[I32273]], [[BB255]] ]
; CHECK-NEXT:    [[I41271:%.*]] = phi i32 [ [[I41]], [[BB139]] ], [ [[I41269]], [[BB255]] ]
; CHECK-NEXT:    [[I27262]] = phi ptr [ [[I27265]], [[BB139]] ], [ [[I27260]], [[BB255]] ]
; CHECK-NEXT:    [[I26255]] = phi ptr [ [[I26258]], [[BB139]] ], [ [[I26253]], [[BB255]] ]
; CHECK-NEXT:    [[I20248]] = phi ptr [ [[I20251]], [[BB139]] ], [ [[I20246]], [[BB255]] ]
; CHECK-NEXT:    [[I19241]] = phi ptr [ [[I19244]], [[BB139]] ], [ [[I19239]], [[BB255]] ]
; CHECK-NEXT:    [[I4233]] = phi ptr [ [[I4236]], [[BB139]] ], [ [[I4231]], [[BB255]] ]
; CHECK-NEXT:    [[I13227]] = phi i32 [ [[I13230]], [[BB139]] ], [ [[I13224]], [[BB255]] ]
; CHECK-NEXT:    [[I18219]] = phi i32 [ [[I18222]], [[BB139]] ], [ [[I18217]], [[BB255]] ]
; CHECK-NEXT:    [[I195]] = phi i32 [ [[I212]], [[BB139]] ], [ [[I189]], [[BB255]] ]
; CHECK-NEXT:    [[I5179]] = phi i32 [ [[I5182]], [[BB139]] ], [ [[I5177]], [[BB255]] ]
; CHECK-NEXT:    [[I30173]] = phi i32 [ [[I30176]], [[BB139]] ], [ [[I30171]], [[BB255]] ]
; CHECK-NEXT:    [[I31167]] = phi i32 [ [[I31170]], [[BB139]] ], [ [[I31165]], [[BB255]] ]
; CHECK-NEXT:    [[I40163:%.*]] = phi i64 [ [[I40]], [[BB139]] ], [ [[I40161]], [[BB255]] ]
; CHECK-NEXT:    [[I10132]] = phi i32 [ [[I10135]], [[BB139]] ], [ [[I10130]], [[BB255]] ]
; CHECK-NEXT:    [[I303:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I294]], [[BB255]] ]
; CHECK-NEXT:    [[I304:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I295]], [[BB255]] ]
; CHECK-NEXT:    [[I305:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I296]], [[BB255]] ]
; CHECK-NEXT:    [[I306:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I297]], [[BB255]] ]
; CHECK-NEXT:    [[I307:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I298]], [[BB255]] ]
; CHECK-NEXT:    [[I308:%.*]] = fcmp ogt double [[I303]], -1.000000e+00
; CHECK-NEXT:    [[I309:%.*]] = select i1 [[I308]], double [[I303]], double -1.000000e+00
; CHECK-NEXT:    [[I310:%.*]] = fcmp ogt double [[I304]], [[I309]]
; CHECK-NEXT:    [[I311:%.*]] = select i1 [[I310]], double [[I304]], double [[I309]]
; CHECK-NEXT:    [[I312:%.*]] = fcmp ogt double [[I305]], [[I311]]
; CHECK-NEXT:    [[I313:%.*]] = select i1 [[I312]], double [[I305]], double [[I311]]
; CHECK-NEXT:    [[I314:%.*]] = fcmp ogt double [[I306]], [[I313]]
; CHECK-NEXT:    [[I315:%.*]] = select i1 [[I314]], double [[I306]], double [[I313]]
; CHECK-NEXT:    [[I316:%.*]] = select i1 [[I310]], i64 2, i64 1
; CHECK-NEXT:    [[I317:%.*]] = fcmp ogt double [[I307]], [[I315]]
; CHECK-NEXT:    [[I318:%.*]] = select i1 [[I312]], i64 3, i64 [[I316]]
; CHECK-NEXT:    [[I319:%.*]] = select i1 [[I314]], i64 4, i64 [[I318]]
; CHECK-NEXT:    [[I320:%.*]] = select i1 [[I317]], i64 5, i64 [[I319]]
; CHECK-NEXT:    [[I321:%.*]] = getelementptr inbounds i64, ptr [[ARG3]], i64 [[I40163]]
; CHECK-NEXT:    store i64 [[I320]], ptr [[I321]], align 8, !tbaa [[TBAA120]]
; CHECK-NEXT:    [[I322:%.*]] = add nsw i32 [[I18219]], [[I41271]]
; CHECK-NEXT:    [[I323]] = sext i32 [[I322]] to i64
; CHECK-NEXT:    [[I324:%.*]] = icmp ugt i64 [[I323]], [[I32275]]
; CHECK-NEXT:    br i1 [[I324]], label [[BB325]], label [[BB39]]
; CHECK:       bb325:
; CHECK-NEXT:    [[I28325]] = phi ptr [ [[I28323]], [[BB302]] ], [ [[I28325]], [[BB35]] ], [ [[I28325]], [[BB29_FROM_BB325:%.*]] ]
; CHECK-NEXT:    [[I25318]] = phi ptr [ [[I25316]], [[BB302]] ], [ [[I25318]], [[BB35]] ], [ [[I25318]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I24311]] = phi ptr [ [[I24309]], [[BB302]] ], [ [[I24311]], [[BB35]] ], [ [[I24311]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I23304]] = phi ptr [ [[I23302]], [[BB302]] ], [ [[I23304]], [[BB35]] ], [ [[I23304]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I22297]] = phi ptr [ [[I22295]], [[BB302]] ], [ [[I22297]], [[BB35]] ], [ [[I22297]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I21290]] = phi ptr [ [[I21288]], [[BB302]] ], [ [[I21290]], [[BB35]] ], [ [[I21290]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I6282]] = phi i32 [ [[I6280]], [[BB302]] ], [ [[I6282]], [[BB35]] ], [ [[I6282]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I27264]] = phi ptr [ [[I27262]], [[BB302]] ], [ [[I27264]], [[BB35]] ], [ [[I27264]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I26257]] = phi ptr [ [[I26255]], [[BB302]] ], [ [[I26257]], [[BB35]] ], [ [[I26257]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I20250]] = phi ptr [ [[I20248]], [[BB302]] ], [ [[I20250]], [[BB35]] ], [ [[I20250]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I19243]] = phi ptr [ [[I19241]], [[BB302]] ], [ [[I19243]], [[BB35]] ], [ [[I19243]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I4235]] = phi ptr [ [[I4233]], [[BB302]] ], [ [[I4235]], [[BB35]] ], [ [[I4235]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I13229]] = phi i32 [ [[I13227]], [[BB302]] ], [ [[I13229]], [[BB35]] ], [ [[I13229]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I18221]] = phi i32 [ [[I18219]], [[BB302]] ], [ [[I18221]], [[BB35]] ], [ [[I18221]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I208]] = phi i32 [ [[I195]], [[BB302]] ], [ [[I208]], [[BB35]] ], [ [[I208]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I5181]] = phi i32 [ [[I5179]], [[BB302]] ], [ [[I5181]], [[BB35]] ], [ [[I5181]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I30175:%.*]] = phi i32 [ [[I30173]], [[BB302]] ], [ [[I328_BB29]], [[BB35]] ], [ [[I328_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I31169:%.*]] = phi i32 [ [[I31167]], [[BB302]] ], [ [[I326_BB29]], [[BB35]] ], [ [[I326_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I10134]] = phi i32 [ [[I10132]], [[BB302]] ], [ [[I10134]], [[BB35]] ], [ [[I10134]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I326:%.*]] = add nsw i32 [[I31169]], [[I13229]]
; CHECK-NEXT:    [[I327:%.*]] = add nsw i32 [[I30175]], [[I13229]]
; CHECK-NEXT:    [[I328:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I327]], i32 [[I6282]])
; CHECK-NEXT:    [[I329:%.*]] = icmp slt i32 [[I326]], [[I5181]]
; CHECK-NEXT:    br i1 [[I329]], label [[BB29_FROM_BB325]], label [[BB330:%.*]]
; CHECK:       bb29.from.bb325:
; CHECK-NEXT:    [[I326_BB29]] = phi i32 [ [[I326]], [[BB325]] ]
; CHECK-NEXT:    [[I328_BB29]] = phi i32 [ [[I328]], [[BB325]] ]
; CHECK-NEXT:    [[I32]] = zext i32 [[I328_BB29]] to i64
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I33:%.*]] = load i32, ptr [[I4235]], align 8, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[I34:%.*]] = icmp sgt i32 [[I33]], 0
; CHECK-NEXT:    br i1 [[I34]], label [[BB35]], label [[BB325]]
; CHECK:       bb330:
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define weak_odr protected void @__omp_offloading_run_event_based_simulation_contd_2(
; CHECK-SAME: ptr noalias noundef [[ARG:%.*]], ptr noundef nonnull align 8 dereferenceable(64) [[ARG1:%.*]], ptr noundef nonnull align 8 dereferenceable(112) [[ARG2:%.*]], ptr noundef [[ARG3:%.*]]) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[GTID74:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CONTCOUNT_IN_PTR75:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 3
; CHECK-NEXT:    [[CONTCOUNT_IN76:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR75]], align 4
; CHECK-NEXT:    [[MASKTHREAD77:%.*]] = icmp ult i32 [[GTID74]], [[CONTCOUNT_IN76]]
; CHECK-NEXT:    br i1 [[MASKTHREAD77]], label [[CACHEREMAT2:%.*]], label [[THREADEXIT:%.*]]
; CHECK:       bb35:
; CHECK-NEXT:    [[I36:%.*]] = add nsw i32 [[I326_BB29:%.*]], [[I208:%.*]]
; CHECK-NEXT:    [[I37:%.*]] = sext i32 [[I36]] to i64
; CHECK-NEXT:    [[I38:%.*]] = icmp ugt i64 [[I37]], [[I32:%.*]]
; CHECK-NEXT:    br i1 [[I38]], label [[BB325:%.*]], label [[BB39:%.*]]
; CHECK:       bb39:
; CHECK-NEXT:    [[I28326:%.*]] = phi ptr [ [[I28325:%.*]], [[BB35:%.*]] ], [ [[I28323:%.*]], [[BB302:%.*]] ]
; CHECK-NEXT:    [[I25319:%.*]] = phi ptr [ [[I25318:%.*]], [[BB35]] ], [ [[I25316:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I24312:%.*]] = phi ptr [ [[I24311:%.*]], [[BB35]] ], [ [[I24309:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I23305:%.*]] = phi ptr [ [[I23304:%.*]], [[BB35]] ], [ [[I23302:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I22298:%.*]] = phi ptr [ [[I22297:%.*]], [[BB35]] ], [ [[I22295:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I21291:%.*]] = phi ptr [ [[I21290:%.*]], [[BB35]] ], [ [[I21288:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I6283:%.*]] = phi i32 [ [[I6282:%.*]], [[BB35]] ], [ [[I6280:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I32277:%.*]] = phi i64 [ [[I32]], [[BB35]] ], [ [[I32275:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I27265:%.*]] = phi ptr [ [[I27264:%.*]], [[BB35]] ], [ [[I27262:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I26258:%.*]] = phi ptr [ [[I26257:%.*]], [[BB35]] ], [ [[I26255:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I20251:%.*]] = phi ptr [ [[I20250:%.*]], [[BB35]] ], [ [[I20248:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I19244:%.*]] = phi ptr [ [[I19243:%.*]], [[BB35]] ], [ [[I19241:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I4236:%.*]] = phi ptr [ [[I4235:%.*]], [[BB35]] ], [ [[I4233:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I13230:%.*]] = phi i32 [ [[I13229:%.*]], [[BB35]] ], [ [[I13227:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I18222:%.*]] = phi i32 [ [[I18221:%.*]], [[BB35]] ], [ [[I18219:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I212:%.*]] = phi i32 [ [[I208]], [[BB35]] ], [ [[I195:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I5182:%.*]] = phi i32 [ [[I5181:%.*]], [[BB35]] ], [ [[I5179:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I30176:%.*]] = phi i32 [ [[I328_BB29:%.*]], [[BB35]] ], [ [[I30173:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I31170:%.*]] = phi i32 [ [[I326_BB29]], [[BB35]] ], [ [[I31167:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I10135:%.*]] = phi i32 [ [[I10134:%.*]], [[BB35]] ], [ [[I10132:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I40:%.*]] = phi i64 [ [[I37]], [[BB35]] ], [ [[I323:%.*]], [[BB302]] ]
; CHECK-NEXT:    [[I41:%.*]] = trunc i64 [[I40]] to i32
; CHECK-NEXT:    [[I42:%.*]] = shl nsw i32 [[I41]], 1
; CHECK-NEXT:    [[I43:%.*]] = sext i32 [[I42]] to i64
; CHECK-NEXT:    [[I44:%.*]] = and i64 [[I43]], 9223372036854775806
; CHECK-NEXT:    [[I45:%.*]] = icmp eq i64 [[I44]], 0
; CHECK-NEXT:    br i1 [[I45]], label [[BB69:%.*]], label [[BB46:%.*]]
; CHECK:       bb46:
; CHECK-NEXT:    [[I47:%.*]] = phi i64 [ 0, [[BB39]] ], [ [[I58:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I48:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I57:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I49:%.*]] = phi i64 [ 1, [[BB39]] ], [ [[I60:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I50:%.*]] = phi i64 [ 2806196910506780709, [[BB39]] ], [ [[I61:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I51:%.*]] = phi i64 [ [[I44]], [[BB39]] ], [ [[I62:%.*]], [[BB46]] ]
; CHECK-NEXT:    [[I52:%.*]] = and i64 [[I51]], 1
; CHECK-NEXT:    [[I53:%.*]] = icmp eq i64 [[I52]], 0
; CHECK-NEXT:    [[I54:%.*]] = mul i64 [[I50]], [[I47]]
; CHECK-NEXT:    [[I55:%.*]] = add i64 [[I54]], [[I49]]
; CHECK-NEXT:    [[I56:%.*]] = select i1 [[I53]], i64 1, i64 [[I50]]
; CHECK-NEXT:    [[I57]] = mul i64 [[I56]], [[I48]]
; CHECK-NEXT:    [[I58]] = select i1 [[I53]], i64 [[I47]], i64 [[I55]]
; CHECK-NEXT:    [[I59:%.*]] = add i64 [[I50]], 1
; CHECK-NEXT:    [[I60]] = mul i64 [[I59]], [[I49]]
; CHECK-NEXT:    [[I61]] = mul i64 [[I50]], [[I50]]
; CHECK-NEXT:    [[I62]] = lshr i64 [[I51]], 1
; CHECK-NEXT:    [[I63:%.*]] = icmp ult i64 [[I51]], 2
; CHECK-NEXT:    br i1 [[I63]], label [[BB64:%.*]], label [[BB46]]
; CHECK:       bb64:
; CHECK-NEXT:    [[I67:%.*]] = mul i64 [[I57]], 1070
; CHECK-NEXT:    [[I68:%.*]] = add i64 [[I67]], [[I58]]
; CHECK-NEXT:    br label [[BB69]]
; CHECK:       bb69:
; CHECK-NEXT:    [[I70:%.*]] = phi i64 [ [[I68]], [[BB64]] ], [ 1070, [[BB39]] ]
; CHECK-NEXT:    [[I71:%.*]] = mul i64 [[I70]], 2806196910506780709
; CHECK-NEXT:    [[I72:%.*]] = add i64 [[I71]], 1
; CHECK-NEXT:    [[I73:%.*]] = and i64 [[I72]], 9223372036854775807
; CHECK-NEXT:    [[I74:%.*]] = uitofp i64 [[I73]] to double
; CHECK-NEXT:    [[I75:%.*]] = fmul double [[I74]], 0x3C00000000000000
; CHECK-NEXT:    [[I76:%.*]] = mul i64 [[I72]], 2806196910506780709
; CHECK-NEXT:    [[I77:%.*]] = add i64 [[I76]], 1
; CHECK-NEXT:    [[I78:%.*]] = and i64 [[I77]], 9223372036854775807
; CHECK-NEXT:    [[I79:%.*]] = uitofp i64 [[I78]] to double
; CHECK-NEXT:    [[I80:%.*]] = fmul double [[I79]], 0x3C00000000000000
; CHECK-NEXT:    [[I81:%.*]] = fcmp uge double [[I80]], 5.200000e-02
; CHECK-NEXT:    br i1 [[I81]], label [[BB82:%.*]], label [[BB103:%.*]]
; CHECK:       bb82:
; CHECK-NEXT:    [[I83:%.*]] = fcmp uge double [[I80]], 3.270000e-01
; CHECK-NEXT:    br i1 [[I83]], label [[BB84:%.*]], label [[BB103]]
; CHECK:       bb84:
; CHECK-NEXT:    [[I85:%.*]] = fcmp uge double [[I80]], 4.610000e-01
; CHECK-NEXT:    br i1 [[I85]], label [[BB86:%.*]], label [[BB103]]
; CHECK:       bb86:
; CHECK-NEXT:    [[I87:%.*]] = fcmp uge double [[I80]], 0x3FE3AE147AE147AF
; CHECK-NEXT:    br i1 [[I87]], label [[BB88:%.*]], label [[BB103]]
; CHECK:       bb88:
; CHECK-NEXT:    [[I89:%.*]] = fcmp uge double [[I80]], 6.790000e-01
; CHECK-NEXT:    br i1 [[I89]], label [[BB90:%.*]], label [[BB103]]
; CHECK:       bb90:
; CHECK-NEXT:    [[I91:%.*]] = fcmp uge double [[I80]], 0x3FE7D70A3D70A3D8
; CHECK-NEXT:    br i1 [[I91]], label [[BB92:%.*]], label [[BB103]]
; CHECK:       bb92:
; CHECK-NEXT:    [[I93:%.*]] = fcmp uge double [[I80]], 8.000000e-01
; CHECK-NEXT:    br i1 [[I93]], label [[BB94:%.*]], label [[BB103]]
; CHECK:       bb94:
; CHECK-NEXT:    [[I95:%.*]] = fcmp uge double [[I80]], 8.080000e-01
; CHECK-NEXT:    br i1 [[I95]], label [[BB96:%.*]], label [[BB103]]
; CHECK:       bb96:
; CHECK-NEXT:    [[I97:%.*]] = fcmp uge double [[I80]], 0x3FEA5604189374BD
; CHECK-NEXT:    br i1 [[I97]], label [[BB98:%.*]], label [[BB103]]
; CHECK:       bb98:
; CHECK-NEXT:    [[I99:%.*]] = fcmp uge double [[I80]], 0x3FEB22D0E560418A
; CHECK-NEXT:    br i1 [[I99]], label [[BB100:%.*]], label [[BB103]]
; CHECK:       bb100:
; CHECK-NEXT:    [[I101:%.*]] = fcmp uge double [[I80]], 0x3FEB8D4FDF3B645B
; CHECK-NEXT:    br i1 [[I101]], label [[BB103_FROM_BB102:%.*]], label [[BB103]]
; CHECK:       bb103.from.bb102:
; CHECK-NEXT:    br label [[BB103]]
; CHECK:       bb103:
; CHECK-NEXT:    [[I104:%.*]] = phi i32 [ 0, [[BB103_FROM_BB102]] ], [ 1, [[BB69]] ], [ 2, [[BB82]] ], [ 3, [[BB84]] ], [ 4, [[BB86]] ], [ 5, [[BB88]] ], [ 6, [[BB90]] ], [ 7, [[BB92]] ], [ 8, [[BB94]] ], [ 9, [[BB96]] ], [ 10, [[BB98]] ], [ 11, [[BB100]] ]
; CHECK-NEXT:    [[I105:%.*]] = load i64, ptr [[I19244]], align 8, !tbaa [[TBAA27]]
; CHECK-NEXT:    [[I106:%.*]] = load i64, ptr [[I20251]], align 8, !tbaa [[TBAA28]]
; CHECK-NEXT:    [[I107:%.*]] = load ptr, ptr [[ARG2]], align 8, !tbaa [[TBAA29]]
; CHECK-NEXT:    [[I108:%.*]] = load ptr, ptr [[I21291]], align 8, !tbaa [[TBAA31]]
; CHECK-NEXT:    [[I109:%.*]] = load ptr, ptr [[I22298]], align 8, !tbaa [[TBAA32]]
; CHECK-NEXT:    [[I110:%.*]] = load ptr, ptr [[I23305]], align 8, !tbaa [[TBAA33]]
; CHECK-NEXT:    [[I111:%.*]] = load ptr, ptr [[I24312]], align 8, !tbaa [[TBAA34]]
; CHECK-NEXT:    [[I112:%.*]] = load ptr, ptr [[I25319]], align 8, !tbaa [[TBAA35]]
; CHECK-NEXT:    [[I113:%.*]] = load i32, ptr [[I26258]], align 8, !tbaa [[TBAA36]]
; CHECK-NEXT:    [[I114:%.*]] = load i32, ptr [[I27265]], align 4, !tbaa [[TBAA37]]
; CHECK-NEXT:    [[I115:%.*]] = load i32, ptr [[I28326]], align 4, !tbaa [[TBAA38]]
; CHECK-NEXT:    switch i32 [[I113]], label [[BB139:%.*]] [
; CHECK-NEXT:      i32 0, label [[BB116:%.*]]
; CHECK-NEXT:      i32 2, label [[CACHESTORE0:%.*]]
; CHECK-NEXT:    ]
; CHECK:       bb116:
; CHECK-NEXT:    [[I117:%.*]] = mul nsw i64 [[I106]], [[I105]]
; CHECK-NEXT:    [[I118:%.*]] = icmp sgt i64 [[I117]], 2
; CHECK-NEXT:    br i1 [[I118]], label [[BB119:%.*]], label [[BB139]]
; CHECK:       bb119:
; CHECK-NEXT:    [[I120:%.*]] = add nsw i64 [[I117]], -1
; CHECK-NEXT:    br label [[BB121:%.*]]
; CHECK:       bb121:
; CHECK-NEXT:    [[I122:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I132:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I123:%.*]] = phi i64 [ 0, [[BB119]] ], [ [[I131:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I124:%.*]] = phi i64 [ [[I120]], [[BB119]] ], [ [[I130:%.*]], [[BB121]] ]
; CHECK-NEXT:    [[I125:%.*]] = lshr i64 [[I122]], 1
; CHECK-NEXT:    [[I126:%.*]] = add nuw nsw i64 [[I125]], [[I123]]
; CHECK-NEXT:    [[I127:%.*]] = getelementptr inbounds double, ptr [[I109]], i64 [[I126]]
; CHECK-NEXT:    [[I128:%.*]] = load double, ptr [[I127]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    [[I129:%.*]] = fcmp ogt double [[I128]], [[I75]]
; CHECK-NEXT:    [[I130]] = select i1 [[I129]], i64 [[I126]], i64 [[I124]]
; CHECK-NEXT:    [[I131]] = select i1 [[I129]], i64 [[I123]], i64 [[I126]]
; CHECK-NEXT:    [[I132]] = sub nsw i64 [[I130]], [[I131]]
; CHECK-NEXT:    [[I133:%.*]] = icmp sgt i64 [[I132]], 1
; CHECK-NEXT:    br i1 [[I133]], label [[BB121]], label [[BB139]]
; CHECK:       CacheStore0:
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[TMP9]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP10]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET:%.*]] = load i32, ptr [[TMP11]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I10135]], ptr [[TMP12]], align 4, !invariant.group [[META41]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[TMP13]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I70]], ptr [[TMP14]], align 8, !invariant.group [[META42]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[TMP15]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I115]], ptr [[TMP17]], align 4, !invariant.group [[META43]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[TMP18]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP19]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP20]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I114]], ptr [[TMP21]], align 4, !invariant.group [[META44]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i64, ptr [[TMP22]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP23]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP25]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 2, ptr [[TMP26]], align 4, !invariant.group [[META45]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP27]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP29]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i32, ptr [[TMP30]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds ptr, ptr [[TMP31]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I112]], ptr [[TMP32]], align 8, !invariant.group [[META46]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i64, ptr [[TMP33]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i32, ptr [[TMP34]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i32, ptr [[TMP35]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i32, ptr [[TMP36]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds ptr, ptr [[TMP37]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds ptr, ptr [[TMP38]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I111]], ptr [[TMP39]], align 8, !invariant.group [[META47]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds i64, ptr [[TMP40]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds i32, ptr [[TMP41]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i32, ptr [[TMP42]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, ptr [[TMP43]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds ptr, ptr [[TMP44]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds ptr, ptr [[TMP45]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP47:%.*]] = getelementptr inbounds ptr, ptr [[TMP46]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I110]], ptr [[TMP47]], align 8, !invariant.group [[META48]]
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds i64, ptr [[TMP48]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP50:%.*]] = getelementptr inbounds i32, ptr [[TMP49]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP51:%.*]] = getelementptr inbounds i32, ptr [[TMP50]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i32, ptr [[TMP51]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds ptr, ptr [[TMP52]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds ptr, ptr [[TMP53]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds ptr, ptr [[TMP54]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP56:%.*]] = getelementptr inbounds ptr, ptr [[TMP55]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I108]], ptr [[TMP56]], align 8, !invariant.group [[META49]]
; CHECK-NEXT:    [[TMP57:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP58:%.*]] = getelementptr inbounds i64, ptr [[TMP57]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i32, ptr [[TMP58]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds i32, ptr [[TMP59]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP61:%.*]] = getelementptr inbounds i32, ptr [[TMP60]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP62:%.*]] = getelementptr inbounds ptr, ptr [[TMP61]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds ptr, ptr [[TMP62]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds ptr, ptr [[TMP63]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds ptr, ptr [[TMP64]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP66:%.*]] = getelementptr inbounds ptr, ptr [[TMP65]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[I107]], ptr [[TMP66]], align 8, !invariant.group [[META50]]
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr inbounds i64, ptr [[TMP67]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP69:%.*]] = getelementptr inbounds i32, ptr [[TMP68]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP70:%.*]] = getelementptr inbounds i32, ptr [[TMP69]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP71:%.*]] = getelementptr inbounds i32, ptr [[TMP70]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP72:%.*]] = getelementptr inbounds ptr, ptr [[TMP71]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP73:%.*]] = getelementptr inbounds ptr, ptr [[TMP72]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds ptr, ptr [[TMP73]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP75:%.*]] = getelementptr inbounds ptr, ptr [[TMP74]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP76:%.*]] = getelementptr inbounds ptr, ptr [[TMP75]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP77:%.*]] = getelementptr inbounds i64, ptr [[TMP76]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I106]], ptr [[TMP77]], align 8, !invariant.group [[META51]]
; CHECK-NEXT:    [[TMP78:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP79:%.*]] = getelementptr inbounds i64, ptr [[TMP78]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP80:%.*]] = getelementptr inbounds i32, ptr [[TMP79]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP81:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP82:%.*]] = getelementptr inbounds i32, ptr [[TMP81]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP83:%.*]] = getelementptr inbounds ptr, ptr [[TMP82]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP84:%.*]] = getelementptr inbounds ptr, ptr [[TMP83]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP85:%.*]] = getelementptr inbounds ptr, ptr [[TMP84]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP86:%.*]] = getelementptr inbounds ptr, ptr [[TMP85]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP87:%.*]] = getelementptr inbounds ptr, ptr [[TMP86]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP88:%.*]] = getelementptr inbounds i64, ptr [[TMP87]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP89:%.*]] = getelementptr inbounds i64, ptr [[TMP88]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I105]], ptr [[TMP89]], align 8, !invariant.group [[META52]]
; CHECK-NEXT:    [[TMP90:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP91:%.*]] = getelementptr inbounds i64, ptr [[TMP90]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr inbounds i32, ptr [[TMP91]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP93:%.*]] = getelementptr inbounds i32, ptr [[TMP92]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP94:%.*]] = getelementptr inbounds i32, ptr [[TMP93]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP95:%.*]] = getelementptr inbounds ptr, ptr [[TMP94]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP96:%.*]] = getelementptr inbounds ptr, ptr [[TMP95]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP97:%.*]] = getelementptr inbounds ptr, ptr [[TMP96]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP98:%.*]] = getelementptr inbounds ptr, ptr [[TMP97]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP99:%.*]] = getelementptr inbounds ptr, ptr [[TMP98]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP100:%.*]] = getelementptr inbounds i64, ptr [[TMP99]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i64, ptr [[TMP100]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP102:%.*]] = getelementptr inbounds i32, ptr [[TMP101]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I104]], ptr [[TMP102]], align 4, !invariant.group [[META53]]
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds i64, ptr [[TMP103]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds i32, ptr [[TMP104]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds i32, ptr [[TMP105]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i32, ptr [[TMP106]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds ptr, ptr [[TMP107]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds ptr, ptr [[TMP108]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP110:%.*]] = getelementptr inbounds ptr, ptr [[TMP109]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP111:%.*]] = getelementptr inbounds ptr, ptr [[TMP110]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP112:%.*]] = getelementptr inbounds ptr, ptr [[TMP111]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP113:%.*]] = getelementptr inbounds i64, ptr [[TMP112]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP114:%.*]] = getelementptr inbounds i64, ptr [[TMP113]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP115:%.*]] = getelementptr inbounds i32, ptr [[TMP114]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP116:%.*]] = getelementptr inbounds i64, ptr [[TMP115]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i64 [[I40]], ptr [[TMP116]], align 8, !invariant.group [[META54]]
; CHECK-NEXT:    [[TMP117:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP118:%.*]] = getelementptr inbounds i64, ptr [[TMP117]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP119:%.*]] = getelementptr inbounds i32, ptr [[TMP118]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds i32, ptr [[TMP119]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP121:%.*]] = getelementptr inbounds i32, ptr [[TMP120]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP122:%.*]] = getelementptr inbounds ptr, ptr [[TMP121]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP123:%.*]] = getelementptr inbounds ptr, ptr [[TMP122]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP124:%.*]] = getelementptr inbounds ptr, ptr [[TMP123]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr inbounds ptr, ptr [[TMP124]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr inbounds ptr, ptr [[TMP125]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP127:%.*]] = getelementptr inbounds i64, ptr [[TMP126]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP128:%.*]] = getelementptr inbounds i64, ptr [[TMP127]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP129:%.*]] = getelementptr inbounds i32, ptr [[TMP128]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP130:%.*]] = getelementptr inbounds i64, ptr [[TMP129]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP131:%.*]] = getelementptr inbounds i32, ptr [[TMP130]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I31170]], ptr [[TMP131]], align 4, !invariant.group [[META55]]
; CHECK-NEXT:    [[TMP132:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP133:%.*]] = getelementptr inbounds i64, ptr [[TMP132]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP134:%.*]] = getelementptr inbounds i32, ptr [[TMP133]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP135:%.*]] = getelementptr inbounds i32, ptr [[TMP134]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP136:%.*]] = getelementptr inbounds i32, ptr [[TMP135]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP137:%.*]] = getelementptr inbounds ptr, ptr [[TMP136]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP138:%.*]] = getelementptr inbounds ptr, ptr [[TMP137]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP139:%.*]] = getelementptr inbounds ptr, ptr [[TMP138]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP140:%.*]] = getelementptr inbounds ptr, ptr [[TMP139]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP141:%.*]] = getelementptr inbounds ptr, ptr [[TMP140]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP142:%.*]] = getelementptr inbounds i64, ptr [[TMP141]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP143:%.*]] = getelementptr inbounds i64, ptr [[TMP142]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP144:%.*]] = getelementptr inbounds i32, ptr [[TMP143]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP145:%.*]] = getelementptr inbounds i64, ptr [[TMP144]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP146:%.*]] = getelementptr inbounds i32, ptr [[TMP145]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP147:%.*]] = getelementptr inbounds i32, ptr [[TMP146]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I30176]], ptr [[TMP147]], align 4, !invariant.group [[META56]]
; CHECK-NEXT:    [[TMP148:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP149:%.*]] = getelementptr inbounds i64, ptr [[TMP148]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP150:%.*]] = getelementptr inbounds i32, ptr [[TMP149]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP151:%.*]] = getelementptr inbounds i32, ptr [[TMP150]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP152:%.*]] = getelementptr inbounds i32, ptr [[TMP151]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP153:%.*]] = getelementptr inbounds ptr, ptr [[TMP152]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP154:%.*]] = getelementptr inbounds ptr, ptr [[TMP153]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP155:%.*]] = getelementptr inbounds ptr, ptr [[TMP154]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP156:%.*]] = getelementptr inbounds ptr, ptr [[TMP155]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP157:%.*]] = getelementptr inbounds ptr, ptr [[TMP156]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP158:%.*]] = getelementptr inbounds i64, ptr [[TMP157]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP159:%.*]] = getelementptr inbounds i64, ptr [[TMP158]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP160:%.*]] = getelementptr inbounds i32, ptr [[TMP159]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP161:%.*]] = getelementptr inbounds i64, ptr [[TMP160]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP162:%.*]] = getelementptr inbounds i32, ptr [[TMP161]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP163:%.*]] = getelementptr inbounds i32, ptr [[TMP162]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP164:%.*]] = getelementptr inbounds i32, ptr [[TMP163]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I5182]], ptr [[TMP164]], align 4, !invariant.group [[META57]]
; CHECK-NEXT:    [[TMP165:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP166:%.*]] = getelementptr inbounds i64, ptr [[TMP165]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP167:%.*]] = getelementptr inbounds i32, ptr [[TMP166]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP168:%.*]] = getelementptr inbounds i32, ptr [[TMP167]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP169:%.*]] = getelementptr inbounds i32, ptr [[TMP168]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP170:%.*]] = getelementptr inbounds ptr, ptr [[TMP169]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP171:%.*]] = getelementptr inbounds ptr, ptr [[TMP170]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP172:%.*]] = getelementptr inbounds ptr, ptr [[TMP171]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP173:%.*]] = getelementptr inbounds ptr, ptr [[TMP172]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP174:%.*]] = getelementptr inbounds ptr, ptr [[TMP173]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP175:%.*]] = getelementptr inbounds i64, ptr [[TMP174]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP176:%.*]] = getelementptr inbounds i64, ptr [[TMP175]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP177:%.*]] = getelementptr inbounds i32, ptr [[TMP176]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP178:%.*]] = getelementptr inbounds i64, ptr [[TMP177]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP179:%.*]] = getelementptr inbounds i32, ptr [[TMP178]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP180:%.*]] = getelementptr inbounds i32, ptr [[TMP179]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP181:%.*]] = getelementptr inbounds i32, ptr [[TMP180]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP182:%.*]] = getelementptr inbounds i32, ptr [[TMP181]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I212]], ptr [[TMP182]], align 4, !invariant.group [[META58]]
; CHECK-NEXT:    [[TMP183:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP184:%.*]] = getelementptr inbounds i64, ptr [[TMP183]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP185:%.*]] = getelementptr inbounds i32, ptr [[TMP184]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP186:%.*]] = getelementptr inbounds i32, ptr [[TMP185]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP187:%.*]] = getelementptr inbounds i32, ptr [[TMP186]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP188:%.*]] = getelementptr inbounds ptr, ptr [[TMP187]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP189:%.*]] = getelementptr inbounds ptr, ptr [[TMP188]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP190:%.*]] = getelementptr inbounds ptr, ptr [[TMP189]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP191:%.*]] = getelementptr inbounds ptr, ptr [[TMP190]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP192:%.*]] = getelementptr inbounds ptr, ptr [[TMP191]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP193:%.*]] = getelementptr inbounds i64, ptr [[TMP192]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP194:%.*]] = getelementptr inbounds i64, ptr [[TMP193]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP195:%.*]] = getelementptr inbounds i32, ptr [[TMP194]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP196:%.*]] = getelementptr inbounds i64, ptr [[TMP195]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP197:%.*]] = getelementptr inbounds i32, ptr [[TMP196]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP198:%.*]] = getelementptr inbounds i32, ptr [[TMP197]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP199:%.*]] = getelementptr inbounds i32, ptr [[TMP198]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP200:%.*]] = getelementptr inbounds i32, ptr [[TMP199]], i32 [[CACHE_OUT_OFFSET]]
; CHECK-NEXT:    [[TMP201:%.*]] = getelementptr inbounds i32, ptr [[TMP200]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store i32 [[I18222]], ptr [[TMP201]], align 4, !invariant.group [[META59]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb139:
; CHECK-NEXT:    [[I140:%.*]] = phi i64 [ -1, [[BB103]] ], [ 0, [[BB116]] ], [ [[I131]], [[BB121]] ]
; CHECK-NEXT:    [[I141:%.*]] = zext nneg i32 [[I104]] to i64
; CHECK-NEXT:    [[I142:%.*]] = getelementptr inbounds i32, ptr [[I107]], i64 [[I141]]
; CHECK-NEXT:    [[I143:%.*]] = load i32, ptr [[I142]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I144:%.*]] = icmp sgt i32 [[I143]], 0
; CHECK-NEXT:    br i1 [[I144]], label [[BB145:%.*]], label [[BB302]]
; CHECK:       bb145:
; CHECK-NEXT:    [[I146:%.*]] = mul nsw i32 [[I115]], [[I104]]
; CHECK-NEXT:    [[I147:%.*]] = mul nsw i64 [[I140]], [[I105]]
; CHECK-NEXT:    [[I148:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I147]]
; CHECK-NEXT:    [[I149:%.*]] = add i64 [[I106]], -1
; CHECK-NEXT:    [[I150:%.*]] = icmp sgt i64 [[I106]], 2
; CHECK-NEXT:    [[I151:%.*]] = add nsw i32 [[I114]], -1
; CHECK-NEXT:    [[I152:%.*]] = sext i32 [[I151]] to i64
; CHECK-NEXT:    [[I153:%.*]] = icmp eq i64 [[I140]], [[I152]]
; CHECK-NEXT:    [[I154:%.*]] = add nsw i64 [[I140]], 1
; CHECK-NEXT:    [[I155:%.*]] = mul nsw i64 [[I154]], [[I105]]
; CHECK-NEXT:    [[I156:%.*]] = getelementptr i32, ptr [[I110]], i64 [[I155]]
; CHECK-NEXT:    [[I157:%.*]] = trunc i64 [[I106]] to i32
; CHECK-NEXT:    [[I158:%.*]] = add i32 [[I157]], -1
; CHECK-NEXT:    br label [[BB159:%.*]]
; CHECK:       bb159:
; CHECK-NEXT:    [[I149345:%.*]] = phi i64 [ [[I149]], [[BB145]] ], [ [[I149344:%.*]], [[BB255:%.*]] ]
; CHECK-NEXT:    [[I156336:%.*]] = phi ptr [ [[I156]], [[BB145]] ], [ [[I156335:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I148334:%.*]] = phi ptr [ [[I148]], [[BB145]] ], [ [[I148333:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I153332:%.*]] = phi i1 [ [[I153]], [[BB145]] ], [ [[I153331:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I146330:%.*]] = phi i32 [ [[I146]], [[BB145]] ], [ [[I146329:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I142328:%.*]] = phi ptr [ [[I142]], [[BB145]] ], [ [[I142327:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I28324:%.*]] = phi ptr [ [[I28326]], [[BB145]] ], [ [[I28321:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I25317:%.*]] = phi ptr [ [[I25319]], [[BB145]] ], [ [[I25314:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I24310:%.*]] = phi ptr [ [[I24312]], [[BB145]] ], [ [[I24307:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I23303:%.*]] = phi ptr [ [[I23305]], [[BB145]] ], [ [[I23300:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I22296:%.*]] = phi ptr [ [[I22298]], [[BB145]] ], [ [[I22293:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I21289:%.*]] = phi ptr [ [[I21291]], [[BB145]] ], [ [[I21286:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I6281:%.*]] = phi i32 [ [[I6283]], [[BB145]] ], [ [[I6278:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I32276:%.*]] = phi i64 [ [[I32277]], [[BB145]] ], [ [[I32273:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I41272:%.*]] = phi i32 [ [[I41]], [[BB145]] ], [ [[I41269:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I75268:%.*]] = phi double [ [[I75]], [[BB145]] ], [ [[I75266:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I27263:%.*]] = phi ptr [ [[I27265]], [[BB145]] ], [ [[I27260:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I26256:%.*]] = phi ptr [ [[I26258]], [[BB145]] ], [ [[I26253:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I20249:%.*]] = phi ptr [ [[I20251]], [[BB145]] ], [ [[I20246:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I19242:%.*]] = phi ptr [ [[I19244]], [[BB145]] ], [ [[I19239:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I4234:%.*]] = phi ptr [ [[I4236]], [[BB145]] ], [ [[I4231:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I13228:%.*]] = phi i32 [ [[I13230]], [[BB145]] ], [ [[I13224:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I18220:%.*]] = phi i32 [ [[I18222]], [[BB145]] ], [ [[I18217:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I197:%.*]] = phi i32 [ [[I212]], [[BB145]] ], [ [[I189:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I5180:%.*]] = phi i32 [ [[I5182]], [[BB145]] ], [ [[I5177:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I30174:%.*]] = phi i32 [ [[I30176]], [[BB145]] ], [ [[I30171:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I31168:%.*]] = phi i32 [ [[I31170]], [[BB145]] ], [ [[I31165:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I40164:%.*]] = phi i64 [ [[I40]], [[BB145]] ], [ [[I40161:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I106158:%.*]] = phi i64 [ [[I106]], [[BB145]] ], [ [[I106157:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I108154:%.*]] = phi ptr [ [[I108]], [[BB145]] ], [ [[I108153:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I111150:%.*]] = phi ptr [ [[I111]], [[BB145]] ], [ [[I111149:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I112147:%.*]] = phi ptr [ [[I112]], [[BB145]] ], [ [[I112146:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I113144:%.*]] = phi i32 [ [[I113]], [[BB145]] ], [ [[I113143:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I70139:%.*]] = phi i64 [ [[I70]], [[BB145]] ], [ [[I70137:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I10133:%.*]] = phi i32 [ [[I10135]], [[BB145]] ], [ [[I10130:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I160:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I298:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I161:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I297:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I162:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I296:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I163:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I295:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I164:%.*]] = phi double [ 0.000000e+00, [[BB145]] ], [ [[I294:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I165:%.*]] = phi i32 [ 0, [[BB145]] ], [ [[I299:%.*]], [[BB255]] ]
; CHECK-NEXT:    [[I166:%.*]] = add nsw i32 [[I165]], [[I146330]]
; CHECK-NEXT:    [[I167:%.*]] = sext i32 [[I166]] to i64
; CHECK-NEXT:    [[I168:%.*]] = getelementptr inbounds i32, ptr [[I112147]], i64 [[I167]]
; CHECK-NEXT:    [[I169:%.*]] = load i32, ptr [[I168]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I170:%.*]] = getelementptr inbounds double, ptr [[I108154]], i64 [[I167]]
; CHECK-NEXT:    [[I171:%.*]] = load double, ptr [[I170]], align 8, !tbaa [[TBAA39]]
; CHECK-NEXT:    switch i32 [[I113144]], label [[CACHESTORE2:%.*]] [
; CHECK-NEXT:      i32 1, label [[CACHESTORE1:%.*]]
; CHECK-NEXT:      i32 0, label [[BB197:%.*]]
; CHECK-NEXT:    ]
; CHECK:       CacheStore1:
; CHECK-NEXT:    [[TMP202:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP203:%.*]] = load ptr, ptr [[TMP202]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR27:%.*]] = getelementptr inbounds i32, ptr [[TMP203]], i32 1
; CHECK-NEXT:    [[CACHEIDX28:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR27]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP204:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP205:%.*]] = load ptr, ptr [[TMP204]], align 8
; CHECK-NEXT:    [[TMP206:%.*]] = getelementptr inbounds ptr, ptr [[TMP205]], i32 1
; CHECK-NEXT:    [[CACHE_OUT_PTR29:%.*]] = load ptr, ptr [[TMP206]], align 8
; CHECK-NEXT:    [[TMP207:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET30:%.*]] = load i32, ptr [[TMP207]], align 4
; CHECK-NEXT:    [[TMP208:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP208]], align 4, !invariant.group [[META61]]
; CHECK-NEXT:    [[TMP209:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP210:%.*]] = getelementptr inbounds i64, ptr [[TMP209]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP210]], align 8, !invariant.group [[META62]]
; CHECK-NEXT:    [[TMP211:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP212:%.*]] = getelementptr inbounds i64, ptr [[TMP211]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP213:%.*]] = getelementptr inbounds ptr, ptr [[TMP212]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP213]], align 8, !invariant.group [[META63]]
; CHECK-NEXT:    [[TMP214:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP215:%.*]] = getelementptr inbounds i64, ptr [[TMP214]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP216:%.*]] = getelementptr inbounds ptr, ptr [[TMP215]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP217:%.*]] = getelementptr inbounds i32, ptr [[TMP216]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP217]], align 4, !invariant.group [[META64]]
; CHECK-NEXT:    [[TMP218:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP219:%.*]] = getelementptr inbounds i64, ptr [[TMP218]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP220:%.*]] = getelementptr inbounds ptr, ptr [[TMP219]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP221:%.*]] = getelementptr inbounds i32, ptr [[TMP220]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP222:%.*]] = getelementptr inbounds i1, ptr [[TMP221]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP222]], align 1, !invariant.group [[META65]]
; CHECK-NEXT:    [[TMP223:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP224:%.*]] = getelementptr inbounds i64, ptr [[TMP223]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP225:%.*]] = getelementptr inbounds ptr, ptr [[TMP224]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP226:%.*]] = getelementptr inbounds i32, ptr [[TMP225]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP227:%.*]] = getelementptr inbounds i1, ptr [[TMP226]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP228:%.*]] = getelementptr inbounds ptr, ptr [[TMP227]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP228]], align 8, !invariant.group [[META66]]
; CHECK-NEXT:    [[TMP229:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP230:%.*]] = getelementptr inbounds i64, ptr [[TMP229]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP231:%.*]] = getelementptr inbounds ptr, ptr [[TMP230]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP232:%.*]] = getelementptr inbounds i32, ptr [[TMP231]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP233:%.*]] = getelementptr inbounds i1, ptr [[TMP232]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP234:%.*]] = getelementptr inbounds ptr, ptr [[TMP233]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP235:%.*]] = getelementptr inbounds ptr, ptr [[TMP234]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP235]], align 8, !invariant.group [[META67]]
; CHECK-NEXT:    [[TMP236:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP237:%.*]] = getelementptr inbounds i64, ptr [[TMP236]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP238:%.*]] = getelementptr inbounds ptr, ptr [[TMP237]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP239:%.*]] = getelementptr inbounds i32, ptr [[TMP238]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP240:%.*]] = getelementptr inbounds i1, ptr [[TMP239]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP241:%.*]] = getelementptr inbounds ptr, ptr [[TMP240]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP242:%.*]] = getelementptr inbounds ptr, ptr [[TMP241]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP243:%.*]] = getelementptr inbounds double, ptr [[TMP242]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP243]], align 8, !invariant.group [[META68]]
; CHECK-NEXT:    [[TMP244:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP245:%.*]] = getelementptr inbounds i64, ptr [[TMP244]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP246:%.*]] = getelementptr inbounds ptr, ptr [[TMP245]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP247:%.*]] = getelementptr inbounds i32, ptr [[TMP246]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP248:%.*]] = getelementptr inbounds i1, ptr [[TMP247]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP249:%.*]] = getelementptr inbounds ptr, ptr [[TMP248]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP250:%.*]] = getelementptr inbounds ptr, ptr [[TMP249]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr inbounds double, ptr [[TMP250]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr inbounds i32, ptr [[TMP251]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP252]], align 4, !invariant.group [[META69]]
; CHECK-NEXT:    [[TMP253:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP254:%.*]] = getelementptr inbounds i64, ptr [[TMP253]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP255:%.*]] = getelementptr inbounds ptr, ptr [[TMP254]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr inbounds i32, ptr [[TMP255]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr inbounds i1, ptr [[TMP256]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP258:%.*]] = getelementptr inbounds ptr, ptr [[TMP257]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr inbounds ptr, ptr [[TMP258]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr inbounds double, ptr [[TMP259]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP261:%.*]] = getelementptr inbounds i32, ptr [[TMP260]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP262:%.*]] = getelementptr inbounds i32, ptr [[TMP261]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP262]], align 4, !invariant.group [[META70]]
; CHECK-NEXT:    [[TMP263:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP264:%.*]] = getelementptr inbounds i64, ptr [[TMP263]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP265:%.*]] = getelementptr inbounds ptr, ptr [[TMP264]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP266:%.*]] = getelementptr inbounds i32, ptr [[TMP265]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP267:%.*]] = getelementptr inbounds i1, ptr [[TMP266]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP268:%.*]] = getelementptr inbounds ptr, ptr [[TMP267]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP269:%.*]] = getelementptr inbounds ptr, ptr [[TMP268]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP270:%.*]] = getelementptr inbounds double, ptr [[TMP269]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP271:%.*]] = getelementptr inbounds i32, ptr [[TMP270]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP272:%.*]] = getelementptr inbounds i32, ptr [[TMP271]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP273:%.*]] = getelementptr inbounds double, ptr [[TMP272]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP273]], align 8, !invariant.group [[META71]]
; CHECK-NEXT:    [[TMP274:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP275:%.*]] = getelementptr inbounds i64, ptr [[TMP274]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP276:%.*]] = getelementptr inbounds ptr, ptr [[TMP275]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP277:%.*]] = getelementptr inbounds i32, ptr [[TMP276]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP278:%.*]] = getelementptr inbounds i1, ptr [[TMP277]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP279:%.*]] = getelementptr inbounds ptr, ptr [[TMP278]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP280:%.*]] = getelementptr inbounds ptr, ptr [[TMP279]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP281:%.*]] = getelementptr inbounds double, ptr [[TMP280]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP282:%.*]] = getelementptr inbounds i32, ptr [[TMP281]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP283:%.*]] = getelementptr inbounds i32, ptr [[TMP282]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP284:%.*]] = getelementptr inbounds double, ptr [[TMP283]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP285:%.*]] = getelementptr inbounds double, ptr [[TMP284]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP285]], align 8, !invariant.group [[META72]]
; CHECK-NEXT:    [[TMP286:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP287:%.*]] = getelementptr inbounds i64, ptr [[TMP286]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP288:%.*]] = getelementptr inbounds ptr, ptr [[TMP287]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP289:%.*]] = getelementptr inbounds i32, ptr [[TMP288]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP290:%.*]] = getelementptr inbounds i1, ptr [[TMP289]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP291:%.*]] = getelementptr inbounds ptr, ptr [[TMP290]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP292:%.*]] = getelementptr inbounds ptr, ptr [[TMP291]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP293:%.*]] = getelementptr inbounds double, ptr [[TMP292]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP294:%.*]] = getelementptr inbounds i32, ptr [[TMP293]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP295:%.*]] = getelementptr inbounds i32, ptr [[TMP294]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP296:%.*]] = getelementptr inbounds double, ptr [[TMP295]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP297:%.*]] = getelementptr inbounds double, ptr [[TMP296]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP298:%.*]] = getelementptr inbounds double, ptr [[TMP297]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP298]], align 8, !invariant.group [[META73]]
; CHECK-NEXT:    [[TMP299:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP300:%.*]] = getelementptr inbounds i64, ptr [[TMP299]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP301:%.*]] = getelementptr inbounds ptr, ptr [[TMP300]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP302:%.*]] = getelementptr inbounds i32, ptr [[TMP301]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP303:%.*]] = getelementptr inbounds i1, ptr [[TMP302]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP304:%.*]] = getelementptr inbounds ptr, ptr [[TMP303]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP305:%.*]] = getelementptr inbounds ptr, ptr [[TMP304]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP306:%.*]] = getelementptr inbounds double, ptr [[TMP305]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP307:%.*]] = getelementptr inbounds i32, ptr [[TMP306]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP308:%.*]] = getelementptr inbounds i32, ptr [[TMP307]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP309:%.*]] = getelementptr inbounds double, ptr [[TMP308]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP310:%.*]] = getelementptr inbounds double, ptr [[TMP309]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP311:%.*]] = getelementptr inbounds double, ptr [[TMP310]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP312:%.*]] = getelementptr inbounds double, ptr [[TMP311]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP312]], align 8, !invariant.group [[META74]]
; CHECK-NEXT:    [[TMP313:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP314:%.*]] = getelementptr inbounds i64, ptr [[TMP313]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP315:%.*]] = getelementptr inbounds ptr, ptr [[TMP314]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP316:%.*]] = getelementptr inbounds i32, ptr [[TMP315]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP317:%.*]] = getelementptr inbounds i1, ptr [[TMP316]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP318:%.*]] = getelementptr inbounds ptr, ptr [[TMP317]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP319:%.*]] = getelementptr inbounds ptr, ptr [[TMP318]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP320:%.*]] = getelementptr inbounds double, ptr [[TMP319]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP321:%.*]] = getelementptr inbounds i32, ptr [[TMP320]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP322:%.*]] = getelementptr inbounds i32, ptr [[TMP321]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP323:%.*]] = getelementptr inbounds double, ptr [[TMP322]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP324:%.*]] = getelementptr inbounds double, ptr [[TMP323]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP325:%.*]] = getelementptr inbounds double, ptr [[TMP324]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP326:%.*]] = getelementptr inbounds double, ptr [[TMP325]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP327:%.*]] = getelementptr inbounds double, ptr [[TMP326]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP327]], align 8, !invariant.group [[META75]]
; CHECK-NEXT:    [[TMP328:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP329:%.*]] = getelementptr inbounds i64, ptr [[TMP328]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP330:%.*]] = getelementptr inbounds ptr, ptr [[TMP329]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP331:%.*]] = getelementptr inbounds i32, ptr [[TMP330]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP332:%.*]] = getelementptr inbounds i1, ptr [[TMP331]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP333:%.*]] = getelementptr inbounds ptr, ptr [[TMP332]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP334:%.*]] = getelementptr inbounds ptr, ptr [[TMP333]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP335:%.*]] = getelementptr inbounds double, ptr [[TMP334]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP336:%.*]] = getelementptr inbounds i32, ptr [[TMP335]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP337:%.*]] = getelementptr inbounds i32, ptr [[TMP336]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP338:%.*]] = getelementptr inbounds double, ptr [[TMP337]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP339:%.*]] = getelementptr inbounds double, ptr [[TMP338]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP340:%.*]] = getelementptr inbounds double, ptr [[TMP339]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP341:%.*]] = getelementptr inbounds double, ptr [[TMP340]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP342:%.*]] = getelementptr inbounds double, ptr [[TMP341]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP343:%.*]] = getelementptr inbounds i32, ptr [[TMP342]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 1, ptr [[TMP343]], align 4, !invariant.group [[META76]]
; CHECK-NEXT:    [[TMP344:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP345:%.*]] = getelementptr inbounds i64, ptr [[TMP344]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP346:%.*]] = getelementptr inbounds ptr, ptr [[TMP345]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP347:%.*]] = getelementptr inbounds i32, ptr [[TMP346]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP348:%.*]] = getelementptr inbounds i1, ptr [[TMP347]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP349:%.*]] = getelementptr inbounds ptr, ptr [[TMP348]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP350:%.*]] = getelementptr inbounds ptr, ptr [[TMP349]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP351:%.*]] = getelementptr inbounds double, ptr [[TMP350]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP352:%.*]] = getelementptr inbounds i32, ptr [[TMP351]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP353:%.*]] = getelementptr inbounds i32, ptr [[TMP352]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP354:%.*]] = getelementptr inbounds double, ptr [[TMP353]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP355:%.*]] = getelementptr inbounds double, ptr [[TMP354]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP356:%.*]] = getelementptr inbounds double, ptr [[TMP355]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP357:%.*]] = getelementptr inbounds double, ptr [[TMP356]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP358:%.*]] = getelementptr inbounds double, ptr [[TMP357]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP359:%.*]] = getelementptr inbounds i32, ptr [[TMP358]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP360:%.*]] = getelementptr inbounds ptr, ptr [[TMP359]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP360]], align 8, !invariant.group [[META77]]
; CHECK-NEXT:    [[TMP361:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP362:%.*]] = getelementptr inbounds i64, ptr [[TMP361]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP363:%.*]] = getelementptr inbounds ptr, ptr [[TMP362]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP364:%.*]] = getelementptr inbounds i32, ptr [[TMP363]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP365:%.*]] = getelementptr inbounds i1, ptr [[TMP364]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP366:%.*]] = getelementptr inbounds ptr, ptr [[TMP365]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP367:%.*]] = getelementptr inbounds ptr, ptr [[TMP366]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP368:%.*]] = getelementptr inbounds double, ptr [[TMP367]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP369:%.*]] = getelementptr inbounds i32, ptr [[TMP368]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP370:%.*]] = getelementptr inbounds i32, ptr [[TMP369]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP371:%.*]] = getelementptr inbounds double, ptr [[TMP370]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP372:%.*]] = getelementptr inbounds double, ptr [[TMP371]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP373:%.*]] = getelementptr inbounds double, ptr [[TMP372]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP374:%.*]] = getelementptr inbounds double, ptr [[TMP373]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP375:%.*]] = getelementptr inbounds double, ptr [[TMP374]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP376:%.*]] = getelementptr inbounds i32, ptr [[TMP375]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP377:%.*]] = getelementptr inbounds ptr, ptr [[TMP376]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP378:%.*]] = getelementptr inbounds ptr, ptr [[TMP377]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP378]], align 8, !invariant.group [[META78]]
; CHECK-NEXT:    [[TMP379:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP380:%.*]] = getelementptr inbounds i64, ptr [[TMP379]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP381:%.*]] = getelementptr inbounds ptr, ptr [[TMP380]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP382:%.*]] = getelementptr inbounds i32, ptr [[TMP381]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP383:%.*]] = getelementptr inbounds i1, ptr [[TMP382]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP384:%.*]] = getelementptr inbounds ptr, ptr [[TMP383]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP385:%.*]] = getelementptr inbounds ptr, ptr [[TMP384]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP386:%.*]] = getelementptr inbounds double, ptr [[TMP385]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP387:%.*]] = getelementptr inbounds i32, ptr [[TMP386]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP388:%.*]] = getelementptr inbounds i32, ptr [[TMP387]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP389:%.*]] = getelementptr inbounds double, ptr [[TMP388]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP390:%.*]] = getelementptr inbounds double, ptr [[TMP389]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP391:%.*]] = getelementptr inbounds double, ptr [[TMP390]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP392:%.*]] = getelementptr inbounds double, ptr [[TMP391]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP393:%.*]] = getelementptr inbounds double, ptr [[TMP392]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP394:%.*]] = getelementptr inbounds i32, ptr [[TMP393]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP395:%.*]] = getelementptr inbounds ptr, ptr [[TMP394]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP396:%.*]] = getelementptr inbounds ptr, ptr [[TMP395]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP397:%.*]] = getelementptr inbounds ptr, ptr [[TMP396]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP397]], align 8, !invariant.group [[META79]]
; CHECK-NEXT:    [[TMP398:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP399:%.*]] = getelementptr inbounds i64, ptr [[TMP398]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP400:%.*]] = getelementptr inbounds ptr, ptr [[TMP399]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP401:%.*]] = getelementptr inbounds i32, ptr [[TMP400]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP402:%.*]] = getelementptr inbounds i1, ptr [[TMP401]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP403:%.*]] = getelementptr inbounds ptr, ptr [[TMP402]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP404:%.*]] = getelementptr inbounds ptr, ptr [[TMP403]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP405:%.*]] = getelementptr inbounds double, ptr [[TMP404]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP406:%.*]] = getelementptr inbounds i32, ptr [[TMP405]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP407:%.*]] = getelementptr inbounds i32, ptr [[TMP406]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP408:%.*]] = getelementptr inbounds double, ptr [[TMP407]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP409:%.*]] = getelementptr inbounds double, ptr [[TMP408]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP410:%.*]] = getelementptr inbounds double, ptr [[TMP409]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP411:%.*]] = getelementptr inbounds double, ptr [[TMP410]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP412:%.*]] = getelementptr inbounds double, ptr [[TMP411]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP413:%.*]] = getelementptr inbounds i32, ptr [[TMP412]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP414:%.*]] = getelementptr inbounds ptr, ptr [[TMP413]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP415:%.*]] = getelementptr inbounds ptr, ptr [[TMP414]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP416:%.*]] = getelementptr inbounds ptr, ptr [[TMP415]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP417:%.*]] = getelementptr inbounds i64, ptr [[TMP416]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP417]], align 8, !invariant.group [[META80]]
; CHECK-NEXT:    [[TMP418:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP419:%.*]] = getelementptr inbounds i64, ptr [[TMP418]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP420:%.*]] = getelementptr inbounds ptr, ptr [[TMP419]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP421:%.*]] = getelementptr inbounds i32, ptr [[TMP420]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP422:%.*]] = getelementptr inbounds i1, ptr [[TMP421]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP423:%.*]] = getelementptr inbounds ptr, ptr [[TMP422]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP424:%.*]] = getelementptr inbounds ptr, ptr [[TMP423]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP425:%.*]] = getelementptr inbounds double, ptr [[TMP424]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP426:%.*]] = getelementptr inbounds i32, ptr [[TMP425]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP427:%.*]] = getelementptr inbounds i32, ptr [[TMP426]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP428:%.*]] = getelementptr inbounds double, ptr [[TMP427]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP429:%.*]] = getelementptr inbounds double, ptr [[TMP428]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP430:%.*]] = getelementptr inbounds double, ptr [[TMP429]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP431:%.*]] = getelementptr inbounds double, ptr [[TMP430]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP432:%.*]] = getelementptr inbounds double, ptr [[TMP431]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP433:%.*]] = getelementptr inbounds i32, ptr [[TMP432]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP434:%.*]] = getelementptr inbounds ptr, ptr [[TMP433]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP435:%.*]] = getelementptr inbounds ptr, ptr [[TMP434]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP436:%.*]] = getelementptr inbounds ptr, ptr [[TMP435]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP437:%.*]] = getelementptr inbounds i64, ptr [[TMP436]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP438:%.*]] = getelementptr inbounds i64, ptr [[TMP437]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP438]], align 8, !invariant.group [[META81]]
; CHECK-NEXT:    [[TMP439:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP440:%.*]] = getelementptr inbounds i64, ptr [[TMP439]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP441:%.*]] = getelementptr inbounds ptr, ptr [[TMP440]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP442:%.*]] = getelementptr inbounds i32, ptr [[TMP441]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP443:%.*]] = getelementptr inbounds i1, ptr [[TMP442]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP444:%.*]] = getelementptr inbounds ptr, ptr [[TMP443]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP445:%.*]] = getelementptr inbounds ptr, ptr [[TMP444]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP446:%.*]] = getelementptr inbounds double, ptr [[TMP445]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP447:%.*]] = getelementptr inbounds i32, ptr [[TMP446]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP448:%.*]] = getelementptr inbounds i32, ptr [[TMP447]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP449:%.*]] = getelementptr inbounds double, ptr [[TMP448]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP450:%.*]] = getelementptr inbounds double, ptr [[TMP449]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP451:%.*]] = getelementptr inbounds double, ptr [[TMP450]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP452:%.*]] = getelementptr inbounds double, ptr [[TMP451]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP453:%.*]] = getelementptr inbounds double, ptr [[TMP452]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP454:%.*]] = getelementptr inbounds i32, ptr [[TMP453]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP455:%.*]] = getelementptr inbounds ptr, ptr [[TMP454]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP456:%.*]] = getelementptr inbounds ptr, ptr [[TMP455]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP457:%.*]] = getelementptr inbounds ptr, ptr [[TMP456]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP458:%.*]] = getelementptr inbounds i64, ptr [[TMP457]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP459:%.*]] = getelementptr inbounds i64, ptr [[TMP458]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP460:%.*]] = getelementptr inbounds i32, ptr [[TMP459]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP460]], align 4, !invariant.group [[META82]]
; CHECK-NEXT:    [[TMP461:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP462:%.*]] = getelementptr inbounds i64, ptr [[TMP461]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP463:%.*]] = getelementptr inbounds ptr, ptr [[TMP462]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP464:%.*]] = getelementptr inbounds i32, ptr [[TMP463]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP465:%.*]] = getelementptr inbounds i1, ptr [[TMP464]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP466:%.*]] = getelementptr inbounds ptr, ptr [[TMP465]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP467:%.*]] = getelementptr inbounds ptr, ptr [[TMP466]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP468:%.*]] = getelementptr inbounds double, ptr [[TMP467]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP469:%.*]] = getelementptr inbounds i32, ptr [[TMP468]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP470:%.*]] = getelementptr inbounds i32, ptr [[TMP469]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP471:%.*]] = getelementptr inbounds double, ptr [[TMP470]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP472:%.*]] = getelementptr inbounds double, ptr [[TMP471]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP473:%.*]] = getelementptr inbounds double, ptr [[TMP472]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP474:%.*]] = getelementptr inbounds double, ptr [[TMP473]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP475:%.*]] = getelementptr inbounds double, ptr [[TMP474]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP476:%.*]] = getelementptr inbounds i32, ptr [[TMP475]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP477:%.*]] = getelementptr inbounds ptr, ptr [[TMP476]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP478:%.*]] = getelementptr inbounds ptr, ptr [[TMP477]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP479:%.*]] = getelementptr inbounds ptr, ptr [[TMP478]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP480:%.*]] = getelementptr inbounds i64, ptr [[TMP479]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP481:%.*]] = getelementptr inbounds i64, ptr [[TMP480]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP482:%.*]] = getelementptr inbounds i32, ptr [[TMP481]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP483:%.*]] = getelementptr inbounds i32, ptr [[TMP482]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP483]], align 4, !invariant.group [[META83]]
; CHECK-NEXT:    [[TMP484:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP485:%.*]] = getelementptr inbounds i64, ptr [[TMP484]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP486:%.*]] = getelementptr inbounds ptr, ptr [[TMP485]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP487:%.*]] = getelementptr inbounds i32, ptr [[TMP486]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP488:%.*]] = getelementptr inbounds i1, ptr [[TMP487]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP489:%.*]] = getelementptr inbounds ptr, ptr [[TMP488]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP490:%.*]] = getelementptr inbounds ptr, ptr [[TMP489]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP491:%.*]] = getelementptr inbounds double, ptr [[TMP490]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP492:%.*]] = getelementptr inbounds i32, ptr [[TMP491]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP493:%.*]] = getelementptr inbounds i32, ptr [[TMP492]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP494:%.*]] = getelementptr inbounds double, ptr [[TMP493]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP495:%.*]] = getelementptr inbounds double, ptr [[TMP494]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP496:%.*]] = getelementptr inbounds double, ptr [[TMP495]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP497:%.*]] = getelementptr inbounds double, ptr [[TMP496]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP498:%.*]] = getelementptr inbounds double, ptr [[TMP497]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP499:%.*]] = getelementptr inbounds i32, ptr [[TMP498]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP500:%.*]] = getelementptr inbounds ptr, ptr [[TMP499]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP501:%.*]] = getelementptr inbounds ptr, ptr [[TMP500]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP502:%.*]] = getelementptr inbounds ptr, ptr [[TMP501]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP503:%.*]] = getelementptr inbounds i64, ptr [[TMP502]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP504:%.*]] = getelementptr inbounds i64, ptr [[TMP503]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP505:%.*]] = getelementptr inbounds i32, ptr [[TMP504]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP506:%.*]] = getelementptr inbounds i32, ptr [[TMP505]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP507:%.*]] = getelementptr inbounds i32, ptr [[TMP506]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP507]], align 4, !invariant.group [[META84]]
; CHECK-NEXT:    [[TMP508:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP509:%.*]] = getelementptr inbounds i64, ptr [[TMP508]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP510:%.*]] = getelementptr inbounds ptr, ptr [[TMP509]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP511:%.*]] = getelementptr inbounds i32, ptr [[TMP510]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP512:%.*]] = getelementptr inbounds i1, ptr [[TMP511]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP513:%.*]] = getelementptr inbounds ptr, ptr [[TMP512]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP514:%.*]] = getelementptr inbounds ptr, ptr [[TMP513]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP515:%.*]] = getelementptr inbounds double, ptr [[TMP514]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP516:%.*]] = getelementptr inbounds i32, ptr [[TMP515]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP517:%.*]] = getelementptr inbounds i32, ptr [[TMP516]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP518:%.*]] = getelementptr inbounds double, ptr [[TMP517]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP519:%.*]] = getelementptr inbounds double, ptr [[TMP518]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP520:%.*]] = getelementptr inbounds double, ptr [[TMP519]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP521:%.*]] = getelementptr inbounds double, ptr [[TMP520]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP522:%.*]] = getelementptr inbounds double, ptr [[TMP521]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP523:%.*]] = getelementptr inbounds i32, ptr [[TMP522]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP524:%.*]] = getelementptr inbounds ptr, ptr [[TMP523]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP525:%.*]] = getelementptr inbounds ptr, ptr [[TMP524]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP526:%.*]] = getelementptr inbounds ptr, ptr [[TMP525]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP527:%.*]] = getelementptr inbounds i64, ptr [[TMP526]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP528:%.*]] = getelementptr inbounds i64, ptr [[TMP527]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP529:%.*]] = getelementptr inbounds i32, ptr [[TMP528]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP530:%.*]] = getelementptr inbounds i32, ptr [[TMP529]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP531:%.*]] = getelementptr inbounds i32, ptr [[TMP530]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP532:%.*]] = getelementptr inbounds i32, ptr [[TMP531]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP532]], align 4, !invariant.group [[META85]]
; CHECK-NEXT:    [[TMP533:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR29]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP534:%.*]] = getelementptr inbounds i64, ptr [[TMP533]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP535:%.*]] = getelementptr inbounds ptr, ptr [[TMP534]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP536:%.*]] = getelementptr inbounds i32, ptr [[TMP535]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP537:%.*]] = getelementptr inbounds i1, ptr [[TMP536]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP538:%.*]] = getelementptr inbounds ptr, ptr [[TMP537]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP539:%.*]] = getelementptr inbounds ptr, ptr [[TMP538]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP540:%.*]] = getelementptr inbounds double, ptr [[TMP539]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP541:%.*]] = getelementptr inbounds i32, ptr [[TMP540]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP542:%.*]] = getelementptr inbounds i32, ptr [[TMP541]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP543:%.*]] = getelementptr inbounds double, ptr [[TMP542]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP544:%.*]] = getelementptr inbounds double, ptr [[TMP543]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP545:%.*]] = getelementptr inbounds double, ptr [[TMP544]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP546:%.*]] = getelementptr inbounds double, ptr [[TMP545]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP547:%.*]] = getelementptr inbounds double, ptr [[TMP546]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP548:%.*]] = getelementptr inbounds i32, ptr [[TMP547]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP549:%.*]] = getelementptr inbounds ptr, ptr [[TMP548]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP550:%.*]] = getelementptr inbounds ptr, ptr [[TMP549]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP551:%.*]] = getelementptr inbounds ptr, ptr [[TMP550]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP552:%.*]] = getelementptr inbounds i64, ptr [[TMP551]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP553:%.*]] = getelementptr inbounds i64, ptr [[TMP552]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP554:%.*]] = getelementptr inbounds i32, ptr [[TMP553]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP555:%.*]] = getelementptr inbounds i32, ptr [[TMP554]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP556:%.*]] = getelementptr inbounds i32, ptr [[TMP555]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP557:%.*]] = getelementptr inbounds i32, ptr [[TMP556]], i32 [[CACHE_OUT_OFFSET30]]
; CHECK-NEXT:    [[TMP558:%.*]] = getelementptr inbounds i32, ptr [[TMP557]], i32 [[CACHEIDX28]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP558]], align 4, !invariant.group [[META86]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       bb197:
; CHECK-NEXT:    [[I198:%.*]] = sext i32 [[I169]] to i64
; CHECK-NEXT:    [[I199:%.*]] = getelementptr i32, ptr [[I148334]], i64 [[I198]]
; CHECK-NEXT:    [[I200:%.*]] = load i32, ptr [[I199]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I201:%.*]] = sext i32 [[I200]] to i64
; CHECK-NEXT:    [[I202:%.*]] = icmp eq i64 [[I149345]], [[I201]]
; CHECK-NEXT:    [[I203:%.*]] = mul nsw i64 [[I106158]], [[I198]]
; CHECK-NEXT:    [[I204:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT:%.*]], ptr [[I111150]], i64 [[I203]]
; CHECK-NEXT:    [[I205:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I204]], i64 [[I201]]
; CHECK-NEXT:    [[I206:%.*]] = select i1 [[I202]], i64 -48, i64 0
; CHECK-NEXT:    [[I207:%.*]] = getelementptr i8, ptr [[I205]], i64 [[I206]]
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       CacheStore2:
; CHECK-NEXT:    [[TMP559:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 3
; CHECK-NEXT:    [[TMP560:%.*]] = load ptr, ptr [[TMP559]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR70:%.*]] = getelementptr inbounds i32, ptr [[TMP560]], i32 2
; CHECK-NEXT:    [[CACHEIDX71:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR70]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP561:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP562:%.*]] = load ptr, ptr [[TMP561]], align 8
; CHECK-NEXT:    [[TMP563:%.*]] = getelementptr inbounds ptr, ptr [[TMP562]], i32 2
; CHECK-NEXT:    [[CACHE_OUT_PTR72:%.*]] = load ptr, ptr [[TMP563]], align 8
; CHECK-NEXT:    [[TMP564:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_OUT_OFFSET73:%.*]] = load i32, ptr [[TMP564]], align 4
; CHECK-NEXT:    [[TMP565:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I10133]], ptr [[TMP565]], align 4, !invariant.group [[META94]]
; CHECK-NEXT:    [[TMP566:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP567:%.*]] = getelementptr inbounds i64, ptr [[TMP566]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I70139]], ptr [[TMP567]], align 8, !invariant.group [[META95]]
; CHECK-NEXT:    [[TMP568:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP569:%.*]] = getelementptr inbounds i64, ptr [[TMP568]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP570:%.*]] = getelementptr inbounds ptr, ptr [[TMP569]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I142328]], ptr [[TMP570]], align 8, !invariant.group [[META96]]
; CHECK-NEXT:    [[TMP571:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP572:%.*]] = getelementptr inbounds i64, ptr [[TMP571]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP573:%.*]] = getelementptr inbounds ptr, ptr [[TMP572]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP574:%.*]] = getelementptr inbounds i32, ptr [[TMP573]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I146330]], ptr [[TMP574]], align 4, !invariant.group [[META97]]
; CHECK-NEXT:    [[TMP575:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP576:%.*]] = getelementptr inbounds i64, ptr [[TMP575]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP577:%.*]] = getelementptr inbounds ptr, ptr [[TMP576]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP578:%.*]] = getelementptr inbounds i32, ptr [[TMP577]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP579:%.*]] = getelementptr inbounds i1, ptr [[TMP578]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i1 [[I153332]], ptr [[TMP579]], align 1, !invariant.group [[META98]]
; CHECK-NEXT:    [[TMP580:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP581:%.*]] = getelementptr inbounds i64, ptr [[TMP580]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP582:%.*]] = getelementptr inbounds ptr, ptr [[TMP581]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP583:%.*]] = getelementptr inbounds i32, ptr [[TMP582]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP584:%.*]] = getelementptr inbounds i1, ptr [[TMP583]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP585:%.*]] = getelementptr inbounds ptr, ptr [[TMP584]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I148334]], ptr [[TMP585]], align 8, !invariant.group [[META99]]
; CHECK-NEXT:    [[TMP586:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP587:%.*]] = getelementptr inbounds i64, ptr [[TMP586]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP588:%.*]] = getelementptr inbounds ptr, ptr [[TMP587]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP589:%.*]] = getelementptr inbounds i32, ptr [[TMP588]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP590:%.*]] = getelementptr inbounds i1, ptr [[TMP589]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP591:%.*]] = getelementptr inbounds ptr, ptr [[TMP590]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP592:%.*]] = getelementptr inbounds ptr, ptr [[TMP591]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I156336]], ptr [[TMP592]], align 8, !invariant.group [[META100]]
; CHECK-NEXT:    [[TMP593:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP594:%.*]] = getelementptr inbounds i64, ptr [[TMP593]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP595:%.*]] = getelementptr inbounds ptr, ptr [[TMP594]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP596:%.*]] = getelementptr inbounds i32, ptr [[TMP595]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP597:%.*]] = getelementptr inbounds i1, ptr [[TMP596]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP598:%.*]] = getelementptr inbounds ptr, ptr [[TMP597]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP599:%.*]] = getelementptr inbounds ptr, ptr [[TMP598]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP600:%.*]] = getelementptr inbounds double, ptr [[TMP599]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I171]], ptr [[TMP600]], align 8, !invariant.group [[META101]]
; CHECK-NEXT:    [[TMP601:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP602:%.*]] = getelementptr inbounds i64, ptr [[TMP601]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP603:%.*]] = getelementptr inbounds ptr, ptr [[TMP602]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP604:%.*]] = getelementptr inbounds i32, ptr [[TMP603]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP605:%.*]] = getelementptr inbounds i1, ptr [[TMP604]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP606:%.*]] = getelementptr inbounds ptr, ptr [[TMP605]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP607:%.*]] = getelementptr inbounds ptr, ptr [[TMP606]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP608:%.*]] = getelementptr inbounds double, ptr [[TMP607]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP609:%.*]] = getelementptr inbounds i32, ptr [[TMP608]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I169]], ptr [[TMP609]], align 4, !invariant.group [[META102]]
; CHECK-NEXT:    [[TMP610:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP611:%.*]] = getelementptr inbounds i64, ptr [[TMP610]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP612:%.*]] = getelementptr inbounds ptr, ptr [[TMP611]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP613:%.*]] = getelementptr inbounds i32, ptr [[TMP612]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP614:%.*]] = getelementptr inbounds i1, ptr [[TMP613]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP615:%.*]] = getelementptr inbounds ptr, ptr [[TMP614]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP616:%.*]] = getelementptr inbounds ptr, ptr [[TMP615]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP617:%.*]] = getelementptr inbounds double, ptr [[TMP616]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP618:%.*]] = getelementptr inbounds i32, ptr [[TMP617]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP619:%.*]] = getelementptr inbounds i32, ptr [[TMP618]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I165]], ptr [[TMP619]], align 4, !invariant.group [[META103]]
; CHECK-NEXT:    [[TMP620:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP621:%.*]] = getelementptr inbounds i64, ptr [[TMP620]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP622:%.*]] = getelementptr inbounds ptr, ptr [[TMP621]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP623:%.*]] = getelementptr inbounds i32, ptr [[TMP622]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP624:%.*]] = getelementptr inbounds i1, ptr [[TMP623]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP625:%.*]] = getelementptr inbounds ptr, ptr [[TMP624]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP626:%.*]] = getelementptr inbounds ptr, ptr [[TMP625]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP627:%.*]] = getelementptr inbounds double, ptr [[TMP626]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP628:%.*]] = getelementptr inbounds i32, ptr [[TMP627]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP629:%.*]] = getelementptr inbounds i32, ptr [[TMP628]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP630:%.*]] = getelementptr inbounds double, ptr [[TMP629]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I164]], ptr [[TMP630]], align 8, !invariant.group [[META104]]
; CHECK-NEXT:    [[TMP631:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP632:%.*]] = getelementptr inbounds i64, ptr [[TMP631]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP633:%.*]] = getelementptr inbounds ptr, ptr [[TMP632]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP634:%.*]] = getelementptr inbounds i32, ptr [[TMP633]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP635:%.*]] = getelementptr inbounds i1, ptr [[TMP634]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP636:%.*]] = getelementptr inbounds ptr, ptr [[TMP635]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP637:%.*]] = getelementptr inbounds ptr, ptr [[TMP636]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP638:%.*]] = getelementptr inbounds double, ptr [[TMP637]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP639:%.*]] = getelementptr inbounds i32, ptr [[TMP638]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP640:%.*]] = getelementptr inbounds i32, ptr [[TMP639]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP641:%.*]] = getelementptr inbounds double, ptr [[TMP640]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP642:%.*]] = getelementptr inbounds double, ptr [[TMP641]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I163]], ptr [[TMP642]], align 8, !invariant.group [[META105]]
; CHECK-NEXT:    [[TMP643:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP644:%.*]] = getelementptr inbounds i64, ptr [[TMP643]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP645:%.*]] = getelementptr inbounds ptr, ptr [[TMP644]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP646:%.*]] = getelementptr inbounds i32, ptr [[TMP645]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP647:%.*]] = getelementptr inbounds i1, ptr [[TMP646]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP648:%.*]] = getelementptr inbounds ptr, ptr [[TMP647]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP649:%.*]] = getelementptr inbounds ptr, ptr [[TMP648]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP650:%.*]] = getelementptr inbounds double, ptr [[TMP649]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP651:%.*]] = getelementptr inbounds i32, ptr [[TMP650]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP652:%.*]] = getelementptr inbounds i32, ptr [[TMP651]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP653:%.*]] = getelementptr inbounds double, ptr [[TMP652]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP654:%.*]] = getelementptr inbounds double, ptr [[TMP653]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP655:%.*]] = getelementptr inbounds double, ptr [[TMP654]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I162]], ptr [[TMP655]], align 8, !invariant.group [[META106]]
; CHECK-NEXT:    [[TMP656:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP657:%.*]] = getelementptr inbounds i64, ptr [[TMP656]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP658:%.*]] = getelementptr inbounds ptr, ptr [[TMP657]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP659:%.*]] = getelementptr inbounds i32, ptr [[TMP658]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP660:%.*]] = getelementptr inbounds i1, ptr [[TMP659]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP661:%.*]] = getelementptr inbounds ptr, ptr [[TMP660]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP662:%.*]] = getelementptr inbounds ptr, ptr [[TMP661]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP663:%.*]] = getelementptr inbounds double, ptr [[TMP662]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP664:%.*]] = getelementptr inbounds i32, ptr [[TMP663]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP665:%.*]] = getelementptr inbounds i32, ptr [[TMP664]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP666:%.*]] = getelementptr inbounds double, ptr [[TMP665]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP667:%.*]] = getelementptr inbounds double, ptr [[TMP666]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP668:%.*]] = getelementptr inbounds double, ptr [[TMP667]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP669:%.*]] = getelementptr inbounds double, ptr [[TMP668]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I161]], ptr [[TMP669]], align 8, !invariant.group [[META107]]
; CHECK-NEXT:    [[TMP670:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP671:%.*]] = getelementptr inbounds i64, ptr [[TMP670]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP672:%.*]] = getelementptr inbounds ptr, ptr [[TMP671]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP673:%.*]] = getelementptr inbounds i32, ptr [[TMP672]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP674:%.*]] = getelementptr inbounds i1, ptr [[TMP673]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP675:%.*]] = getelementptr inbounds ptr, ptr [[TMP674]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP676:%.*]] = getelementptr inbounds ptr, ptr [[TMP675]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP677:%.*]] = getelementptr inbounds double, ptr [[TMP676]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP678:%.*]] = getelementptr inbounds i32, ptr [[TMP677]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP679:%.*]] = getelementptr inbounds i32, ptr [[TMP678]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP680:%.*]] = getelementptr inbounds double, ptr [[TMP679]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP681:%.*]] = getelementptr inbounds double, ptr [[TMP680]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP682:%.*]] = getelementptr inbounds double, ptr [[TMP681]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP683:%.*]] = getelementptr inbounds double, ptr [[TMP682]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP684:%.*]] = getelementptr inbounds double, ptr [[TMP683]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store double [[I160]], ptr [[TMP684]], align 8, !invariant.group [[META108]]
; CHECK-NEXT:    [[TMP685:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP686:%.*]] = getelementptr inbounds i64, ptr [[TMP685]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP687:%.*]] = getelementptr inbounds ptr, ptr [[TMP686]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP688:%.*]] = getelementptr inbounds i32, ptr [[TMP687]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP689:%.*]] = getelementptr inbounds i1, ptr [[TMP688]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP690:%.*]] = getelementptr inbounds ptr, ptr [[TMP689]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP691:%.*]] = getelementptr inbounds ptr, ptr [[TMP690]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP692:%.*]] = getelementptr inbounds double, ptr [[TMP691]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP693:%.*]] = getelementptr inbounds i32, ptr [[TMP692]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP694:%.*]] = getelementptr inbounds i32, ptr [[TMP693]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP695:%.*]] = getelementptr inbounds double, ptr [[TMP694]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP696:%.*]] = getelementptr inbounds double, ptr [[TMP695]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP697:%.*]] = getelementptr inbounds double, ptr [[TMP696]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP698:%.*]] = getelementptr inbounds double, ptr [[TMP697]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP699:%.*]] = getelementptr inbounds double, ptr [[TMP698]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP700:%.*]] = getelementptr inbounds i32, ptr [[TMP699]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I113144]], ptr [[TMP700]], align 4, !invariant.group [[META109]]
; CHECK-NEXT:    [[TMP701:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP702:%.*]] = getelementptr inbounds i64, ptr [[TMP701]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP703:%.*]] = getelementptr inbounds ptr, ptr [[TMP702]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP704:%.*]] = getelementptr inbounds i32, ptr [[TMP703]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP705:%.*]] = getelementptr inbounds i1, ptr [[TMP704]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP706:%.*]] = getelementptr inbounds ptr, ptr [[TMP705]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP707:%.*]] = getelementptr inbounds ptr, ptr [[TMP706]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP708:%.*]] = getelementptr inbounds double, ptr [[TMP707]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP709:%.*]] = getelementptr inbounds i32, ptr [[TMP708]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP710:%.*]] = getelementptr inbounds i32, ptr [[TMP709]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP711:%.*]] = getelementptr inbounds double, ptr [[TMP710]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP712:%.*]] = getelementptr inbounds double, ptr [[TMP711]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP713:%.*]] = getelementptr inbounds double, ptr [[TMP712]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP714:%.*]] = getelementptr inbounds double, ptr [[TMP713]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP715:%.*]] = getelementptr inbounds double, ptr [[TMP714]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP716:%.*]] = getelementptr inbounds i32, ptr [[TMP715]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP717:%.*]] = getelementptr inbounds ptr, ptr [[TMP716]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I112147]], ptr [[TMP717]], align 8, !invariant.group [[META110]]
; CHECK-NEXT:    [[TMP718:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP719:%.*]] = getelementptr inbounds i64, ptr [[TMP718]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP720:%.*]] = getelementptr inbounds ptr, ptr [[TMP719]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP721:%.*]] = getelementptr inbounds i32, ptr [[TMP720]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP722:%.*]] = getelementptr inbounds i1, ptr [[TMP721]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP723:%.*]] = getelementptr inbounds ptr, ptr [[TMP722]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP724:%.*]] = getelementptr inbounds ptr, ptr [[TMP723]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP725:%.*]] = getelementptr inbounds double, ptr [[TMP724]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP726:%.*]] = getelementptr inbounds i32, ptr [[TMP725]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP727:%.*]] = getelementptr inbounds i32, ptr [[TMP726]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP728:%.*]] = getelementptr inbounds double, ptr [[TMP727]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP729:%.*]] = getelementptr inbounds double, ptr [[TMP728]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP730:%.*]] = getelementptr inbounds double, ptr [[TMP729]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP731:%.*]] = getelementptr inbounds double, ptr [[TMP730]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP732:%.*]] = getelementptr inbounds double, ptr [[TMP731]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP733:%.*]] = getelementptr inbounds i32, ptr [[TMP732]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP734:%.*]] = getelementptr inbounds ptr, ptr [[TMP733]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP735:%.*]] = getelementptr inbounds ptr, ptr [[TMP734]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I111150]], ptr [[TMP735]], align 8, !invariant.group [[META111]]
; CHECK-NEXT:    [[TMP736:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP737:%.*]] = getelementptr inbounds i64, ptr [[TMP736]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP738:%.*]] = getelementptr inbounds ptr, ptr [[TMP737]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP739:%.*]] = getelementptr inbounds i32, ptr [[TMP738]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP740:%.*]] = getelementptr inbounds i1, ptr [[TMP739]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP741:%.*]] = getelementptr inbounds ptr, ptr [[TMP740]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP742:%.*]] = getelementptr inbounds ptr, ptr [[TMP741]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP743:%.*]] = getelementptr inbounds double, ptr [[TMP742]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP744:%.*]] = getelementptr inbounds i32, ptr [[TMP743]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP745:%.*]] = getelementptr inbounds i32, ptr [[TMP744]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP746:%.*]] = getelementptr inbounds double, ptr [[TMP745]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP747:%.*]] = getelementptr inbounds double, ptr [[TMP746]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP748:%.*]] = getelementptr inbounds double, ptr [[TMP747]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP749:%.*]] = getelementptr inbounds double, ptr [[TMP748]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP750:%.*]] = getelementptr inbounds double, ptr [[TMP749]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP751:%.*]] = getelementptr inbounds i32, ptr [[TMP750]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP752:%.*]] = getelementptr inbounds ptr, ptr [[TMP751]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP753:%.*]] = getelementptr inbounds ptr, ptr [[TMP752]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP754:%.*]] = getelementptr inbounds ptr, ptr [[TMP753]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store ptr [[I108154]], ptr [[TMP754]], align 8, !invariant.group [[META112]]
; CHECK-NEXT:    [[TMP755:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP756:%.*]] = getelementptr inbounds i64, ptr [[TMP755]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP757:%.*]] = getelementptr inbounds ptr, ptr [[TMP756]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP758:%.*]] = getelementptr inbounds i32, ptr [[TMP757]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP759:%.*]] = getelementptr inbounds i1, ptr [[TMP758]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP760:%.*]] = getelementptr inbounds ptr, ptr [[TMP759]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP761:%.*]] = getelementptr inbounds ptr, ptr [[TMP760]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP762:%.*]] = getelementptr inbounds double, ptr [[TMP761]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP763:%.*]] = getelementptr inbounds i32, ptr [[TMP762]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP764:%.*]] = getelementptr inbounds i32, ptr [[TMP763]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP765:%.*]] = getelementptr inbounds double, ptr [[TMP764]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP766:%.*]] = getelementptr inbounds double, ptr [[TMP765]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP767:%.*]] = getelementptr inbounds double, ptr [[TMP766]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP768:%.*]] = getelementptr inbounds double, ptr [[TMP767]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP769:%.*]] = getelementptr inbounds double, ptr [[TMP768]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP770:%.*]] = getelementptr inbounds i32, ptr [[TMP769]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP771:%.*]] = getelementptr inbounds ptr, ptr [[TMP770]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP772:%.*]] = getelementptr inbounds ptr, ptr [[TMP771]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP773:%.*]] = getelementptr inbounds ptr, ptr [[TMP772]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP774:%.*]] = getelementptr inbounds i64, ptr [[TMP773]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I106158]], ptr [[TMP774]], align 8, !invariant.group [[META113]]
; CHECK-NEXT:    [[TMP775:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP776:%.*]] = getelementptr inbounds i64, ptr [[TMP775]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP777:%.*]] = getelementptr inbounds ptr, ptr [[TMP776]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP778:%.*]] = getelementptr inbounds i32, ptr [[TMP777]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP779:%.*]] = getelementptr inbounds i1, ptr [[TMP778]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP780:%.*]] = getelementptr inbounds ptr, ptr [[TMP779]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP781:%.*]] = getelementptr inbounds ptr, ptr [[TMP780]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP782:%.*]] = getelementptr inbounds double, ptr [[TMP781]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP783:%.*]] = getelementptr inbounds i32, ptr [[TMP782]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP784:%.*]] = getelementptr inbounds i32, ptr [[TMP783]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP785:%.*]] = getelementptr inbounds double, ptr [[TMP784]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP786:%.*]] = getelementptr inbounds double, ptr [[TMP785]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP787:%.*]] = getelementptr inbounds double, ptr [[TMP786]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP788:%.*]] = getelementptr inbounds double, ptr [[TMP787]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP789:%.*]] = getelementptr inbounds double, ptr [[TMP788]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP790:%.*]] = getelementptr inbounds i32, ptr [[TMP789]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP791:%.*]] = getelementptr inbounds ptr, ptr [[TMP790]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP792:%.*]] = getelementptr inbounds ptr, ptr [[TMP791]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP793:%.*]] = getelementptr inbounds ptr, ptr [[TMP792]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP794:%.*]] = getelementptr inbounds i64, ptr [[TMP793]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP795:%.*]] = getelementptr inbounds i64, ptr [[TMP794]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i64 [[I40164]], ptr [[TMP795]], align 8, !invariant.group [[META114]]
; CHECK-NEXT:    [[TMP796:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP797:%.*]] = getelementptr inbounds i64, ptr [[TMP796]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP798:%.*]] = getelementptr inbounds ptr, ptr [[TMP797]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP799:%.*]] = getelementptr inbounds i32, ptr [[TMP798]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP800:%.*]] = getelementptr inbounds i1, ptr [[TMP799]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP801:%.*]] = getelementptr inbounds ptr, ptr [[TMP800]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP802:%.*]] = getelementptr inbounds ptr, ptr [[TMP801]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP803:%.*]] = getelementptr inbounds double, ptr [[TMP802]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP804:%.*]] = getelementptr inbounds i32, ptr [[TMP803]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP805:%.*]] = getelementptr inbounds i32, ptr [[TMP804]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP806:%.*]] = getelementptr inbounds double, ptr [[TMP805]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP807:%.*]] = getelementptr inbounds double, ptr [[TMP806]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP808:%.*]] = getelementptr inbounds double, ptr [[TMP807]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP809:%.*]] = getelementptr inbounds double, ptr [[TMP808]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP810:%.*]] = getelementptr inbounds double, ptr [[TMP809]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP811:%.*]] = getelementptr inbounds i32, ptr [[TMP810]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP812:%.*]] = getelementptr inbounds ptr, ptr [[TMP811]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP813:%.*]] = getelementptr inbounds ptr, ptr [[TMP812]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP814:%.*]] = getelementptr inbounds ptr, ptr [[TMP813]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP815:%.*]] = getelementptr inbounds i64, ptr [[TMP814]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP816:%.*]] = getelementptr inbounds i64, ptr [[TMP815]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP817:%.*]] = getelementptr inbounds i32, ptr [[TMP816]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I31168]], ptr [[TMP817]], align 4, !invariant.group [[META115]]
; CHECK-NEXT:    [[TMP818:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP819:%.*]] = getelementptr inbounds i64, ptr [[TMP818]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP820:%.*]] = getelementptr inbounds ptr, ptr [[TMP819]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP821:%.*]] = getelementptr inbounds i32, ptr [[TMP820]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP822:%.*]] = getelementptr inbounds i1, ptr [[TMP821]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP823:%.*]] = getelementptr inbounds ptr, ptr [[TMP822]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP824:%.*]] = getelementptr inbounds ptr, ptr [[TMP823]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP825:%.*]] = getelementptr inbounds double, ptr [[TMP824]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP826:%.*]] = getelementptr inbounds i32, ptr [[TMP825]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP827:%.*]] = getelementptr inbounds i32, ptr [[TMP826]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP828:%.*]] = getelementptr inbounds double, ptr [[TMP827]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP829:%.*]] = getelementptr inbounds double, ptr [[TMP828]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP830:%.*]] = getelementptr inbounds double, ptr [[TMP829]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP831:%.*]] = getelementptr inbounds double, ptr [[TMP830]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP832:%.*]] = getelementptr inbounds double, ptr [[TMP831]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP833:%.*]] = getelementptr inbounds i32, ptr [[TMP832]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP834:%.*]] = getelementptr inbounds ptr, ptr [[TMP833]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP835:%.*]] = getelementptr inbounds ptr, ptr [[TMP834]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP836:%.*]] = getelementptr inbounds ptr, ptr [[TMP835]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP837:%.*]] = getelementptr inbounds i64, ptr [[TMP836]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP838:%.*]] = getelementptr inbounds i64, ptr [[TMP837]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP839:%.*]] = getelementptr inbounds i32, ptr [[TMP838]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP840:%.*]] = getelementptr inbounds i32, ptr [[TMP839]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I30174]], ptr [[TMP840]], align 4, !invariant.group [[META116]]
; CHECK-NEXT:    [[TMP841:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP842:%.*]] = getelementptr inbounds i64, ptr [[TMP841]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP843:%.*]] = getelementptr inbounds ptr, ptr [[TMP842]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP844:%.*]] = getelementptr inbounds i32, ptr [[TMP843]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP845:%.*]] = getelementptr inbounds i1, ptr [[TMP844]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP846:%.*]] = getelementptr inbounds ptr, ptr [[TMP845]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP847:%.*]] = getelementptr inbounds ptr, ptr [[TMP846]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP848:%.*]] = getelementptr inbounds double, ptr [[TMP847]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP849:%.*]] = getelementptr inbounds i32, ptr [[TMP848]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP850:%.*]] = getelementptr inbounds i32, ptr [[TMP849]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP851:%.*]] = getelementptr inbounds double, ptr [[TMP850]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP852:%.*]] = getelementptr inbounds double, ptr [[TMP851]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP853:%.*]] = getelementptr inbounds double, ptr [[TMP852]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP854:%.*]] = getelementptr inbounds double, ptr [[TMP853]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP855:%.*]] = getelementptr inbounds double, ptr [[TMP854]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP856:%.*]] = getelementptr inbounds i32, ptr [[TMP855]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP857:%.*]] = getelementptr inbounds ptr, ptr [[TMP856]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP858:%.*]] = getelementptr inbounds ptr, ptr [[TMP857]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP859:%.*]] = getelementptr inbounds ptr, ptr [[TMP858]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP860:%.*]] = getelementptr inbounds i64, ptr [[TMP859]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP861:%.*]] = getelementptr inbounds i64, ptr [[TMP860]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP862:%.*]] = getelementptr inbounds i32, ptr [[TMP861]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP863:%.*]] = getelementptr inbounds i32, ptr [[TMP862]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP864:%.*]] = getelementptr inbounds i32, ptr [[TMP863]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I5180]], ptr [[TMP864]], align 4, !invariant.group [[META117]]
; CHECK-NEXT:    [[TMP865:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP866:%.*]] = getelementptr inbounds i64, ptr [[TMP865]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP867:%.*]] = getelementptr inbounds ptr, ptr [[TMP866]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP868:%.*]] = getelementptr inbounds i32, ptr [[TMP867]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP869:%.*]] = getelementptr inbounds i1, ptr [[TMP868]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP870:%.*]] = getelementptr inbounds ptr, ptr [[TMP869]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP871:%.*]] = getelementptr inbounds ptr, ptr [[TMP870]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP872:%.*]] = getelementptr inbounds double, ptr [[TMP871]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP873:%.*]] = getelementptr inbounds i32, ptr [[TMP872]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP874:%.*]] = getelementptr inbounds i32, ptr [[TMP873]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP875:%.*]] = getelementptr inbounds double, ptr [[TMP874]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP876:%.*]] = getelementptr inbounds double, ptr [[TMP875]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP877:%.*]] = getelementptr inbounds double, ptr [[TMP876]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP878:%.*]] = getelementptr inbounds double, ptr [[TMP877]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP879:%.*]] = getelementptr inbounds double, ptr [[TMP878]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP880:%.*]] = getelementptr inbounds i32, ptr [[TMP879]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP881:%.*]] = getelementptr inbounds ptr, ptr [[TMP880]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP882:%.*]] = getelementptr inbounds ptr, ptr [[TMP881]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP883:%.*]] = getelementptr inbounds ptr, ptr [[TMP882]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP884:%.*]] = getelementptr inbounds i64, ptr [[TMP883]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP885:%.*]] = getelementptr inbounds i64, ptr [[TMP884]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP886:%.*]] = getelementptr inbounds i32, ptr [[TMP885]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP887:%.*]] = getelementptr inbounds i32, ptr [[TMP886]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP888:%.*]] = getelementptr inbounds i32, ptr [[TMP887]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP889:%.*]] = getelementptr inbounds i32, ptr [[TMP888]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I197]], ptr [[TMP889]], align 4, !invariant.group [[META118]]
; CHECK-NEXT:    [[TMP890:%.*]] = getelementptr inbounds i32, ptr [[CACHE_OUT_PTR72]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP891:%.*]] = getelementptr inbounds i64, ptr [[TMP890]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP892:%.*]] = getelementptr inbounds ptr, ptr [[TMP891]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP893:%.*]] = getelementptr inbounds i32, ptr [[TMP892]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP894:%.*]] = getelementptr inbounds i1, ptr [[TMP893]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP895:%.*]] = getelementptr inbounds ptr, ptr [[TMP894]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP896:%.*]] = getelementptr inbounds ptr, ptr [[TMP895]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP897:%.*]] = getelementptr inbounds double, ptr [[TMP896]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP898:%.*]] = getelementptr inbounds i32, ptr [[TMP897]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP899:%.*]] = getelementptr inbounds i32, ptr [[TMP898]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP900:%.*]] = getelementptr inbounds double, ptr [[TMP899]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP901:%.*]] = getelementptr inbounds double, ptr [[TMP900]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP902:%.*]] = getelementptr inbounds double, ptr [[TMP901]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP903:%.*]] = getelementptr inbounds double, ptr [[TMP902]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP904:%.*]] = getelementptr inbounds double, ptr [[TMP903]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP905:%.*]] = getelementptr inbounds i32, ptr [[TMP904]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP906:%.*]] = getelementptr inbounds ptr, ptr [[TMP905]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP907:%.*]] = getelementptr inbounds ptr, ptr [[TMP906]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP908:%.*]] = getelementptr inbounds ptr, ptr [[TMP907]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP909:%.*]] = getelementptr inbounds i64, ptr [[TMP908]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP910:%.*]] = getelementptr inbounds i64, ptr [[TMP909]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP911:%.*]] = getelementptr inbounds i32, ptr [[TMP910]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP912:%.*]] = getelementptr inbounds i32, ptr [[TMP911]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP913:%.*]] = getelementptr inbounds i32, ptr [[TMP912]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP914:%.*]] = getelementptr inbounds i32, ptr [[TMP913]], i32 [[CACHE_OUT_OFFSET73]]
; CHECK-NEXT:    [[TMP915:%.*]] = getelementptr inbounds i32, ptr [[TMP914]], i32 [[CACHEIDX71]]
; CHECK-NEXT:    store i32 [[I18220]], ptr [[TMP915]], align 4, !invariant.group [[META119]]
; CHECK-NEXT:    br label [[THREADEXIT]]
; CHECK:       CacheRemat2:
; CHECK-NEXT:    [[TMP916:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 5
; CHECK-NEXT:    [[TMP917:%.*]] = load ptr, ptr [[TMP916]], align 8
; CHECK-NEXT:    [[TMP918:%.*]] = getelementptr inbounds ptr, ptr [[TMP917]], i32 5
; CHECK-NEXT:    [[CACHE_IN_PTR78:%.*]] = load ptr, ptr [[TMP918]], align 8
; CHECK-NEXT:    [[TMP919:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ARG]], i32 0, i32 4
; CHECK-NEXT:    [[CACHE_IN_OFFSET79:%.*]] = load i32, ptr [[TMP919]], align 4
; CHECK-NEXT:    [[TMP920:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[GTID74]]
; CHECK-NEXT:    [[I10_CACHE80:%.*]] = load i32, ptr [[TMP920]], align 4, !invariant.group [[META94]]
; CHECK-NEXT:    [[TMP921:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP922:%.*]] = getelementptr inbounds i64, ptr [[TMP921]], i32 [[GTID74]]
; CHECK-NEXT:    [[I70_CACHE81:%.*]] = load i64, ptr [[TMP922]], align 8, !invariant.group [[META95]]
; CHECK-NEXT:    [[TMP923:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP924:%.*]] = getelementptr inbounds i64, ptr [[TMP923]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP925:%.*]] = getelementptr inbounds ptr, ptr [[TMP924]], i32 [[GTID74]]
; CHECK-NEXT:    [[I142_CACHE82:%.*]] = load ptr, ptr [[TMP925]], align 8, !invariant.group [[META96]]
; CHECK-NEXT:    [[TMP926:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP927:%.*]] = getelementptr inbounds i64, ptr [[TMP926]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP928:%.*]] = getelementptr inbounds ptr, ptr [[TMP927]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP929:%.*]] = getelementptr inbounds i32, ptr [[TMP928]], i32 [[GTID74]]
; CHECK-NEXT:    [[I146_CACHE83:%.*]] = load i32, ptr [[TMP929]], align 4, !invariant.group [[META97]]
; CHECK-NEXT:    [[TMP930:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP931:%.*]] = getelementptr inbounds i64, ptr [[TMP930]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP932:%.*]] = getelementptr inbounds ptr, ptr [[TMP931]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP933:%.*]] = getelementptr inbounds i32, ptr [[TMP932]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP934:%.*]] = getelementptr inbounds i1, ptr [[TMP933]], i32 [[GTID74]]
; CHECK-NEXT:    [[I153_CACHE84:%.*]] = load i1, ptr [[TMP934]], align 1, !invariant.group [[META98]]
; CHECK-NEXT:    [[TMP935:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP936:%.*]] = getelementptr inbounds i64, ptr [[TMP935]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP937:%.*]] = getelementptr inbounds ptr, ptr [[TMP936]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP938:%.*]] = getelementptr inbounds i32, ptr [[TMP937]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP939:%.*]] = getelementptr inbounds i1, ptr [[TMP938]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP940:%.*]] = getelementptr inbounds ptr, ptr [[TMP939]], i32 [[GTID74]]
; CHECK-NEXT:    [[I148_CACHE85:%.*]] = load ptr, ptr [[TMP940]], align 8, !invariant.group [[META99]]
; CHECK-NEXT:    [[TMP941:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP942:%.*]] = getelementptr inbounds i64, ptr [[TMP941]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP943:%.*]] = getelementptr inbounds ptr, ptr [[TMP942]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP944:%.*]] = getelementptr inbounds i32, ptr [[TMP943]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP945:%.*]] = getelementptr inbounds i1, ptr [[TMP944]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP946:%.*]] = getelementptr inbounds ptr, ptr [[TMP945]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP947:%.*]] = getelementptr inbounds ptr, ptr [[TMP946]], i32 [[GTID74]]
; CHECK-NEXT:    [[I156_CACHE86:%.*]] = load ptr, ptr [[TMP947]], align 8, !invariant.group [[META100]]
; CHECK-NEXT:    [[TMP948:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP949:%.*]] = getelementptr inbounds i64, ptr [[TMP948]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP950:%.*]] = getelementptr inbounds ptr, ptr [[TMP949]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP951:%.*]] = getelementptr inbounds i32, ptr [[TMP950]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP952:%.*]] = getelementptr inbounds i1, ptr [[TMP951]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP953:%.*]] = getelementptr inbounds ptr, ptr [[TMP952]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP954:%.*]] = getelementptr inbounds ptr, ptr [[TMP953]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP955:%.*]] = getelementptr inbounds double, ptr [[TMP954]], i32 [[GTID74]]
; CHECK-NEXT:    [[I171_CACHE87:%.*]] = load double, ptr [[TMP955]], align 8, !invariant.group [[META101]]
; CHECK-NEXT:    [[TMP956:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP957:%.*]] = getelementptr inbounds i64, ptr [[TMP956]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP958:%.*]] = getelementptr inbounds ptr, ptr [[TMP957]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP959:%.*]] = getelementptr inbounds i32, ptr [[TMP958]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP960:%.*]] = getelementptr inbounds i1, ptr [[TMP959]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP961:%.*]] = getelementptr inbounds ptr, ptr [[TMP960]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP962:%.*]] = getelementptr inbounds ptr, ptr [[TMP961]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP963:%.*]] = getelementptr inbounds double, ptr [[TMP962]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP964:%.*]] = getelementptr inbounds i32, ptr [[TMP963]], i32 [[GTID74]]
; CHECK-NEXT:    [[I169_CACHE88:%.*]] = load i32, ptr [[TMP964]], align 4, !invariant.group [[META102]]
; CHECK-NEXT:    [[TMP965:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP966:%.*]] = getelementptr inbounds i64, ptr [[TMP965]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP967:%.*]] = getelementptr inbounds ptr, ptr [[TMP966]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP968:%.*]] = getelementptr inbounds i32, ptr [[TMP967]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP969:%.*]] = getelementptr inbounds i1, ptr [[TMP968]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP970:%.*]] = getelementptr inbounds ptr, ptr [[TMP969]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP971:%.*]] = getelementptr inbounds ptr, ptr [[TMP970]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP972:%.*]] = getelementptr inbounds double, ptr [[TMP971]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP973:%.*]] = getelementptr inbounds i32, ptr [[TMP972]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP974:%.*]] = getelementptr inbounds i32, ptr [[TMP973]], i32 [[GTID74]]
; CHECK-NEXT:    [[I165_CACHE89:%.*]] = load i32, ptr [[TMP974]], align 4, !invariant.group [[META103]]
; CHECK-NEXT:    [[TMP975:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP976:%.*]] = getelementptr inbounds i64, ptr [[TMP975]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP977:%.*]] = getelementptr inbounds ptr, ptr [[TMP976]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP978:%.*]] = getelementptr inbounds i32, ptr [[TMP977]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP979:%.*]] = getelementptr inbounds i1, ptr [[TMP978]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP980:%.*]] = getelementptr inbounds ptr, ptr [[TMP979]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP981:%.*]] = getelementptr inbounds ptr, ptr [[TMP980]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP982:%.*]] = getelementptr inbounds double, ptr [[TMP981]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP983:%.*]] = getelementptr inbounds i32, ptr [[TMP982]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP984:%.*]] = getelementptr inbounds i32, ptr [[TMP983]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP985:%.*]] = getelementptr inbounds double, ptr [[TMP984]], i32 [[GTID74]]
; CHECK-NEXT:    [[I164_CACHE90:%.*]] = load double, ptr [[TMP985]], align 8, !invariant.group [[META104]]
; CHECK-NEXT:    [[TMP986:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP987:%.*]] = getelementptr inbounds i64, ptr [[TMP986]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP988:%.*]] = getelementptr inbounds ptr, ptr [[TMP987]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP989:%.*]] = getelementptr inbounds i32, ptr [[TMP988]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP990:%.*]] = getelementptr inbounds i1, ptr [[TMP989]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP991:%.*]] = getelementptr inbounds ptr, ptr [[TMP990]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP992:%.*]] = getelementptr inbounds ptr, ptr [[TMP991]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP993:%.*]] = getelementptr inbounds double, ptr [[TMP992]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP994:%.*]] = getelementptr inbounds i32, ptr [[TMP993]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP995:%.*]] = getelementptr inbounds i32, ptr [[TMP994]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP996:%.*]] = getelementptr inbounds double, ptr [[TMP995]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP997:%.*]] = getelementptr inbounds double, ptr [[TMP996]], i32 [[GTID74]]
; CHECK-NEXT:    [[I163_CACHE91:%.*]] = load double, ptr [[TMP997]], align 8, !invariant.group [[META105]]
; CHECK-NEXT:    [[TMP998:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP999:%.*]] = getelementptr inbounds i64, ptr [[TMP998]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1000:%.*]] = getelementptr inbounds ptr, ptr [[TMP999]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1001:%.*]] = getelementptr inbounds i32, ptr [[TMP1000]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1002:%.*]] = getelementptr inbounds i1, ptr [[TMP1001]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1003:%.*]] = getelementptr inbounds ptr, ptr [[TMP1002]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1004:%.*]] = getelementptr inbounds ptr, ptr [[TMP1003]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1005:%.*]] = getelementptr inbounds double, ptr [[TMP1004]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1006:%.*]] = getelementptr inbounds i32, ptr [[TMP1005]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1007:%.*]] = getelementptr inbounds i32, ptr [[TMP1006]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1008:%.*]] = getelementptr inbounds double, ptr [[TMP1007]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1009:%.*]] = getelementptr inbounds double, ptr [[TMP1008]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1010:%.*]] = getelementptr inbounds double, ptr [[TMP1009]], i32 [[GTID74]]
; CHECK-NEXT:    [[I162_CACHE92:%.*]] = load double, ptr [[TMP1010]], align 8, !invariant.group [[META106]]
; CHECK-NEXT:    [[TMP1011:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1012:%.*]] = getelementptr inbounds i64, ptr [[TMP1011]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1013:%.*]] = getelementptr inbounds ptr, ptr [[TMP1012]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1014:%.*]] = getelementptr inbounds i32, ptr [[TMP1013]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1015:%.*]] = getelementptr inbounds i1, ptr [[TMP1014]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1016:%.*]] = getelementptr inbounds ptr, ptr [[TMP1015]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1017:%.*]] = getelementptr inbounds ptr, ptr [[TMP1016]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1018:%.*]] = getelementptr inbounds double, ptr [[TMP1017]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1019:%.*]] = getelementptr inbounds i32, ptr [[TMP1018]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1020:%.*]] = getelementptr inbounds i32, ptr [[TMP1019]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1021:%.*]] = getelementptr inbounds double, ptr [[TMP1020]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1022:%.*]] = getelementptr inbounds double, ptr [[TMP1021]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1023:%.*]] = getelementptr inbounds double, ptr [[TMP1022]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1024:%.*]] = getelementptr inbounds double, ptr [[TMP1023]], i32 [[GTID74]]
; CHECK-NEXT:    [[I161_CACHE93:%.*]] = load double, ptr [[TMP1024]], align 8, !invariant.group [[META107]]
; CHECK-NEXT:    [[TMP1025:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1026:%.*]] = getelementptr inbounds i64, ptr [[TMP1025]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1027:%.*]] = getelementptr inbounds ptr, ptr [[TMP1026]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1028:%.*]] = getelementptr inbounds i32, ptr [[TMP1027]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1029:%.*]] = getelementptr inbounds i1, ptr [[TMP1028]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1030:%.*]] = getelementptr inbounds ptr, ptr [[TMP1029]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1031:%.*]] = getelementptr inbounds ptr, ptr [[TMP1030]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1032:%.*]] = getelementptr inbounds double, ptr [[TMP1031]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1033:%.*]] = getelementptr inbounds i32, ptr [[TMP1032]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1034:%.*]] = getelementptr inbounds i32, ptr [[TMP1033]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1035:%.*]] = getelementptr inbounds double, ptr [[TMP1034]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1036:%.*]] = getelementptr inbounds double, ptr [[TMP1035]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1037:%.*]] = getelementptr inbounds double, ptr [[TMP1036]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1038:%.*]] = getelementptr inbounds double, ptr [[TMP1037]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1039:%.*]] = getelementptr inbounds double, ptr [[TMP1038]], i32 [[GTID74]]
; CHECK-NEXT:    [[I160_CACHE94:%.*]] = load double, ptr [[TMP1039]], align 8, !invariant.group [[META108]]
; CHECK-NEXT:    [[TMP1040:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1041:%.*]] = getelementptr inbounds i64, ptr [[TMP1040]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1042:%.*]] = getelementptr inbounds ptr, ptr [[TMP1041]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1043:%.*]] = getelementptr inbounds i32, ptr [[TMP1042]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1044:%.*]] = getelementptr inbounds i1, ptr [[TMP1043]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1045:%.*]] = getelementptr inbounds ptr, ptr [[TMP1044]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1046:%.*]] = getelementptr inbounds ptr, ptr [[TMP1045]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1047:%.*]] = getelementptr inbounds double, ptr [[TMP1046]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1048:%.*]] = getelementptr inbounds i32, ptr [[TMP1047]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1049:%.*]] = getelementptr inbounds i32, ptr [[TMP1048]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1050:%.*]] = getelementptr inbounds double, ptr [[TMP1049]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1051:%.*]] = getelementptr inbounds double, ptr [[TMP1050]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1052:%.*]] = getelementptr inbounds double, ptr [[TMP1051]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1053:%.*]] = getelementptr inbounds double, ptr [[TMP1052]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1054:%.*]] = getelementptr inbounds double, ptr [[TMP1053]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1055:%.*]] = getelementptr inbounds i32, ptr [[TMP1054]], i32 [[GTID74]]
; CHECK-NEXT:    [[I113_CACHE95:%.*]] = load i32, ptr [[TMP1055]], align 4, !invariant.group [[META109]]
; CHECK-NEXT:    [[TMP1056:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1057:%.*]] = getelementptr inbounds i64, ptr [[TMP1056]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1058:%.*]] = getelementptr inbounds ptr, ptr [[TMP1057]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1059:%.*]] = getelementptr inbounds i32, ptr [[TMP1058]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1060:%.*]] = getelementptr inbounds i1, ptr [[TMP1059]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1061:%.*]] = getelementptr inbounds ptr, ptr [[TMP1060]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1062:%.*]] = getelementptr inbounds ptr, ptr [[TMP1061]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1063:%.*]] = getelementptr inbounds double, ptr [[TMP1062]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1064:%.*]] = getelementptr inbounds i32, ptr [[TMP1063]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1065:%.*]] = getelementptr inbounds i32, ptr [[TMP1064]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1066:%.*]] = getelementptr inbounds double, ptr [[TMP1065]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1067:%.*]] = getelementptr inbounds double, ptr [[TMP1066]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1068:%.*]] = getelementptr inbounds double, ptr [[TMP1067]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1069:%.*]] = getelementptr inbounds double, ptr [[TMP1068]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1070:%.*]] = getelementptr inbounds double, ptr [[TMP1069]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1071:%.*]] = getelementptr inbounds i32, ptr [[TMP1070]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1072:%.*]] = getelementptr inbounds ptr, ptr [[TMP1071]], i32 [[GTID74]]
; CHECK-NEXT:    [[I112_CACHE96:%.*]] = load ptr, ptr [[TMP1072]], align 8, !invariant.group [[META110]]
; CHECK-NEXT:    [[TMP1073:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1074:%.*]] = getelementptr inbounds i64, ptr [[TMP1073]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1075:%.*]] = getelementptr inbounds ptr, ptr [[TMP1074]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1076:%.*]] = getelementptr inbounds i32, ptr [[TMP1075]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1077:%.*]] = getelementptr inbounds i1, ptr [[TMP1076]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1078:%.*]] = getelementptr inbounds ptr, ptr [[TMP1077]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1079:%.*]] = getelementptr inbounds ptr, ptr [[TMP1078]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1080:%.*]] = getelementptr inbounds double, ptr [[TMP1079]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1081:%.*]] = getelementptr inbounds i32, ptr [[TMP1080]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1082:%.*]] = getelementptr inbounds i32, ptr [[TMP1081]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1083:%.*]] = getelementptr inbounds double, ptr [[TMP1082]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1084:%.*]] = getelementptr inbounds double, ptr [[TMP1083]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1085:%.*]] = getelementptr inbounds double, ptr [[TMP1084]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1086:%.*]] = getelementptr inbounds double, ptr [[TMP1085]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1087:%.*]] = getelementptr inbounds double, ptr [[TMP1086]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1088:%.*]] = getelementptr inbounds i32, ptr [[TMP1087]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1089:%.*]] = getelementptr inbounds ptr, ptr [[TMP1088]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1090:%.*]] = getelementptr inbounds ptr, ptr [[TMP1089]], i32 [[GTID74]]
; CHECK-NEXT:    [[I111_CACHE97:%.*]] = load ptr, ptr [[TMP1090]], align 8, !invariant.group [[META111]]
; CHECK-NEXT:    [[TMP1091:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1092:%.*]] = getelementptr inbounds i64, ptr [[TMP1091]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1093:%.*]] = getelementptr inbounds ptr, ptr [[TMP1092]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1094:%.*]] = getelementptr inbounds i32, ptr [[TMP1093]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1095:%.*]] = getelementptr inbounds i1, ptr [[TMP1094]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1096:%.*]] = getelementptr inbounds ptr, ptr [[TMP1095]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1097:%.*]] = getelementptr inbounds ptr, ptr [[TMP1096]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1098:%.*]] = getelementptr inbounds double, ptr [[TMP1097]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1099:%.*]] = getelementptr inbounds i32, ptr [[TMP1098]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1100:%.*]] = getelementptr inbounds i32, ptr [[TMP1099]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1101:%.*]] = getelementptr inbounds double, ptr [[TMP1100]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1102:%.*]] = getelementptr inbounds double, ptr [[TMP1101]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1103:%.*]] = getelementptr inbounds double, ptr [[TMP1102]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1104:%.*]] = getelementptr inbounds double, ptr [[TMP1103]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1105:%.*]] = getelementptr inbounds double, ptr [[TMP1104]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1106:%.*]] = getelementptr inbounds i32, ptr [[TMP1105]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1107:%.*]] = getelementptr inbounds ptr, ptr [[TMP1106]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1108:%.*]] = getelementptr inbounds ptr, ptr [[TMP1107]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1109:%.*]] = getelementptr inbounds ptr, ptr [[TMP1108]], i32 [[GTID74]]
; CHECK-NEXT:    [[I108_CACHE98:%.*]] = load ptr, ptr [[TMP1109]], align 8, !invariant.group [[META112]]
; CHECK-NEXT:    [[TMP1110:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1111:%.*]] = getelementptr inbounds i64, ptr [[TMP1110]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1112:%.*]] = getelementptr inbounds ptr, ptr [[TMP1111]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1113:%.*]] = getelementptr inbounds i32, ptr [[TMP1112]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1114:%.*]] = getelementptr inbounds i1, ptr [[TMP1113]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1115:%.*]] = getelementptr inbounds ptr, ptr [[TMP1114]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1116:%.*]] = getelementptr inbounds ptr, ptr [[TMP1115]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1117:%.*]] = getelementptr inbounds double, ptr [[TMP1116]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1118:%.*]] = getelementptr inbounds i32, ptr [[TMP1117]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1119:%.*]] = getelementptr inbounds i32, ptr [[TMP1118]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1120:%.*]] = getelementptr inbounds double, ptr [[TMP1119]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1121:%.*]] = getelementptr inbounds double, ptr [[TMP1120]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1122:%.*]] = getelementptr inbounds double, ptr [[TMP1121]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1123:%.*]] = getelementptr inbounds double, ptr [[TMP1122]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1124:%.*]] = getelementptr inbounds double, ptr [[TMP1123]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1125:%.*]] = getelementptr inbounds i32, ptr [[TMP1124]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1126:%.*]] = getelementptr inbounds ptr, ptr [[TMP1125]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1127:%.*]] = getelementptr inbounds ptr, ptr [[TMP1126]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1128:%.*]] = getelementptr inbounds ptr, ptr [[TMP1127]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1129:%.*]] = getelementptr inbounds i64, ptr [[TMP1128]], i32 [[GTID74]]
; CHECK-NEXT:    [[I106_CACHE99:%.*]] = load i64, ptr [[TMP1129]], align 8, !invariant.group [[META113]]
; CHECK-NEXT:    [[TMP1130:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1131:%.*]] = getelementptr inbounds i64, ptr [[TMP1130]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1132:%.*]] = getelementptr inbounds ptr, ptr [[TMP1131]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1133:%.*]] = getelementptr inbounds i32, ptr [[TMP1132]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1134:%.*]] = getelementptr inbounds i1, ptr [[TMP1133]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1135:%.*]] = getelementptr inbounds ptr, ptr [[TMP1134]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1136:%.*]] = getelementptr inbounds ptr, ptr [[TMP1135]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1137:%.*]] = getelementptr inbounds double, ptr [[TMP1136]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1138:%.*]] = getelementptr inbounds i32, ptr [[TMP1137]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1139:%.*]] = getelementptr inbounds i32, ptr [[TMP1138]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1140:%.*]] = getelementptr inbounds double, ptr [[TMP1139]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1141:%.*]] = getelementptr inbounds double, ptr [[TMP1140]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1142:%.*]] = getelementptr inbounds double, ptr [[TMP1141]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1143:%.*]] = getelementptr inbounds double, ptr [[TMP1142]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1144:%.*]] = getelementptr inbounds double, ptr [[TMP1143]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1145:%.*]] = getelementptr inbounds i32, ptr [[TMP1144]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1146:%.*]] = getelementptr inbounds ptr, ptr [[TMP1145]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1147:%.*]] = getelementptr inbounds ptr, ptr [[TMP1146]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1148:%.*]] = getelementptr inbounds ptr, ptr [[TMP1147]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1149:%.*]] = getelementptr inbounds i64, ptr [[TMP1148]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1150:%.*]] = getelementptr inbounds i64, ptr [[TMP1149]], i32 [[GTID74]]
; CHECK-NEXT:    [[I40_CACHE100:%.*]] = load i64, ptr [[TMP1150]], align 8, !invariant.group [[META114]]
; CHECK-NEXT:    [[TMP1151:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1152:%.*]] = getelementptr inbounds i64, ptr [[TMP1151]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1153:%.*]] = getelementptr inbounds ptr, ptr [[TMP1152]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1154:%.*]] = getelementptr inbounds i32, ptr [[TMP1153]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1155:%.*]] = getelementptr inbounds i1, ptr [[TMP1154]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1156:%.*]] = getelementptr inbounds ptr, ptr [[TMP1155]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1157:%.*]] = getelementptr inbounds ptr, ptr [[TMP1156]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1158:%.*]] = getelementptr inbounds double, ptr [[TMP1157]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1159:%.*]] = getelementptr inbounds i32, ptr [[TMP1158]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1160:%.*]] = getelementptr inbounds i32, ptr [[TMP1159]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1161:%.*]] = getelementptr inbounds double, ptr [[TMP1160]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1162:%.*]] = getelementptr inbounds double, ptr [[TMP1161]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1163:%.*]] = getelementptr inbounds double, ptr [[TMP1162]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1164:%.*]] = getelementptr inbounds double, ptr [[TMP1163]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1165:%.*]] = getelementptr inbounds double, ptr [[TMP1164]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1166:%.*]] = getelementptr inbounds i32, ptr [[TMP1165]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1167:%.*]] = getelementptr inbounds ptr, ptr [[TMP1166]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1168:%.*]] = getelementptr inbounds ptr, ptr [[TMP1167]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1169:%.*]] = getelementptr inbounds ptr, ptr [[TMP1168]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1170:%.*]] = getelementptr inbounds i64, ptr [[TMP1169]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1171:%.*]] = getelementptr inbounds i64, ptr [[TMP1170]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1172:%.*]] = getelementptr inbounds i32, ptr [[TMP1171]], i32 [[GTID74]]
; CHECK-NEXT:    [[I31_CACHE101:%.*]] = load i32, ptr [[TMP1172]], align 4, !invariant.group [[META115]]
; CHECK-NEXT:    [[TMP1173:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1174:%.*]] = getelementptr inbounds i64, ptr [[TMP1173]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1175:%.*]] = getelementptr inbounds ptr, ptr [[TMP1174]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1176:%.*]] = getelementptr inbounds i32, ptr [[TMP1175]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1177:%.*]] = getelementptr inbounds i1, ptr [[TMP1176]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1178:%.*]] = getelementptr inbounds ptr, ptr [[TMP1177]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1179:%.*]] = getelementptr inbounds ptr, ptr [[TMP1178]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1180:%.*]] = getelementptr inbounds double, ptr [[TMP1179]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1181:%.*]] = getelementptr inbounds i32, ptr [[TMP1180]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1182:%.*]] = getelementptr inbounds i32, ptr [[TMP1181]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1183:%.*]] = getelementptr inbounds double, ptr [[TMP1182]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1184:%.*]] = getelementptr inbounds double, ptr [[TMP1183]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1185:%.*]] = getelementptr inbounds double, ptr [[TMP1184]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1186:%.*]] = getelementptr inbounds double, ptr [[TMP1185]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1187:%.*]] = getelementptr inbounds double, ptr [[TMP1186]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1188:%.*]] = getelementptr inbounds i32, ptr [[TMP1187]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1189:%.*]] = getelementptr inbounds ptr, ptr [[TMP1188]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1190:%.*]] = getelementptr inbounds ptr, ptr [[TMP1189]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1191:%.*]] = getelementptr inbounds ptr, ptr [[TMP1190]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1192:%.*]] = getelementptr inbounds i64, ptr [[TMP1191]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1193:%.*]] = getelementptr inbounds i64, ptr [[TMP1192]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1194:%.*]] = getelementptr inbounds i32, ptr [[TMP1193]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1195:%.*]] = getelementptr inbounds i32, ptr [[TMP1194]], i32 [[GTID74]]
; CHECK-NEXT:    [[I30_CACHE102:%.*]] = load i32, ptr [[TMP1195]], align 4, !invariant.group [[META116]]
; CHECK-NEXT:    [[TMP1196:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1197:%.*]] = getelementptr inbounds i64, ptr [[TMP1196]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1198:%.*]] = getelementptr inbounds ptr, ptr [[TMP1197]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1199:%.*]] = getelementptr inbounds i32, ptr [[TMP1198]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1200:%.*]] = getelementptr inbounds i1, ptr [[TMP1199]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1201:%.*]] = getelementptr inbounds ptr, ptr [[TMP1200]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1202:%.*]] = getelementptr inbounds ptr, ptr [[TMP1201]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1203:%.*]] = getelementptr inbounds double, ptr [[TMP1202]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1204:%.*]] = getelementptr inbounds i32, ptr [[TMP1203]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1205:%.*]] = getelementptr inbounds i32, ptr [[TMP1204]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1206:%.*]] = getelementptr inbounds double, ptr [[TMP1205]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1207:%.*]] = getelementptr inbounds double, ptr [[TMP1206]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1208:%.*]] = getelementptr inbounds double, ptr [[TMP1207]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1209:%.*]] = getelementptr inbounds double, ptr [[TMP1208]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1210:%.*]] = getelementptr inbounds double, ptr [[TMP1209]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1211:%.*]] = getelementptr inbounds i32, ptr [[TMP1210]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1212:%.*]] = getelementptr inbounds ptr, ptr [[TMP1211]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1213:%.*]] = getelementptr inbounds ptr, ptr [[TMP1212]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1214:%.*]] = getelementptr inbounds ptr, ptr [[TMP1213]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1215:%.*]] = getelementptr inbounds i64, ptr [[TMP1214]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1216:%.*]] = getelementptr inbounds i64, ptr [[TMP1215]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1217:%.*]] = getelementptr inbounds i32, ptr [[TMP1216]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1218:%.*]] = getelementptr inbounds i32, ptr [[TMP1217]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1219:%.*]] = getelementptr inbounds i32, ptr [[TMP1218]], i32 [[GTID74]]
; CHECK-NEXT:    [[I5_CACHE103:%.*]] = load i32, ptr [[TMP1219]], align 4, !invariant.group [[META117]]
; CHECK-NEXT:    [[TMP1220:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1221:%.*]] = getelementptr inbounds i64, ptr [[TMP1220]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1222:%.*]] = getelementptr inbounds ptr, ptr [[TMP1221]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1223:%.*]] = getelementptr inbounds i32, ptr [[TMP1222]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1224:%.*]] = getelementptr inbounds i1, ptr [[TMP1223]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1225:%.*]] = getelementptr inbounds ptr, ptr [[TMP1224]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1226:%.*]] = getelementptr inbounds ptr, ptr [[TMP1225]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1227:%.*]] = getelementptr inbounds double, ptr [[TMP1226]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1228:%.*]] = getelementptr inbounds i32, ptr [[TMP1227]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1229:%.*]] = getelementptr inbounds i32, ptr [[TMP1228]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1230:%.*]] = getelementptr inbounds double, ptr [[TMP1229]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1231:%.*]] = getelementptr inbounds double, ptr [[TMP1230]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1232:%.*]] = getelementptr inbounds double, ptr [[TMP1231]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1233:%.*]] = getelementptr inbounds double, ptr [[TMP1232]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1234:%.*]] = getelementptr inbounds double, ptr [[TMP1233]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1235:%.*]] = getelementptr inbounds i32, ptr [[TMP1234]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1236:%.*]] = getelementptr inbounds ptr, ptr [[TMP1235]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1237:%.*]] = getelementptr inbounds ptr, ptr [[TMP1236]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1238:%.*]] = getelementptr inbounds ptr, ptr [[TMP1237]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1239:%.*]] = getelementptr inbounds i64, ptr [[TMP1238]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1240:%.*]] = getelementptr inbounds i64, ptr [[TMP1239]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1241:%.*]] = getelementptr inbounds i32, ptr [[TMP1240]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1242:%.*]] = getelementptr inbounds i32, ptr [[TMP1241]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1243:%.*]] = getelementptr inbounds i32, ptr [[TMP1242]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1244:%.*]] = getelementptr inbounds i32, ptr [[TMP1243]], i32 [[GTID74]]
; CHECK-NEXT:    [[I_CACHE104:%.*]] = load i32, ptr [[TMP1244]], align 4, !invariant.group [[META118]]
; CHECK-NEXT:    [[TMP1245:%.*]] = getelementptr inbounds i32, ptr [[CACHE_IN_PTR78]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1246:%.*]] = getelementptr inbounds i64, ptr [[TMP1245]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1247:%.*]] = getelementptr inbounds ptr, ptr [[TMP1246]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1248:%.*]] = getelementptr inbounds i32, ptr [[TMP1247]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1249:%.*]] = getelementptr inbounds i1, ptr [[TMP1248]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1250:%.*]] = getelementptr inbounds ptr, ptr [[TMP1249]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1251:%.*]] = getelementptr inbounds ptr, ptr [[TMP1250]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1252:%.*]] = getelementptr inbounds double, ptr [[TMP1251]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1253:%.*]] = getelementptr inbounds i32, ptr [[TMP1252]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1254:%.*]] = getelementptr inbounds i32, ptr [[TMP1253]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1255:%.*]] = getelementptr inbounds double, ptr [[TMP1254]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1256:%.*]] = getelementptr inbounds double, ptr [[TMP1255]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1257:%.*]] = getelementptr inbounds double, ptr [[TMP1256]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1258:%.*]] = getelementptr inbounds double, ptr [[TMP1257]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1259:%.*]] = getelementptr inbounds double, ptr [[TMP1258]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1260:%.*]] = getelementptr inbounds i32, ptr [[TMP1259]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1261:%.*]] = getelementptr inbounds ptr, ptr [[TMP1260]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1262:%.*]] = getelementptr inbounds ptr, ptr [[TMP1261]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1263:%.*]] = getelementptr inbounds ptr, ptr [[TMP1262]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1264:%.*]] = getelementptr inbounds i64, ptr [[TMP1263]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1265:%.*]] = getelementptr inbounds i64, ptr [[TMP1264]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1266:%.*]] = getelementptr inbounds i32, ptr [[TMP1265]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1267:%.*]] = getelementptr inbounds i32, ptr [[TMP1266]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1268:%.*]] = getelementptr inbounds i32, ptr [[TMP1267]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1269:%.*]] = getelementptr inbounds i32, ptr [[TMP1268]], i32 [[CACHE_IN_OFFSET79]]
; CHECK-NEXT:    [[TMP1270:%.*]] = getelementptr inbounds i32, ptr [[TMP1269]], i32 [[GTID74]]
; CHECK-NEXT:    [[I18_CACHE105:%.*]] = load i32, ptr [[TMP1270]], align 4, !invariant.group [[META119]]
; CHECK-NEXT:    [[I13_RECOMPUTE106:%.*]] = shl nsw i32 [[I10_CACHE80]], 7
; CHECK-NEXT:    [[I4_RECOMPUTE107:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I19_RECOMPUTE108:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 8
; CHECK-NEXT:    [[I20_RECOMPUTE109:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 16
; CHECK-NEXT:    [[I26_RECOMPUTE110:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 40
; CHECK-NEXT:    [[I27_RECOMPUTE111:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 44
; CHECK-NEXT:    [[I71_RECOMPUTE112:%.*]] = mul i64 [[I70_CACHE81]], 2806196910506780709
; CHECK-NEXT:    [[I72_RECOMPUTE113:%.*]] = add i64 [[I71_RECOMPUTE112]], 1
; CHECK-NEXT:    [[I73_RECOMPUTE114:%.*]] = and i64 [[I72_RECOMPUTE113]], 9223372036854775807
; CHECK-NEXT:    [[I74_RECOMPUTE115:%.*]] = uitofp i64 [[I73_RECOMPUTE114]] to double
; CHECK-NEXT:    [[I75_RECOMPUTE116:%.*]] = fmul double [[I74_RECOMPUTE115]], 0x3C00000000000000
; CHECK-NEXT:    [[I149_RECOMPUTE117:%.*]] = add i64 [[I106_CACHE99]], -1
; CHECK-NEXT:    [[I150_RECOMPUTE118:%.*]] = icmp sgt i64 [[I106_CACHE99]], 2
; CHECK-NEXT:    [[I157_RECOMPUTE119:%.*]] = trunc i64 [[I106_CACHE99]] to i32
; CHECK-NEXT:    [[I158_RECOMPUTE120:%.*]] = add i32 [[I157_RECOMPUTE119]], -1
; CHECK-NEXT:    [[I41_RECOMPUTE121:%.*]] = trunc i64 [[I40_CACHE100]] to i32
; CHECK-NEXT:    [[I32_RECOMPUTE122:%.*]] = zext i32 [[I30_CACHE102]] to i64
; CHECK-NEXT:    [[I6_RECOMPUTE123:%.*]] = add nsw i32 [[I5_CACHE103]], -1
; CHECK-NEXT:    [[I21_RECOMPUTE124:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 8
; CHECK-NEXT:    [[I22_RECOMPUTE125:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 24
; CHECK-NEXT:    [[I23_RECOMPUTE126:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 32
; CHECK-NEXT:    [[I24_RECOMPUTE127:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 40
; CHECK-NEXT:    [[I25_RECOMPUTE128:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 16
; CHECK-NEXT:    [[I28_RECOMPUTE129:%.*]] = getelementptr inbounds i8, ptr [[ARG2]], i64 76
; CHECK-NEXT:    [[I209:%.*]] = sext i32 [[I169_CACHE88]] to i64
; CHECK-NEXT:    [[I210:%.*]] = getelementptr i32, ptr [[I148_CACHE85]], i64 [[I209]]
; CHECK-NEXT:    [[I211:%.*]] = load i32, ptr [[I210]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    br i1 [[I153_CACHE84]], label [[BB216:%.*]], label [[BB212:%.*]]
; CHECK:       bb212:
; CHECK-NEXT:    [[I213:%.*]] = getelementptr i32, ptr [[I156_CACHE86]], i64 [[I209]]
; CHECK-NEXT:    [[I214:%.*]] = load i32, ptr [[I213]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I215:%.*]] = add nsw i32 [[I214]], 1
; CHECK-NEXT:    br label [[BB216]]
; CHECK:       bb216:
; CHECK-NEXT:    [[I217:%.*]] = phi i32 [ [[I215]], [[BB212]] ], [ [[I158_RECOMPUTE120]], [[CACHEREMAT2]] ]
; CHECK-NEXT:    [[I218:%.*]] = mul nsw i64 [[I106_CACHE99]], [[I209]]
; CHECK-NEXT:    [[I219:%.*]] = sext i32 [[I211]] to i64
; CHECK-NEXT:    [[I220:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I111_CACHE97]], i64 [[I218]]
; CHECK-NEXT:    [[I221:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I220]], i64 [[I219]]
; CHECK-NEXT:    [[I222:%.*]] = load double, ptr [[I221]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I223:%.*]] = sext i32 [[I217]] to i64
; CHECK-NEXT:    [[I224:%.*]] = fcmp ult double [[I222]], [[I75_RECOMPUTE116]]
; CHECK-NEXT:    br i1 [[I224]], label [[BB225:%.*]], label [[BB245:%.*]]
; CHECK:       bb225:
; CHECK-NEXT:    [[I226:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I220]], i64 [[I223]]
; CHECK-NEXT:    [[I227:%.*]] = load double, ptr [[I226]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I228:%.*]] = fcmp ugt double [[I227]], [[I75_RECOMPUTE116]]
; CHECK-NEXT:    br i1 [[I228]], label [[BB229:%.*]], label [[BB245]]
; CHECK:       bb229:
; CHECK-NEXT:    [[I230:%.*]] = sub nsw i64 [[I223]], [[I219]]
; CHECK-NEXT:    [[I231:%.*]] = icmp sgt i64 [[I230]], 1
; CHECK-NEXT:    br i1 [[I231]], label [[BB232:%.*]], label [[BB245]]
; CHECK:       bb232:
; CHECK-NEXT:    [[I233:%.*]] = phi i64 [ [[I230]], [[BB229]] ], [ [[I243:%.*]], [[BB232]] ]
; CHECK-NEXT:    [[I234:%.*]] = phi i64 [ [[I219]], [[BB229]] ], [ [[I242:%.*]], [[BB232]] ]
; CHECK-NEXT:    [[I235:%.*]] = phi i64 [ [[I223]], [[BB229]] ], [ [[I241:%.*]], [[BB232]] ]
; CHECK-NEXT:    [[I236:%.*]] = lshr i64 [[I233]], 1
; CHECK-NEXT:    [[I237:%.*]] = add nsw i64 [[I236]], [[I234]]
; CHECK-NEXT:    [[I238:%.*]] = getelementptr inbounds [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I220]], i64 [[I237]]
; CHECK-NEXT:    [[I239:%.*]] = load double, ptr [[I238]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I240:%.*]] = fcmp ogt double [[I239]], [[I75_RECOMPUTE116]]
; CHECK-NEXT:    [[I241]] = select i1 [[I240]], i64 [[I237]], i64 [[I235]]
; CHECK-NEXT:    [[I242]] = select i1 [[I240]], i64 [[I234]], i64 [[I237]]
; CHECK-NEXT:    [[I243]] = sub nsw i64 [[I241]], [[I242]]
; CHECK-NEXT:    [[I244:%.*]] = icmp sgt i64 [[I243]], 1
; CHECK-NEXT:    br i1 [[I244]], label [[BB232]], label [[BB245]]
; CHECK:       bb245:
; CHECK-NEXT:    [[I246:%.*]] = phi i64 [ 0, [[BB216]] ], [ [[I149_RECOMPUTE117]], [[BB225]] ], [ [[I219]], [[BB229]] ], [ [[I242]], [[BB232]] ]
; CHECK-NEXT:    [[I247:%.*]] = shl i64 [[I246]], 32
; CHECK-NEXT:    [[I248:%.*]] = ashr exact i64 [[I247]], 32
; CHECK-NEXT:    [[I249:%.*]] = icmp eq i64 [[I248]], [[I149_RECOMPUTE117]]
; CHECK-NEXT:    br i1 [[I249]], label [[BB250:%.*]], label [[BB253:%.*]]
; CHECK:       bb250:
; CHECK-NEXT:    [[I251:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I220]], i64 [[I149_RECOMPUTE117]]
; CHECK-NEXT:    [[I252:%.*]] = getelementptr i8, ptr [[I251]], i64 -48
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       bb253:
; CHECK-NEXT:    [[I254:%.*]] = getelementptr [[STRUCT_NUCLIDEGRIDPOINT]], ptr [[I220]], i64 [[I248]]
; CHECK-NEXT:    br label [[BB255]]
; CHECK:       bb255:
; CHECK-NEXT:    [[I149344]] = phi i64 [ [[I149_RECOMPUTE117]], [[BB253]] ], [ [[I149_RECOMPUTE117]], [[BB250]] ], [ [[I149345]], [[BB197]] ]
; CHECK-NEXT:    [[I160343:%.*]] = phi double [ [[I160_CACHE94]], [[BB253]] ], [ [[I160_CACHE94]], [[BB250]] ], [ [[I160]], [[BB197]] ]
; CHECK-NEXT:    [[I161342:%.*]] = phi double [ [[I161_CACHE93]], [[BB253]] ], [ [[I161_CACHE93]], [[BB250]] ], [ [[I161]], [[BB197]] ]
; CHECK-NEXT:    [[I162341:%.*]] = phi double [ [[I162_CACHE92]], [[BB253]] ], [ [[I162_CACHE92]], [[BB250]] ], [ [[I162]], [[BB197]] ]
; CHECK-NEXT:    [[I163340:%.*]] = phi double [ [[I163_CACHE91]], [[BB253]] ], [ [[I163_CACHE91]], [[BB250]] ], [ [[I163]], [[BB197]] ]
; CHECK-NEXT:    [[I164339:%.*]] = phi double [ [[I164_CACHE90]], [[BB253]] ], [ [[I164_CACHE90]], [[BB250]] ], [ [[I164]], [[BB197]] ]
; CHECK-NEXT:    [[I165338:%.*]] = phi i32 [ [[I165_CACHE89]], [[BB253]] ], [ [[I165_CACHE89]], [[BB250]] ], [ [[I165]], [[BB197]] ]
; CHECK-NEXT:    [[I171337:%.*]] = phi double [ [[I171_CACHE87]], [[BB253]] ], [ [[I171_CACHE87]], [[BB250]] ], [ [[I171]], [[BB197]] ]
; CHECK-NEXT:    [[I156335]] = phi ptr [ [[I156_CACHE86]], [[BB253]] ], [ [[I156_CACHE86]], [[BB250]] ], [ [[I156336]], [[BB197]] ]
; CHECK-NEXT:    [[I148333]] = phi ptr [ [[I148_CACHE85]], [[BB253]] ], [ [[I148_CACHE85]], [[BB250]] ], [ [[I148334]], [[BB197]] ]
; CHECK-NEXT:    [[I153331]] = phi i1 [ [[I153_CACHE84]], [[BB253]] ], [ [[I153_CACHE84]], [[BB250]] ], [ [[I153332]], [[BB197]] ]
; CHECK-NEXT:    [[I146329]] = phi i32 [ [[I146_CACHE83]], [[BB253]] ], [ [[I146_CACHE83]], [[BB250]] ], [ [[I146330]], [[BB197]] ]
; CHECK-NEXT:    [[I142327]] = phi ptr [ [[I142_CACHE82]], [[BB253]] ], [ [[I142_CACHE82]], [[BB250]] ], [ [[I142328]], [[BB197]] ]
; CHECK-NEXT:    [[I28321]] = phi ptr [ [[I28_RECOMPUTE129]], [[BB253]] ], [ [[I28_RECOMPUTE129]], [[BB250]] ], [ [[I28324]], [[BB197]] ]
; CHECK-NEXT:    [[I25314]] = phi ptr [ [[I25_RECOMPUTE128]], [[BB253]] ], [ [[I25_RECOMPUTE128]], [[BB250]] ], [ [[I25317]], [[BB197]] ]
; CHECK-NEXT:    [[I24307]] = phi ptr [ [[I24_RECOMPUTE127]], [[BB253]] ], [ [[I24_RECOMPUTE127]], [[BB250]] ], [ [[I24310]], [[BB197]] ]
; CHECK-NEXT:    [[I23300]] = phi ptr [ [[I23_RECOMPUTE126]], [[BB253]] ], [ [[I23_RECOMPUTE126]], [[BB250]] ], [ [[I23303]], [[BB197]] ]
; CHECK-NEXT:    [[I22293]] = phi ptr [ [[I22_RECOMPUTE125]], [[BB253]] ], [ [[I22_RECOMPUTE125]], [[BB250]] ], [ [[I22296]], [[BB197]] ]
; CHECK-NEXT:    [[I21286]] = phi ptr [ [[I21_RECOMPUTE124]], [[BB253]] ], [ [[I21_RECOMPUTE124]], [[BB250]] ], [ [[I21289]], [[BB197]] ]
; CHECK-NEXT:    [[I6278]] = phi i32 [ [[I6_RECOMPUTE123]], [[BB253]] ], [ [[I6_RECOMPUTE123]], [[BB250]] ], [ [[I6281]], [[BB197]] ]
; CHECK-NEXT:    [[I32273]] = phi i64 [ [[I32_RECOMPUTE122]], [[BB253]] ], [ [[I32_RECOMPUTE122]], [[BB250]] ], [ [[I32276]], [[BB197]] ]
; CHECK-NEXT:    [[I41269]] = phi i32 [ [[I41_RECOMPUTE121]], [[BB253]] ], [ [[I41_RECOMPUTE121]], [[BB250]] ], [ [[I41272]], [[BB197]] ]
; CHECK-NEXT:    [[I75266]] = phi double [ [[I75_RECOMPUTE116]], [[BB253]] ], [ [[I75_RECOMPUTE116]], [[BB250]] ], [ [[I75268]], [[BB197]] ]
; CHECK-NEXT:    [[I27260]] = phi ptr [ [[I27_RECOMPUTE111]], [[BB253]] ], [ [[I27_RECOMPUTE111]], [[BB250]] ], [ [[I27263]], [[BB197]] ]
; CHECK-NEXT:    [[I26253]] = phi ptr [ [[I26_RECOMPUTE110]], [[BB253]] ], [ [[I26_RECOMPUTE110]], [[BB250]] ], [ [[I26256]], [[BB197]] ]
; CHECK-NEXT:    [[I20246]] = phi ptr [ [[I20_RECOMPUTE109]], [[BB253]] ], [ [[I20_RECOMPUTE109]], [[BB250]] ], [ [[I20249]], [[BB197]] ]
; CHECK-NEXT:    [[I19239]] = phi ptr [ [[I19_RECOMPUTE108]], [[BB253]] ], [ [[I19_RECOMPUTE108]], [[BB250]] ], [ [[I19242]], [[BB197]] ]
; CHECK-NEXT:    [[I4231]] = phi ptr [ [[I4_RECOMPUTE107]], [[BB253]] ], [ [[I4_RECOMPUTE107]], [[BB250]] ], [ [[I4234]], [[BB197]] ]
; CHECK-NEXT:    [[I13224]] = phi i32 [ [[I13_RECOMPUTE106]], [[BB253]] ], [ [[I13_RECOMPUTE106]], [[BB250]] ], [ [[I13228]], [[BB197]] ]
; CHECK-NEXT:    [[I18217]] = phi i32 [ [[I18_CACHE105]], [[BB253]] ], [ [[I18_CACHE105]], [[BB250]] ], [ [[I18220]], [[BB197]] ]
; CHECK-NEXT:    [[I189]] = phi i32 [ [[I_CACHE104]], [[BB253]] ], [ [[I_CACHE104]], [[BB250]] ], [ [[I197]], [[BB197]] ]
; CHECK-NEXT:    [[I5177]] = phi i32 [ [[I5_CACHE103]], [[BB253]] ], [ [[I5_CACHE103]], [[BB250]] ], [ [[I5180]], [[BB197]] ]
; CHECK-NEXT:    [[I30171]] = phi i32 [ [[I30_CACHE102]], [[BB253]] ], [ [[I30_CACHE102]], [[BB250]] ], [ [[I30174]], [[BB197]] ]
; CHECK-NEXT:    [[I31165]] = phi i32 [ [[I31_CACHE101]], [[BB253]] ], [ [[I31_CACHE101]], [[BB250]] ], [ [[I31168]], [[BB197]] ]
; CHECK-NEXT:    [[I40161]] = phi i64 [ [[I40_CACHE100]], [[BB253]] ], [ [[I40_CACHE100]], [[BB250]] ], [ [[I40164]], [[BB197]] ]
; CHECK-NEXT:    [[I106157]] = phi i64 [ [[I106_CACHE99]], [[BB253]] ], [ [[I106_CACHE99]], [[BB250]] ], [ [[I106158]], [[BB197]] ]
; CHECK-NEXT:    [[I108153]] = phi ptr [ [[I108_CACHE98]], [[BB253]] ], [ [[I108_CACHE98]], [[BB250]] ], [ [[I108154]], [[BB197]] ]
; CHECK-NEXT:    [[I111149]] = phi ptr [ [[I111_CACHE97]], [[BB253]] ], [ [[I111_CACHE97]], [[BB250]] ], [ [[I111150]], [[BB197]] ]
; CHECK-NEXT:    [[I112146]] = phi ptr [ [[I112_CACHE96]], [[BB253]] ], [ [[I112_CACHE96]], [[BB250]] ], [ [[I112147]], [[BB197]] ]
; CHECK-NEXT:    [[I113143]] = phi i32 [ [[I113_CACHE95]], [[BB253]] ], [ [[I113_CACHE95]], [[BB250]] ], [ 0, [[BB197]] ]
; CHECK-NEXT:    [[I70137]] = phi i64 [ [[I70_CACHE81]], [[BB253]] ], [ [[I70_CACHE81]], [[BB250]] ], [ [[I70139]], [[BB197]] ]
; CHECK-NEXT:    [[I10130]] = phi i32 [ [[I10_CACHE80]], [[BB253]] ], [ [[I10_CACHE80]], [[BB250]] ], [ [[I10133]], [[BB197]] ]
; CHECK-NEXT:    [[I256:%.*]] = phi ptr [ [[I252]], [[BB250]] ], [ [[I254]], [[BB253]] ], [ [[I207]], [[BB197]] ]
; CHECK-NEXT:    [[I257:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 48
; CHECK-NEXT:    [[I258:%.*]] = load double, ptr [[I257]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I259:%.*]] = fsub double [[I258]], [[I75266]]
; CHECK-NEXT:    [[I260:%.*]] = load double, ptr [[I256]], align 8, !tbaa [[TBAA87]]
; CHECK-NEXT:    [[I261:%.*]] = fsub double [[I258]], [[I260]]
; CHECK-NEXT:    [[I262:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 56
; CHECK-NEXT:    [[I263:%.*]] = load double, ptr [[I262]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I264:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 8
; CHECK-NEXT:    [[I265:%.*]] = load double, ptr [[I264]], align 8, !tbaa [[TBAA89]]
; CHECK-NEXT:    [[I266:%.*]] = fsub double [[I263]], [[I265]]
; CHECK-NEXT:    [[I267:%.*]] = fneg double [[I259]]
; CHECK-NEXT:    [[I268:%.*]] = fdiv double [[I267]], [[I261]]
; CHECK-NEXT:    [[I269:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I266]], double [[I263]])
; CHECK-NEXT:    [[I270:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 64
; CHECK-NEXT:    [[I271:%.*]] = load double, ptr [[I270]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I272:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 16
; CHECK-NEXT:    [[I273:%.*]] = load double, ptr [[I272]], align 8, !tbaa [[TBAA90]]
; CHECK-NEXT:    [[I274:%.*]] = fsub double [[I271]], [[I273]]
; CHECK-NEXT:    [[I275:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I274]], double [[I271]])
; CHECK-NEXT:    [[I276:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 72
; CHECK-NEXT:    [[I277:%.*]] = load double, ptr [[I276]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I278:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 24
; CHECK-NEXT:    [[I279:%.*]] = load double, ptr [[I278]], align 8, !tbaa [[TBAA91]]
; CHECK-NEXT:    [[I280:%.*]] = fsub double [[I277]], [[I279]]
; CHECK-NEXT:    [[I281:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I280]], double [[I277]])
; CHECK-NEXT:    [[I282:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 80
; CHECK-NEXT:    [[I283:%.*]] = load double, ptr [[I282]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I284:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 32
; CHECK-NEXT:    [[I285:%.*]] = load double, ptr [[I284]], align 8, !tbaa [[TBAA92]]
; CHECK-NEXT:    [[I286:%.*]] = fsub double [[I283]], [[I285]]
; CHECK-NEXT:    [[I287:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I286]], double [[I283]])
; CHECK-NEXT:    [[I288:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 88
; CHECK-NEXT:    [[I289:%.*]] = load double, ptr [[I288]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I290:%.*]] = getelementptr inbounds i8, ptr [[I256]], i64 40
; CHECK-NEXT:    [[I291:%.*]] = load double, ptr [[I290]], align 8, !tbaa [[TBAA93]]
; CHECK-NEXT:    [[I292:%.*]] = fsub double [[I289]], [[I291]]
; CHECK-NEXT:    [[I293:%.*]] = tail call double @llvm.fmuladd.f64(double [[I268]], double [[I292]], double [[I289]])
; CHECK-NEXT:    [[I294]] = tail call double @llvm.fmuladd.f64(double [[I269]], double [[I171337]], double [[I164339]])
; CHECK-NEXT:    [[I295]] = tail call double @llvm.fmuladd.f64(double [[I275]], double [[I171337]], double [[I163340]])
; CHECK-NEXT:    [[I296]] = tail call double @llvm.fmuladd.f64(double [[I281]], double [[I171337]], double [[I162341]])
; CHECK-NEXT:    [[I297]] = tail call double @llvm.fmuladd.f64(double [[I287]], double [[I171337]], double [[I161342]])
; CHECK-NEXT:    [[I298]] = tail call double @llvm.fmuladd.f64(double [[I293]], double [[I171337]], double [[I160343]])
; CHECK-NEXT:    [[I299]] = add nuw nsw i32 [[I165338]], 1
; CHECK-NEXT:    [[I300:%.*]] = load i32, ptr [[I142327]], align 4, !tbaa [[TBAA60]]
; CHECK-NEXT:    [[I301:%.*]] = icmp slt i32 [[I299]], [[I300]]
; CHECK-NEXT:    br i1 [[I301]], label [[BB159]], label [[BB302]]
; CHECK:       bb302:
; CHECK-NEXT:    [[I28323]] = phi ptr [ [[I28326]], [[BB139]] ], [ [[I28321]], [[BB255]] ]
; CHECK-NEXT:    [[I25316]] = phi ptr [ [[I25319]], [[BB139]] ], [ [[I25314]], [[BB255]] ]
; CHECK-NEXT:    [[I24309]] = phi ptr [ [[I24312]], [[BB139]] ], [ [[I24307]], [[BB255]] ]
; CHECK-NEXT:    [[I23302]] = phi ptr [ [[I23305]], [[BB139]] ], [ [[I23300]], [[BB255]] ]
; CHECK-NEXT:    [[I22295]] = phi ptr [ [[I22298]], [[BB139]] ], [ [[I22293]], [[BB255]] ]
; CHECK-NEXT:    [[I21288]] = phi ptr [ [[I21291]], [[BB139]] ], [ [[I21286]], [[BB255]] ]
; CHECK-NEXT:    [[I6280]] = phi i32 [ [[I6283]], [[BB139]] ], [ [[I6278]], [[BB255]] ]
; CHECK-NEXT:    [[I32275]] = phi i64 [ [[I32277]], [[BB139]] ], [ [[I32273]], [[BB255]] ]
; CHECK-NEXT:    [[I41271:%.*]] = phi i32 [ [[I41]], [[BB139]] ], [ [[I41269]], [[BB255]] ]
; CHECK-NEXT:    [[I27262]] = phi ptr [ [[I27265]], [[BB139]] ], [ [[I27260]], [[BB255]] ]
; CHECK-NEXT:    [[I26255]] = phi ptr [ [[I26258]], [[BB139]] ], [ [[I26253]], [[BB255]] ]
; CHECK-NEXT:    [[I20248]] = phi ptr [ [[I20251]], [[BB139]] ], [ [[I20246]], [[BB255]] ]
; CHECK-NEXT:    [[I19241]] = phi ptr [ [[I19244]], [[BB139]] ], [ [[I19239]], [[BB255]] ]
; CHECK-NEXT:    [[I4233]] = phi ptr [ [[I4236]], [[BB139]] ], [ [[I4231]], [[BB255]] ]
; CHECK-NEXT:    [[I13227]] = phi i32 [ [[I13230]], [[BB139]] ], [ [[I13224]], [[BB255]] ]
; CHECK-NEXT:    [[I18219]] = phi i32 [ [[I18222]], [[BB139]] ], [ [[I18217]], [[BB255]] ]
; CHECK-NEXT:    [[I195]] = phi i32 [ [[I212]], [[BB139]] ], [ [[I189]], [[BB255]] ]
; CHECK-NEXT:    [[I5179]] = phi i32 [ [[I5182]], [[BB139]] ], [ [[I5177]], [[BB255]] ]
; CHECK-NEXT:    [[I30173]] = phi i32 [ [[I30176]], [[BB139]] ], [ [[I30171]], [[BB255]] ]
; CHECK-NEXT:    [[I31167]] = phi i32 [ [[I31170]], [[BB139]] ], [ [[I31165]], [[BB255]] ]
; CHECK-NEXT:    [[I40163:%.*]] = phi i64 [ [[I40]], [[BB139]] ], [ [[I40161]], [[BB255]] ]
; CHECK-NEXT:    [[I10132]] = phi i32 [ [[I10135]], [[BB139]] ], [ [[I10130]], [[BB255]] ]
; CHECK-NEXT:    [[I303:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I294]], [[BB255]] ]
; CHECK-NEXT:    [[I304:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I295]], [[BB255]] ]
; CHECK-NEXT:    [[I305:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I296]], [[BB255]] ]
; CHECK-NEXT:    [[I306:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I297]], [[BB255]] ]
; CHECK-NEXT:    [[I307:%.*]] = phi double [ 0.000000e+00, [[BB139]] ], [ [[I298]], [[BB255]] ]
; CHECK-NEXT:    [[I308:%.*]] = fcmp ogt double [[I303]], -1.000000e+00
; CHECK-NEXT:    [[I309:%.*]] = select i1 [[I308]], double [[I303]], double -1.000000e+00
; CHECK-NEXT:    [[I310:%.*]] = fcmp ogt double [[I304]], [[I309]]
; CHECK-NEXT:    [[I311:%.*]] = select i1 [[I310]], double [[I304]], double [[I309]]
; CHECK-NEXT:    [[I312:%.*]] = fcmp ogt double [[I305]], [[I311]]
; CHECK-NEXT:    [[I313:%.*]] = select i1 [[I312]], double [[I305]], double [[I311]]
; CHECK-NEXT:    [[I314:%.*]] = fcmp ogt double [[I306]], [[I313]]
; CHECK-NEXT:    [[I315:%.*]] = select i1 [[I314]], double [[I306]], double [[I313]]
; CHECK-NEXT:    [[I316:%.*]] = select i1 [[I310]], i64 2, i64 1
; CHECK-NEXT:    [[I317:%.*]] = fcmp ogt double [[I307]], [[I315]]
; CHECK-NEXT:    [[I318:%.*]] = select i1 [[I312]], i64 3, i64 [[I316]]
; CHECK-NEXT:    [[I319:%.*]] = select i1 [[I314]], i64 4, i64 [[I318]]
; CHECK-NEXT:    [[I320:%.*]] = select i1 [[I317]], i64 5, i64 [[I319]]
; CHECK-NEXT:    [[I321:%.*]] = getelementptr inbounds i64, ptr [[ARG3]], i64 [[I40163]]
; CHECK-NEXT:    store i64 [[I320]], ptr [[I321]], align 8, !tbaa [[TBAA120]]
; CHECK-NEXT:    [[I322:%.*]] = add nsw i32 [[I18219]], [[I41271]]
; CHECK-NEXT:    [[I323]] = sext i32 [[I322]] to i64
; CHECK-NEXT:    [[I324:%.*]] = icmp ugt i64 [[I323]], [[I32275]]
; CHECK-NEXT:    br i1 [[I324]], label [[BB325]], label [[BB39]]
; CHECK:       bb325:
; CHECK-NEXT:    [[I28325]] = phi ptr [ [[I28323]], [[BB302]] ], [ [[I28325]], [[BB35]] ], [ [[I28325]], [[BB29_FROM_BB325:%.*]] ]
; CHECK-NEXT:    [[I25318]] = phi ptr [ [[I25316]], [[BB302]] ], [ [[I25318]], [[BB35]] ], [ [[I25318]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I24311]] = phi ptr [ [[I24309]], [[BB302]] ], [ [[I24311]], [[BB35]] ], [ [[I24311]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I23304]] = phi ptr [ [[I23302]], [[BB302]] ], [ [[I23304]], [[BB35]] ], [ [[I23304]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I22297]] = phi ptr [ [[I22295]], [[BB302]] ], [ [[I22297]], [[BB35]] ], [ [[I22297]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I21290]] = phi ptr [ [[I21288]], [[BB302]] ], [ [[I21290]], [[BB35]] ], [ [[I21290]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I6282]] = phi i32 [ [[I6280]], [[BB302]] ], [ [[I6282]], [[BB35]] ], [ [[I6282]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I27264]] = phi ptr [ [[I27262]], [[BB302]] ], [ [[I27264]], [[BB35]] ], [ [[I27264]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I26257]] = phi ptr [ [[I26255]], [[BB302]] ], [ [[I26257]], [[BB35]] ], [ [[I26257]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I20250]] = phi ptr [ [[I20248]], [[BB302]] ], [ [[I20250]], [[BB35]] ], [ [[I20250]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I19243]] = phi ptr [ [[I19241]], [[BB302]] ], [ [[I19243]], [[BB35]] ], [ [[I19243]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I4235]] = phi ptr [ [[I4233]], [[BB302]] ], [ [[I4235]], [[BB35]] ], [ [[I4235]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I13229]] = phi i32 [ [[I13227]], [[BB302]] ], [ [[I13229]], [[BB35]] ], [ [[I13229]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I18221]] = phi i32 [ [[I18219]], [[BB302]] ], [ [[I18221]], [[BB35]] ], [ [[I18221]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I208]] = phi i32 [ [[I195]], [[BB302]] ], [ [[I208]], [[BB35]] ], [ [[I208]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I5181]] = phi i32 [ [[I5179]], [[BB302]] ], [ [[I5181]], [[BB35]] ], [ [[I5181]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I30175:%.*]] = phi i32 [ [[I30173]], [[BB302]] ], [ [[I328_BB29]], [[BB35]] ], [ [[I328_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I31169:%.*]] = phi i32 [ [[I31167]], [[BB302]] ], [ [[I326_BB29]], [[BB35]] ], [ [[I326_BB29]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    [[I10134]] = phi i32 [ [[I10132]], [[BB302]] ], [ [[I10134]], [[BB35]] ], [ [[I10134]], [[BB29_FROM_BB325]] ]
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I326:%.*]] = add nsw i32 [[I31169]], [[I13229]]
; CHECK-NEXT:    [[I327:%.*]] = add nsw i32 [[I30175]], [[I13229]]
; CHECK-NEXT:    [[I328:%.*]] = tail call i32 @llvm.smin.i32(i32 [[I327]], i32 [[I6282]])
; CHECK-NEXT:    [[I329:%.*]] = icmp slt i32 [[I326]], [[I5181]]
; CHECK-NEXT:    br i1 [[I329]], label [[BB29_FROM_BB325]], label [[BB330:%.*]]
; CHECK:       bb29.from.bb325:
; CHECK-NEXT:    [[I326_BB29]] = phi i32 [ [[I326]], [[BB325]] ]
; CHECK-NEXT:    [[I328_BB29]] = phi i32 [ [[I328]], [[BB325]] ]
; CHECK-NEXT:    [[I32]] = zext i32 [[I328_BB29]] to i64
; CHECK-NEXT:    tail call void @llvm.nvvm.barrier0() #[[ATTR9]]
; CHECK-NEXT:    [[I33:%.*]] = load i32, ptr [[I4235]], align 8, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[I34:%.*]] = icmp sgt i32 [[I33]], 0
; CHECK-NEXT:    br i1 [[I34]], label [[BB35]], label [[BB325]]
; CHECK:       bb330:
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;.
; CHECK: [[RNG17]] = !{i32 1, i32 0}
; CHECK: [[RNG18]] = !{i32 0, i32 -1}
; CHECK: [[TBAA19]] = !{[[META20:![0-9]+]], [[META21:![0-9]+]], i64 24}
; CHECK: [[META20]] = !{!"", [[META21]], i64 0, [[META24:![0-9]+]], i64 8, [[META24]], i64 16, [[META21]], i64 24, [[META25:![0-9]+]], i64 32, [[META21]], i64 40, [[META21]], i64 44, [[META21]], i64 48, [[META21]], i64 52, [[META21]], i64 56, [[META21]], i64 60}
; CHECK: [[META21]] = !{!"int", [[META22:![0-9]+]], i64 0}
; CHECK: [[META22]] = !{!"omnipotent char", [[META23:![0-9]+]], i64 0}
; CHECK: [[META23]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[META24]] = !{!"long", [[META22]], i64 0}
; CHECK: [[META25]] = !{!"any pointer", [[META22]], i64 0}
; CHECK: [[RNG26]] = !{i32 -2147483648, i32 2147483647}
; CHECK: [[TBAA27]] = !{[[META20]], [[META24]], i64 8}
; CHECK: [[TBAA28]] = !{[[META20]], [[META24]], i64 16}
; CHECK: [[TBAA29]] = !{[[META30:![0-9]+]], [[META25]], i64 0}
; CHECK: [[META30]] = !{!"", [[META25]], i64 0, [[META25]], i64 8, [[META25]], i64 16, [[META25]], i64 24, [[META25]], i64 32, [[META25]], i64 40, [[META21]], i64 48, [[META21]], i64 52, [[META21]], i64 56, [[META21]], i64 60, [[META24]], i64 64, [[META21]], i64 72, [[META21]], i64 76, [[META25]], i64 80, [[META21]], i64 88, [[META25]], i64 96, [[META21]], i64 104}
; CHECK: [[TBAA31]] = !{[[META30]], [[META25]], i64 8}
; CHECK: [[TBAA32]] = !{[[META30]], [[META25]], i64 24}
; CHECK: [[TBAA33]] = !{[[META30]], [[META25]], i64 32}
; CHECK: [[TBAA34]] = !{[[META30]], [[META25]], i64 40}
; CHECK: [[TBAA35]] = !{[[META30]], [[META25]], i64 16}
; CHECK: [[TBAA36]] = !{[[META20]], [[META21]], i64 40}
; CHECK: [[TBAA37]] = !{[[META20]], [[META21]], i64 44}
; CHECK: [[TBAA38]] = !{[[META30]], [[META21]], i64 76}
; CHECK: [[TBAA39]] = !{[[META40:![0-9]+]], [[META40]], i64 0}
; CHECK: [[META40]] = !{!"double", [[META22]], i64 0}
; CHECK: [[META41]] = distinct !{}
; CHECK: [[META42]] = distinct !{}
; CHECK: [[META43]] = distinct !{}
; CHECK: [[META44]] = distinct !{}
; CHECK: [[META45]] = distinct !{}
; CHECK: [[META46]] = distinct !{}
; CHECK: [[META47]] = distinct !{}
; CHECK: [[META48]] = distinct !{}
; CHECK: [[META49]] = distinct !{}
; CHECK: [[META50]] = distinct !{}
; CHECK: [[META51]] = distinct !{}
; CHECK: [[META52]] = distinct !{}
; CHECK: [[META53]] = distinct !{}
; CHECK: [[META54]] = distinct !{}
; CHECK: [[META55]] = distinct !{}
; CHECK: [[META56]] = distinct !{}
; CHECK: [[META57]] = distinct !{}
; CHECK: [[META58]] = distinct !{}
; CHECK: [[META59]] = distinct !{}
; CHECK: [[TBAA60]] = !{[[META21]], [[META21]], i64 0}
; CHECK: [[META61]] = distinct !{}
; CHECK: [[META62]] = distinct !{}
; CHECK: [[META63]] = distinct !{}
; CHECK: [[META64]] = distinct !{}
; CHECK: [[META65]] = distinct !{}
; CHECK: [[META66]] = distinct !{}
; CHECK: [[META67]] = distinct !{}
; CHECK: [[META68]] = distinct !{}
; CHECK: [[META69]] = distinct !{}
; CHECK: [[META70]] = distinct !{}
; CHECK: [[META71]] = distinct !{}
; CHECK: [[META72]] = distinct !{}
; CHECK: [[META73]] = distinct !{}
; CHECK: [[META74]] = distinct !{}
; CHECK: [[META75]] = distinct !{}
; CHECK: [[META76]] = distinct !{}
; CHECK: [[META77]] = distinct !{}
; CHECK: [[META78]] = distinct !{}
; CHECK: [[META79]] = distinct !{}
; CHECK: [[META80]] = distinct !{}
; CHECK: [[META81]] = distinct !{}
; CHECK: [[META82]] = distinct !{}
; CHECK: [[META83]] = distinct !{}
; CHECK: [[META84]] = distinct !{}
; CHECK: [[META85]] = distinct !{}
; CHECK: [[META86]] = distinct !{}
; CHECK: [[TBAA87]] = !{[[META88:![0-9]+]], [[META40]], i64 0}
; CHECK: [[META88]] = !{!"", [[META40]], i64 0, [[META40]], i64 8, [[META40]], i64 16, [[META40]], i64 24, [[META40]], i64 32, [[META40]], i64 40}
; CHECK: [[TBAA89]] = !{[[META88]], [[META40]], i64 8}
; CHECK: [[TBAA90]] = !{[[META88]], [[META40]], i64 16}
; CHECK: [[TBAA91]] = !{[[META88]], [[META40]], i64 24}
; CHECK: [[TBAA92]] = !{[[META88]], [[META40]], i64 32}
; CHECK: [[TBAA93]] = !{[[META88]], [[META40]], i64 40}
; CHECK: [[META94]] = distinct !{}
; CHECK: [[META95]] = distinct !{}
; CHECK: [[META96]] = distinct !{}
; CHECK: [[META97]] = distinct !{}
; CHECK: [[META98]] = distinct !{}
; CHECK: [[META99]] = distinct !{}
; CHECK: [[META100]] = distinct !{}
; CHECK: [[META101]] = distinct !{}
; CHECK: [[META102]] = distinct !{}
; CHECK: [[META103]] = distinct !{}
; CHECK: [[META104]] = distinct !{}
; CHECK: [[META105]] = distinct !{}
; CHECK: [[META106]] = distinct !{}
; CHECK: [[META107]] = distinct !{}
; CHECK: [[META108]] = distinct !{}
; CHECK: [[META109]] = distinct !{}
; CHECK: [[META110]] = distinct !{}
; CHECK: [[META111]] = distinct !{}
; CHECK: [[META112]] = distinct !{}
; CHECK: [[META113]] = distinct !{}
; CHECK: [[META114]] = distinct !{}
; CHECK: [[META115]] = distinct !{}
; CHECK: [[META116]] = distinct !{}
; CHECK: [[META117]] = distinct !{}
; CHECK: [[META118]] = distinct !{}
; CHECK: [[META119]] = distinct !{}
; CHECK: [[TBAA120]] = !{[[META121:![0-9]+]], [[META121]], i64 0}
; CHECK: [[META121]] = !{!"long long", [[META22]], i64 0}
;.
