; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 4
; RUN: opt < %s -S -passes="openmp-opt-postlink,ipsccp,simplifycfg" --split-kernel-remat-mode=cache | FileCheck %s --check-prefix=CHECK-CACHE
; RUN: opt < %s -S -passes="openmp-opt-postlink,ipsccp,simplifycfg" --split-kernel-remat-mode=recompute | FileCheck %s --check-prefix=CHECK-RECOMPUTE
; RUN: opt < %s -S -passes="openmp-opt-postlink,ipsccp,simplifycfg" --split-kernel-remat-mode=mincut | FileCheck %s --check-prefix=CHECK-MINCUT

target triple = "nvptx64"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32, i32, ptr }
%struct.KernelLaunchEnvironmentTy = type { i32, i32, ptr, i32 }

@test_kernel_environment = weak_odr protected local_unnamed_addr constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 512, i32 1, i32 1, i32 1, i32 0, i32 0, ptr null }, ptr null, ptr null }

declare void @__ompx_split()

declare i32 @__kmpc_target_init(ptr, ptr)
declare void @__kmpc_target_deinit()

define void @test(ptr %launch_env, ptr %tid_addr, ptr %ptr1, ptr %ptr2, ptr %dyn) "kernel" "omp_target_thread_limit"="32" "omp_target_num_teams"="1" {
  entry:
    %i = call i32 @__kmpc_target_init(ptr @test_kernel_environment, ptr %dyn)
    %tid = load i64, ptr %tid_addr
    %arrayidx1 = getelementptr inbounds double, ptr %ptr1, i64 %tid
    %arrayidx2 = getelementptr inbounds double, ptr %ptr2, i64 %tid
    %val1 = load double, ptr %arrayidx1
    %val2 = load double, ptr %arrayidx2
    %mul = fmul double %val1, %val2
    %cmp = icmp ult i64 0, %tid
    br i1 %cmp, label %if, label %end
  if:
    call void @__ompx_split()
    store double %mul, ptr %arrayidx1
    br label %end
  end:
    %mul1 = fmul double %mul, %mul
    store double %mul1, ptr %arrayidx1
    call void @__kmpc_target_deinit()
    ret void
}

!llvm.module.flags = !{!3, !4}

!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}


; CHECK: define void @test(ptr %launch_env, ptr %tid_addr, ptr %ptr1, ptr %ptr2, ptr %dyn)
; CHECK-NEXT: entry:
; CHECK-NEXT:   %i = call i32 @__kmpc_target_init(ptr @test_kernel_environment, ptr %dyn)
; CHECK-NEXT:   %tid = load i64, ptr %tid_addr
; CHECK-NEXT:   %arrayidx1 = getelementptr inbounds double, ptr %ptr1, i64 %tid
; CHECK-NEXT:   %arrayidx2 = getelementptr inbounds double, ptr %ptr2, i64 %tid
; CHECK-NEXT:   %val1 = load double, ptr %arrayidx1
; CHECK-NEXT:   %val2 = load double, ptr %arrayidx2
; CHECK-NEXT:   %mul = fmul double %val1, %val2
; CHECK-NEXT:   %cmp = icmp ult i64 0, %tid
; CHECK-NEXT:   br i1 %cmp, label %CacheStore, label %end
; CHECK: end:                                              ; preds = %entry
; CHECK-NEXT:   %mul1 = fmul double %mul, %mul
; CHECK-NEXT:   store double %mul1, ptr %arrayidx1
; CHECK-NEXT:   call void @__kmpc_target_deinit()
; CHECK-NEXT:   ret void
; CHECK-NEXT: }
; CHECK: define void @test_contd_0(ptr %launch_env, ptr %tid_addr, ptr %ptr1, ptr %ptr2, ptr %dyn)
; CHECK-NEXT: entry:
; CHECK-NEXT:   %0 = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:   %1 = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:   %2 = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:   %3 = mul i32 %1, %2
; CHECK-NEXT:   %gtid = add i32 %0, %3
; CHECK-NEXT:   %4 = getelementptr inbounds %struct.KernelLaunchEnvironmentTy.0, ptr %launch_env, i32 0, i32 3
; CHECK-NEXT:   %5 = load ptr, ptr %4
; CHECK-NEXT:   %contcount.in.ptr = getelementptr inbounds i32, ptr %5, i32 1
; CHECK-NEXT:   %contcount.in = load i32, ptr %contcount.in.ptr
; CHECK-NEXT:   %6 = icmp ult i32 %gtid, %contcount.in
; CHECK-NEXT:   br i1 %6, label %CacheRemat, label %ThreadExit
; CHECK: ThreadExit:                                       ; preds = %entry
; CHECK-NEXT:   call void asm sideeffect "exit;", ""()
; CHECK-NEXT:   unreachable
; CHECK-NEXT: }
; CHECK-CACHE-LABEL: define void @test(
; CHECK-CACHE-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-CACHE-NEXT:  ContDispatchBB:
; CHECK-CACHE-NEXT:    [[I:%.*]] = call i32 @__kmpc_target_init(ptr @test_kernel_environment, ptr [[DYN]])
; CHECK-CACHE-NEXT:    [[TID:%.*]] = load i64, ptr [[TID_ADDR]], align 8
; CHECK-CACHE-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[PTR1]], i64 [[TID]]
; CHECK-CACHE-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds double, ptr [[PTR2]], i64 [[TID]]
; CHECK-CACHE-NEXT:    [[VAL1:%.*]] = load double, ptr [[ARRAYIDX1]], align 8
; CHECK-CACHE-NEXT:    [[VAL2:%.*]] = load double, ptr [[ARRAYIDX2]], align 8
; CHECK-CACHE-NEXT:    [[MUL:%.*]] = fmul double [[VAL1]], [[VAL2]]
; CHECK-CACHE-NEXT:    [[CMP:%.*]] = icmp ult i64 0, [[TID]]
; CHECK-CACHE-NEXT:    br i1 [[CMP]], label [[CACHESTORE0:%.*]], label [[END:%.*]]
; CHECK-CACHE:       CacheStore0:
; CHECK-CACHE-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-CACHE-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-CACHE-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-CACHE-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-CACHE-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-CACHE-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-CACHE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-CACHE-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-CACHE-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-CACHE-NEXT:    [[TMP5:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-CACHE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-CACHE-NEXT:    store ptr [[ARRAYIDX1]], ptr [[TMP6]], align 8, !invariant.group [[META3:![0-9]+]]
; CHECK-CACHE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[TMP5]]
; CHECK-CACHE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds double, ptr [[TMP7]], i32 [[CACHEIDX]]
; CHECK-CACHE-NEXT:    store double [[MUL]], ptr [[TMP8]], align 8, !invariant.group [[META4:![0-9]+]]
; CHECK-CACHE-NEXT:    call void asm sideeffect "exit
; CHECK-CACHE-NEXT:    unreachable
; CHECK-CACHE:       end:
; CHECK-CACHE-NEXT:    [[MUL1:%.*]] = fmul double [[MUL]], [[MUL]]
; CHECK-CACHE-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1]], align 8
; CHECK-CACHE-NEXT:    call void @__kmpc_target_deinit()
; CHECK-CACHE-NEXT:    ret void
;
;
; CHECK-CACHE-LABEL: define void @test_contd_0(
; CHECK-CACHE-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0]] {
; CHECK-CACHE-NEXT:  ContDispatchBB:
; CHECK-CACHE-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-CACHE-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-CACHE-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-CACHE-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-CACHE-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-CACHE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-CACHE-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-CACHE-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 1
; CHECK-CACHE-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-CACHE-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-CACHE-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT0:%.*]], label [[THREADEXIT:%.*]]
; CHECK-CACHE:       CacheRemat0:
; CHECK-CACHE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-CACHE-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-CACHE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds ptr, ptr [[TMP7]], i32 1
; CHECK-CACHE-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-CACHE-NEXT:    [[CACHECELL1:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-CACHE-NEXT:    [[TMP9:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-CACHE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-CACHE-NEXT:    [[ARRAYIDX1_CACHE:%.*]] = load ptr, ptr [[TMP10]], align 8, !invariant.group [[META3]]
; CHECK-CACHE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[TMP9]]
; CHECK-CACHE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds double, ptr [[TMP11]], i32 [[GTID]]
; CHECK-CACHE-NEXT:    [[MUL_CACHE:%.*]] = load double, ptr [[TMP12]], align 8, !invariant.group [[META4]]
; CHECK-CACHE-NEXT:    store double [[MUL_CACHE]], ptr [[ARRAYIDX1_CACHE]], align 8
; CHECK-CACHE-NEXT:    [[MUL1:%.*]] = fmul double [[MUL_CACHE]], [[MUL_CACHE]]
; CHECK-CACHE-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1_CACHE]], align 8
; CHECK-CACHE-NEXT:    call void @__kmpc_target_deinit()
; CHECK-CACHE-NEXT:    ret void
; CHECK-CACHE:       ThreadExit:
; CHECK-CACHE-NEXT:    call void asm sideeffect "exit
; CHECK-CACHE-NEXT:    unreachable
;
;
; CHECK-RECOMPUTE-LABEL: define void @test(
; CHECK-RECOMPUTE-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-RECOMPUTE-NEXT:  ContDispatchBB:
; CHECK-RECOMPUTE-NEXT:    [[I:%.*]] = call i32 @__kmpc_target_init(ptr @test_kernel_environment, ptr [[DYN]])
; CHECK-RECOMPUTE-NEXT:    [[TID:%.*]] = load i64, ptr [[TID_ADDR]], align 8
; CHECK-RECOMPUTE-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[PTR1]], i64 [[TID]]
; CHECK-RECOMPUTE-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds double, ptr [[PTR2]], i64 [[TID]]
; CHECK-RECOMPUTE-NEXT:    [[VAL1:%.*]] = load double, ptr [[ARRAYIDX1]], align 8
; CHECK-RECOMPUTE-NEXT:    [[VAL2:%.*]] = load double, ptr [[ARRAYIDX2]], align 8
; CHECK-RECOMPUTE-NEXT:    [[MUL:%.*]] = fmul double [[VAL1]], [[VAL2]]
; CHECK-RECOMPUTE-NEXT:    [[CMP:%.*]] = icmp ult i64 0, [[TID]]
; CHECK-RECOMPUTE-NEXT:    br i1 [[CMP]], label [[CACHESTORE0:%.*]], label [[END:%.*]]
; CHECK-RECOMPUTE:       CacheStore0:
; CHECK-RECOMPUTE-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-RECOMPUTE-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-RECOMPUTE-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-RECOMPUTE-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-RECOMPUTE-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-RECOMPUTE-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-RECOMPUTE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-RECOMPUTE-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-RECOMPUTE-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-RECOMPUTE-NEXT:    [[TMP5:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-RECOMPUTE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds double, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-RECOMPUTE-NEXT:    store double [[VAL2]], ptr [[TMP6]], align 8, !invariant.group [[META3:![0-9]+]]
; CHECK-RECOMPUTE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds double, ptr [[CACHE_OUT_PTR]], i32 [[TMP5]]
; CHECK-RECOMPUTE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds double, ptr [[TMP7]], i32 [[CACHEIDX]]
; CHECK-RECOMPUTE-NEXT:    store double [[VAL1]], ptr [[TMP8]], align 8, !invariant.group [[META4:![0-9]+]]
; CHECK-RECOMPUTE-NEXT:    [[TMP9:%.*]] = getelementptr inbounds double, ptr [[CACHE_OUT_PTR]], i32 [[TMP5]]
; CHECK-RECOMPUTE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds double, ptr [[TMP9]], i32 [[TMP5]]
; CHECK-RECOMPUTE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i64, ptr [[TMP10]], i32 [[CACHEIDX]]
; CHECK-RECOMPUTE-NEXT:    store i64 [[TID]], ptr [[TMP11]], align 8, !invariant.group [[META5:![0-9]+]]
; CHECK-RECOMPUTE-NEXT:    call void asm sideeffect "exit
; CHECK-RECOMPUTE-NEXT:    unreachable
; CHECK-RECOMPUTE:       end:
; CHECK-RECOMPUTE-NEXT:    [[MUL1:%.*]] = fmul double [[MUL]], [[MUL]]
; CHECK-RECOMPUTE-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1]], align 8
; CHECK-RECOMPUTE-NEXT:    call void @__kmpc_target_deinit()
; CHECK-RECOMPUTE-NEXT:    ret void
;
;
; CHECK-RECOMPUTE-LABEL: define void @test_contd_0(
; CHECK-RECOMPUTE-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0]] {
; CHECK-RECOMPUTE-NEXT:  ContDispatchBB:
; CHECK-RECOMPUTE-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-RECOMPUTE-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-RECOMPUTE-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-RECOMPUTE-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-RECOMPUTE-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-RECOMPUTE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-RECOMPUTE-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-RECOMPUTE-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 1
; CHECK-RECOMPUTE-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-RECOMPUTE-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-RECOMPUTE-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT0:%.*]], label [[THREADEXIT:%.*]]
; CHECK-RECOMPUTE:       CacheRemat0:
; CHECK-RECOMPUTE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-RECOMPUTE-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-RECOMPUTE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds ptr, ptr [[TMP7]], i32 1
; CHECK-RECOMPUTE-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-RECOMPUTE-NEXT:    [[CACHECELL1:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-RECOMPUTE-NEXT:    [[TMP9:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-RECOMPUTE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds double, ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-RECOMPUTE-NEXT:    [[VAL2_CACHE:%.*]] = load double, ptr [[TMP10]], align 8, !invariant.group [[META3]]
; CHECK-RECOMPUTE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds double, ptr [[CACHE_IN_PTR]], i32 [[TMP9]]
; CHECK-RECOMPUTE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds double, ptr [[TMP11]], i32 [[GTID]]
; CHECK-RECOMPUTE-NEXT:    [[VAL1_CACHE:%.*]] = load double, ptr [[TMP12]], align 8, !invariant.group [[META4]]
; CHECK-RECOMPUTE-NEXT:    [[TMP13:%.*]] = getelementptr inbounds double, ptr [[CACHE_IN_PTR]], i32 [[TMP9]]
; CHECK-RECOMPUTE-NEXT:    [[TMP14:%.*]] = getelementptr inbounds double, ptr [[TMP13]], i32 [[TMP9]]
; CHECK-RECOMPUTE-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i64, ptr [[TMP14]], i32 [[GTID]]
; CHECK-RECOMPUTE-NEXT:    [[TID_CACHE:%.*]] = load i64, ptr [[TMP15]], align 8, !invariant.group [[META5]]
; CHECK-RECOMPUTE-NEXT:    [[ARRAYIDX1_RECOMPUTE:%.*]] = getelementptr inbounds double, ptr [[PTR1]], i64 [[TID_CACHE]]
; CHECK-RECOMPUTE-NEXT:    [[MUL_RECOMPUTE:%.*]] = fmul double [[VAL1_CACHE]], [[VAL2_CACHE]]
; CHECK-RECOMPUTE-NEXT:    store double [[MUL_RECOMPUTE]], ptr [[ARRAYIDX1_RECOMPUTE]], align 8
; CHECK-RECOMPUTE-NEXT:    [[MUL1:%.*]] = fmul double [[MUL_RECOMPUTE]], [[MUL_RECOMPUTE]]
; CHECK-RECOMPUTE-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1_RECOMPUTE]], align 8
; CHECK-RECOMPUTE-NEXT:    call void @__kmpc_target_deinit()
; CHECK-RECOMPUTE-NEXT:    ret void
; CHECK-RECOMPUTE:       ThreadExit:
; CHECK-RECOMPUTE-NEXT:    call void asm sideeffect "exit
; CHECK-RECOMPUTE-NEXT:    unreachable
;
;
; CHECK-MINCUT-LABEL: define void @test(
; CHECK-MINCUT-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-MINCUT-NEXT:  ContDispatchBB:
; CHECK-MINCUT-NEXT:    [[I:%.*]] = call i32 @__kmpc_target_init(ptr @test_kernel_environment, ptr [[DYN]])
; CHECK-MINCUT-NEXT:    [[TID:%.*]] = load i64, ptr [[TID_ADDR]], align 8
; CHECK-MINCUT-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[PTR1]], i64 [[TID]]
; CHECK-MINCUT-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds double, ptr [[PTR2]], i64 [[TID]]
; CHECK-MINCUT-NEXT:    [[VAL1:%.*]] = load double, ptr [[ARRAYIDX1]], align 8
; CHECK-MINCUT-NEXT:    [[VAL2:%.*]] = load double, ptr [[ARRAYIDX2]], align 8
; CHECK-MINCUT-NEXT:    [[MUL:%.*]] = fmul double [[VAL1]], [[VAL2]]
; CHECK-MINCUT-NEXT:    [[CMP:%.*]] = icmp ult i64 0, [[TID]]
; CHECK-MINCUT-NEXT:    br i1 [[CMP]], label [[CACHESTORE0:%.*]], label [[END:%.*]]
; CHECK-MINCUT:       CacheStore0:
; CHECK-MINCUT-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-MINCUT-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-MINCUT-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-MINCUT-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-MINCUT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-MINCUT-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-MINCUT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-MINCUT-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-MINCUT-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-MINCUT-NEXT:    [[TMP5:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-MINCUT-NEXT:    [[TMP6:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-MINCUT-NEXT:    store ptr [[ARRAYIDX1]], ptr [[TMP6]], align 8, !invariant.group [[META3:![0-9]+]]
; CHECK-MINCUT-NEXT:    [[TMP7:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[TMP5]]
; CHECK-MINCUT-NEXT:    [[TMP8:%.*]] = getelementptr inbounds double, ptr [[TMP7]], i32 [[CACHEIDX]]
; CHECK-MINCUT-NEXT:    store double [[MUL]], ptr [[TMP8]], align 8, !invariant.group [[META4:![0-9]+]]
; CHECK-MINCUT-NEXT:    call void asm sideeffect "exit
; CHECK-MINCUT-NEXT:    unreachable
; CHECK-MINCUT:       end:
; CHECK-MINCUT-NEXT:    [[MUL1:%.*]] = fmul double [[MUL]], [[MUL]]
; CHECK-MINCUT-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1]], align 8
; CHECK-MINCUT-NEXT:    call void @__kmpc_target_deinit()
; CHECK-MINCUT-NEXT:    ret void
;
;
; CHECK-MINCUT-LABEL: define void @test_contd_0(
; CHECK-MINCUT-SAME: ptr [[LAUNCH_ENV:%.*]], ptr [[TID_ADDR:%.*]], ptr [[PTR1:%.*]], ptr [[PTR2:%.*]], ptr [[DYN:%.*]]) #[[ATTR0]] {
; CHECK-MINCUT-NEXT:  ContDispatchBB:
; CHECK-MINCUT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-MINCUT-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-MINCUT-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-MINCUT-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-MINCUT-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-MINCUT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[LAUNCH_ENV]], i32 0, i32 3
; CHECK-MINCUT-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-MINCUT-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 1
; CHECK-MINCUT-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-MINCUT-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-MINCUT-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT0:%.*]], label [[THREADEXIT:%.*]]
; CHECK-MINCUT:       CacheRemat0:
; CHECK-MINCUT-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[LAUNCH_ENV]], i32 0, i32 4
; CHECK-MINCUT-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-MINCUT-NEXT:    [[TMP8:%.*]] = getelementptr inbounds ptr, ptr [[TMP7]], i32 1
; CHECK-MINCUT-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-MINCUT-NEXT:    [[CACHECELL1:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-MINCUT-NEXT:    [[TMP9:%.*]] = load i32, ptr @test_cache_offset, align 4
; CHECK-MINCUT-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-MINCUT-NEXT:    [[ARRAYIDX1_CACHE:%.*]] = load ptr, ptr [[TMP10]], align 8, !invariant.group [[META3]]
; CHECK-MINCUT-NEXT:    [[TMP11:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[TMP9]]
; CHECK-MINCUT-NEXT:    [[TMP12:%.*]] = getelementptr inbounds double, ptr [[TMP11]], i32 [[GTID]]
; CHECK-MINCUT-NEXT:    [[MUL_CACHE:%.*]] = load double, ptr [[TMP12]], align 8, !invariant.group [[META4]]
; CHECK-MINCUT-NEXT:    store double [[MUL_CACHE]], ptr [[ARRAYIDX1_CACHE]], align 8
; CHECK-MINCUT-NEXT:    [[MUL1:%.*]] = fmul double [[MUL_CACHE]], [[MUL_CACHE]]
; CHECK-MINCUT-NEXT:    store double [[MUL1]], ptr [[ARRAYIDX1_CACHE]], align 8
; CHECK-MINCUT-NEXT:    call void @__kmpc_target_deinit()
; CHECK-MINCUT-NEXT:    ret void
; CHECK-MINCUT:       ThreadExit:
; CHECK-MINCUT-NEXT:    call void asm sideeffect "exit
; CHECK-MINCUT-NEXT:    unreachable
;
;.
; CHECK-CACHE: [[META3]] = distinct !{}
; CHECK-CACHE: [[META4]] = distinct !{}
;.
; CHECK-RECOMPUTE: [[META3]] = distinct !{}
; CHECK-RECOMPUTE: [[META4]] = distinct !{}
; CHECK-RECOMPUTE: [[META5]] = distinct !{}
;.
; CHECK-MINCUT: [[META3]] = distinct !{}
; CHECK-MINCUT: [[META4]] = distinct !{}
;.
