; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 4
; RUN: opt < %s -S -passes="openmp-opt-postlink,ipsccp,simplifycfg" | FileCheck %s

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8, i32, i32, i32, i32, i32, i32, i32, ptr }

@square_kernel_environment = weak_odr protected local_unnamed_addr constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2, i32 1, i32 512, i32 1, i32 1, i32 0, i32 0, i32 1, ptr null }, ptr null, ptr null }

declare noundef i32 @llvm.nvvm.read.ptx.sreg.tid.x() #0

declare noundef i32 @llvm.nvvm.read.ptx.sreg.ntid.x() #0

declare noundef i32 @llvm.nvvm.read.ptx.sreg.ctaid.x() #0

declare noundef i32 @llvm.nvvm.read.ptx.sreg.nctaid.x() #0

declare void @__ompx_split() local_unnamed_addr #1

define void @square(ptr %env, ptr %x) "kernel" {
  %tid = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  %x_i = getelementptr double, ptr %x, i32 %tid
  %val = load double, ptr %x_i
  call void @__ompx_split()
  %sq = fmul double %val, %val
  store double %sq, ptr %x_i
  ret void
}

!llvm.module.flags = !{!3, !4}

!3 = !{i32 7, !"openmp", i32 51}
!4 = !{i32 7, !"openmp-device", i32 51}

; CHECK-LABEL: define void @square(
; CHECK-SAME: ptr [[ENV:%.*]], ptr [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[TID:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[X_I:%.*]] = getelementptr double, ptr [[X]], i32 [[TID]]
; CHECK-NEXT:    [[VAL:%.*]] = load double, ptr [[X_I]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ENV]], i32 0, i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[CONTCOUNT_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 0
; CHECK-NEXT:    [[CACHEIDX:%.*]] = atomicrmw add ptr [[CONTCOUNT_PTR]], i32 1 monotonic, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ENV]], i32 0, i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i32 0
; CHECK-NEXT:    [[CACHE_OUT_PTR:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CACHECELL:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr @square_cache_offset, align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store ptr [[X_I]], ptr [[TMP6]], align 8, !invariant.group [[META3:![0-9]+]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_OUT_PTR]], i32 [[TMP5]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds double, ptr [[TMP7]], i32 [[CACHEIDX]]
; CHECK-NEXT:    store double [[VAL]], ptr [[TMP8]], align 8, !invariant.group [[META4:![0-9]+]]
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;
; CHECK-LABEL: define void @square_contd_0(
; CHECK-SAME: ptr [[ENV:%.*]], ptr [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  ContDispatchBB:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ntid.x()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.nvvm.read.ptx.sreg.ctaid.x()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[GTID:%.*]] = add i32 [[TMP0]], [[TMP3]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0:%.*]], ptr [[ENV]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[CONTCOUNT_IN_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i32 1
; CHECK-NEXT:    [[CONTCOUNT_IN:%.*]] = load i32, ptr [[CONTCOUNT_IN_PTR]], align 4
; CHECK-NEXT:    [[MASKTHREAD:%.*]] = icmp ult i32 [[GTID]], [[CONTCOUNT_IN]]
; CHECK-NEXT:    br i1 [[MASKTHREAD]], label [[CACHEREMAT0:%.*]], label [[THREADEXIT:%.*]]
; CHECK:       CacheRemat0:
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [[STRUCT_KERNELLAUNCHENVIRONMENTTY_0]], ptr [[ENV]], i32 0, i32 4
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds ptr, ptr [[TMP7]], i32 1
; CHECK-NEXT:    [[CACHE_IN_PTR:%.*]] = load ptr, ptr [[TMP8]], align 8
; CHECK-NEXT:    [[CACHECELL1:%.*]] = getelementptr inbounds [[CACHE_CELL0:%.*]], ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr @square_cache_offset, align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[GTID]]
; CHECK-NEXT:    [[X_I_CACHE:%.*]] = load ptr, ptr [[TMP10]], align 8, !invariant.group [[META3]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds ptr, ptr [[CACHE_IN_PTR]], i32 [[TMP9]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds double, ptr [[TMP11]], i32 [[GTID]]
; CHECK-NEXT:    [[VAL_CACHE:%.*]] = load double, ptr [[TMP12]], align 8, !invariant.group [[META4]]
; CHECK-NEXT:    [[SQ:%.*]] = fmul double [[VAL_CACHE]], [[VAL_CACHE]]
; CHECK-NEXT:    store double [[SQ]], ptr [[X_I_CACHE]], align 8
; CHECK-NEXT:    ret void
; CHECK:       ThreadExit:
; CHECK-NEXT:    call void asm sideeffect "exit
; CHECK-NEXT:    unreachable
;
;.
; CHECK: [[META3]] = distinct !{}
; CHECK: [[META4]] = distinct !{}
;.
