; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu < %s | FileCheck %s

define i8 @urem_i8(i8 %x) {
; CHECK-LABEL: urem_i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #9363 // =0x2493
; CHECK-NEXT:    and w9, w0, #0xff
; CHECK-NEXT:    mul w8, w9, w8
; CHECK-NEXT:    and w8, w8, #0xffff
; CHECK-NEXT:    lsl w9, w8, #3
; CHECK-NEXT:    sub w8, w9, w8
; CHECK-NEXT:    lsr w0, w8, #16
; CHECK-NEXT:    ret
  %r = urem i8 %x, 7
  ret i8 %r
}

define i8 @urem_i8_no_fixup(i8 %x) {
; CHECK-LABEL: urem_i8_no_fixup:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #13108 // =0x3334
; CHECK-NEXT:    and w9, w0, #0xff
; CHECK-NEXT:    mul w8, w9, w8
; CHECK-NEXT:    and w8, w8, #0xfffc
; CHECK-NEXT:    add w8, w8, w8, lsl #2
; CHECK-NEXT:    lsr w0, w8, #16
; CHECK-NEXT:    ret
  %r = urem i8 %x, 5
  ret i8 %r
}
define i16 @srem_i16(i16 %x) {
; CHECK-LABEL: srem_i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    sxth w8, w0
; CHECK-NEXT:    mov w9, #21385 // =0x5389
; CHECK-NEXT:    mul w8, w8, w9
; CHECK-NEXT:    lsr w8, w8, #16
; CHECK-NEXT:    sub w8, w8, w0
; CHECK-NEXT:    sbfx w9, w8, #6, #10
; CHECK-NEXT:    and w8, w8, #0x8000
; CHECK-NEXT:    add w8, w9, w8, lsr #15
; CHECK-NEXT:    mov w9, #-95 // =0xffffffa1
; CHECK-NEXT:    msub w0, w8, w9, w0
; CHECK-NEXT:    ret
  %r = srem i16 %x, -95
  ret i16 %r
}

define <8 x i8> @urem_v8i8(<8 x i8> %x) {
; CHECK-LABEL: urem_v8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #6554 // =0x199a
; CHECK-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-NEXT:    dup v1.8h, w8
; CHECK-NEXT:    mul v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    movi v1.8h, #10
; CHECK-NEXT:    umull2 v2.4s, v0.8h, v1.8h
; CHECK-NEXT:    umull v0.4s, v0.4h, v1.4h
; CHECK-NEXT:    uzp2 v0.8h, v0.8h, v2.8h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
  %r = urem <8 x i8> %x, <i8 10, i8 10, i8 10, i8 10, i8 10, i8 10, i8 10, i8 10>
  ret <8 x i8> %r
}

define <8 x i8> @urem_v8i8_7(<8 x i8> %x) {
; CHECK-LABEL: urem_v8i8_7:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #9363 // =0x2493
; CHECK-NEXT:    ushll v0.8h, v0.8b, #0
; CHECK-NEXT:    dup v1.8h, w8
; CHECK-NEXT:    mul v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    movi v1.8h, #7
; CHECK-NEXT:    umull2 v2.4s, v0.8h, v1.8h
; CHECK-NEXT:    umull v0.4s, v0.4h, v1.4h
; CHECK-NEXT:    uzp2 v0.8h, v0.8h, v2.8h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    ret
  %r = urem <8 x i8> %x, splat (i8 7)
  ret <8 x i8> %r
}

define <4 x i16> @srem_v4i16(<4 x i16> %x) {
; CHECK-LABEL: srem_v4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    movi v1.8b, #153
; CHECK-NEXT:    mvni v2.4h, #9
; CHECK-NEXT:    smull v1.4s, v0.4h, v1.4h
; CHECK-NEXT:    sshr v1.4s, v1.4s, #18
; CHECK-NEXT:    xtn v1.4h, v1.4s
; CHECK-NEXT:    usra v1.4h, v1.4h, #15
; CHECK-NEXT:    mls v0.4h, v1.4h, v2.4h
; CHECK-NEXT:    ret
  %r = srem <4 x i16> %x, <i16 -10, i16 -10, i16 -10, i16 -10>
  ret <4 x i16> %r
}
