; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mattr=+sve < %s | FileCheck %s --check-prefix=SVE
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mattr=+sve2 < %s | FileCheck %s --check-prefix=SVE2

define <vscale x 8 x i8> @urem_nxv8i8(<vscale x 8 x i8> %x) {
; CHECK-LABEL: urem_nxv8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #9363 // =0x2493
; CHECK-NEXT:    and z0.h, z0.h, #0xff
; CHECK-NEXT:    mov z1.h, w8
; CHECK-NEXT:    mul z0.h, z0.h, z1.h
; CHECK-NEXT:    mov z1.h, #7 // =0x7
; CHECK-NEXT:    umulh z0.h, z0.h, z1.h
; CHECK-NEXT:    ret
; SVE-LABEL: urem_nxv8i8:
; SVE:       // %bb.0:
; SVE-NEXT:    mov w8, #9376 // =0x24a0
; SVE-NEXT:    and z0.h, z0.h, #0xff
; SVE-NEXT:    ptrue p0.h
; SVE-NEXT:    mov z1.h, w8
; SVE-NEXT:    mul z0.h, p0/m, z0.h, z1.h
; SVE-NEXT:    mov z1.h, #7 // =0x7
; SVE-NEXT:    umulh z0.h, p0/m, z0.h, z1.h
; SVE-NEXT:    ret
;
; SVE2-LABEL: urem_nxv8i8:
; SVE2:       // %bb.0:
; SVE2-NEXT:    mov w8, #9376 // =0x24a0
; SVE2-NEXT:    and z0.h, z0.h, #0xff
; SVE2-NEXT:    mov z1.h, w8
; SVE2-NEXT:    mul z0.h, z0.h, z1.h
; SVE2-NEXT:    mov z1.h, #7 // =0x7
; SVE2-NEXT:    umulh z0.h, z0.h, z1.h
; SVE2-NEXT:    ret
  %r = urem <vscale x 8 x i8> %x, splat (i8 7)
  ret <vscale x 8 x i8> %r
}

define <vscale x 8 x i8> @srem_nxv8i8(<vscale x 8 x i8> %x) {
; CHECK-LABEL: srem_nxv8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h
; CHECK-NEXT:    mov w8, #9363 // =0x2493
; CHECK-NEXT:    mov z2.h, #7 // =0x7
; CHECK-NEXT:    mov z1.h, w8
; CHECK-NEXT:    sxtb z0.h, p0/m, z0.h
; CHECK-NEXT:    mul z1.h, z0.h, z1.h
; CHECK-NEXT:    lsr z0.h, z0.h, #7
; CHECK-NEXT:    and z0.h, z0.h, #0x6
; CHECK-NEXT:    umulh z1.h, z1.h, z2.h
; CHECK-NEXT:    sub z0.h, z1.h, z0.h
; CHECK-NEXT:    ret
; SVE-LABEL: srem_nxv8i8:
; SVE:       // %bb.0:
; SVE-NEXT:    ptrue p0.h
; SVE-NEXT:    mov w8, #9408 // =0x24c0
; SVE-NEXT:    mov z2.h, #7 // =0x7
; SVE-NEXT:    mov z1.h, w8
; SVE-NEXT:    sxtb z0.h, p0/m, z0.h
; SVE-NEXT:    mul z1.h, p0/m, z1.h, z0.h
; SVE-NEXT:    lsr z0.h, z0.h, #7
; SVE-NEXT:    and z0.h, z0.h, #0x6
; SVE-NEXT:    umulh z1.h, p0/m, z1.h, z2.h
; SVE-NEXT:    sub z0.h, z1.h, z0.h
; SVE-NEXT:    ret
;
; SVE2-LABEL: srem_nxv8i8:
; SVE2:       // %bb.0:
; SVE2-NEXT:    ptrue p0.h
; SVE2-NEXT:    mov w8, #9408 // =0x24c0
; SVE2-NEXT:    mov z2.h, #7 // =0x7
; SVE2-NEXT:    mov z1.h, w8
; SVE2-NEXT:    sxtb z0.h, p0/m, z0.h
; SVE2-NEXT:    mul z1.h, z0.h, z1.h
; SVE2-NEXT:    lsr z0.h, z0.h, #7
; SVE2-NEXT:    and z0.h, z0.h, #0x6
; SVE2-NEXT:    umulh z1.h, z1.h, z2.h
; SVE2-NEXT:    sub z0.h, z1.h, z0.h
; SVE2-NEXT:    ret
  %r = srem <vscale x 8 x i8> %x, splat (i8 -7)
  ret <vscale x 8 x i8> %r
}

define <vscale x 4 x i16> @urem_nxv4i16(<vscale x 4 x i16> %x) {
; CHECK-LABEL: urem_nxv4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #55879 // =0xda47
; CHECK-NEXT:    and z0.s, z0.s, #0xffff
; CHECK-NEXT:    movk w8, #689, lsl #16
; CHECK-NEXT:    mov z1.s, w8
; CHECK-NEXT:    mul z0.s, z0.s, z1.s
; CHECK-NEXT:    mov z1.s, #95 // =0x5f
; CHECK-NEXT:    umulh z0.s, z0.s, z1.s
; CHECK-NEXT:    ret
; SVE-LABEL: urem_nxv4i16:
; SVE:       // %bb.0:
; SVE-NEXT:    mov w8, #56320 // =0xdc00
; SVE-NEXT:    and z0.s, z0.s, #0xffff
; SVE-NEXT:    ptrue p0.s
; SVE-NEXT:    movk w8, #689, lsl #16
; SVE-NEXT:    mov z1.s, w8
; SVE-NEXT:    mul z0.s, p0/m, z0.s, z1.s
; SVE-NEXT:    mov z1.s, #95 // =0x5f
; SVE-NEXT:    umulh z0.s, p0/m, z0.s, z1.s
; SVE-NEXT:    ret
;
; SVE2-LABEL: urem_nxv4i16:
; SVE2:       // %bb.0:
; SVE2-NEXT:    mov w8, #56320 // =0xdc00
; SVE2-NEXT:    and z0.s, z0.s, #0xffff
; SVE2-NEXT:    movk w8, #689, lsl #16
; SVE2-NEXT:    mov z1.s, w8
; SVE2-NEXT:    mul z0.s, z0.s, z1.s
; SVE2-NEXT:    mov z1.s, #95 // =0x5f
; SVE2-NEXT:    umulh z0.s, z0.s, z1.s
; SVE2-NEXT:    ret
  %r = urem <vscale x 4 x i16> %x, splat (i16 95)
  ret <vscale x 4 x i16> %r
}

define <vscale x 4 x i16> @srem_nxv4i16(<vscale x 4 x i16> %x) {
; CHECK-LABEL: srem_nxv4i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    mov w8, #55879 // =0xda47
; CHECK-NEXT:    mov z2.s, #95 // =0x5f
; CHECK-NEXT:    movk w8, #689, lsl #16
; CHECK-NEXT:    mov z3.s, #94 // =0x5e
; CHECK-NEXT:    sxth z0.s, p0/m, z0.s
; CHECK-NEXT:    mov z1.s, w8
; CHECK-NEXT:    mul z1.s, z0.s, z1.s
; CHECK-NEXT:    lsr z0.s, z0.s, #15
; CHECK-NEXT:    and z0.d, z0.d, z3.d
; CHECK-NEXT:    umulh z1.s, z1.s, z2.s
; CHECK-NEXT:    sub z0.s, z1.s, z0.s
; CHECK-NEXT:    ret
; SVE-LABEL: srem_nxv4i16:
; SVE:       // %bb.0:
; SVE-NEXT:    ptrue p0.s
; SVE-NEXT:    mov w8, #56320 // =0xdc00
; SVE-NEXT:    mov z2.s, #95 // =0x5f
; SVE-NEXT:    movk w8, #689, lsl #16
; SVE-NEXT:    mov z3.s, #94 // =0x5e
; SVE-NEXT:    sxth z0.s, p0/m, z0.s
; SVE-NEXT:    mov z1.s, w8
; SVE-NEXT:    mul z1.s, p0/m, z1.s, z0.s
; SVE-NEXT:    lsr z0.s, z0.s, #15
; SVE-NEXT:    and z0.d, z0.d, z3.d
; SVE-NEXT:    umulh z1.s, p0/m, z1.s, z2.s
; SVE-NEXT:    sub z0.s, z1.s, z0.s
; SVE-NEXT:    ret
;
; SVE2-LABEL: srem_nxv4i16:
; SVE2:       // %bb.0:
; SVE2-NEXT:    ptrue p0.s
; SVE2-NEXT:    mov w8, #56320 // =0xdc00
; SVE2-NEXT:    mov z2.s, #95 // =0x5f
; SVE2-NEXT:    movk w8, #689, lsl #16
; SVE2-NEXT:    mov z3.s, #94 // =0x5e
; SVE2-NEXT:    sxth z0.s, p0/m, z0.s
; SVE2-NEXT:    mov z1.s, w8
; SVE2-NEXT:    mul z1.s, z0.s, z1.s
; SVE2-NEXT:    lsr z0.s, z0.s, #15
; SVE2-NEXT:    and z0.d, z0.d, z3.d
; SVE2-NEXT:    umulh z1.s, z1.s, z2.s
; SVE2-NEXT:    sub z0.s, z1.s, z0.s
; SVE2-NEXT:    ret
  %r = srem <vscale x 4 x i16> %x, splat (i16 -95)
  ret <vscale x 4 x i16> %r
}

define <vscale x 2 x i32> @urem_nxv2i32(<vscale x 2 x i32> %x) {
; CHECK-LABEL: urem_nxv2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x8, #7589 // =0x1da5
; CHECK-NEXT:    and z0.d, z0.d, #0xffffffff
; CHECK-NEXT:    movk x8, #4139, lsl #16
; CHECK-NEXT:    movk x8, #55878, lsl #32
; CHECK-NEXT:    movk x8, #689, lsl #48
; CHECK-NEXT:    mov z1.d, x8
; CHECK-NEXT:    mul z0.d, z0.d, z1.d
; CHECK-NEXT:    mov z1.d, #95 // =0x5f
; CHECK-NEXT:    umulh z0.d, z0.d, z1.d
; CHECK-NEXT:    ret
; SVE-LABEL: urem_nxv2i32:
; SVE:       // %bb.0:
; SVE-NEXT:    mov x8, #301989888 // =0x12000000
; SVE-NEXT:    and z0.d, z0.d, #0xffffffff
; SVE-NEXT:    ptrue p0.d
; SVE-NEXT:    movk x8, #55878, lsl #32
; SVE-NEXT:    movk x8, #689, lsl #48
; SVE-NEXT:    mov z1.d, x8
; SVE-NEXT:    mul z0.d, p0/m, z0.d, z1.d
; SVE-NEXT:    mov z1.d, #95 // =0x5f
; SVE-NEXT:    umulh z0.d, p0/m, z0.d, z1.d
; SVE-NEXT:    ret
;
; SVE2-LABEL: urem_nxv2i32:
; SVE2:       // %bb.0:
; SVE2-NEXT:    mov x8, #301989888 // =0x12000000
; SVE2-NEXT:    and z0.d, z0.d, #0xffffffff
; SVE2-NEXT:    movk x8, #55878, lsl #32
; SVE2-NEXT:    movk x8, #689, lsl #48
; SVE2-NEXT:    mov z1.d, x8
; SVE2-NEXT:    mul z0.d, z0.d, z1.d
; SVE2-NEXT:    mov z1.d, #95 // =0x5f
; SVE2-NEXT:    umulh z0.d, z0.d, z1.d
; SVE2-NEXT:    ret
  %r = urem <vscale x 2 x i32> %x, splat (i32 95)
  ret <vscale x 2 x i32> %r
}

define <vscale x 2 x i32> @srem_nxv2i32(<vscale x 2 x i32> %x) {
; CHECK-LABEL: srem_nxv2i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x8, #7589 // =0x1da5
; CHECK-NEXT:    ptrue p0.d
; CHECK-NEXT:    mov z2.d, #95 // =0x5f
; CHECK-NEXT:    movk x8, #4139, lsl #16
; CHECK-NEXT:    mov z3.d, #94 // =0x5e
; CHECK-NEXT:    movk x8, #55878, lsl #32
; CHECK-NEXT:    sxtw z0.d, p0/m, z0.d
; CHECK-NEXT:    movk x8, #689, lsl #48
; CHECK-NEXT:    mov z1.d, x8
; CHECK-NEXT:    mul z1.d, z0.d, z1.d
; CHECK-NEXT:    lsr z0.d, z0.d, #31
; CHECK-NEXT:    and z0.d, z0.d, z3.d
; CHECK-NEXT:    umulh z1.d, z1.d, z2.d
; CHECK-NEXT:    sub z0.d, z1.d, z0.d
; CHECK-NEXT:    ret
; SVE-LABEL: srem_nxv2i32:
; SVE:       // %bb.0:
; SVE-NEXT:    mov x8, #335544320 // =0x14000000
; SVE-NEXT:    ptrue p0.d
; SVE-NEXT:    mov z2.d, #95 // =0x5f
; SVE-NEXT:    movk x8, #55878, lsl #32
; SVE-NEXT:    mov z3.d, #94 // =0x5e
; SVE-NEXT:    movk x8, #689, lsl #48
; SVE-NEXT:    sxtw z0.d, p0/m, z0.d
; SVE-NEXT:    mov z1.d, x8
; SVE-NEXT:    mul z1.d, p0/m, z1.d, z0.d
; SVE-NEXT:    lsr z0.d, z0.d, #31
; SVE-NEXT:    and z0.d, z0.d, z3.d
; SVE-NEXT:    umulh z1.d, p0/m, z1.d, z2.d
; SVE-NEXT:    sub z0.d, z1.d, z0.d
; SVE-NEXT:    ret
;
; SVE2-LABEL: srem_nxv2i32:
; SVE2:       // %bb.0:
; SVE2-NEXT:    mov x8, #335544320 // =0x14000000
; SVE2-NEXT:    ptrue p0.d
; SVE2-NEXT:    mov z2.d, #95 // =0x5f
; SVE2-NEXT:    movk x8, #55878, lsl #32
; SVE2-NEXT:    mov z3.d, #94 // =0x5e
; SVE2-NEXT:    movk x8, #689, lsl #48
; SVE2-NEXT:    sxtw z0.d, p0/m, z0.d
; SVE2-NEXT:    mov z1.d, x8
; SVE2-NEXT:    mul z1.d, z0.d, z1.d
; SVE2-NEXT:    lsr z0.d, z0.d, #31
; SVE2-NEXT:    and z0.d, z0.d, z3.d
; SVE2-NEXT:    umulh z1.d, z1.d, z2.d
; SVE2-NEXT:    sub z0.d, z1.d, z0.d
; SVE2-NEXT:    ret
  %r = srem <vscale x 2 x i32> %x, splat (i32 -95)
  ret <vscale x 2 x i32> %r
}
