; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=slp-vectorizer -mtriple=riscv64-unknown-linux-gnu -mattr=+v < %s | FileCheck %s

@n = external global [0 x i64]

define i32 @main() {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr getelementptr (i8, ptr @n, i64 32), align 8
; CHECK-NEXT:    [[CONV13_I_1:%.*]] = trunc i64 [[TMP0]] to i32
; CHECK-NEXT:    [[COND_I_1:%.*]] = tail call i32 @llvm.smin.i32(i32 [[CONV13_I_1]], i32 0)
; CHECK-NEXT:    [[CONV40_I_1:%.*]] = sext i32 [[COND_I_1]] to i64
; CHECK-NEXT:    [[COND47_I_1:%.*]] = tail call i64 @llvm.umin.i64(i64 [[CONV40_I_1]], i64 17179869184)
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i64 [[COND47_I_1]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP6]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr @n, align 8
; CHECK-NEXT:    [[CONV13_I_2:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[COND_I_2:%.*]] = tail call i32 @llvm.smin.i32(i32 [[CONV13_I_2]], i32 0)
; CHECK-NEXT:    [[CONV40_I_2:%.*]] = sext i32 [[COND_I_2]] to i64
; CHECK-NEXT:    [[COND47_I_2:%.*]] = tail call i64 @llvm.umin.i64(i64 [[CONV40_I_2]], i64 17179869184)
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i64 [[COND47_I_2]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = or i32 [[TMP9]], [[TMP8]]
; CHECK-NEXT:    ret i32 [[TMP7]]
;
entry:
  %0 = load i64, ptr getelementptr (i8, ptr @n, i64 32), align 8
  %conv13.i.1 = trunc i64 %0 to i32
  %cond.i.1 = tail call i32 @llvm.smin.i32(i32 %conv13.i.1, i32 0)
  %conv40.i.1 = sext i32 %cond.i.1 to i64
  %cond47.i.1 = tail call i64 @llvm.umin.i64(i64 %conv40.i.1, i64 17179869184)
  %1 = trunc i64 %cond47.i.1 to i32
  %2 = add i32 %1, 1
  %3 = load i64, ptr @n, align 8
  %conv13.i.2 = trunc i64 %3 to i32
  %cond.i.2 = tail call i32 @llvm.smin.i32(i32 %conv13.i.2, i32 0)
  %conv40.i.2 = sext i32 %cond.i.2 to i64
  %cond47.i.2 = tail call i64 @llvm.umin.i64(i64 %conv40.i.2, i64 17179869184)
  %4 = trunc i64 %cond47.i.2 to i32
  %5 = or i32 %2, %4
  ret i32 %5
}

declare i32 @llvm.smin.i32(i32, i32)
declare i64 @llvm.umin.i64(i64, i64)
